import { Suspense } from 'react';
import PassportClient from './PassportClient';
import StageTail from '../StageTail';
import { isStageServer } from '@/lib/stage';
import { PUZZLES } from './puzzles';
import { DAYS } from './days';
import { T } from '@/lib/theme';
import { SITE_URL } from '@/lib/site';
import { categoryCrumb } from '@/lib/game-seo';

// Passport launched 2026-10-04. One mystery country a day, played five ways
// (landmark, flag, borders, capital, numbers), one score out of 50, and the
// run ends on the passport that score earns. The bank (app/passport/days.js,
// generated by scripts/gen-passport.mjs) is resolved HERE, on the server, and
// only the picked day ships to the browser, so tomorrow's country never
// reaches a client. The landmark photo comes from /api/passport/img, keyed by
// puzzle number and refused for a day that is not yet live, and the Commons
// title is stripped here because it usually names the place.

export const metadata = {
  title: 'Free Daily Geography Game: Passport | Mind Loft',
  description:
    'A free daily geography game. One mystery country a day, played five ways: name it from a zoomed landmark photo, build its flag, list its neighbors, pin its capital and call its size. Score out of 50 and travel home on the passport you earned. No app, no signup.',
  alternates: { canonical: '/passport' },
  openGraph: {
    images: [{ url: '/og/passport.png', width: 1200, height: 630, alt: 'Passport, a daily geography game from Mind Loft' }],
    title: 'Passport: The Daily Geography Run',
    description: 'One mystery country, five rounds, 50 points. Which passport will you travel home on?',
    url: '/passport', type: 'website', siteName: 'Mind Loft',
  },
  twitter: { images: ['/og/passport.png'], card: 'summary_large_image', title: 'Passport: The Daily Geography Run', description: 'One mystery country, five rounds, 50 points.' },
};

const gameJsonLd = {
  '@context': 'https://schema.org', '@type': 'Game', name: 'Passport',
  alternateName: 'Passport: Daily Geography Game', url: `${SITE_URL}/passport`,
  description:
    'A free daily geography game. Each day has one mystery country, played in five rounds of 10 points: name the country from a landmark photo that zooms out with every wrong guess, build its flag in three picks, name its land neighbors before three strikes, drop a pin on its capital, and call five countries bigger or smaller. The score out of 50 decides which real passport, from the Henley Passport Index, the player travels home on. Everyone gets the same country each day.',
  genre: ['Trivia', 'Geography Quiz', 'Quiz', 'Puzzle'],
  gamePlatform: 'Web browser', isAccessibleForFree: true, inLanguage: 'en',
  numberOfPlayers: { '@type': 'QuantitativeValue', minValue: 1, maxValue: 1 },
  publisher: { '@type': 'Organization', name: 'Mind Loft', url: `${SITE_URL}` },
};
const breadcrumbJsonLd = {
  '@context': 'https://schema.org', '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_URL}` },
    categoryCrumb('passport'),
    { '@type': 'ListItem', position: 3, name: 'Passport' },
  ],
};

export const dynamic = 'force-dynamic';

function etTodayServer() {
  try { return new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' }); }
  catch (e) { return new Date().toISOString().slice(0, 10); }
}

function ComingSoon({ first }) {
  return (
    <div style={{ minHeight: '100vh', background: T.surface, fontFamily: "'Manrope', system-ui, sans-serif", display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
      <div style={{ textAlign: 'center', maxWidth: 420 }}>
        <div style={{ display: 'inline-flex', flexDirection: 'column', justifyContent: 'space-between', width: 92, height: 128, borderRadius: 8, background: '#7d1d2c', color: '#e3c77a', padding: '14px 10px', marginBottom: 18, boxShadow: '0 10px 24px rgba(0,0,0,0.25)', fontWeight: 900, letterSpacing: 2, fontSize: 11 }}>
          <span>MIND LOFT</span>
          <span style={{ fontSize: 26 }}>&#9737;</span>
          <span>PASSPORT</span>
        </div>
        <h1 style={{ fontSize: 24, fontWeight: 800, color: T.ink, margin: '0 0 8px' }}>Passport launches {first ? first.dateLabel : 'soon'}.</h1>
        <p style={{ fontSize: 15, color: T.muted, fontWeight: 600, lineHeight: 1.5, margin: '0 0 18px' }}>
          The daily geography run. One mystery country, five rounds, 50 points. Come back when the first country boards.
        </p>
        <a href="/daily" style={{ color: '#7d1d2c', fontWeight: 800, textDecoration: 'underline' }}>See the other daily puzzles &rarr;</a>
      </div>
    </div>
  );
}

export default function PassportPage({ searchParams }) {
  const today = etTodayServer();
  const visible = PUZZLES.filter((p) => p.live <= today);
  if (!visible.length) return <ComingSoon first={PUZZLES[0]} />;
  const n = Number(searchParams && searchParams.p);
  const forceNum = Number.isInteger(n) && n > 0 && visible.some((p) => p.num === n) ? n : null;
  const picked = (forceNum && visible.find((p) => p.num === forceNum)) || visible[visible.length - 1];
  const full = DAYS[picked.num];
  const { t: _title, ...land } = full.land;
  const day = { ...full, land };
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(gameJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <Suspense fallback={null}>
        <PassportClient key={picked.num} puzzles={visible} day={day} forceNum={forceNum} />
      </Suspense>
      <StageTail self="passport" stage={isStageServer('passport', searchParams)} />
    </>
  );
}
