// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to
// the client — so future puzzles (and their answers) never ship to the
// browser bundle.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'garble-7-9-26',
    live: '2026-07-09',
    dateLabel: 'July 9, 2026',
    clue: 'The only perfect vision — it just shows up too late.',
    final: 'HINDSIGHT',
    words: [
      { answer: 'HABIT', scramble: 'TABHI', marks: [0, 3] },
      { answer: 'DRESS', scramble: 'REDSS', marks: [0, 4] },
      { answer: 'GRAIN', scramble: 'NARGI', marks: [0, 4] },
      { answer: 'WEIGHT', scramble: 'HEWGIT', marks: [2, 4] },
      { answer: 'STRAND', scramble: 'DARNTS', marks: [1] },
    ],
  },
  {
    num: 2,
    quizId: 'garble-7-10-26',
    live: '2026-07-10',
    dateLabel: 'July 10, 2026',
    clue: "What the arsonist's master plan did.",
    final: 'BACKFIRE',
    words: [
      { answer: 'FABLE', scramble: 'LEFBA', marks: [0, 1] },
      { answer: 'BRICK', scramble: 'RKBCI', marks: [0, 3] },
      { answer: 'KIOSK', scramble: 'KKOIS', marks: [0] },
      { answer: 'IRATE', scramble: 'TREAI', marks: [0, 1] },
      { answer: 'EVADE', scramble: 'VDAEE', marks: [0] },
    ],
  },
  {
    num: 3,
    quizId: 'garble-7-11-26',
    live: '2026-07-11',
    dateLabel: 'July 11, 2026',
    clue: "How the ski-resort mayor won re-election.",
    final: 'LANDSLIDE',
    words: [
      { answer: 'BLAND', scramble: 'BDLAN', marks: [1, 2, 3] },
      { answer: 'DITCH', scramble: 'DTCHI', marks: [0, 1] },
      { answer: 'SPELL', scramble: 'PELSL', marks: [0, 3] },
      { answer: 'EVOKE', scramble: 'OVEEK', marks: [0] },
      { answer: 'DEPTH', scramble: 'HEPDT', marks: [0] },
    ],
  },
  {
    num: 4,
    quizId: 'garble-7-12-26',
    live: '2026-07-12',
    dateLabel: 'July 12, 2026',
    clue: "The suggestion box, to whoever actually reads it.",
    final: 'GOLDMINE',
    words: [
      { answer: 'GLOOM', scramble: 'GMOLO', marks: [0, 4] },
      { answer: 'AVOID', scramble: 'AIODV', marks: [2, 4] },
      { answer: 'MINCE', scramble: 'NMIEC', marks: [1, 2] },
      { answer: 'EJECT', scramble: 'TCEEJ', marks: [0] },
      { answer: 'LILAC', scramble: 'ALCIL', marks: [0] },
    ],
  },
  {
    num: 5,
    quizId: 'garble-7-13-26',
    live: '2026-07-13',
    dateLabel: 'July 13, 2026',
    clue: "The insomniac's only dream.",
    final: 'NIGHTMARE',
    words: [
      { answer: 'MIGHT', scramble: 'GHMTI', marks: [0, 1, 2] },
      { answer: 'TENTH', scramble: 'HTTNE', marks: [0, 2, 4] },
      { answer: 'ANKLE', scramble: 'NKALE', marks: [0] },
      { answer: 'RIVER', scramble: 'IRVER', marks: [0] },
      { answer: 'ELUDE', scramble: 'LUEED', marks: [0] },
    ],
  },
  {
    num: 6,
    quizId: 'garble-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    clue: "How the chess hustler says goodbye.",
    final: 'CHECKMATE',
    words: [
      { answer: 'CHIME', scramble: 'CIEMH', marks: [0, 1] },
      { answer: 'MAGIC', scramble: 'AICGM', marks: [0, 4] },
      { answer: 'TRACK', scramble: 'CKRTA', marks: [2, 4] },
      { answer: 'TEMPO', scramble: 'TMPEO', marks: [0, 1] },
      { answer: 'EVENT', scramble: 'VENET', marks: [0] },
    ],
  },
  {
    num: 7,
    quizId: 'garble-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    clue: "Forecast for the pity party.",
    final: 'DOWNPOUR',
    words: [
      { answer: 'DONUT', scramble: 'DNTUO', marks: [0, 2] },
      { answer: 'WAGON', scramble: 'GWNAO', marks: [0] },
      { answer: 'PROUD', scramble: 'URDOP', marks: [0, 1, 3] },
      { answer: 'OASIS', scramble: 'IASSO', marks: [0] },
      { answer: 'ORBIT', scramble: 'RITOB', marks: [0] },
    ],
  },
  {
    num: 8,
    quizId: 'garble-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    clue: "What the hat shop hands out free of charge.",
    final: 'HEADACHE',
    words: [
      { answer: 'HEDGE', scramble: 'HDGEE', marks: [0, 2] },
      { answer: 'COACH', scramble: 'OACHC', marks: [0, 4] },
      { answer: 'ADAPT', scramble: 'PATDA', marks: [0, 2] },
      { answer: 'ELEGY', scramble: 'ELYGE', marks: [0] },
      { answer: 'EIGHT', scramble: 'THEIG', marks: [0] },
    ],
  },
  {
    num: 9,
    quizId: 'garble-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    clue: "Set it to remember it; type it to forget it.",
    final: 'PASSWORD',
    words: [
      { answer: 'SWAMP', scramble: 'MASPW', marks: [1, 4] },
      { answer: 'DRAMA', scramble: 'ADAMR', marks: [0, 2] },
      { answer: 'SCOUT', scramble: 'UOCTS', marks: [0, 2] },
      { answer: 'RUMOR', scramble: 'ROURM', marks: [0] },
      { answer: 'SYRUP', scramble: 'URSPY', marks: [0] },
    ],
  },
  {
    num: 10,
    quizId: 'garble-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    clue: "The turkey's last will and testament.",
    final: 'WISHBONE',
    words: [
      { answer: 'WHISK', scramble: 'SKIWH', marks: [0, 1, 3] },
      { answer: 'BANJO', scramble: 'NAJOB', marks: [0, 2] },
      { answer: 'OZONE', scramble: 'ZNOEO', marks: [0] },
      { answer: 'IGLOO', scramble: 'IGOOL', marks: [0] },
      { answer: 'ELECT', scramble: 'ECELT', marks: [0] },
    ],
  },
  {
    num: 11,
    quizId: 'garble-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    clue: "The kite's five-o'clock routine.",
    final: 'TAILSPIN',
    words: [
      { answer: 'TWIRL', scramble: 'LIRTW', marks: [0, 4] },
      { answer: 'PIANO', scramble: 'NAPOI', marks: [0, 2] },
      { answer: 'INEPT', scramble: 'PITNE', marks: [0, 1] },
      { answer: 'SKIES', scramble: 'SISKE', marks: [0] },
      { answer: 'IVORY', scramble: 'RVIOY', marks: [0] },
    ],
  },
  {
    num: 12,
    quizId: 'garble-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    clue: "A commute for astronauts who missed the bus.",
    final: 'MOONWALK',
    words: [
      { answer: 'KNOLL', scramble: 'NOLLK', marks: [0, 1, 3] },
      { answer: 'WOMAN', scramble: 'NOMWA', marks: [0, 3] },
      { answer: 'MERCY', scramble: 'YMRCE', marks: [0] },
      { answer: 'OPERA', scramble: 'PAEOR', marks: [0] },
      { answer: 'OFTEN', scramble: 'NEOFT', marks: [0] },
    ],
  },
  {
    num: 13,
    quizId: 'garble-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    clue: "The hero's permanent plus-one.",
    final: 'SIDEKICK',
    words: [
      { answer: 'CIVIC', scramble: 'CIICV', marks: [0] },
      { answer: 'SKUNK', scramble: 'NKKSU', marks: [0, 1] },
      { answer: 'KHAKI', scramble: 'HKAKI', marks: [0] },
      { answer: 'DIODE', scramble: 'DDEIO', marks: [0, 1] },
      { answer: 'IMBUE', scramble: 'MEUBI', marks: [0, 4] },
    ],
  },
  {
    num: 14,
    quizId: 'garble-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    clue: "Where cruise ships keep the extra drama.",
    final: 'OVERBOARD',
    words: [
      { answer: 'BRAVO', scramble: 'ABORV', marks: [0, 1, 3] },
      { answer: 'MAJOR', scramble: 'JAMRO', marks: [1, 3] },
      { answer: 'DODGE', scramble: 'EDODG', marks: [0, 1] },
      { answer: 'RODEO', scramble: 'EROOD', marks: [0] },
      { answer: 'EPOXY', scramble: 'YOPXE', marks: [0] },
    ],
  },
  {
    num: 15,
    quizId: 'garble-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    clue: "The comedian always gets the last word. This one.",
    final: 'PUNCHLINE',
    words: [
      { answer: 'PLUCK', scramble: 'CUKPL', marks: [0] },
      { answer: 'LOGIC', scramble: 'LGIOC', marks: [0, 4] },
      { answer: 'NINTH', scramble: 'HINTN', marks: [0, 2, 4] },
      { answer: 'UNITY', scramble: 'NYITU', marks: [0, 2] },
      { answer: 'ELOPE', scramble: 'EELPO', marks: [0] },
    ],
  },
  {
    num: 16,
    quizId: 'garble-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    clue: "Where marshmallows and ghost stories meet their end.",
    final: 'CAMPFIRE',
    words: [
      { answer: 'CABIN', scramble: 'IBCAN', marks: [0, 1] },
      { answer: 'PRIME', scramble: 'ERMPI', marks: [0, 3] },
      { answer: 'FLINT', scramble: 'ILFNT', marks: [0, 2] },
      { answer: 'ROBIN', scramble: 'NIBRO', marks: [0] },
      { answer: 'ENJOY', scramble: 'NOYJE', marks: [0] },
    ],
  },
  {
    num: 17,
    quizId: 'garble-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    clue: "The meeting you attend without leaving your chair.",
    final: 'DAYDREAM',
    words: [
      { answer: 'ADAGE', scramble: 'AAGED', marks: [0, 1] },
      { answer: 'MURKY', scramble: 'MRUKY', marks: [0, 4] },
      { answer: 'DINER', scramble: 'RNDIE', marks: [0, 4] },
      { answer: 'APRON', scramble: 'APNRO', marks: [0] },
      { answer: 'ERUPT', scramble: 'EURTP', marks: [0] },
    ],
  },
  {
    num: 18,
    quizId: 'garble-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    clue: "Every skyscraper's baby photo.",
    final: 'BLUEPRINT',
    // SUNDAY EDITION: every answer is SIX letters instead of five. Same five
    // words, same 9 marked letters feeding BLUEPRINT, just a longer unscramble.
    words: [
      { answer: 'BRIDGE', scramble: 'IEDGBR', marks: [0, 2] },
      { answer: 'PLANET', scramble: 'TNLEAP', marks: [0, 1] },
      { answer: 'ROCKET', scramble: 'KCRTOE', marks: [0, 4] },
      { answer: 'TURTLE', scramble: 'ETTLRU', marks: [0, 1] },
      { answer: 'SALMON', scramble: 'NLOSMA', marks: [5] },
    ],
  },
  {
    num: 19,
    quizId: 'garble-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    clue: "The ground's way of asking you to stay.",
    final: 'QUICKSAND',
    words: [
      { answer: 'QUILT', scramble: 'UTLQI', marks: [0, 1, 2] },
      { answer: 'SNACK', scramble: 'NSACK', marks: [3, 4] },
      { answer: 'DUSKY', scramble: 'YDKSU', marks: [0, 2] },
      { answer: 'ADOPT', scramble: 'ODAPT', marks: [0] },
      { answer: 'NUDGE', scramble: 'GNEDU', marks: [0] },
    ],
  },
  {
    num: 20,
    quizId: 'garble-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    clue: "Miles and miles without an inch of progress.",
    final: 'TREADMILL',
    words: [
      { answer: 'MEDAL', scramble: 'MDALE', marks: [0, 2] },
      { answer: 'LEMUR', scramble: 'ERMLU', marks: [0, 4] },
      { answer: 'TWANG', scramble: 'TNWGA', marks: [0, 2] },
      { answer: 'LINEN', scramble: 'ILNEN', marks: [0, 1] },
      { answer: 'EMBER', scramble: 'EEMRB', marks: [0] },
    ],
  },
  {
    num: 21,
    quizId: 'garble-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    clue: "The trip with a lifetime of terms and conditions.",
    final: 'HONEYMOON',
    words: [
      { answer: 'MOODY', scramble: 'OOMDY', marks: [0, 1] },
      { answer: 'HYENA', scramble: 'NAYEH', marks: [0, 1] },
      { answer: 'ONION', scramble: 'OONIN', marks: [0, 1] },
      { answer: 'ENEMY', scramble: 'NMEEY', marks: [0, 1] },
      { answer: 'OUNCE', scramble: 'NEOUC', marks: [0] },
    ],
  },
  {
    num: 22,
    quizId: 'garble-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    clue: "It never sails, but every ship trusts it.",
    final: 'LIGHTHOUSE',
    words: [
      { answer: 'GHOUL', scramble: 'LHOUG', marks: [0, 1] },
      { answer: 'HOTEL', scramble: 'HLEOT', marks: [0, 2] },
      { answer: 'LOUSE', scramble: 'OLUES', marks: [1, 2] },
      { answer: 'SLICE', scramble: 'LEISC', marks: [0, 1] },
      { answer: 'EXILE', scramble: 'EEILX', marks: [0, 2] },
    ],
  },
  {
    num: 23,
    quizId: 'garble-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    clue: "Winter's overdue apology, finally paid back in blossoms.",
    final: 'SPRINGTIME',
    words: [
      { answer: 'PLUSH', scramble: 'HPLUS', marks: [0, 3] },
      { answer: 'PRIZE', scramble: 'EIPRZ', marks: [1, 2] },
      { answer: 'GRANT', scramble: 'AGNTR', marks: [0, 3] },
      { answer: 'TWICE', scramble: 'CETIW', marks: [0, 2] },
      { answer: 'MONEY', scramble: 'EMOYN', marks: [0, 3] },
    ],
  },
  {
    num: 24,
    quizId: 'garble-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    clue: "The brain the whole heist quietly reports to.",
    final: 'MASTERMIND',
    words: [
      { answer: 'MAYBE', scramble: 'ABEMY', marks: [0, 1] },
      { answer: 'MUDDY', scramble: 'DDMYU', marks: [0, 2] },
      { answer: 'STUNT', scramble: 'NSTTU', marks: [0, 1] },
      { answer: 'RIVER', scramble: 'ERIRV', marks: [0, 3] },
      { answer: 'UNITY', scramble: 'ITNYU', marks: [1, 2] },
    ],
  },
  {
    num: 25,
    quizId: 'garble-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    clue: "What the map's X has been guarding all along.",
    final: 'TREASURE',
    words: [
      { answer: 'MARKET', scramble: 'AKTREM', marks: [1] },
      { answer: 'QUARTZ', scramble: 'URZATQ', marks: [1] },
      { answer: 'GRAVEL', scramble: 'RVLAEG', marks: [1] },
      { answer: 'ROTATE', scramble: 'OAETTR', marks: [0, 2, 5] },
      { answer: 'SQUARE', scramble: 'QAEURS', marks: [0, 5] },
    ],
  },
  {
    num: 26,
    quizId: 'garble-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    clue: "A pale ribbon of light the night lays across the floor.",
    final: 'MOONBEAM',
    words: [
      { answer: 'MONEY', scramble: 'OEMNY', marks: [0, 1, 2] },
      { answer: 'PLUMB', scramble: 'LMPUB', marks: [3] },
      { answer: 'THUMB', scramble: 'HMTUB', marks: [4] },
      { answer: 'GLOVE', scramble: 'LVGOE', marks: [2] },
      { answer: 'BRAVE', scramble: 'RVBAE', marks: [2, 4] },
    ],
  },
  {
    num: 27,
    quizId: 'garble-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    clue: "What floods the room the moment the blinds come up.",
    final: 'SUNSHINE',
    words: [
      { answer: 'SHINE', scramble: 'ENSHI', marks: [0, 1, 3, 4] },
      { answer: 'HOUSE', scramble: 'SHOEU', marks: [2] },
      { answer: 'SUNNY', scramble: 'USYNN', marks: [0] },
      { answer: 'MUSIC', scramble: 'CIMUS', marks: [3] },
      { answer: 'UNION', scramble: 'OUNNI', marks: [1] },
    ],
  },
  {
    num: 28,
    quizId: 'garble-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    clue: "The first pale light that ends the night.",
    final: 'DAYBREAK',
    words: [
      { answer: 'GRAND', scramble: 'NDGRA', marks: [1, 2, 4] },
      { answer: 'BRAVE', scramble: 'BERVA', marks: [0, 4] },
      { answer: 'RHYME', scramble: 'HMERY', marks: [2] },
      { answer: 'KOALA', scramble: 'OLKAA', marks: [0] },
      { answer: 'PLANT', scramble: 'PTLNA', marks: [2] },
    ],
  },
  {
    num: 29,
    quizId: 'garble-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    clue: "The finale that paints the Fourth of July sky.",
    final: 'FIREWORK',
    words: [
      { answer: 'FLOOR', scramble: 'OFLRO', marks: [0, 2, 4] },
      { answer: 'IVORY', scramble: 'VIYRO', marks: [0, 3] },
      { answer: 'CROWD', scramble: 'DWCRO', marks: [3] },
      { answer: 'BRAVE', scramble: 'EBRAV', marks: [4] },
      { answer: 'BRICK', scramble: 'KRIBC', marks: [4] },
    ],
  },
  {
    num: 30,
    quizId: 'garble-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    clue: "Winter's quiet white blanket, drifting down.",
    final: 'SNOWFALL',
    words: [
      { answer: 'FLOOR', scramble: 'FOLRO', marks: [0, 1, 2] },
      { answer: 'JELLY', scramble: 'EYLJL', marks: [2] },
      { answer: 'CROWD', scramble: 'ODCRW', marks: [3] },
      { answer: 'PLANT', scramble: 'PALTN', marks: [2, 3] },
      { answer: 'MUSIC', scramble: 'UCSMI', marks: [2] },
    ],
  },
  {
    num: 31,
    quizId: 'garble-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    clue: "What too much noise and paperwork leaves pounding.",
    final: 'HEADACHE',
    words: [
      { answer: 'BEACH', scramble: 'BEAHC', marks: [1, 2, 3, 4] },
      { answer: 'CHAIR', scramble: 'ARCHI', marks: [2] },
      { answer: 'KNEEL', scramble: 'LKNEE', marks: [2] },
      { answer: 'GRAND', scramble: 'GRADN', marks: [4] },
      { answer: 'HONEY', scramble: 'YNHOE', marks: [0] },
    ],
  },
  {
    num: 32,
    quizId: 'garble-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    clue: "Where every day feels like an endless holiday.",
    final: 'PARADISE',
    words: [
      { answer: 'PARADE', scramble: 'ERAAPD', marks: [0, 1, 2, 3] },
      { answer: 'ISLAND', scramble: 'ASDILN', marks: [5] },
      { answer: 'SAILOR', scramble: 'RISALO', marks: [2] },
      { answer: 'SPRING', scramble: 'GRPISN', marks: [0] },
      { answer: 'ENGINE', scramble: 'INEEGN', marks: [0] },
    ],
  },
  {
    num: 33,
    quizId: 'garble-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    clue: "The moon's slow climb over the evening horizon.",
    final: 'MOONRISE',
    words: [
      { answer: 'GOOSE', scramble: 'OGOES', marks: [1, 2, 3] },
      { answer: 'MONEY', scramble: 'NYMOE', marks: [0, 2] },
      { answer: 'SHINE', scramble: 'SEHIN', marks: [4] },
      { answer: 'UNION', scramble: 'NUINO', marks: [2] },
      { answer: 'RHYME', scramble: 'YERHM', marks: [0] },
    ],
  },

  {
    num: 34,
    quizId: 'garble-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    clue: "The loud committee that runs every harbour.",
    final: 'SEAGULLS',
    words: [
      { answer: 'ROLLS', scramble: 'LRSLO', marks: [4] },
      { answer: 'BEGUN', scramble: 'ENGBU', marks: [1, 2, 3] },
      { answer: 'CANAL', scramble: 'AANLC', marks: [4] },
      { answer: 'ALBUM', scramble: 'LABMU', marks: [0, 1] },
      { answer: 'BLUES', scramble: 'EUBSL', marks: [4] },
    ],
  },
  {
    num: 35,
    quizId: 'garble-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    clue: "Where a thought goes before it can escape.",
    final: 'NOTEBOOK',
    words: [
      { answer: 'PATCH', scramble: 'CPAHT', marks: [2] },
      { answer: 'TOWNS', scramble: 'WONTS', marks: [1] },
      { answer: 'LOOKS', scramble: 'KOLSO', marks: [1] },
      { answer: 'NOBLE', scramble: 'ONEBL', marks: [1, 2, 4] },
      { answer: 'THANK', scramble: 'HAKTN', marks: [3, 4] },
    ],
  },
  {
    num: 36,
    quizId: 'garble-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    clue: "The small print hiding at the bottom.",
    final: 'FOOTNOTE',
    words: [
      { answer: 'METRO', scramble: 'MTORE', marks: [2] },
      { answer: 'UNION', scramble: 'INUON', marks: [1] },
      { answer: 'CLOTH', scramble: 'OHCLT', marks: [2, 3] },
      { answer: 'OFFER', scramble: 'FFREO', marks: [0, 1, 3] },
      { answer: 'VIDEO', scramble: 'DIVEO', marks: [4] },
    ],
  },
  {
    num: 37,
    quizId: 'garble-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    clue: "The slope the sheep prefer to the flat.",
    final: 'HILLSIDE',
    words: [
      { answer: 'ALPHA', scramble: 'HPAAL', marks: [1] },
      { answer: 'WHILE', scramble: 'WIEHL', marks: [1, 2, 3] },
      { answer: 'SUITE', scramble: 'SITUE', marks: [2, 4] },
      { answer: 'BANDS', scramble: 'NSDBA', marks: [4] },
      { answer: 'ORDER', scramble: 'OREDR', marks: [2] },
    ],
  },
  {
    num: 38,
    quizId: 'garble-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    clue: "The last drink before the stairs.",
    final: 'NIGHTCAP',
    words: [
      { answer: 'SALAD', scramble: 'LDSAA', marks: [1] },
      { answer: 'PHOTO', scramble: 'OHPOT', marks: [0] },
      { answer: 'GROUP', scramble: 'OPGRU', marks: [0] },
      { answer: 'KICKS', scramble: 'IKCKS', marks: [1, 2] },
      { answer: 'MONTH', scramble: 'TNMHO', marks: [2, 3, 4] },
    ],
  },
  {
    num: 39,
    quizId: 'garble-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    clue: "Where the axe waits out the summer.",
    final: 'WOODSHED',
    words: [
      { answer: 'ROUNDS', scramble: 'SDONRU', marks: [4, 5] },
      { answer: 'CHOSEN', scramble: 'CNSOHE', marks: [1, 2, 4] },
      { answer: 'GAINED', scramble: 'NIEAGD', marks: [5] },
      { answer: 'TOWARD', scramble: 'DOWRTA', marks: [2] },
      { answer: 'LOOKED', scramble: 'OEDOKL', marks: [1] },
    ],
  },
  {
    num: 40,
    quizId: 'garble-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    clue: "Where the milk bottles used to wait.",
    final: 'DOORSTEP',
    words: [
      { answer: 'WORST', scramble: 'RTSWO', marks: [1, 4] },
      { answer: 'LOWER', scramble: 'RWLEO', marks: [1] },
      { answer: 'HOPES', scramble: 'OHPSE', marks: [2, 3, 4] },
      { answer: 'CREAM', scramble: 'ACREM', marks: [1] },
      { answer: 'DRILL', scramble: 'DRLLI', marks: [0] },
    ],
  },
  {
    num: 41,
    quizId: 'garble-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    clue: "The place your accent came from.",
    final: 'HOMETOWN',
    words: [
      { answer: 'CLOTH', scramble: 'LHTCO', marks: [2] },
      { answer: 'TWINS', scramble: 'NWIST', marks: [1] },
      { answer: 'HONOR', scramble: 'NOOHR', marks: [1] },
      { answer: 'MEANT', scramble: 'ETNAM', marks: [0, 1, 3, 4] },
      { answer: 'TOUCH', scramble: 'CHOTU', marks: [4] },
    ],
  },
  {
    num: 42,
    quizId: 'garble-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    clue: "One candle for every year, and a wish at the end.",
    final: 'BIRTHDAY',
    words: [
      { answer: 'FAITH', scramble: 'FHITA', marks: [2] },
      { answer: 'BREED', scramble: 'DREEB', marks: [0] },
      { answer: 'PAGES', scramble: 'APSGE', marks: [1] },
      { answer: 'DIRTY', scramble: 'RDTYI', marks: [0, 2, 3] },
      { answer: 'HURRY', scramble: 'RHRUY', marks: [0, 4] },
    ],
  },
  {
    num: 43,
    quizId: 'garble-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    clue: "The biggest type on the front page.",
    final: 'HEADLINE',
    words: [
      { answer: 'NINTH', scramble: 'NTIHN', marks: [1, 4] },
      { answer: 'DELAY', scramble: 'AYLED', marks: [1, 3] },
      { answer: 'DATED', scramble: 'ADTDE', marks: [3] },
      { answer: 'FINAL', scramble: 'FNILA', marks: [2, 4] },
      { answer: 'CHILD', scramble: 'LHCDI', marks: [4] },
    ],
  },
  {
    num: 44,
    quizId: 'garble-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    clue: "One small instalment of a downpour.",
    final: 'RAINDROP',
    words: [
      { answer: 'FRANK', scramble: 'FAKRN', marks: [2] },
      { answer: 'SOUND', scramble: 'OUNDS', marks: [3] },
      { answer: 'GROUP', scramble: 'UOPRG', marks: [1, 4] },
      { answer: 'VIRUS', scramble: 'RVUIS', marks: [1, 2] },
      { answer: 'HOLDS', scramble: 'SOLHD', marks: [1, 3] },
    ],
  },
  {
    num: 45,
    quizId: 'garble-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    clue: "What you tell a lost stranger to look for.",
    final: 'LANDMARK',
    words: [
      { answer: 'SOUND', scramble: 'NDOSU', marks: [4] },
      { answer: 'CHECK', scramble: 'ECKHC', marks: [4] },
      { answer: 'APPLY', scramble: 'YPPAL', marks: [0] },
      { answer: 'MINOR', scramble: 'MOINR', marks: [0, 2, 4] },
      { answer: 'USUAL', scramble: 'UAULS', marks: [3, 4] },
    ],
  },
  {
    num: 46,
    quizId: 'garble-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    clue: "Too narrow for anything that runs on wheels.",
    final: 'FOOTPATH',
    words: [
      { answer: 'PROFIT', scramble: 'FORPTI', marks: [0, 3] },
      { answer: 'WORTHY', scramble: 'HRWOTY', marks: [1, 3] },
      { answer: 'SHORTS', scramble: 'SOSTHR', marks: [2, 4] },
      { answer: 'MATRIX', scramble: 'AIMTXR', marks: [1] },
      { answer: 'HIDDEN', scramble: 'EDHIND', marks: [0] },
    ],
  },
  {
    num: 47,
    quizId: 'garble-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    clue: "Winter, stacked neatly against a wall.",
    final: 'FIREWOOD',
    words: [
      { answer: 'BOOKS', scramble: 'OBKSO', marks: [1] },
      { answer: 'FORMS', scramble: 'SRMOF', marks: [0, 2] },
      { answer: 'DIRTY', scramble: 'YDRIT', marks: [0, 1] },
      { answer: 'MOVES', scramble: 'OMEVS', marks: [1, 3] },
      { answer: 'WORST', scramble: 'OSTRW', marks: [0] },
    ],
  },
  {
    num: 48,
    quizId: 'garble-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    clue: "A road that carries barges instead of cars.",
    final: 'WATERWAY',
    words: [
      { answer: 'GUIDE', scramble: 'DIUEG', marks: [4] },
      { answer: 'DEPTH', scramble: 'TPHED', marks: [3] },
      { answer: 'PLACE', scramble: 'PAECL', marks: [2] },
      { answer: 'WOMAN', scramble: 'MWOAN', marks: [0, 3] },
      { answer: 'WORRY', scramble: 'RRWYO', marks: [0, 2, 4] },
    ],
  },
  {
    num: 49,
    quizId: 'garble-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    clue: "The dog's favourite piece of street furniture.",
    final: 'LAMPPOST',
    words: [
      { answer: 'JAPAN', scramble: 'APAJN', marks: [1] },
      { answer: 'BUCKS', scramble: 'CSBUK', marks: [4] },
      { answer: 'SORTS', scramble: 'OTSSR', marks: [3] },
      { answer: 'PRIME', scramble: 'IEMRP', marks: [0, 3] },
      { answer: 'PILOT', scramble: 'IOTLP', marks: [0, 2, 3] },
    ],
  },
  {
    num: 50,
    quizId: 'garble-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    clue: "A slow way up and a very quick way down.",
    final: 'MOUNTAIN',
    words: [
      { answer: 'MUSIC', scramble: 'MCIUS', marks: [0, 1] },
      { answer: 'SWEET', scramble: 'ESTWE', marks: [4] },
      { answer: 'GRAND', scramble: 'DAGRN', marks: [2, 3] },
      { answer: 'TWINS', scramble: 'INTSW', marks: [2, 3] },
      { answer: 'UNION', scramble: 'NOUNI', marks: [3] },
    ],
  },
  {
    num: 51,
    quizId: 'garble-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    clue: "Where the sand runs out and the salt begins.",
    final: 'SEASHORE',
    words: [
      { answer: 'DERBY', scramble: 'DBRYE', marks: [1] },
      { answer: 'ORBIT', scramble: 'BRTIO', marks: [0] },
      { answer: 'ISSUE', scramble: 'SUSEI', marks: [1, 2, 4] },
      { answer: 'CRAZY', scramble: 'ZARCY', marks: [1, 2] },
      { answer: 'CHAIR', scramble: 'AIRCH', marks: [1] },
    ],
  },
  {
    num: 52,
    quizId: 'garble-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    clue: "Two lines that never meet yet always arrive.",
    final: 'RAILROAD',
    words: [
      { answer: 'GRAIN', scramble: 'ARGNI', marks: [1, 2] },
      { answer: 'DRUGS', scramble: 'SDRGU', marks: [0] },
      { answer: 'BROWN', scramble: 'WBNRO', marks: [1] },
      { answer: 'KNIFE', scramble: 'NEFIK', marks: [2] },
      { answer: 'ALLOW', scramble: 'LOWLA', marks: [0, 1, 3] },
    ],
  },
  {
    num: 53,
    quizId: 'garble-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    clue: "Ground that belongs to the trees.",
    final: 'WOODLAND',
    words: [
      { answer: 'YELLOW', scramble: 'WELYLO', marks: [5] },
      { answer: 'SYMBOL', scramble: 'MBLSYO', marks: [4] },
      { answer: 'ANYONE', scramble: 'ANONEY', marks: [3] },
      { answer: 'ADDING', scramble: 'DDGAIN', marks: [0, 1, 2, 4] },
      { answer: 'ISLAND', scramble: 'LDSNAI', marks: [2] },
    ],
  },
  {
    num: 54,
    quizId: 'garble-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    clue: "Winter, stacked neatly against a wall.",
    final: 'FIREWOOD',
    words: [
      { answer: 'LEVEL', scramble: 'ELVLE', marks: [1] },
      { answer: 'CREAM', scramble: 'EMRCA', marks: [1] },
      { answer: 'FIFTH', scramble: 'FFTHI', marks: [0, 1] },
      { answer: 'FORMS', scramble: 'FOSRM', marks: [1] },
      { answer: 'WOULD', scramble: 'WOUDL', marks: [0, 1, 4] },
    ],
  },
  {
    num: 55,
    quizId: 'garble-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    clue: "Where a thought goes before it can escape.",
    final: 'NOTEBOOK',
    words: [
      { answer: 'CHART', scramble: 'CTHAR', marks: [4] },
      { answer: 'BROKE', scramble: 'ERKBO', marks: [3, 4] },
      { answer: 'BONUS', scramble: 'UNBOS', marks: [0, 1, 2] },
      { answer: 'COURT', scramble: 'CUTRO', marks: [1] },
      { answer: 'PHOTO', scramble: 'PHOOT', marks: [2] },
    ],
  },
  {
    num: 56,
    quizId: 'garble-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    clue: "The biggest type on the front page.",
    final: 'HEADLINE',
    words: [
      { answer: 'SIZED', scramble: 'IEZSD', marks: [4] },
      { answer: 'CHECK', scramble: 'CCKEH', marks: [1] },
      { answer: 'PITCH', scramble: 'ICTPH', marks: [1] },
      { answer: 'VALVE', scramble: 'VVLAE', marks: [1, 4] },
      { answer: 'NOBLE', scramble: 'LOEBN', marks: [0, 3, 4] },
    ],
  },
  {
    num: 57,
    quizId: 'garble-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    clue: "One small instalment of a downpour.",
    final: 'RAINDROP',
    words: [
      { answer: 'RAPID', scramble: 'RIDAP', marks: [0, 2, 3, 4] },
      { answer: 'REBEL', scramble: 'EBERL', marks: [0] },
      { answer: 'RUINS', scramble: 'INUSR', marks: [3] },
      { answer: 'LABOR', scramble: 'BOLAR', marks: [3] },
      { answer: 'ARENA', scramble: 'AERAN', marks: [0] },
    ],
  },
  {
    num: 58,
    quizId: 'garble-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    clue: "Where the axe waits out the summer.",
    final: 'WOODSHED',
    words: [
      { answer: 'WATCH', scramble: 'WCHTA', marks: [0] },
      { answer: 'FLOOD', scramble: 'LOODF', marks: [2] },
      { answer: 'BLADE', scramble: 'ELBDA', marks: [4] },
      { answer: 'LORDS', scramble: 'SRDOL', marks: [1, 3, 4] },
      { answer: 'DUTCH', scramble: 'HUCDT', marks: [0, 4] },
    ],
  },
  {
    num: 59,
    quizId: 'garble-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    clue: "Two lines that never meet yet always arrive.",
    final: 'RAILROAD',
    words: [
      { answer: 'FAILS', scramble: 'ASIFL', marks: [1, 2] },
      { answer: 'RURAL', scramble: 'RLAUR', marks: [0, 2, 3] },
      { answer: 'LOOSE', scramble: 'OOELS', marks: [0] },
      { answer: 'BRAND', scramble: 'DNABR', marks: [4] },
      { answer: 'GOING', scramble: 'GGNOI', marks: [1] },
    ],
  },
  {
    num: 60,
    quizId: 'garble-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    clue: "One candle for every year, and a wish at the end.",
    final: 'BIRTHDAY',
    words: [
      { answer: 'FOUGHT', scramble: 'FGOHTU', marks: [4] },
      { answer: 'NATIVE', scramble: 'VIANTE', marks: [1] },
      { answer: 'ATTEND', scramble: 'NTDEAT', marks: [1, 5] },
      { answer: 'JERSEY', scramble: 'YREEJS', marks: [2, 5] },
      { answer: 'SUBMIT', scramble: 'BTSIMU', marks: [2, 4] },
    ],
  },
  {
    num: 61,
    quizId: 'garble-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    clue: "The slope the sheep prefer to the flat.",
    final: 'HILLSIDE',
    words: [
      { answer: 'INDIE', scramble: 'EIDIN', marks: [0, 3] },
      { answer: 'NOBLE', scramble: 'OELBN', marks: [3] },
      { answer: 'HOLDS', scramble: 'OSDLH', marks: [0, 3, 4] },
      { answer: 'LIKED', scramble: 'ILEDK', marks: [3] },
      { answer: 'SPELL', scramble: 'EPLSL', marks: [3] },
    ],
  },
  {
    num: 62,
    quizId: 'garble-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    clue: "Ground that belongs to the trees.",
    final: 'WOODLAND',
    words: [
      { answer: 'ADDED', scramble: 'DDADE', marks: [0, 1, 2] },
      { answer: 'WINDS', scramble: 'IDNWS', marks: [0] },
      { answer: 'SOUND', scramble: 'ONUSD', marks: [1, 3] },
      { answer: 'FORMS', scramble: 'MOSFR', marks: [1] },
      { answer: 'APPLY', scramble: 'APYLP', marks: [3] },
    ],
  },
  {
    num: 63,
    quizId: 'garble-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    clue: "What you tell a lost stranger to look for.",
    final: 'LANDMARK',
    words: [
      { answer: 'ULTRA', scramble: 'LTRAU', marks: [1, 3] },
      { answer: 'ASKED', scramble: 'EDSKA', marks: [2, 4] },
      { answer: 'TREND', scramble: 'RNTED', marks: [3] },
      { answer: 'IMAGE', scramble: 'EAMIG', marks: [1, 2] },
      { answer: 'HAVEN', scramble: 'AHVNE', marks: [1] },
    ],
  },
  {
    num: 64,
    quizId: 'garble-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    clue: "Too narrow for anything that runs on wheels.",
    final: 'FOOTPATH',
    words: [
      { answer: 'COSTS', scramble: 'TSSOC', marks: [1] },
      { answer: 'FIFTH', scramble: 'ITHFF', marks: [0, 4] },
      { answer: 'ZONES', scramble: 'ZSONE', marks: [1] },
      { answer: 'PATCH', scramble: 'TPHCA', marks: [0, 1, 2] },
      { answer: 'MIGHT', scramble: 'HMTGI', marks: [4] },
    ],
  },
  {
    num: 65,
    quizId: 'garble-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    clue: "The small print hiding at the bottom.",
    final: 'FOOTNOTE',
    words: [
      { answer: 'WOUND', scramble: 'UDNOW', marks: [1, 3] },
      { answer: 'OFTEN', scramble: 'OTEFN', marks: [0, 2, 3] },
      { answer: 'THIRD', scramble: 'HRTDI', marks: [0] },
      { answer: 'FEWER', scramble: 'WFREE', marks: [0] },
      { answer: 'PHOTO', scramble: 'OTPHO', marks: [2] },
    ],
  },
  {
    num: 66,
    quizId: 'garble-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    clue: "The famously bad place to drop a needle.",
    final: 'HAYSTACK',
    words: [
      { answer: 'CATCH', scramble: 'AHCCT', marks: [1, 4] },
      { answer: 'TWEET', scramble: 'TTWEE', marks: [0] },
      { answer: 'BROKE', scramble: 'OKBER', marks: [3] },
      { answer: 'CARRY', scramble: 'YRACR', marks: [0, 1, 4] },
      { answer: 'PICKS', scramble: 'KCSIP', marks: [4] },
    ],
  },
  {
    num: 67,
    quizId: 'garble-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    clue: "A road that carries barges instead of cars.",
    final: 'WATERWAY',
    words: [
      { answer: 'WINTER', scramble: 'WRNEIT', marks: [0, 4] },
      { answer: 'WAITED', scramble: 'DTIAWE', marks: [0, 1, 3] },
      { answer: 'GROUND', scramble: 'RDNUGO', marks: [1] },
      { answer: 'HIGHLY', scramble: 'YLHIGH', marks: [5] },
      { answer: 'REALLY', scramble: 'LYRLAE', marks: [2] },
    ],
  },
  {
    num: 68,
    quizId: 'garble-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    clue: "Where the sand runs out and the salt begins.",
    final: 'SEASHORE',
    words: [
      { answer: 'LOVER', scramble: 'RLOVE', marks: [1, 3, 4] },
      { answer: 'BRASS', scramble: 'SRABS', marks: [2, 3] },
      { answer: 'MILLS', scramble: 'LSILM', marks: [4] },
      { answer: 'ISSUE', scramble: 'EUSIS', marks: [4] },
      { answer: 'FIGHT', scramble: 'FGITH', marks: [3] },
    ],
  },
  {
    num: 69,
    quizId: 'garble-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    clue: "The place your accent came from.",
    final: 'HOMETOWN',
    words: [
      { answer: 'TOUCH', scramble: 'HOUTC', marks: [0, 1, 4] },
      { answer: 'SHOWN', scramble: 'ONWHS', marks: [3] },
      { answer: 'EMAIL', scramble: 'LEMAI', marks: [1] },
      { answer: 'AGENT', scramble: 'GAENT', marks: [2, 3] },
      { answer: 'GLORY', scramble: 'ROGLY', marks: [2] },
    ],
  },
  {
    num: 70,
    quizId: 'garble-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    clue: "Where the wind is heard before it is felt.",
    final: 'TREETOPS',
    words: [
      { answer: 'ERROR', scramble: 'ORERR', marks: [3] },
      { answer: 'GUEST', scramble: 'USGTE', marks: [4] },
      { answer: 'PRESS', scramble: 'PSRSE', marks: [0] },
      { answer: 'SWEET', scramble: 'SWETE', marks: [0, 2, 3, 4] },
      { answer: 'REACH', scramble: 'CEARH', marks: [0] },
    ],
  },
  {
    num: 71,
    quizId: 'garble-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    clue: "The one sailing at the front of the fleet.",
    final: 'FLAGSHIP',
    words: [
      { answer: 'LAUGH', scramble: 'HALUG', marks: [0, 3, 4] },
      { answer: 'FUNDS', scramble: 'NSDFU', marks: [4] },
      { answer: 'FORCE', scramble: 'ORCFE', marks: [0] },
      { answer: 'FAILS', scramble: 'FILAS', marks: [1, 2] },
      { answer: 'CHIPS', scramble: 'HCIPS', marks: [3] },
    ],
  },
  {
    num: 72,
    quizId: 'garble-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    clue: "The dog's favourite piece of street furniture.",
    final: 'LAMPPOST',
    words: [
      { answer: 'HAPPY', scramble: 'PAPHY', marks: [2, 3] },
      { answer: 'CLIMB', scramble: 'BLICM', marks: [1, 3] },
      { answer: 'GROUP', scramble: 'PGURO', marks: [2] },
      { answer: 'SCARY', scramble: 'CRAYS', marks: [0] },
      { answer: 'WATER', scramble: 'RTWAE', marks: [1, 2] },
    ],
  },
  {
    num: 73,
    quizId: 'garble-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    clue: "The last drink before the stairs.",
    final: 'NIGHTCAP',
    words: [
      { answer: 'HABIT', scramble: 'IBHTA', marks: [0, 1, 3, 4] },
      { answer: 'WITCH', scramble: 'CIHWT', marks: [3] },
      { answer: 'BEGUN', scramble: 'BGNEU', marks: [2] },
      { answer: 'PROVE', scramble: 'ROVPE', marks: [0] },
      { answer: 'BLANK', scramble: 'ALKBN', marks: [3] },
    ],
  },
  {
    num: 74,
    quizId: 'garble-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    clue: "Where the milk bottles used to wait.",
    final: 'DOORSTEP',
    words: [
      { answer: 'POETRY', scramble: 'OTPREY', marks: [1, 2, 3] },
      { answer: 'CUSTOM', scramble: 'CMTOSU', marks: [2, 4] },
      { answer: 'VIEWED', scramble: 'DVEEIW', marks: [5] },
      { answer: 'COMPLY', scramble: 'LYOMPC', marks: [3] },
      { answer: 'EFFORT', scramble: 'ETFORF', marks: [4] },
    ],
  },
  {
    num: 75,
    quizId: 'garble-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    clue: "The loud committee that runs every harbour.",
    final: 'SEAGULLS',
    words: [
      { answer: 'KNIFE', scramble: 'FIEKN', marks: [4] },
      { answer: 'PAUSE', scramble: 'EAPSU', marks: [3] },
      { answer: 'LINED', scramble: 'LIEND', marks: [0] },
      { answer: 'GROWS', scramble: 'SROWG', marks: [0] },
      { answer: 'USUAL', scramble: 'LUASU', marks: [0, 1, 3, 4] },
    ],
  },
  {
    num: 76,
    quizId: 'garble-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    clue: "A slow way up and a very quick way down.",
    final: 'MOUNTAIN',
    words: [
      { answer: 'FILMS', scramble: 'LMISF', marks: [3] },
      { answer: 'SHIFT', scramble: 'TIHSF', marks: [4] },
      { answer: 'WOMAN', scramble: 'NWAMO', marks: [1, 3] },
      { answer: 'MUSIC', scramble: 'MUSCI', marks: [1, 3] },
      { answer: 'UNION', scramble: 'OINNU', marks: [1, 4] },
    ],
  },
  {
    num: 77,
    quizId: 'garble-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    clue: "Where a hull is built long before it ever floats.",
    final: 'SHIPYARD',
    words: [
      { answer: 'PARTY', scramble: 'TRPAY', marks: [0] },
      { answer: 'HAPPY', scramble: 'PPYAH', marks: [4] },
      { answer: 'SPENT', scramble: 'SNEPT', marks: [0] },
      { answer: 'BRAIN', scramble: 'ARINB', marks: [1, 3] },
      { answer: 'HANDS', scramble: 'AHDNS', marks: [0, 1, 3] },
    ],
  },
  {
    num: 78,
    quizId: 'garble-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    clue: "A small rocky aquarium the sea leaves behind.",
    final: 'TIDEPOOL',
    words: [
      { answer: 'PUNCH', scramble: 'CUNHP', marks: [0] },
      { answer: 'BUILT', scramble: 'ILUBT', marks: [3, 4] },
      { answer: 'ROUND', scramble: 'UNORD', marks: [4] },
      { answer: 'ABOVE', scramble: 'VEOAB', marks: [2] },
      { answer: 'VIDEO', scramble: 'EDIVO', marks: [1, 3, 4] },
    ],
  },
  {
    num: 79,
    quizId: 'garble-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    clue: "Heather, wind and not a tree in sight.",
    final: 'MOORLAND',
    words: [
      { answer: 'WORLD', scramble: 'RODWL', marks: [1, 2] },
      { answer: 'MONEY', scramble: 'ENOYM', marks: [0, 1, 2] },
      { answer: 'BLANK', scramble: 'AKBNL', marks: [2] },
      { answer: 'MOVED', scramble: 'EODVM', marks: [4] },
      { answer: 'LABEL', scramble: 'BLALE', marks: [0] },
    ],
  },
  {
    num: 80,
    quizId: 'garble-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    clue: "Where the promenade meets the weather.",
    final: 'SEAFRONT',
    words: [
      { answer: 'BRAIN', scramble: 'RIBNA', marks: [1] },
      { answer: 'CARGO', scramble: 'OGRAC', marks: [1] },
      { answer: 'BONDS', scramble: 'DSBNO', marks: [1] },
      { answer: 'FAILS', scramble: 'LIFSA', marks: [0] },
      { answer: 'SPENT', scramble: 'NESPT', marks: [0, 2, 3, 4] },
    ],
  },
  {
    num: 81,
    quizId: 'garble-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    clue: "A dark timber that makes a guitar sing.",
    final: 'ROSEWOOD',
    words: [
      { answer: 'COOPER', scramble: 'OREPCO', marks: [1, 2] },
      { answer: 'WEIGHT', scramble: 'WEIGTH', marks: [0] },
      { answer: 'BODIES', scramble: 'IBDSOE', marks: [2, 4] },
      { answer: 'ROUNDS', scramble: 'SROUND', marks: [5] },
      { answer: 'AFFORD', scramble: 'DRAFFO', marks: [3, 4] },
    ],
  },
  {
    num: 82,
    quizId: 'garble-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    clue: "Little cages of light carried on a pole.",
    final: 'LANTERNS',
    words: [
      { answer: 'GUEST', scramble: 'STGUE', marks: [3] },
      { answer: 'ULTRA', scramble: 'ARULT', marks: [1, 2, 3] },
      { answer: 'VENUE', scramble: 'NVEEU', marks: [1, 2] },
      { answer: 'MONEY', scramble: 'MNOEY', marks: [2] },
      { answer: 'ALBUM', scramble: 'AMBUL', marks: [0] },
    ],
  },
  {
    num: 83,
    quizId: 'garble-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    clue: "It grinds the corn as long as the weather cooperates.",
    final: 'WINDMILL',
    words: [
      { answer: 'MOUNT', scramble: 'NTOMU', marks: [0, 3] },
      { answer: 'BILLS', scramble: 'SLIBL', marks: [2, 3] },
      { answer: 'WINDS', scramble: 'WISDN', marks: [0, 1] },
      { answer: 'INDIE', scramble: 'NEIDI', marks: [2] },
      { answer: 'BUILT', scramble: 'LBITU', marks: [2] },
    ],
  },
  {
    num: 84,
    quizId: 'garble-9-30-26',
    live: '2026-09-30',
    dateLabel: 'September 30, 2026',
    sunday: false,
    clue: 'What the desert throws when it loses its temper.',
    final: 'SANDSTORM',
    words: [
      { answer: 'SHIRT', scramble: 'ISTRH', marks: [0, 3, 4] },
      { answer: 'ROYAL', scramble: 'OAYLR', marks: [1, 3] },
      { answer: 'HOUND', scramble: 'NUOHD', marks: [3, 4] },
      { answer: 'GROOM', scramble: 'OGMOR', marks: [4] },
      { answer: 'SKULL', scramble: 'LKLSU', marks: [0] },
    ],
  },
  {
    num: 85,
    quizId: 'garble-10-1-26',
    live: '2026-10-01',
    dateLabel: 'October 1, 2026',
    sunday: false,
    clue: 'The drain, showing off.',
    final: 'WHIRLPOOL',
    words: [
      { answer: 'LOCAL', scramble: 'ALLCO', marks: [0] },
      { answer: 'HOWDY', scramble: 'YHODW', marks: [0, 1, 2] },
      { answer: 'CROSS', scramble: 'RSCOS', marks: [1, 2] },
      { answer: 'LOFTY', scramble: 'FYLOT', marks: [0] },
      { answer: 'POLIO', scramble: 'OLPOI', marks: [0, 3] },
    ],
  },
  {
    num: 86,
    quizId: 'garble-10-2-26',
    live: '2026-10-02',
    dateLabel: 'October 2, 2026',
    sunday: false,
    clue: 'A contract with no paperwork.',
    final: 'HANDSHAKE',
    words: [
      { answer: 'GLAND', scramble: 'NDGLA', marks: [2, 4] },
      { answer: 'LIGHT', scramble: 'IHTLG', marks: [3] },
      { answer: 'FLUSH', scramble: 'SFUHL', marks: [3, 4] },
      { answer: 'FLUKE', scramble: 'UEKFL', marks: [3, 4] },
      { answer: 'MANGA', scramble: 'ANGMA', marks: [1, 2] },
    ],
  },
  {
    num: 87,
    quizId: 'garble-10-3-26',
    live: '2026-10-03',
    dateLabel: 'October 3, 2026',
    sunday: false,
    clue: 'A rock you are pleased to hit.',
    final: 'MILESTONE',
    words: [
      { answer: 'FAIRY', scramble: 'YARFI', marks: [2] },
      { answer: 'THEME', scramble: 'TEMEH', marks: [2, 3] },
      { answer: 'FILTH', scramble: 'TFIHL', marks: [2, 3] },
      { answer: 'BATON', scramble: 'NBTAO', marks: [3, 4] },
      { answer: 'GENES', scramble: 'NEESG', marks: [1, 4] },
    ],
  },
  {
    num: 88,
    quizId: 'garble-10-4-26',
    live: '2026-10-04',
    dateLabel: 'October 4, 2026',
    sunday: true,
    clue: 'Straw man, literally, and it works.',
    final: 'SCARECROW',
    words: [
      { answer: 'HOSEYS', scramble: 'EHYSOS', marks: [1, 3, 5] },
      { answer: 'ARRAYS', scramble: 'SYARRA', marks: [1, 2, 3] },
      { answer: 'CILIUM', scramble: 'MCIUIL', marks: [0] },
      { answer: 'COPPRA', scramble: 'APCPOR', marks: [0] },
      { answer: 'WALKER', scramble: 'KLERWA', marks: [0] },
    ],
  },
  {
    num: 89,
    quizId: 'garble-10-5-26',
    live: '2026-10-05',
    dateLabel: 'October 5, 2026',
    sunday: false,
    clue: 'The one drop nobody gets hurt in.',
    final: 'NIGHTFALL',
    words: [
      { answer: 'MATTE', scramble: 'TTMEA', marks: [1, 3] },
      { answer: 'TYING', scramble: 'YNGIT', marks: [2, 3, 4] },
      { answer: 'ALOHA', scramble: 'OALAH', marks: [1, 3] },
      { answer: 'PLUME', scramble: 'ULMEP', marks: [1] },
      { answer: 'FRAME', scramble: 'MFEAR', marks: [0] },
    ],
  },
  {
    num: 90,
    quizId: 'garble-10-6-26',
    live: '2026-10-06',
    dateLabel: 'October 6, 2026',
    sunday: false,
    clue: 'The slow way between floors, one promise at a time.',
    final: 'STAIRCASE',
    words: [
      { answer: 'LATCH', scramble: 'TLCAH', marks: [1, 2, 3] },
      { answer: 'POISE', scramble: 'OPIES', marks: [2, 3, 4] },
      { answer: 'CURRY', scramble: 'RYUCR', marks: [3] },
      { answer: 'SAVVY', scramble: 'VSYVA', marks: [1] },
      { answer: 'SHEEN', scramble: 'SEHNE', marks: [0] },
    ],
  },
  {
    num: 91,
    quizId: 'garble-10-7-26',
    live: '2026-10-07',
    dateLabel: 'October 7, 2026',
    sunday: false,
    clue: 'The bloom that always knows which way to look.',
    final: 'SUNFLOWER',
    words: [
      { answer: 'ROUGH', scramble: 'UGROH', marks: [0, 1] },
      { answer: 'WALLY', scramble: 'ALLYW', marks: [0, 2] },
      { answer: 'GULLY', scramble: 'LUGYL', marks: [1] },
      { answer: 'TOKEN', scramble: 'TKNOE', marks: [3, 4] },
      { answer: 'STAFF', scramble: 'TFSAF', marks: [0, 4] },
    ],
  },
  {
    num: 92,
    quizId: 'garble-10-8-26',
    live: '2026-10-08',
    dateLabel: 'October 8, 2026',
    sunday: false,
    clue: 'A river that gave up on gravity negotiations.',
    final: 'WATERFALL',
    words: [
      { answer: 'BRILL', scramble: 'RILLB', marks: [1, 3, 4] },
      { answer: 'AWARD', scramble: 'ADRWA', marks: [0, 1, 2] },
      { answer: 'PETTY', scramble: 'YTTPE', marks: [3] },
      { answer: 'MERRY', scramble: 'RREMY', marks: [1] },
      { answer: 'FURRY', scramble: 'RUFYR', marks: [0] },
    ],
  },
  {
    num: 93,
    quizId: 'garble-10-9-26',
    live: '2026-10-09',
    dateLabel: 'October 9, 2026',
    sunday: false,
    clue: 'Three feet of judgement.',
    final: 'YARDSTICK',
    words: [
      { answer: 'FINCH', scramble: 'CIHNF', marks: [3] },
      { answer: 'MOUND', scramble: 'DUONM', marks: [4] },
      { answer: 'HARSH', scramble: 'ARSHH', marks: [1, 2, 3] },
      { answer: 'KITTY', scramble: 'TKYTI', marks: [0, 3, 4] },
      { answer: 'QUICK', scramble: 'CKQUI', marks: [2] },
    ],
  },
  {
    num: 94,
    quizId: 'garble-10-10-26',
    live: '2026-10-10',
    dateLabel: 'October 10, 2026',
    sunday: false,
    clue: 'Praise for anything that never surprises you.',
    final: 'CLOCKWORK',
    words: [
      { answer: 'JERKY', scramble: 'YEJRK', marks: [2, 3] },
      { answer: 'FLOCK', scramble: 'CFLKO', marks: [2, 4] },
      { answer: 'JOLLY', scramble: 'LLYJO', marks: [1, 2] },
      { answer: 'WEAVE', scramble: 'WAEEV', marks: [0] },
      { answer: 'CROCK', scramble: 'KRCOC', marks: [0, 3] },
    ],
  },
  {
    num: 95,
    quizId: 'garble-10-11-26',
    live: '2026-10-11',
    dateLabel: 'October 11, 2026',
    sunday: true,
    clue: 'Where the rooster files his complaints.',
    final: 'FARMHOUSE',
    words: [
      { answer: 'KOUROI', scramble: 'IRKOUO', marks: [2] },
      { answer: 'CURARI', scramble: 'RAIRUC', marks: [3, 4] },
      { answer: 'CHIMPS', scramble: 'SMCHPI', marks: [1, 3] },
      { answer: 'EPOPTS', scramble: 'TPSEPO', marks: [0, 2, 5] },
      { answer: 'HUFFED', scramble: 'FDEUHF', marks: [2] },
    ],
  },
  {
    num: 96,
    quizId: 'garble-10-12-26',
    live: '2026-10-12',
    dateLabel: 'October 12, 2026',
    sunday: false,
    clue: 'All sting, no spine.',
    final: 'JELLYFISH',
    words: [
      { answer: 'VAULT', scramble: 'ULAVT', marks: [3] },
      { answer: 'FIXED', scramble: 'XFDEI', marks: [0, 1, 3] },
      { answer: 'AMUSE', scramble: 'EAMSU', marks: [3] },
      { answer: 'JUICE', scramble: 'IEUJC', marks: [0] },
      { answer: 'HILLY', scramble: 'YLILH', marks: [0, 2, 4] },
    ],
  },
  {
    num: 97,
    quizId: 'garble-10-13-26',
    live: '2026-10-13',
    dateLabel: 'October 13, 2026',
    sunday: false,
    clue: 'A seat no toad has ever used.',
    final: 'TOADSTOOL',
    words: [
      { answer: 'GRAPH', scramble: 'RAPHG', marks: [2] },
      { answer: 'LATTE', scramble: 'TLETA', marks: [0, 2, 3] },
      { answer: 'BASIC', scramble: 'CABSI', marks: [2] },
      { answer: 'DODGY', scramble: 'ODDYG', marks: [1, 2] },
      { answer: 'TOOTH', scramble: 'THTOO', marks: [1, 2] },
    ],
  },
  {
    num: 98,
    quizId: 'garble-10-14-26',
    live: '2026-10-14',
    dateLabel: 'October 14, 2026',
    sunday: false,
    clue: 'Money the tree dropped.',
    final: 'WINDFALL',
    words: [
      { answer: 'BLEND', scramble: 'NEDBL', marks: [1, 4] },
      { answer: 'BRINK', scramble: 'RKNBI', marks: [2] },
      { answer: 'WHINE', scramble: 'EWNHI', marks: [0] },
      { answer: 'FELON', scramble: 'ENLFO', marks: [0, 2, 4] },
      { answer: 'KRAFT', scramble: 'RAKTF', marks: [2] },
    ],
  },
  {
    num: 99,
    quizId: 'garble-10-15-26',
    live: '2026-10-15',
    dateLabel: 'October 15, 2026',
    sunday: false,
    clue: 'Portable weather immunity.',
    final: 'RAINCOAT',
    words: [
      { answer: 'SILKY', scramble: 'LKIYS', marks: [1] },
      { answer: 'CLASS', scramble: 'SCLSA', marks: [0, 2] },
      { answer: 'FLOWN', scramble: 'LFNOW', marks: [2] },
      { answer: 'CRYPT', scramble: 'TPCRY', marks: [4] },
      { answer: 'PRANK', scramble: 'KNARP', marks: [1, 2, 3] },
    ],
  },
  {
    num: 100,
    quizId: 'garble-10-16-26',
    live: '2026-10-16',
    dateLabel: 'October 16, 2026',
    sunday: false,
    clue: 'The sea pulling the rug out.',
    final: 'UNDERTOW',
    words: [
      { answer: 'WAIVE', scramble: 'VEIAW', marks: [4] },
      { answer: 'ROWAN', scramble: 'NWROA', marks: [0, 1] },
      { answer: 'TRIAD', scramble: 'IARDT', marks: [4] },
      { answer: 'SWUNG', scramble: 'SGWUN', marks: [1, 2, 3] },
      { answer: 'QUART', scramble: 'RTAQU', marks: [4] },
    ],
  },
  {
    num: 101,
    quizId: 'garble-10-17-26',
    live: '2026-10-17',
    dateLabel: 'October 17, 2026',
    sunday: false,
    clue: 'How two pieces of wood agree.',
    final: 'DOVETAIL',
    words: [
      { answer: 'BAKED', scramble: 'KDBAE', marks: [1] },
      { answer: 'ALLEY', scramble: 'YLELA', marks: [2, 3] },
      { answer: 'COUNT', scramble: 'NUCTO', marks: [1, 4] },
      { answer: 'KINDS', scramble: 'SNKDI', marks: [1, 3] },
      { answer: 'NAVAL', scramble: 'ALNVA', marks: [2] },
    ],
  },
  {
    num: 102,
    quizId: 'garble-10-18-26',
    live: '2026-10-18',
    dateLabel: 'October 18, 2026',
    sunday: true,
    clue: 'A blizzard with a formal invitation.',
    final: 'SNOWSTORM',
    words: [
      { answer: 'RANDAN', scramble: 'NDNARA', marks: [0, 5] },
      { answer: 'SHAKES', scramble: 'EKHSSA', marks: [0, 5] },
      { answer: 'WOOSES', scramble: 'SEOWSO', marks: [0, 1] },
      { answer: 'MYOPIA', scramble: 'MPYOAI', marks: [0, 2] },
      { answer: 'VASTLY', scramble: 'SATYVL', marks: [3] },
    ],
  },
  {
    num: 103,
    quizId: 'garble-10-19-26',
    live: '2026-10-19',
    dateLabel: 'October 19, 2026',
    sunday: false,
    clue: 'News from a place that may not be there any more.',
    final: 'STARLIGHT',
    words: [
      { answer: 'TAKIN', scramble: 'NTIAK', marks: [1, 3] },
      { answer: 'GRAFT', scramble: 'FRTAG', marks: [0, 4] },
      { answer: 'HAIRY', scramble: 'RHIYA', marks: [0, 3] },
      { answer: 'PATTY', scramble: 'TTYPA', marks: [3] },
      { answer: 'BLISS', scramble: 'ISSBL', marks: [1, 4] },
    ],
  },
  {
    num: 104,
    quizId: 'garble-10-20-26',
    live: '2026-10-20',
    dateLabel: 'October 20, 2026',
    sunday: false,
    clue: 'The oldest seat with a mind of its own.',
    final: 'HORSEBACK',
    words: [
      { answer: 'TRAIT', scramble: 'AIRTT', marks: [1] },
      { answer: 'POUCH', scramble: 'OHCPU', marks: [1, 3] },
      { answer: 'PATIO', scramble: 'OTPIA', marks: [1] },
      { answer: 'BLEAK', scramble: 'LEABK', marks: [0, 2, 4] },
      { answer: 'HIGHS', scramble: 'ISHGH', marks: [0, 4] },
    ],
  },
  {
    num: 105,
    quizId: 'garble-10-21-26',
    live: '2026-10-21',
    dateLabel: 'October 21, 2026',
    sunday: false,
    clue: 'The room member that only shows up in winter.',
    final: 'FIREPLACE',
    words: [
      { answer: 'PLAID', scramble: 'DLIAP', marks: [0, 2, 3] },
      { answer: 'SLASH', scramble: 'LASHS', marks: [1] },
      { answer: 'THIEF', scramble: 'EIFHT', marks: [4] },
      { answer: 'PENCE', scramble: 'ECEPN', marks: [3] },
      { answer: 'CREME', scramble: 'EERCM', marks: [1, 2, 4] },
    ],
  },
  {
    num: 106,
    quizId: 'garble-10-22-26',
    live: '2026-10-22',
    dateLabel: 'October 22, 2026',
    sunday: false,
    clue: 'Where the seats watch and the players show off.',
    final: 'GRANDSTAND',
    words: [
      { answer: 'DOUGH', scramble: 'UGDOH', marks: [0, 3] },
      { answer: 'RANDY', scramble: 'ADNYR', marks: [0] },
      { answer: 'TAKEN', scramble: 'ENAKT', marks: [0, 1, 4] },
      { answer: 'PADDY', scramble: 'PDAYD', marks: [1, 3] },
      { answer: 'SHINY', scramble: 'YISNH', marks: [0, 3] },
    ],
  },
  {
    num: 107,
    quizId: 'garble-10-23-26',
    live: '2026-10-23',
    dateLabel: 'October 23, 2026',
    sunday: false,
    clue: 'The one who came to the dance to hold up the room.',
    final: 'WALLFLOWER',
    words: [
      { answer: 'JOKER', scramble: 'REJKO', marks: [1] },
      { answer: 'FAULT', scramble: 'AUTLF', marks: [0, 1] },
      { answer: 'KELLY', scramble: 'LEYKL', marks: [1, 2, 3] },
      { answer: 'BRAWL', scramble: 'RBLWA', marks: [1, 3, 4] },
      { answer: 'WACKY', scramble: 'CWKAY', marks: [0] },
    ],
  },
  {
    num: 108,
    quizId: 'garble-10-24-26',
    live: '2026-10-24',
    dateLabel: 'October 24, 2026',
    sunday: false,
    clue: 'The soil quietly ploughing itself.',
    final: 'EARTHWORM',
    words: [
      { answer: 'BOWER', scramble: 'ERWBO', marks: [1, 2, 3] },
      { answer: 'FIFTY', scramble: 'YTFIF', marks: [3] },
      { answer: 'CHAMP', scramble: 'AHPCM', marks: [2, 3] },
      { answer: 'HOVER', scramble: 'RVOHE', marks: [0, 4] },
      { answer: 'GROWL', scramble: 'OLRGW', marks: [1] },
    ],
  },
  {
    num: 109,
    quizId: 'garble-10-25-26',
    live: '2026-10-25',
    dateLabel: 'October 25, 2026',
    sunday: true,
    clue: 'A trail that only birds ever profit from.',
    final: 'BREADCRUMB',
    words: [
      { answer: 'DURGAN', scramble: 'GANRDU', marks: [2, 4] },
      { answer: 'EXHUME', scramble: 'EMXHEU', marks: [4] },
      { answer: 'BRACTS', scramble: 'CARSBT', marks: [0, 1, 3] },
      { answer: 'UNPINS', scramble: 'SPUNNI', marks: [0] },
      { answer: 'DAYBED', scramble: 'BYDADE', marks: [0, 3, 4] },
    ],
  },
  {
    num: 110,
    quizId: 'garble-10-26-26',
    live: '2026-10-26',
    dateLabel: 'October 26, 2026',
    sunday: false,
    clue: 'A carpenter who works from the head down.',
    final: 'WOODPECKER',
    words: [
      { answer: 'QUARK', scramble: 'ARUQK', marks: [3] },
      { answer: 'CROWN', scramble: 'WNRCO', marks: [0, 2, 3] },
      { answer: 'PIECE', scramble: 'ECIEP', marks: [0, 2, 4] },
      { answer: 'BLOWN', scramble: 'BONLW', marks: [2] },
      { answer: 'DRINK', scramble: 'DNKIR', marks: [0, 4] },
    ],
  },
  {
    num: 111,
    quizId: 'garble-10-27-26',
    live: '2026-10-27',
    dateLabel: 'October 27, 2026',
    sunday: false,
    clue: 'A sweet that pretends it is doing you good.',
    final: 'PEPPERMINT',
    words: [
      { answer: 'DRANK', scramble: 'KRDAN', marks: [3] },
      { answer: 'ADMIT', scramble: 'ATIDM', marks: [2, 3, 4] },
      { answer: 'SIEVE', scramble: 'VESEI', marks: [2, 4] },
      { answer: 'PIPER', scramble: 'REPIP', marks: [0] },
      { answer: 'UPPER', scramble: 'UERPP', marks: [1, 2, 4] },
    ],
  },
  {
    num: 112,
    quizId: 'garble-10-28-26',
    live: '2026-10-28',
    dateLabel: 'October 28, 2026',
    sunday: false,
    clue: 'Between the meal and the furniture, taking all the risk.',
    final: 'TABLECLOTH',
    words: [
      { answer: 'TRUMP', scramble: 'PTURM', marks: [0] },
      { answer: 'FATTY', scramble: 'TTFAY', marks: [1] },
      { answer: 'BEECH', scramble: 'EHEBC', marks: [0, 4] },
      { answer: 'CLOCK', scramble: 'OCCKL', marks: [1, 2, 3] },
      { answer: 'FLUTE', scramble: 'UFETL', marks: [1, 3, 4] },
    ],
  },
  {
    num: 113,
    quizId: 'garble-10-29-26',
    live: '2026-10-29',
    dateLabel: 'October 29, 2026',
    sunday: false,
    clue: 'A road that says no.',
    final: 'DRAWBRIDGE',
    words: [
      { answer: 'HORDE', scramble: 'EHROD', marks: [3] },
      { answer: 'ABOUT', scramble: 'OUTBA', marks: [1] },
      { answer: 'WAGED', scramble: 'GEDAW', marks: [1, 3, 4] },
      { answer: 'GRIME', scramble: 'EIMRG', marks: [0, 1, 2] },
      { answer: 'WAFER', scramble: 'EWFRA', marks: [0, 4] },
    ],
  },
  {
    num: 114,
    quizId: 'garble-10-30-26',
    live: '2026-10-30',
    dateLabel: 'October 30, 2026',
    sunday: false,
    clue: 'Spotted, and welcome anyway.',
    final: 'LADYBIRD',
    words: [
      { answer: 'BOUND', scramble: 'ODUBN', marks: [4] },
      { answer: 'YUMMY', scramble: 'MMUYY', marks: [4] },
      { answer: 'CABLE', scramble: 'AEBCL', marks: [1, 2, 3] },
      { answer: 'BLIND', scramble: 'BNDLI', marks: [4] },
      { answer: 'BIKER', scramble: 'RKIEB', marks: [1, 4] },
    ],
  },
  {
    num: 115,
    quizId: 'garble-10-31-26',
    live: '2026-10-31',
    dateLabel: 'October 31, 2026',
    sunday: false,
    clue: 'The only worm anyone waits up for.',
    final: 'GLOWWORM',
    words: [
      { answer: 'CLAMP', scramble: 'ACMLP', marks: [3] },
      { answer: 'PRINT', scramble: 'TPIRN', marks: [1] },
      { answer: 'LOTTO', scramble: 'TOLOT', marks: [0, 1, 4] },
      { answer: 'WEDGE', scramble: 'GDWEE', marks: [0, 3] },
      { answer: 'CLOWN', scramble: 'LOCNW', marks: [3] },
    ],
  },
  {
    num: 116,
    quizId: 'garble-11-1-26',
    live: '2026-11-01',
    dateLabel: 'November 1, 2026',
    sunday: true,
    clue: 'Strikes while the iron is hot, and gets paid for it.',
    final: 'BLACKSMITH',
    words: [
      { answer: 'STIGMA', scramble: 'MSTGAI', marks: [2] },
      { answer: 'HEALER', scramble: 'RLHEEA', marks: [0, 2] },
      { answer: 'AMBUSH', scramble: 'BHSAUM', marks: [1, 2, 4] },
      { answer: 'KETTLE', scramble: 'TELEKT', marks: [0, 4] },
      { answer: 'STRICT', scramble: 'RCSTIT', marks: [1, 4] },
    ],
  },
  {
    num: 117,
    quizId: 'garble-11-2-26',
    live: '2026-11-02',
    dateLabel: 'November 2, 2026',
    sunday: false,
    clue: 'Half of a pair that only works as a team.',
    final: 'CHOPSTICK',
    words: [
      { answer: 'PICKY', scramble: 'CYPIK', marks: [0, 2, 3] },
      { answer: 'CIVIL', scramble: 'LVCII', marks: [0] },
      { answer: 'MOUTH', scramble: 'TOMHU', marks: [1, 4] },
      { answer: 'SWIFT', scramble: 'ITFSW', marks: [0, 4] },
      { answer: 'VITAL', scramble: 'ATILV', marks: [1] },
    ],
  },
  {
    num: 118,
    quizId: 'garble-11-3-26',
    live: '2026-11-03',
    dateLabel: 'November 3, 2026',
    sunday: false,
    clue: 'A window with its head in the clouds.',
    final: 'SKYLIGHT',
    words: [
      { answer: 'THICK', scramble: 'CIHTK', marks: [1] },
      { answer: 'SHAKY', scramble: 'SAKYH', marks: [0, 3] },
      { answer: 'VIVID', scramble: 'IVDVI', marks: [3] },
      { answer: 'GOOFY', scramble: 'YFGOO', marks: [0, 4] },
      { answer: 'FATAL', scramble: 'AFTLA', marks: [2, 4] },
    ],
  },
  {
    num: 119,
    quizId: 'garble-11-4-26',
    live: '2026-11-04',
    dateLabel: 'November 4, 2026',
    sunday: false,
    clue: 'Devours every chapter and never gains a pound.',
    final: 'BOOKWORM',
    words: [
      { answer: 'FLANK', scramble: 'NLKFA', marks: [4] },
      { answer: 'EERIE', scramble: 'EIEER', marks: [2] },
      { answer: 'WOODY', scramble: 'DOYOW', marks: [0, 1, 2] },
      { answer: 'JUMBO', scramble: 'UJBOM', marks: [2, 3] },
      { answer: 'SNOWY', scramble: 'NSOYW', marks: [2] },
    ],
  },
  {
    num: 120,
    quizId: 'garble-11-5-26',
    live: '2026-11-05',
    dateLabel: 'November 5, 2026',
    sunday: false,
    clue: "The evergreen's scaly little seed vault.",
    final: 'PINECONE',
    words: [
      { answer: 'AIDED', scramble: 'DDEAI', marks: [1, 3] },
      { answer: 'PHONY', scramble: 'HNPOY', marks: [3] },
      { answer: 'EMPTY', scramble: 'MPTEY', marks: [0, 2] },
      { answer: 'INBOX', scramble: 'XBNOI', marks: [1, 3] },
      { answer: 'LYRIC', scramble: 'LRICY', marks: [4] },
    ],
  },
  {
    num: 121,
    quizId: 'garble-11-6-26',
    live: '2026-11-06',
    dateLabel: 'November 6, 2026',
    sunday: false,
    clue: 'One press and the whole house knows.',
    final: 'DOORBELL',
    words: [
      { answer: 'BLOND', scramble: 'LNDOB', marks: [1, 4] },
      { answer: 'UNCLE', scramble: 'LUECN', marks: [3] },
      { answer: 'EXCEL', scramble: 'XEECL', marks: [0] },
      { answer: 'PRIOR', scramble: 'IOPRR', marks: [1] },
      { answer: 'TABOO', scramble: 'OTOAB', marks: [2, 3, 4] },
    ],
  },
  {
    num: 122,
    quizId: 'garble-11-7-26',
    live: '2026-11-07',
    dateLabel: 'November 7, 2026',
    sunday: false,
    clue: 'Starts small, rolls downhill, gets out of hand.',
    final: 'SNOWBALL',
    words: [
      { answer: 'AWFUL', scramble: 'LFAUW', marks: [1, 4] },
      { answer: 'VALID', scramble: 'IVADL', marks: [2] },
      { answer: 'LIMBO', scramble: 'LOBMI', marks: [3, 4] },
      { answer: 'NANNY', scramble: 'YNNAN', marks: [0, 1] },
      { answer: 'SALSA', scramble: 'ASLAS', marks: [0] },
    ],
  },
  {
    num: 123,
    quizId: 'garble-11-8-26',
    live: '2026-11-08',
    dateLabel: 'November 8, 2026',
    sunday: true,
    clue: 'Stubborn from the top down.',
    final: 'HEADSTRONG',
    words: [
      { answer: 'DEPICT', scramble: 'CDTPIE', marks: [5] },
      { answer: 'WRIGHT', scramble: 'GTWRIH', marks: [1, 3] },
      { answer: 'ZODIAC', scramble: 'ZIOACD', marks: [1, 2, 4] },
      { answer: 'SKETCH', scramble: 'SCHKET', marks: [0, 2, 5] },
      { answer: 'POISON', scramble: 'OONISP', marks: [5] },
    ],
  },
  {
    num: 124,
    quizId: 'garble-11-9-26',
    live: '2026-11-09',
    dateLabel: 'November 9, 2026',
    sunday: false,
    clue: 'It only whistles once things come to a boil.',
    final: 'TEAKETTLE',
    words: [
      { answer: 'EXERT', scramble: 'ETRXE', marks: [0, 2, 4] },
      { answer: 'LEGAL', scramble: 'GALLE', marks: [4] },
      { answer: 'SWEPT', scramble: 'PTSWE', marks: [2, 4] },
      { answer: 'TRUNK', scramble: 'RKNTU', marks: [0, 4] },
      { answer: 'FAUNA', scramble: 'ANAUF', marks: [4] },
    ],
  },
  {
    num: 125,
    quizId: 'garble-11-10-26',
    live: '2026-11-10',
    dateLabel: 'November 10, 2026',
    sunday: false,
    clue: 'Every letter waiting its turn to be pressed.',
    final: 'KEYBOARD',
    words: [
      { answer: 'BERRY', scramble: 'ERBYR', marks: [4] },
      { answer: 'AUDIO', scramble: 'DIOUA', marks: [0, 2, 4] },
      { answer: 'WRECK', scramble: 'RKWEC', marks: [4] },
      { answer: 'TRUTH', scramble: 'THRUT', marks: [1] },
      { answer: 'ABBEY', scramble: 'BAYBE', marks: [2, 3] },
    ],
  },
  {
    num: 126,
    quizId: 'garble-11-11-26',
    live: '2026-11-11',
    dateLabel: 'November 11, 2026',
    sunday: false,
    clue: 'Luggage that insists on a piggyback ride.',
    final: 'BACKPACK',
    words: [
      { answer: 'LUCKY', scramble: 'CLUYK', marks: [2, 3] },
      { answer: 'APART', scramble: 'PARTA', marks: [1, 2] },
      { answer: 'ICING', scramble: 'IIGCN', marks: [1] },
      { answer: 'TOTAL', scramble: 'TLATO', marks: [3] },
      { answer: 'BULKY', scramble: 'LBYUK', marks: [0, 3] },
    ],
  },
  {
    num: 127,
    quizId: 'garble-11-12-26',
    live: '2026-11-12',
    dateLabel: 'November 12, 2026',
    sunday: false,
    clue: 'Borrowed glow, returned by morning.',
    final: 'MOONLIGHT',
    words: [
      { answer: 'COLON', scramble: 'OCLNO', marks: [1, 3, 4] },
      { answer: 'CHILL', scramble: 'LCHLI', marks: [1, 2, 4] },
      { answer: 'GAUGE', scramble: 'UEAGG', marks: [3] },
      { answer: 'MOTTO', scramble: 'TMOOT', marks: [3] },
      { answer: 'MOTOR', scramble: 'OTROM', marks: [0] },
    ],
  },
  {
    num: 128,
    quizId: 'garble-11-13-26',
    live: '2026-11-13',
    dateLabel: 'November 13, 2026',
    sunday: false,
    clue: 'Where your prints are kept on file.',
    final: 'FINGERTIP',
    words: [
      { answer: 'POPPY', scramble: 'PPYOP', marks: [3] },
      { answer: 'AWARE', scramble: 'ERAWA', marks: [3] },
      { answer: 'CHICK', scramble: 'CKHIC', marks: [2] },
      { answer: 'TIGER', scramble: 'RETIG', marks: [0, 2, 3] },
      { answer: 'FUNGI', scramble: 'NGIFU', marks: [0, 2, 4] },
    ],
  },
  {
    num: 129,
    quizId: 'garble-11-14-26',
    live: '2026-11-14',
    dateLabel: 'November 14, 2026',
    sunday: false,
    clue: 'A clock that runs on sand, not batteries.',
    final: 'HOURGLASS',
    words: [
      { answer: 'CRUSH', scramble: 'SHCUR', marks: [1, 2, 4] },
      { answer: 'TALLY', scramble: 'LYATL', marks: [1, 2] },
      { answer: 'STONY', scramble: 'TONSY', marks: [0] },
      { answer: 'PROOF', scramble: 'ROOFP', marks: [2] },
      { answer: 'GRASS', scramble: 'SGRAS', marks: [0, 3] },
    ],
  },
  {
    num: 130,
    quizId: 'garble-11-15-26',
    live: '2026-11-15',
    dateLabel: 'November 15, 2026',
    sunday: true,
    clue: "What's left after the cream makes its escape.",
    final: 'BUTTERMILK',
    words: [
      { answer: 'PURITY', scramble: 'URTYIP', marks: [1, 3, 4] },
      { answer: 'CAMERA', scramble: 'AMCAER', marks: [4] },
      { answer: 'BALLOT', scramble: 'OLBTAL', marks: [2, 5] },
      { answer: 'MAKING', scramble: 'AMNKGI', marks: [0, 2] },
      { answer: 'BEHIND', scramble: 'EHBDNI', marks: [0, 1] },
    ],
  },
  {
    num: 131,
    quizId: 'garble-11-16-26',
    live: '2026-11-16',
    dateLabel: 'November 16, 2026',
    sunday: false,
    clue: 'The mattress in its Sunday best.',
    final: 'BEDSPREAD',
    words: [
      { answer: 'BLUFF', scramble: 'FUFBL', marks: [0] },
      { answer: 'QUAKE', scramble: 'AQKUE', marks: [4] },
      { answer: 'ABIDE', scramble: 'EDABI', marks: [0, 3, 4] },
      { answer: 'PORCH', scramble: 'COPHR', marks: [0, 2] },
      { answer: 'MIDST', scramble: 'TISMD', marks: [2, 3] },
    ],
  },
  {
    num: 132,
    quizId: 'garble-11-17-26',
    live: '2026-11-17',
    dateLabel: 'November 17, 2026',
    sunday: false,
    clue: 'A grid where every answer has to get along with its neighbors.',
    final: 'CROSSWORD',
    words: [
      { answer: 'LOUSY', scramble: 'ULYSO', marks: [1, 3] },
      { answer: 'FOCUS', scramble: 'SCFOU', marks: [1, 4] },
      { answer: 'DRAWN', scramble: 'DNWAR', marks: [0, 1, 3] },
      { answer: 'HAVOC', scramble: 'VOAHC', marks: [4] },
      { answer: 'QUERY', scramble: 'EYQUR', marks: [3] },
    ],
  },
  {
    num: 133,
    quizId: 'garble-11-18-26',
    live: '2026-11-18',
    dateLabel: 'November 18, 2026',
    sunday: false,
    clue: "The ship's plan B.",
    final: 'LIFEBOAT',
    words: [
      { answer: 'ROVER', scramble: 'EVRRO', marks: [3] },
      { answer: 'ARROW', scramble: 'RWOAR', marks: [0, 3] },
      { answer: 'AISLE', scramble: 'LSAIE', marks: [1] },
      { answer: 'BLUNT', scramble: 'NLTUB', marks: [0, 4] },
      { answer: 'FOCAL', scramble: 'OCAFL', marks: [0, 4] },
    ],
  },
  {
    num: 134,
    quizId: 'garble-11-19-26',
    live: '2026-11-19',
    dateLabel: 'November 19, 2026',
    sunday: false,
    clue: 'Where the whole story fits, briefly.',
    final: 'NUTSHELL',
    words: [
      { answer: 'LINER', scramble: 'ERNIL', marks: [2] },
      { answer: 'SEIZE', scramble: 'ISZEE', marks: [0] },
      { answer: 'CLOAK', scramble: 'OCAKL', marks: [1] },
      { answer: 'ELITE', scramble: 'TLEEI', marks: [0, 1, 3] },
      { answer: 'YOUTH', scramble: 'UTYHO', marks: [2, 4] },
    ],
  },
  {
    num: 135,
    quizId: 'garble-11-20-26',
    live: '2026-11-20',
    dateLabel: 'November 20, 2026',
    sunday: false,
    clue: 'Rough around the edges, and proud of it.',
    final: 'SANDPAPER',
    words: [
      { answer: 'PAVED', scramble: 'DPVAE', marks: [0, 4] },
      { answer: 'ANNEX', scramble: 'XNANE', marks: [0, 1] },
      { answer: 'PANIC', scramble: 'INACP', marks: [0, 1] },
      { answer: 'GROSS', scramble: 'RSSOG', marks: [1, 4] },
      { answer: 'JUDGE', scramble: 'UJGDE', marks: [4] },
    ],
  },
  {
    num: 136,
    quizId: 'garble-11-21-26',
    live: '2026-11-21',
    dateLabel: 'November 21, 2026',
    sunday: false,
    clue: 'A summer fruit that is mostly beverage.',
    final: 'WATERMELON',
    words: [
      { answer: 'METAL', scramble: 'ALTME', marks: [0, 1, 3] },
      { answer: 'SIXTH', scramble: 'ISXHT', marks: [3] },
      { answer: 'WAGER', scramble: 'REAWG', marks: [0, 3, 4] },
      { answer: 'CLONE', scramble: 'OENLC', marks: [1, 3] },
      { answer: 'PIVOT', scramble: 'VOTPI', marks: [3] },
    ],
  },
  {
    num: 137,
    quizId: 'garble-11-22-26',
    live: '2026-11-22',
    dateLabel: 'November 22, 2026',
    sunday: true,
    clue: 'Keeps count and never picks a side.',
    final: 'SCOREBOARD',
    words: [
      { answer: 'LOOSEN', scramble: 'SLEONO', marks: [1, 3] },
      { answer: 'MELLOW', scramble: 'OLWELM', marks: [1] },
      { answer: 'CLOUDY', scramble: 'LUCOYD', marks: [0, 2, 4] },
      { answer: 'ROBBER', scramble: 'OERRBB', marks: [3, 5] },
      { answer: 'ABSORB', scramble: 'SOBRBA', marks: [0, 4] },
    ],
  },
  {
    num: 138,
    quizId: 'garble-11-23-26',
    live: '2026-11-23',
    dateLabel: 'November 23, 2026',
    sunday: false,
    clue: "A caterpillar's grand makeover.",
    final: 'BUTTERFLY',
    words: [
      { answer: 'FLUID', scramble: 'FDLUI', marks: [0, 1, 2] },
      { answer: 'BIRCH', scramble: 'IBHRC', marks: [2] },
      { answer: 'TITLE', scramble: 'ETLIT', marks: [0, 2] },
      { answer: 'BORNE', scramble: 'BEORN', marks: [0, 4] },
      { answer: 'SALLY', scramble: 'YLLAS', marks: [4] },
    ],
  },
  {
    num: 139,
    quizId: 'garble-11-24-26',
    live: '2026-11-24',
    dateLabel: 'November 24, 2026',
    sunday: false,
    clue: "The dog's favorite meal, allegedly.",
    final: 'HOMEWORK',
    words: [
      { answer: 'SORRY', scramble: 'RYORS', marks: [2] },
      { answer: 'CHOKE', scramble: 'HOECK', marks: [1, 2, 3] },
      { answer: 'WHARF', scramble: 'FWHRA', marks: [0] },
      { answer: 'IMPLY', scramble: 'MIYPL', marks: [1] },
      { answer: 'MODEM', scramble: 'DEOMM', marks: [1, 3] },
    ],
  },
  {
    num: 140,
    quizId: 'garble-11-25-26',
    live: '2026-11-25',
    dateLabel: 'November 25, 2026',
    sunday: false,
    clue: 'Where the dishes go to bed.',
    final: 'CUPBOARD',
    words: [
      { answer: 'DRAFT', scramble: 'RATFD', marks: [1] },
      { answer: 'WINDY', scramble: 'DYWNI', marks: [3] },
      { answer: 'LUNCH', scramble: 'HNUCL', marks: [1, 3] },
      { answer: 'SPICY', scramble: 'YCISP', marks: [1] },
      { answer: 'ABBOT', scramble: 'TAOBB', marks: [0, 2, 3] },
    ],
  },
  {
    num: 141,
    quizId: 'garble-11-26-26',
    live: '2026-11-26',
    dateLabel: 'November 26, 2026',
    sunday: false,
    clue: 'The only percussion served at the feast.',
    final: 'DRUMSTICK',
    words: [
      { answer: 'GUISE', scramble: 'USEGI', marks: [3] },
      { answer: 'MIMIC', scramble: 'IMMCI', marks: [0, 4] },
      { answer: 'AUDIT', scramble: 'TDIAU', marks: [1, 2, 4] },
      { answer: 'THINK', scramble: 'NIHKT', marks: [4] },
      { answer: 'DRIFT', scramble: 'RIFDT', marks: [1, 2] },
    ],
  },
  {
    num: 142,
    quizId: 'garble-11-27-26',
    live: '2026-11-27',
    dateLabel: 'November 27, 2026',
    sunday: false,
    clue: "The feast's encore performance.",
    final: 'LEFTOVERS',
    words: [
      { answer: 'GRIEF', scramble: 'IFRGE', marks: [1, 3, 4] },
      { answer: 'SMITH', scramble: 'MSIHT', marks: [0] },
      { answer: 'TOXIC', scramble: 'ITCXO', marks: [1] },
      { answer: 'DEITY', scramble: 'YDIET', marks: [3] },
      { answer: 'NOVEL', scramble: 'VLENO', marks: [2, 3, 4] },
    ],
  },
  {
    num: 143,
    quizId: 'garble-11-28-26',
    live: '2026-11-28',
    dateLabel: 'November 28, 2026',
    sunday: false,
    clue: 'The final scene where somebody has to blink.',
    final: 'SHOWDOWN',
    words: [
      { answer: 'WHEAT', scramble: 'THAWE', marks: [0] },
      { answer: 'SWORN', scramble: 'ONWSR', marks: [0, 1, 4] },
      { answer: 'MATCH', scramble: 'HMTAC', marks: [4] },
      { answer: 'POUND', scramble: 'DNUPO', marks: [1, 4] },
      { answer: 'HOLLY', scramble: 'OHYLL', marks: [1] },
    ],
  },
  {
    num: 144,
    quizId: 'garble-11-29-26',
    live: '2026-11-29',
    dateLabel: 'November 29, 2026',
    sunday: true,
    clue: 'No two alike, and none of them last.',
    final: 'SNOWFLAKE',
    words: [
      { answer: 'CANVAS', scramble: 'SNCAAV', marks: [2, 4, 5] },
      { answer: 'COOKED', scramble: 'OOKCDE', marks: [3] },
      { answer: 'STUDIO', scramble: 'SIOUTD', marks: [5] },
      { answer: 'SURFER', scramble: 'RFEURS', marks: [3] },
      { answer: 'FELLOW', scramble: 'LWEFOL', marks: [1, 3, 5] },
    ],
  },
  {
    num: 145,
    quizId: 'garble-11-30-26',
    live: '2026-11-30',
    dateLabel: 'November 30, 2026',
    sunday: false,
    clue: 'A walk where every step is a balancing act.',
    final: 'TIGHTROPE',
    words: [
      { answer: 'CRIME', scramble: 'CEMRI', marks: [1, 2, 4] },
      { answer: 'GUILT', scramble: 'LIGTU', marks: [0, 4] },
      { answer: 'HEFTY', scramble: 'TEHYF', marks: [3] },
      { answer: 'COCOA', scramble: 'OCACO', marks: [3] },
      { answer: 'PINCH', scramble: 'NCHPI', marks: [0, 4] },
    ],
  },
];
