// Puzzle data for Stands, the daily round-robin reconstruction. Imported ONLY
// by the server page (app/stands/page.js), which filters live<=today before
// passing boards to the client.
//
// Everyone played everyone once. Win 3, draw 1, loss 0. The results sheet is
// gone and a handful of facts survive; rebuild every result.
//
// Clue schema (x, y are indexes into teams):
//   beat {x,y}      x beat y
//   drew {x,y}      x and y drew
//   points {x,p}    x finished on p points
//   wins {x,n}      x won exactly n
//   draws {x,n}     x drew exactly n
//   unbeaten {x}    x lost none
//   winless {x}     x won none
//   above {x,y}     x finished strictly above y on points
//   totalDraws {n}  exactly n matches were drawn
//
// LEAK GUARD: the results are NOT stored. Every board is machine-verified
// (scripts/verify-stands.mjs) to admit exactly one table, and to carry a
// MINIMAL clue set: drop any single clue and the table stops being unique. The
// client re-derives the table with the same bounded search.
export const PUZZLES = [
  {
    num: 1, quizId: 'stands-7-24-26', live: '2026-07-24', dateLabel: 'July 24, 2026', sunday: false,
    teams: ['Alderton', 'Brackwell', 'Corvale', 'Dunmoor', 'Eastfield'],
    clues: [
      { type: 'points', x: 1, p: 2 },
      { type: 'points', x: 4, p: 6 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'drew', x: 0, y: 3 },
    ],
  },
  {
    num: 2, quizId: 'stands-7-25-26', live: '2026-07-25', dateLabel: 'July 25, 2026', sunday: false,
    teams: ['Ashcombe', 'Bellhaven', 'Croftwood', 'Dalridge', 'Elmsworth'],
    clues: [
      { type: 'draws', x: 4, n: 1 },
      { type: 'unbeaten', x: 0 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'unbeaten', x: 3 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'wins', x: 1, n: 0 },
      { type: 'draws', x: 1, n: 1 },
    ],
  },
  {
    num: 3, quizId: 'stands-7-26-26', live: '2026-07-26', dateLabel: 'July 26, 2026', sunday: true,
    teams: ['Ardwick', 'Bexley Vale', 'Calderhurst', 'Draymoor', 'Endsleigh', 'Foxholm'],
    clues: [
      { type: 'points', x: 1, p: 6 },
      { type: 'points', x: 5, p: 4 },
      { type: 'unbeaten', x: 4 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'wins', x: 2, n: 3 },
      { type: 'beat', x: 5, y: 2 },
      { type: 'beat', x: 0, y: 5 },
      { type: 'points', x: 0, p: 8 },
      { type: 'totalDraws', n: 4 },
    ],
  },
  {
    num: 4, quizId: 'stands-7-27-26', live: '2026-07-27', dateLabel: 'July 27, 2026', sunday: false,
    teams: ['Alderton', 'Brackwell', 'Corvale', 'Dunmoor', 'Eastfield'],
    clues: [
      { type: 'totalDraws', n: 2 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'winless', x: 2 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'points', x: 3, p: 3 },
      { type: 'unbeaten', x: 0 },
    ],
  },
  {
    num: 5, quizId: 'stands-7-28-26', live: '2026-07-28', dateLabel: 'July 28, 2026', sunday: false,
    teams: ['Ashcombe', 'Bellhaven', 'Croftwood', 'Dalridge', 'Elmsworth'],
    clues: [
      { type: 'above', x: 2, y: 1 },
      { type: 'draws', x: 4, n: 3 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'points', x: 0, p: 0 },
      { type: 'draws', x: 1, n: 1 },
    ],
  },
  {
    num: 6, quizId: 'stands-7-29-26', live: '2026-07-29', dateLabel: 'July 29, 2026', sunday: false,
    teams: ['Ardwick', 'Bexley Vale', 'Calderhurst', 'Draymoor', 'Endsleigh'],
    clues: [
      { type: 'above', x: 2, y: 3 },
      { type: 'draws', x: 0, n: 3 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'points', x: 3, p: 4 },
      { type: 'above', x: 1, y: 2 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'wins', x: 4, n: 2 },
    ],
  },
  {
    num: 7, quizId: 'stands-7-30-26', live: '2026-07-30', dateLabel: 'July 30, 2026', sunday: false,
    teams: ['Alderton', 'Brackwell', 'Corvale', 'Dunmoor', 'Eastfield'],
    clues: [
      { type: 'drew', x: 0, y: 2 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'points', x: 4, p: 5 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'points', x: 2, p: 7 },
      { type: 'winless', x: 1 },
      { type: 'unbeaten', x: 0 },
      { type: 'beat', x: 2, y: 3 },
    ],
  },
  {
    num: 8, quizId: 'stands-7-31-26', live: '2026-07-31', dateLabel: 'July 31, 2026', sunday: false,
    teams: ['Ashcombe', 'Bellhaven', 'Croftwood', 'Dalridge', 'Elmsworth'],
    clues: [
      { type: 'beat', x: 3, y: 4 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'winless', x: 1 },
      { type: 'beat', x: 2, y: 0 },
      { type: 'above', x: 4, y: 3 },
      { type: 'draws', x: 2, n: 2 },
    ],
  },
  {
    num: 9, quizId: 'stands-8-1-26', live: '2026-08-01', dateLabel: 'August 1, 2026', sunday: false,
    teams: ['Ardwick', 'Bexley Vale', 'Calderhurst', 'Draymoor', 'Endsleigh'],
    clues: [
      { type: 'points', x: 3, p: 4 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'points', x: 4, p: 8 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'unbeaten', x: 2 },
      { type: 'wins', x: 1, n: 2 },
    ],
  },
  {
    num: 10, quizId: 'stands-8-2-26', live: '2026-08-02', dateLabel: 'August 2, 2026', sunday: true,
    teams: ['Alderton', 'Brackwell', 'Corvale', 'Dunmoor', 'Eastfield', 'Farrowgate'],
    clues: [
      { type: 'totalDraws', n: 3 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'wins', x: 3, n: 4 },
      { type: 'points', x: 5, p: 10 },
      { type: 'points', x: 2, p: 9 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'above', x: 0, y: 4 },
      { type: 'beat', x: 0, y: 3 },
    ],
  },
  {
    num: 11, quizId: 'stands-8-3-26', live: '2026-08-03', dateLabel: 'August 3, 2026', sunday: false,
    teams: ['Ashcombe', 'Bellhaven', 'Croftwood', 'Dalridge', 'Elmsworth'],
    clues: [
      { type: 'drew', x: 1, y: 3 },
      { type: 'points', x: 3, p: 6 },
      { type: 'above', x: 1, y: 0 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'points', x: 2, p: 7 },
      { type: 'draws', x: 4, n: 0 },
      { type: 'draws', x: 0, n: 2 },
    ],
  },
  {
    num: 12, quizId: 'stands-8-4-26', live: '2026-08-04', dateLabel: 'August 4, 2026', sunday: false,
    teams: ['Ardwick', 'Bexley Vale', 'Calderhurst', 'Draymoor', 'Endsleigh'],
    clues: [
      { type: 'above', x: 0, y: 1 },
      { type: 'points', x: 4, p: 6 },
      { type: 'totalDraws', n: 4 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 2, p: 7 },
      { type: 'above', x: 4, y: 3 },
      { type: 'drew', x: 1, y: 2 },
    ],
  },
  {
    num: 13, quizId: 'stands-8-5-26', live: '2026-08-05', dateLabel: 'August 5, 2026', sunday: false,
    teams: ['Alderton', 'Brackwell', 'Corvale', 'Dunmoor', 'Eastfield'],
    clues: [
      { type: 'wins', x: 4, n: 2 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'draws', x: 3, n: 0 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'above', x: 1, y: 3 },
      { type: 'above', x: 2, y: 1 },
    ],
  },
  {
    num: 14, quizId: 'stands-8-6-26', live: '2026-08-06', dateLabel: 'August 6, 2026', sunday: false,
    teams: ['Ashcombe', 'Bellhaven', 'Croftwood', 'Dalridge', 'Elmsworth'],
    clues: [
      { type: 'points', x: 1, p: 7 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'points', x: 2, p: 7 },
      { type: 'beat', x: 4, y: 0 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'beat', x: 1, y: 0 },
    ],
  },
  {
    num: 15, quizId: 'stands-8-7-26', live: '2026-08-07', dateLabel: 'August 7, 2026', sunday: false,
    teams: ['Ashmore', 'Byrneside', 'Cranmere', 'Darnley', 'Ellerby'],
    clues: [
      { type: 'drew', x: 2, y: 3 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'totalDraws', n: 3 },
      { type: 'points', x: 3, p: 7 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'above', x: 1, y: 0 },
      { type: 'drew', x: 1, y: 4 },
      { type: 'wins', x: 4, n: 3 },
    ],
  },
  {
    num: 16, quizId: 'stands-8-8-26', live: '2026-08-08', dateLabel: 'August 8, 2026', sunday: false,
    teams: ['Ashcombe', 'Barrowfield', 'Chalkwell', 'Denbury', 'Everleigh'],
    clues: [
      { type: 'drew', x: 1, y: 4 },
      { type: 'above', x: 0, y: 4 },
      { type: 'unbeaten', x: 1 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'points', x: 2, p: 4 },
      { type: 'totalDraws', n: 3 },
      { type: 'wins', x: 4, n: 2 },
    ],
  },
  {
    num: 17, quizId: 'stands-8-9-26', live: '2026-08-09', dateLabel: 'August 9, 2026', sunday: true,
    teams: ['Ashmore', 'Burnhill', 'Corvale', 'Darnley', 'Eastfield', 'Fallowdene'],
    clues: [
      { type: 'points', x: 2, p: 4 },
      { type: 'points', x: 0, p: 3 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'beat', x: 5, y: 0 },
      { type: 'beat', x: 5, y: 4 },
      { type: 'drew', x: 3, y: 4 },
      { type: 'beat', x: 2, y: 5 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'points', x: 3, p: 11 },
    ],
  },
  {
    num: 18, quizId: 'stands-8-10-26', live: '2026-08-10', dateLabel: 'August 10, 2026', sunday: false,
    teams: ['Ambleside', 'Blakeney', 'Cotterill', 'Dunmoor', 'Ellerby'],
    clues: [
      { type: 'beat', x: 4, y: 0 },
      { type: 'totalDraws', n: 2 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'winless', x: 1 },
      { type: 'wins', x: 2, n: 3 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'points', x: 4, p: 4 },
    ],
  },
  {
    num: 19, quizId: 'stands-8-11-26', live: '2026-08-11', dateLabel: 'August 11, 2026', sunday: false,
    teams: ['Ashmore', 'Brackwell', 'Comberton', 'Denbury', 'Edenhall'],
    clues: [
      { type: 'above', x: 2, y: 3 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'wins', x: 4, n: 3 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'draws', x: 1, n: 2 },
    ],
  },
  {
    num: 20, quizId: 'stands-8-12-26', live: '2026-08-12', dateLabel: 'August 12, 2026', sunday: false,
    teams: ['Ashmore', 'Burnhill', 'Croftwood', 'Doverleigh', 'Eastfield'],
    clues: [
      { type: 'unbeaten', x: 2 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 0, p: 2 },
      { type: 'above', x: 3, y: 1 },
      { type: 'beat', x: 1, y: 4 },
    ],
  },
  {
    num: 21, quizId: 'stands-8-13-26', live: '2026-08-13', dateLabel: 'August 13, 2026', sunday: false,
    teams: ['Averton', 'Burnhill', 'Comberton', 'Dalridge', 'Esk Vale'],
    clues: [
      { type: 'points', x: 4, p: 0 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'points', x: 2, p: 9 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'beat', x: 0, y: 1 },
    ],
  },
  {
    num: 22, quizId: 'stands-8-14-26', live: '2026-08-14', dateLabel: 'August 14, 2026', sunday: false,
    teams: ['Alderton', 'Burnhill', 'Comberton', 'Denbury', 'Elmsworth'],
    clues: [
      { type: 'draws', x: 3, n: 1 },
      { type: 'wins', x: 4, n: 0 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'above', x: 4, y: 1 },
      { type: 'points', x: 2, p: 7 },
      { type: 'points', x: 0, p: 9 },
    ],
  },
  {
    num: 23, quizId: 'stands-8-15-26', live: '2026-08-15', dateLabel: 'August 15, 2026', sunday: false,
    teams: ['Ashmore', 'Brackwell', 'Croftwood', 'Doverleigh', 'Esk Vale'],
    clues: [
      { type: 'beat', x: 2, y: 4 },
      { type: 'draws', x: 1, n: 0 },
      { type: 'unbeaten', x: 2 },
      { type: 'wins', x: 1, n: 3 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'points', x: 0, p: 1 },
      { type: 'wins', x: 3, n: 2 },
    ],
  },
  {
    num: 24, quizId: 'stands-8-16-26', live: '2026-08-16', dateLabel: 'August 16, 2026', sunday: true,
    teams: ['Ashcombe', 'Bramford', 'Cranmere', 'Denbury', 'Ellerby', 'Fenwick'],
    clues: [
      { type: 'wins', x: 4, n: 3 },
      { type: 'points', x: 4, p: 9 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 0, p: 3 },
      { type: 'above', x: 2, y: 0 },
      { type: 'points', x: 3, p: 11 },
      { type: 'draws', x: 1, n: 3 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'wins', x: 1, n: 1 },
      { type: 'beat', x: 0, y: 2 },
    ],
  },
  {
    num: 25, quizId: 'stands-8-17-26', live: '2026-08-17', dateLabel: 'August 17, 2026', sunday: false,
    teams: ['Arnfield', 'Burnhill', 'Comberton', 'Denbury', 'Edenhall'],
    clues: [
      { type: 'points', x: 3, p: 3 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'points', x: 4, p: 3 },
      { type: 'beat', x: 4, y: 3 },
      { type: 'above', x: 1, y: 0 },
      { type: 'points', x: 2, p: 10 },
    ],
  },
  {
    num: 26, quizId: 'stands-8-18-26', live: '2026-08-18', dateLabel: 'August 18, 2026', sunday: false,
    teams: ['Ambleside', 'Blakeney', 'Comberton', 'Dockwray', 'Ewhurst'],
    clues: [
      { type: 'draws', x: 1, n: 0 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'above', x: 4, y: 3 },
      { type: 'points', x: 2, p: 3 },
      { type: 'points', x: 0, p: 5 },
      { type: 'wins', x: 3, n: 2 },
    ],
  },
  {
    num: 27, quizId: 'stands-8-19-26', live: '2026-08-19', dateLabel: 'August 19, 2026', sunday: false,
    teams: ['Ashmore', 'Bramford', 'Charnwood', 'Dunsmere', 'Everleigh'],
    clues: [
      { type: 'above', x: 0, y: 2 },
      { type: 'draws', x: 2, n: 0 },
      { type: 'wins', x: 3, n: 3 },
      { type: 'points', x: 1, p: 3 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'draws', x: 4, n: 1 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'beat', x: 1, y: 2 },
    ],
  },
  {
    num: 28, quizId: 'stands-8-20-26', live: '2026-08-20', dateLabel: 'August 20, 2026', sunday: false,
    teams: ['Alderton', 'Blakeney', 'Chalkwell', 'Denbury', 'Eastfield'],
    clues: [
      { type: 'points', x: 2, p: 4 },
      { type: 'draws', x: 1, n: 0 },
      { type: 'above', x: 1, y: 3 },
      { type: 'totalDraws', n: 3 },
      { type: 'above', x: 0, y: 1 },
      { type: 'winless', x: 4 },
      { type: 'draws', x: 4, n: 1 },
    ],
  },
  {
    num: 29, quizId: 'stands-8-21-26', live: '2026-08-21', dateLabel: 'August 21, 2026', sunday: false,
    teams: ['Ambleside', 'Byrneside', 'Cotterill', 'Darnley', 'Everleigh'],
    clues: [
      { type: 'drew', x: 1, y: 3 },
      { type: 'unbeaten', x: 0 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'points', x: 3, p: 2 },
      { type: 'points', x: 4, p: 6 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'above', x: 1, y: 3 },
      { type: 'points', x: 2, p: 5 },
    ],
  },
  {
    num: 30, quizId: 'stands-8-22-26', live: '2026-08-22', dateLabel: 'August 22, 2026', sunday: false,
    teams: ['Alderton', 'Bexmoor', 'Corvale', 'Dalridge', 'Ellerby'],
    clues: [
      { type: 'above', x: 1, y: 4 },
      { type: 'winless', x: 2 },
      { type: 'above', x: 3, y: 0 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'wins', x: 4, n: 3 },
      { type: 'draws', x: 2, n: 0 },
    ],
  },
  {
    num: 31, quizId: 'stands-8-23-26', live: '2026-08-23', dateLabel: 'August 23, 2026', sunday: true,
    teams: ['Alderton', 'Bexmoor', 'Chalkwell', 'Darnley', 'Eastfield', 'Fallowdene'],
    clues: [
      { type: 'beat', x: 4, y: 2 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'points', x: 5, p: 9 },
      { type: 'wins', x: 5, n: 3 },
      { type: 'draws', x: 4, n: 2 },
      { type: 'draws', x: 2, n: 3 },
      { type: 'wins', x: 2, n: 0 },
      { type: 'above', x: 5, y: 4 },
      { type: 'above', x: 1, y: 3 },
      { type: 'drew', x: 1, y: 3 },
    ],
  },
  {
    num: 32, quizId: 'stands-8-24-26', live: '2026-08-24', dateLabel: 'August 24, 2026', sunday: false,
    teams: ['Ashmore', 'Bexmoor', 'Charnwood', 'Drayfield', 'Everleigh'],
    clues: [
      { type: 'totalDraws', n: 3 },
      { type: 'points', x: 4, p: 10 },
      { type: 'points', x: 1, p: 4 },
      { type: 'points', x: 0, p: 4 },
      { type: 'drew', x: 3, y: 4 },
      { type: 'above', x: 2, y: 0 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'beat', x: 1, y: 3 },
    ],
  },
  {
    num: 33, quizId: 'stands-8-25-26', live: '2026-08-25', dateLabel: 'August 25, 2026', sunday: false,
    teams: ['Averton', 'Brackwell', 'Corvale', 'Dockwray', 'Everleigh'],
    clues: [
      { type: 'above', x: 3, y: 0 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'points', x: 2, p: 1 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'wins', x: 1, n: 3 },
      { type: 'points', x: 3, p: 7 },
    ],
  },
  {
    num: 34, quizId: 'stands-8-26-26', live: '2026-08-26', dateLabel: 'August 26, 2026', sunday: false,
    teams: ['Ashmore', 'Barrowfield', 'Cotterill', 'Denbury', 'Everleigh'],
    clues: [
      { type: 'drew', x: 1, y: 3 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'points', x: 4, p: 5 },
      { type: 'beat', x: 2, y: 0 },
      { type: 'totalDraws', n: 4 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'above', x: 0, y: 2 },
      { type: 'drew', x: 3, y: 4 },
    ],
  },
  {
    num: 35, quizId: 'stands-8-27-26', live: '2026-08-27', dateLabel: 'August 27, 2026', sunday: false,
    teams: ['Aldwick', 'Bexmoor', 'Calderby', 'Dunmoor', 'Elmsworth'],
    clues: [
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 3, y: 2 },
      { type: 'draws', x: 2, n: 0 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'points', x: 4, p: 4 },
      { type: 'above', x: 2, y: 1 },
      { type: 'above', x: 2, y: 0 },
    ],
  },
  {
    num: 36, quizId: 'stands-8-28-26', live: '2026-08-28', dateLabel: 'August 28, 2026', sunday: false,
    teams: ['Alderton', 'Burnhill', 'Cranmere', 'Doverleigh', 'Ellerby'],
    clues: [
      { type: 'draws', x: 0, n: 0 },
      { type: 'beat', x: 4, y: 0 },
      { type: 'wins', x: 1, n: 2 },
      { type: 'above', x: 0, y: 2 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 3, p: 3 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'points', x: 2, p: 4 },
    ],
  },
  {
    num: 37, quizId: 'stands-8-29-26', live: '2026-08-29', dateLabel: 'August 29, 2026', sunday: false,
    teams: ['Ashcombe', 'Bexmoor', 'Cranmere', 'Darnley', 'Eastfield'],
    clues: [
      { type: 'beat', x: 2, y: 1 },
      { type: 'points', x: 4, p: 4 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'totalDraws', n: 4 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 3, p: 8 },
      { type: 'draws', x: 2, n: 2 },
    ],
  },
  {
    num: 38, quizId: 'stands-8-30-26', live: '2026-08-30', dateLabel: 'August 30, 2026', sunday: true,
    teams: ['Alderton', 'Blakeney', 'Charnwood', 'Dalridge', 'Ewhurst', 'Fenwick'],
    clues: [
      { type: 'totalDraws', n: 4 },
      { type: 'above', x: 2, y: 4 },
      { type: 'drew', x: 1, y: 4 },
      { type: 'points', x: 5, p: 7 },
      { type: 'above', x: 3, y: 0 },
      { type: 'draws', x: 0, n: 2 },
      { type: 'beat', x: 2, y: 5 },
      { type: 'points', x: 3, p: 9 },
      { type: 'beat', x: 3, y: 5 },
      { type: 'points', x: 2, p: 4 },
    ],
  },
  {
    num: 39, quizId: 'stands-8-31-26', live: '2026-08-31', dateLabel: 'August 31, 2026', sunday: false,
    teams: ['Averton', 'Byrneside', 'Cotterill', 'Dockwray', 'Everleigh'],
    clues: [
      { type: 'wins', x: 2, n: 0 },
      { type: 'wins', x: 1, n: 3 },
      { type: 'above', x: 2, y: 4 },
      { type: 'points', x: 0, p: 9 },
      { type: 'points', x: 4, p: 2 },
    ],
  },
  {
    num: 40, quizId: 'stands-9-1-26', live: '2026-09-01', dateLabel: 'September 1, 2026', sunday: false,
    teams: ['Aldwick', 'Bramford', 'Cotterill', 'Darnley', 'Endermere'],
    clues: [
      { type: 'drew', x: 1, y: 4 },
      { type: 'points', x: 4, p: 3 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'above', x: 3, y: 4 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'points', x: 1, p: 4 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'points', x: 2, p: 8 },
    ],
  },
  {
    num: 41, quizId: 'stands-9-2-26', live: '2026-09-02', dateLabel: 'September 2, 2026', sunday: false,
    teams: ['Ambleside', 'Bramford', 'Cotterill', 'Drayfield', 'Ellerby'],
    clues: [
      { type: 'wins', x: 1, n: 1 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'points', x: 4, p: 3 },
      { type: 'points', x: 3, p: 4 },
      { type: 'points', x: 2, p: 4 },
      { type: 'draws', x: 1, n: 2 },
    ],
  },
  {
    num: 42, quizId: 'stands-9-3-26', live: '2026-09-03', dateLabel: 'September 3, 2026', sunday: false,
    teams: ['Ashcombe', 'Byrneside', 'Chalkwell', 'Darnley', 'Eastfield'],
    clues: [
      { type: 'beat', x: 2, y: 3 },
      { type: 'points', x: 2, p: 6 },
      { type: 'points', x: 4, p: 4 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'totalDraws', n: 3 },
      { type: 'winless', x: 0 },
      { type: 'wins', x: 3, n: 2 },
    ],
  },
  {
    num: 43, quizId: 'stands-9-4-26', live: '2026-09-04', dateLabel: 'September 4, 2026', sunday: false,
    teams: ['Arnfield', 'Brackwell', 'Cranmere', 'Dunmoor', 'Esk Vale'],
    clues: [
      { type: 'beat', x: 2, y: 3 },
      { type: 'points', x: 4, p: 5 },
      { type: 'points', x: 3, p: 7 },
      { type: 'wins', x: 0, n: 3 },
      { type: 'draws', x: 1, n: 2 },
    ],
  },
  {
    num: 44, quizId: 'stands-9-5-26', live: '2026-09-05', dateLabel: 'September 5, 2026', sunday: false,
    teams: ['Averton', 'Barrowfield', 'Chalkwell', 'Dunsmere', 'Ewhurst'],
    clues: [
      { type: 'above', x: 0, y: 2 },
      { type: 'totalDraws', n: 2 },
      { type: 'above', x: 1, y: 0 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'wins', x: 3, n: 0 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'beat', x: 1, y: 4 },
    ],
  },
  {
    num: 45, quizId: 'stands-9-6-26', live: '2026-09-06', dateLabel: 'September 6, 2026', sunday: true,
    teams: ['Ashcombe', 'Blakeney', 'Comberton', 'Drayfield', 'Ellerby', 'Fallowdene'],
    clues: [
      { type: 'beat', x: 1, y: 5 },
      { type: 'above', x: 2, y: 5 },
      { type: 'points', x: 0, p: 10 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'draws', x: 3, n: 2 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 1, p: 8 },
      { type: 'wins', x: 4, n: 4 },
    ],
  },
  {
    num: 46, quizId: 'stands-9-7-26', live: '2026-09-07', dateLabel: 'September 7, 2026', sunday: false,
    teams: ['Aldwick', 'Brackwell', 'Corvale', 'Denbury', 'Ewhurst'],
    clues: [
      { type: 'above', x: 2, y: 3 },
      { type: 'beat', x: 2, y: 0 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'wins', x: 3, n: 1 },
      { type: 'points', x: 4, p: 6 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'wins', x: 0, n: 1 },
      { type: 'beat', x: 1, y: 2 },
    ],
  },
  {
    num: 47, quizId: 'stands-9-8-26', live: '2026-09-08', dateLabel: 'September 8, 2026', sunday: false,
    teams: ['Ashmore', 'Barrowfield', 'Chalkwell', 'Dalridge', 'Edenhall'],
    clues: [
      { type: 'beat', x: 1, y: 0 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'above', x: 4, y: 3 },
      { type: 'points', x: 0, p: 5 },
      { type: 'points', x: 2, p: 6 },
      { type: 'above', x: 0, y: 1 },
    ],
  },
  {
    num: 48, quizId: 'stands-9-9-26', live: '2026-09-09', dateLabel: 'September 9, 2026', sunday: false,
    teams: ['Ambleside', 'Blakeney', 'Comberton', 'Drayfield', 'Elmsworth'],
    clues: [
      { type: 'points', x: 0, p: 4 },
      { type: 'points', x: 3, p: 9 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'wins', x: 1, n: 3 },
      { type: 'points', x: 2, p: 7 },
    ],
  },
  {
    num: 49, quizId: 'stands-9-10-26', live: '2026-09-10', dateLabel: 'September 10, 2026', sunday: false,
    teams: ['Alderton', 'Barrowfield', 'Croftwood', 'Dunmoor', 'Everleigh'],
    clues: [
      { type: 'beat', x: 0, y: 2 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 0, p: 5 },
      { type: 'wins', x: 4, n: 2 },
      { type: 'wins', x: 3, n: 3 },
      { type: 'wins', x: 1, n: 2 },
    ],
  },
  {
    num: 50, quizId: 'stands-9-11-26', live: '2026-09-11', dateLabel: 'September 11, 2026', sunday: false,
    teams: ['Averton', 'Bexmoor', 'Calderby', 'Drayfield', 'Elmsworth'],
    clues: [
      { type: 'drew', x: 0, y: 3 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'beat', x: 4, y: 3 },
      { type: 'wins', x: 2, n: 3 },
      { type: 'above', x: 0, y: 2 },
    ],
  },
  {
    num: 51, quizId: 'stands-9-12-26', live: '2026-09-12', dateLabel: 'September 12, 2026', sunday: false,
    teams: ['Ashcombe', 'Byrneside', 'Corvale', 'Dalridge', 'Ellerby'],
    clues: [
      { type: 'drew', x: 0, y: 3 },
      { type: 'points', x: 1, p: 4 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'above', x: 0, y: 2 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 2, p: 5 },
      { type: 'points', x: 3, p: 7 },
    ],
  },
  {
    num: 52, quizId: 'stands-9-13-26', live: '2026-09-13', dateLabel: 'September 13, 2026', sunday: true,
    teams: ['Ambleside', 'Bellhaven', 'Corvale', 'Dalridge', 'Esk Vale', 'Farnleigh'],
    clues: [
      { type: 'wins', x: 0, n: 3 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'above', x: 4, y: 2 },
      { type: 'above', x: 2, y: 1 },
      { type: 'drew', x: 4, y: 5 },
      { type: 'unbeaten', x: 4 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'totalDraws', n: 3 },
      { type: 'points', x: 5, p: 4 },
    ],
  },
  {
    num: 53, quizId: 'stands-9-14-26', live: '2026-09-14', dateLabel: 'September 14, 2026', sunday: false,
    teams: ['Arnfield', 'Bramford', 'Charnwood', 'Dunmoor', 'Endermere'],
    clues: [
      { type: 'points', x: 0, p: 3 },
      { type: 'beat', x: 4, y: 3 },
      { type: 'wins', x: 2, n: 0 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'wins', x: 1, n: 1 },
      { type: 'wins', x: 3, n: 3 },
    ],
  },
  {
    num: 54, quizId: 'stands-9-15-26', live: '2026-09-15', dateLabel: 'September 15, 2026', sunday: false,
    teams: ['Ashmore', 'Bexmoor', 'Cotterill', 'Dunmoor', 'Edenhall'],
    clues: [
      { type: 'drew', x: 1, y: 4 },
      { type: 'unbeaten', x: 4 },
      { type: 'above', x: 3, y: 2 },
      { type: 'points', x: 3, p: 4 },
      { type: 'wins', x: 1, n: 0 },
      { type: 'totalDraws', n: 2 },
    ],
  },
  {
    num: 55, quizId: 'stands-9-16-26', live: '2026-09-16', dateLabel: 'September 16, 2026', sunday: false,
    teams: ['Aldwick', 'Blakeney', 'Calderby', 'Denbury', 'Ellerby'],
    clues: [
      { type: 'unbeaten', x: 3 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'wins', x: 0, n: 0 },
      { type: 'draws', x: 0, n: 2 },
      { type: 'points', x: 4, p: 2 },
      { type: 'drew', x: 1, y: 3 },
      { type: 'wins', x: 2, n: 1 },
    ],
  },
  {
    num: 56, quizId: 'stands-9-17-26', live: '2026-09-17', dateLabel: 'September 17, 2026', sunday: false,
    teams: ['Ashcombe', 'Blakeney', 'Croftwood', 'Darnley', 'Endermere'],
    clues: [
      { type: 'drew', x: 3, y: 4 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'wins', x: 1, n: 1 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'totalDraws', n: 3 },
      { type: 'points', x: 0, p: 10 },
      { type: 'points', x: 4, p: 6 },
    ],
  },
  {
    num: 57, quizId: 'stands-9-18-26', live: '2026-09-18', dateLabel: 'September 18, 2026', sunday: false,
    teams: ['Arnfield', 'Bramford', 'Charnwood', 'Drayfield', 'Endermere'],
    clues: [
      { type: 'draws', x: 0, n: 3 },
      { type: 'points', x: 2, p: 2 },
      { type: 'above', x: 1, y: 4 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'points', x: 4, p: 5 },
    ],
  },
  {
    num: 58, quizId: 'stands-9-19-26', live: '2026-09-19', dateLabel: 'September 19, 2026', sunday: false,
    teams: ['Averton', 'Byrneside', 'Corvale', 'Dunmoor', 'Ewhurst'],
    clues: [
      { type: 'above', x: 0, y: 4 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'draws', x: 2, n: 0 },
      { type: 'winless', x: 2 },
      { type: 'totalDraws', n: 4 },
      { type: 'drew', x: 1, y: 4 },
      { type: 'draws', x: 4, n: 1 },
    ],
  },
  {
    num: 59, quizId: 'stands-9-20-26', live: '2026-09-20', dateLabel: 'September 20, 2026', sunday: true,
    teams: ['Ambleside', 'Bramford', 'Charnwood', 'Denbury', 'Eastfield', 'Fenmarch'],
    clues: [
      { type: 'above', x: 2, y: 4 },
      { type: 'points', x: 1, p: 7 },
      { type: 'beat', x: 2, y: 5 },
      { type: 'points', x: 2, p: 5 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'beat', x: 1, y: 5 },
      { type: 'above', x: 2, y: 5 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'totalDraws', n: 4 },
    ],
  },
  {
    num: 60, quizId: 'stands-9-21-26', live: '2026-09-21', dateLabel: 'September 21, 2026', sunday: false,
    teams: ['Alverston', 'Byrneside', 'Croftwood', 'Doverleigh', 'Endermere'],
    clues: [
      { type: 'beat', x: 2, y: 1 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'wins', x: 0, n: 0 },
      { type: 'wins', x: 4, n: 0 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'draws', x: 3, n: 2 },
      { type: 'wins', x: 1, n: 2 },
    ],
  },
  {
    num: 61, quizId: 'stands-9-22-26', live: '2026-09-22', dateLabel: 'September 22, 2026', sunday: false,
    teams: ['Ashcombe', 'Bramford', 'Comberton', 'Denbury', 'Edenhall'],
    clues: [
      { type: 'beat', x: 3, y: 2 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'points', x: 0, p: 5 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'totalDraws', n: 2 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'winless', x: 1 },
    ],
  },
  {
    num: 62, quizId: 'stands-9-23-26', live: '2026-09-23', dateLabel: 'September 23, 2026', sunday: false,
    teams: ['Averton', 'Burnhill', 'Cotterill', 'Drayfield', 'Ewhurst'],
    clues: [
      { type: 'wins', x: 4, n: 2 },
      { type: 'wins', x: 3, n: 1 },
      { type: 'unbeaten', x: 4 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'drew', x: 3, y: 4 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'draws', x: 1, n: 1 },
    ],
  },
  {
    num: 63, quizId: 'stands-9-24-26', live: '2026-09-24', dateLabel: 'September 24, 2026', sunday: false,
    teams: ['Ashcombe', 'Bexmoor', 'Cotterill', 'Doverleigh', 'Esk Vale'],
    clues: [
      { type: 'above', x: 4, y: 2 },
      { type: 'points', x: 0, p: 12 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'wins', x: 3, n: 1 },
      { type: 'totalDraws', n: 1 },
      { type: 'points', x: 1, p: 7 },
    ],
  },
  {
    num: 64, quizId: 'stands-9-25-26', live: '2026-09-25', dateLabel: 'September 25, 2026', sunday: false,
    teams: ['Arnfield', 'Bexmoor', 'Croftwood', 'Dunmoor', 'Elmsworth'],
    clues: [
      { type: 'points', x: 1, p: 4 },
      { type: 'points', x: 2, p: 2 },
      { type: 'draws', x: 3, n: 0 },
      { type: 'above', x: 0, y: 1 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'points', x: 4, p: 9 },
    ],
  },
  {
    num: 65, quizId: 'stands-9-26-26', live: '2026-09-26', dateLabel: 'September 26, 2026', sunday: false,
    teams: ['Alderton', 'Bexmoor', 'Croftwood', 'Dalridge', 'Everleigh'],
    clues: [
      { type: 'draws', x: 3, n: 2 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 4, p: 5 },
      { type: 'above', x: 3, y: 2 },
      { type: 'points', x: 1, p: 8 },
      { type: 'above', x: 2, y: 0 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'drew', x: 3, y: 4 },
    ],
  },
  {
    num: 66, quizId: 'stands-9-27-26', live: '2026-09-27', dateLabel: 'September 27, 2026', sunday: true,
    teams: ['Ashcombe', 'Burnhill', 'Corvale', 'Dalridge', 'Everleigh', 'Frithwood'],
    clues: [
      { type: 'drew', x: 0, y: 3 },
      { type: 'points', x: 1, p: 10 },
      { type: 'points', x: 2, p: 8 },
      { type: 'draws', x: 0, n: 2 },
      { type: 'beat', x: 4, y: 5 },
      { type: 'totalDraws', n: 3 },
      { type: 'points', x: 3, p: 10 },
      { type: 'beat', x: 4, y: 3 },
      { type: 'wins', x: 0, n: 1 },
      { type: 'points', x: 4, p: 6 },
    ],
  },
  {
    num: 67, quizId: 'stands-9-28-26', live: '2026-09-28', dateLabel: 'September 28, 2026', sunday: false,
    teams: ['Aldwick', 'Burnhill', 'Charnwood', 'Doverleigh', 'Ewhurst'],
    clues: [
      { type: 'beat', x: 4, y: 1 },
      { type: 'above', x: 4, y: 3 },
      { type: 'wins', x: 0, n: 1 },
      { type: 'draws', x: 2, n: 2 },
      { type: 'points', x: 3, p: 7 },
      { type: 'draws', x: 4, n: 2 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'unbeaten', x: 2 },
    ],
  },
  {
    num: 68, quizId: 'stands-9-29-26', live: '2026-09-29', dateLabel: 'September 29, 2026', sunday: false,
    teams: ['Ambleside', 'Byrneside', 'Comberton', 'Drayfield', 'Everleigh'],
    clues: [
      { type: 'wins', x: 4, n: 1 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'winless', x: 1 },
      { type: 'points', x: 1, p: 3 },
      { type: 'points', x: 3, p: 6 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'draws', x: 4, n: 1 },
    ],
  },
  {
    num: 69, quizId: 'stands-9-30-26', live: '2026-09-30', dateLabel: 'September 30, 2026', sunday: false,
    teams: ['Arkholme', 'Balderstone', 'Culverton', 'Duxbury', 'Elverdale'],
    clues: [
      { type: 'beat', x: 4, y: 3 },
      { type: 'wins', x: 4, n: 2 },
      { type: 'points', x: 1, p: 4 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'draws', x: 0, n: 0 },
      { type: 'draws', x: 2, n: 0 },
      { type: 'above', x: 2, y: 0 },
      { type: 'beat', x: 4, y: 2 },
    ],
  },
  {
    num: 70, quizId: 'stands-10-1-26', live: '2026-10-01', dateLabel: 'October 1, 2026', sunday: false,
    teams: ['Astley Vale', 'Braycott', 'Cheveley', 'Dinsdale', 'Elverdale'],
    clues: [
      { type: 'beat', x: 0, y: 1 },
      { type: 'points', x: 3, p: 4 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'points', x: 4, p: 5 },
      { type: 'points', x: 0, p: 4 },
    ],
  },
  {
    num: 71, quizId: 'stands-10-2-26', live: '2026-10-02', dateLabel: 'October 2, 2026', sunday: false,
    teams: ['Ashenden', 'Bryning', 'Corsley', 'Duxbury', 'Enderby'],
    clues: [
      { type: 'points', x: 3, p: 1 },
      { type: 'draws', x: 2, n: 0 },
      { type: 'points', x: 0, p: 7 },
      { type: 'above', x: 1, y: 0 },
      { type: 'points', x: 4, p: 1 },
    ],
  },
  {
    num: 72, quizId: 'stands-10-3-26', live: '2026-10-03', dateLabel: 'October 3, 2026', sunday: false,
    teams: ['Arrowfield', 'Barmoor', 'Culverton', 'Dalehead', 'Enderby'],
    clues: [
      { type: 'beat', x: 1, y: 3 },
      { type: 'points', x: 0, p: 6 },
      { type: 'points', x: 4, p: 0 },
      { type: 'points', x: 3, p: 7 },
      { type: 'wins', x: 2, n: 3 },
    ],
  },
  {
    num: 73, quizId: 'stands-10-4-26', live: '2026-10-04', dateLabel: 'October 4, 2026', sunday: true,
    teams: ['Arrowfield', 'Barmoor', 'Cranbourne', 'Dalehead', 'Elmbridge', 'Foxbourne'],
    clues: [
      { type: 'points', x: 5, p: 7 },
      { type: 'points', x: 1, p: 13 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'beat', x: 1, y: 5 },
      { type: 'above', x: 2, y: 5 },
      { type: 'beat', x: 4, y: 0 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'points', x: 3, p: 2 },
      { type: 'beat', x: 0, y: 5 },
    ],
  },
  {
    num: 74, quizId: 'stands-10-5-26', live: '2026-10-05', dateLabel: 'October 5, 2026', sunday: false,
    teams: ['Ashburn', 'Balderstone', 'Cranbourne', 'Delverton', 'Elverdale'],
    clues: [
      { type: 'draws', x: 3, n: 2 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'points', x: 2, p: 3 },
      { type: 'points', x: 0, p: 1 },
      { type: 'wins', x: 3, n: 1 },
      { type: 'points', x: 1, p: 7 },
      { type: 'beat', x: 3, y: 0 },
    ],
  },
  {
    num: 75, quizId: 'stands-10-6-26', live: '2026-10-06', dateLabel: 'October 6, 2026', sunday: false,
    teams: ['Anscombe', 'Beckwater', 'Cheveley', 'Duxbury', 'Elmbridge'],
    clues: [
      { type: 'beat', x: 3, y: 1 },
      { type: 'draws', x: 4, n: 0 },
      { type: 'points', x: 2, p: 12 },
      { type: 'points', x: 0, p: 4 },
      { type: 'above', x: 3, y: 1 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'beat', x: 0, y: 4 },
    ],
  },
  {
    num: 76, quizId: 'stands-10-7-26', live: '2026-10-07', dateLabel: 'October 7, 2026', sunday: false,
    teams: ['Ashburn', 'Bledlow', 'Culverton', 'Danesmoor', 'Everton Bar'],
    clues: [
      { type: 'draws', x: 3, n: 1 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'above', x: 4, y: 1 },
      { type: 'points', x: 4, p: 4 },
      { type: 'beat', x: 2, y: 0 },
      { type: 'above', x: 3, y: 4 },
      { type: 'beat', x: 1, y: 4 },
      { type: 'points', x: 2, p: 10 },
    ],
  },
  {
    num: 77, quizId: 'stands-10-8-26', live: '2026-10-08', dateLabel: 'October 8, 2026', sunday: false,
    teams: ['Anscombe', 'Bryning', 'Cheveley', 'Duxbury', 'Eddisford'],
    clues: [
      { type: 'above', x: 2, y: 3 },
      { type: 'points', x: 2, p: 4 },
      { type: 'draws', x: 1, n: 3 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'points', x: 4, p: 4 },
    ],
  },
  {
    num: 78, quizId: 'stands-10-9-26', live: '2026-10-09', dateLabel: 'October 9, 2026', sunday: false,
    teams: ['Anscombe', 'Balderstone', 'Culverton', 'Duxbury', 'Eddisford'],
    clues: [
      { type: 'beat', x: 1, y: 2 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'above', x: 4, y: 0 },
      { type: 'drew', x: 3, y: 4 },
      { type: 'points', x: 0, p: 6 },
      { type: 'beat', x: 1, y: 0 },
    ],
  },
  {
    num: 79, quizId: 'stands-10-10-26', live: '2026-10-10', dateLabel: 'October 10, 2026', sunday: false,
    teams: ['Arkholme', 'Bowness End', 'Camberholt', 'Downholme', 'Eskholme'],
    clues: [
      { type: 'points', x: 2, p: 6 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'wins', x: 4, n: 2 },
      { type: 'points', x: 3, p: 9 },
      { type: 'points', x: 0, p: 4 },
      { type: 'beat', x: 2, y: 4 },
    ],
  },
  {
    num: 80, quizId: 'stands-10-11-26', live: '2026-10-11', dateLabel: 'October 11, 2026', sunday: true,
    teams: ['Ashburn', 'Bramhope', 'Cheveley', 'Drover Green', 'Elmbridge', 'Foxbourne'],
    clues: [
      { type: 'points', x: 1, p: 4 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 2, p: 13 },
      { type: 'points', x: 3, p: 9 },
      { type: 'wins', x: 4, n: 3 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'points', x: 5, p: 5 },
      { type: 'beat', x: 3, y: 5 },
    ],
  },
  {
    num: 81, quizId: 'stands-10-12-26', live: '2026-10-12', dateLabel: 'October 12, 2026', sunday: false,
    teams: ['Aveley', 'Braycott', 'Cranbourne', 'Drover Green', 'Eastholm'],
    clues: [
      { type: 'beat', x: 2, y: 0 },
      { type: 'totalDraws', n: 4 },
      { type: 'above', x: 0, y: 2 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 1, p: 3 },
      { type: 'drew', x: 1, y: 2 },
      { type: 'drew', x: 3, y: 4 },
    ],
  },
  {
    num: 82, quizId: 'stands-10-13-26', live: '2026-10-13', dateLabel: 'October 13, 2026', sunday: false,
    teams: ['Arkholme', 'Barmoor', 'Corsley', 'Downholme', 'Elverdale'],
    clues: [
      { type: 'totalDraws', n: 1 },
      { type: 'points', x: 0, p: 6 },
      { type: 'draws', x: 3, n: 0 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'wins', x: 3, n: 2 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 3, y: 2 },
      { type: 'above', x: 0, y: 1 },
    ],
  },
  {
    num: 83, quizId: 'stands-10-14-26', live: '2026-10-14', dateLabel: 'October 14, 2026', sunday: false,
    teams: ['Alderbeck', 'Bryning', 'Cropwell', 'Dinsdale', 'Eastholm'],
    clues: [
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 3, p: 8 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'draws', x: 2, n: 2 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'totalDraws', n: 6 },
    ],
  },
  {
    num: 84, quizId: 'stands-10-15-26', live: '2026-10-15', dateLabel: 'October 15, 2026', sunday: false,
    teams: ['Alderbeck', 'Bledlow', 'Cranbourne', 'Delverton', 'Eastholm'],
    clues: [
      { type: 'wins', x: 2, n: 1 },
      { type: 'draws', x: 0, n: 3 },
      { type: 'points', x: 4, p: 3 },
      { type: 'beat', x: 2, y: 0 },
      { type: 'above', x: 2, y: 3 },
      { type: 'totalDraws', n: 6 },
    ],
  },
  {
    num: 85, quizId: 'stands-10-16-26', live: '2026-10-16', dateLabel: 'October 16, 2026', sunday: false,
    teams: ['Ashenden', 'Bryning', 'Cranbourne', 'Delverton', 'Enderby'],
    clues: [
      { type: 'beat', x: 0, y: 1 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'draws', x: 3, n: 2 },
      { type: 'points', x: 2, p: 9 },
    ],
  },
  {
    num: 86, quizId: 'stands-10-17-26', live: '2026-10-17', dateLabel: 'October 17, 2026', sunday: false,
    teams: ['Ashburn', 'Bramhope', 'Cranbourne', 'Dinsdale', 'Elverdale'],
    clues: [
      { type: 'points', x: 1, p: 10 },
      { type: 'draws', x: 2, n: 2 },
      { type: 'beat', x: 4, y: 3 },
      { type: 'points', x: 0, p: 6 },
      { type: 'beat', x: 2, y: 3 },
      { type: 'points', x: 3, p: 1 },
    ],
  },
  {
    num: 87, quizId: 'stands-10-18-26', live: '2026-10-18', dateLabel: 'October 18, 2026', sunday: true,
    teams: ['Arrowfield', 'Braycott', 'Cranbourne', 'Downholme', 'Elmbridge', 'Fairholme'],
    clues: [
      { type: 'beat', x: 5, y: 1 },
      { type: 'draws', x: 5, n: 2 },
      { type: 'points', x: 4, p: 7 },
      { type: 'beat', x: 5, y: 2 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'beat', x: 0, y: 5 },
      { type: 'above', x: 2, y: 4 },
      { type: 'draws', x: 3, n: 2 },
      { type: 'points', x: 1, p: 7 },
    ],
  },
  {
    num: 88, quizId: 'stands-10-19-26', live: '2026-10-19', dateLabel: 'October 19, 2026', sunday: false,
    teams: ['Ashburn', 'Bledlow', 'Chatsmoor', 'Delverton', 'Everton Bar'],
    clues: [
      { type: 'beat', x: 3, y: 4 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'points', x: 2, p: 3 },
      { type: 'above', x: 3, y: 0 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 1, y: 0 },
    ],
  },
  {
    num: 89, quizId: 'stands-10-20-26', live: '2026-10-20', dateLabel: 'October 20, 2026', sunday: false,
    teams: ['Ashenden', 'Bowness End', 'Clayton Vale', 'Duxbury', 'Elverdale'],
    clues: [
      { type: 'draws', x: 2, n: 1 },
      { type: 'points', x: 1, p: 5 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'points', x: 0, p: 4 },
      { type: 'points', x: 3, p: 5 },
      { type: 'points', x: 4, p: 3 },
    ],
  },
  {
    num: 90, quizId: 'stands-10-21-26', live: '2026-10-21', dateLabel: 'October 21, 2026', sunday: false,
    teams: ['Anscombe', 'Beckwater', 'Cheveley', 'Delverton', 'Elmbridge'],
    clues: [
      { type: 'wins', x: 4, n: 1 },
      { type: 'wins', x: 2, n: 0 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'points', x: 3, p: 5 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'points', x: 0, p: 5 },
      { type: 'beat', x: 3, y: 1 },
    ],
  },
  {
    num: 91, quizId: 'stands-10-22-26', live: '2026-10-22', dateLabel: 'October 22, 2026', sunday: false,
    teams: ['Ashburn', 'Braycott', 'Cropwell', 'Danesmoor', 'Eddisford'],
    clues: [
      { type: 'wins', x: 3, n: 0 },
      { type: 'points', x: 4, p: 5 },
      { type: 'points', x: 0, p: 8 },
      { type: 'above', x: 3, y: 2 },
      { type: 'points', x: 1, p: 10 },
    ],
  },
  {
    num: 92, quizId: 'stands-10-23-26', live: '2026-10-23', dateLabel: 'October 23, 2026', sunday: false,
    teams: ['Arkholme', 'Balderstone', 'Camberholt', 'Downholme', 'Elverdale'],
    clues: [
      { type: 'draws', x: 1, n: 2 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'points', x: 4, p: 9 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 2, y: 1 },
      { type: 'draws', x: 3, n: 1 },
    ],
  },
  {
    num: 93, quizId: 'stands-10-24-26', live: '2026-10-24', dateLabel: 'October 24, 2026', sunday: false,
    teams: ['Astley Vale', 'Beckwater', 'Cropwell', 'Downholme', 'Everton Bar'],
    clues: [
      { type: 'points', x: 0, p: 9 },
      { type: 'points', x: 1, p: 3 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'points', x: 4, p: 4 },
    ],
  },
  {
    num: 94, quizId: 'stands-10-25-26', live: '2026-10-25', dateLabel: 'October 25, 2026', sunday: true,
    teams: ['Ashburn', 'Bowness End', 'Corsley', 'Downholme', 'Eastholm', 'Fernhurst'],
    clues: [
      { type: 'beat', x: 1, y: 5 },
      { type: 'above', x: 2, y: 3 },
      { type: 'points', x: 1, p: 5 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'beat', x: 4, y: 0 },
      { type: 'points', x: 5, p: 10 },
      { type: 'points', x: 0, p: 10 },
      { type: 'points', x: 4, p: 5 },
    ],
  },
  {
    num: 95, quizId: 'stands-10-26-26', live: '2026-10-26', dateLabel: 'October 26, 2026', sunday: false,
    teams: ['Aveley', 'Balderstone', 'Cheveley', 'Delverton', 'Elmbridge'],
    clues: [
      { type: 'above', x: 2, y: 0 },
      { type: 'draws', x: 1, n: 2 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'drew', x: 0, y: 3 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'beat', x: 0, y: 4 },
    ],
  },
  {
    num: 96, quizId: 'stands-10-27-26', live: '2026-10-27', dateLabel: 'October 27, 2026', sunday: false,
    teams: ['Astley Vale', 'Balderstone', 'Culverton', 'Delverton', 'Eskholme'],
    clues: [
      { type: 'draws', x: 1, n: 3 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'above', x: 2, y: 4 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'points', x: 0, p: 7 },
      { type: 'points', x: 3, p: 5 },
      { type: 'beat', x: 3, y: 2 },
    ],
  },
  {
    num: 97, quizId: 'stands-10-28-26', live: '2026-10-28', dateLabel: 'October 28, 2026', sunday: false,
    teams: ['Arrowfield', 'Braycott', 'Cranbourne', 'Drover Green', 'Everton Bar'],
    clues: [
      { type: 'drew', x: 0, y: 4 },
      { type: 'points', x: 2, p: 2 },
      { type: 'above', x: 0, y: 4 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 1, p: 5 },
      { type: 'points', x: 4, p: 6 },
    ],
  },
  {
    num: 98, quizId: 'stands-10-29-26', live: '2026-10-29', dateLabel: 'October 29, 2026', sunday: false,
    teams: ['Arkholme', 'Beckwater', 'Corsley', 'Delverton', 'Enderby'],
    clues: [
      { type: 'beat', x: 1, y: 3 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'beat', x: 0, y: 2 },
      { type: 'points', x: 0, p: 10 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 0, y: 1 },
      { type: 'above', x: 2, y: 4 },
      { type: 'points', x: 3, p: 2 },
      { type: 'beat', x: 1, y: 2 },
    ],
  },
  {
    num: 99, quizId: 'stands-10-30-26', live: '2026-10-30', dateLabel: 'October 30, 2026', sunday: false,
    teams: ['Arkholme', 'Beckwater', 'Cheveley', 'Duxbury', 'Elmbridge'],
    clues: [
      { type: 'wins', x: 4, n: 2 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'above', x: 1, y: 4 },
      { type: 'above', x: 3, y: 4 },
      { type: 'points', x: 2, p: 3 },
      { type: 'drew', x: 0, y: 2 },
    ],
  },
  {
    num: 100, quizId: 'stands-10-31-26', live: '2026-10-31', dateLabel: 'October 31, 2026', sunday: false,
    teams: ['Arrowfield', 'Bramhope', 'Cheveley', 'Delverton', 'Enderby'],
    clues: [
      { type: 'wins', x: 0, n: 2 },
      { type: 'draws', x: 2, n: 2 },
      { type: 'draws', x: 0, n: 2 },
      { type: 'drew', x: 1, y: 2 },
      { type: 'points', x: 3, p: 0 },
      { type: 'unbeaten', x: 2 },
      { type: 'points', x: 4, p: 5 },
    ],
  },
  {
    num: 101, quizId: 'stands-11-1-26', live: '2026-11-01', dateLabel: 'November 1, 2026', sunday: true,
    teams: ['Alderton', 'Barrowfield', 'Camberholt', 'Dinsdale', 'Endsleigh', 'Foxbourne'],
    clues: [
      { type: 'beat', x: 5, y: 4 },
      { type: 'points', x: 5, p: 8 },
      { type: 'points', x: 3, p: 5 },
      { type: 'beat', x: 5, y: 3 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 0, p: 5 },
      { type: 'points', x: 4, p: 12 },
      { type: 'drew', x: 2, y: 5 },
      { type: 'points', x: 1, p: 7 },
      { type: 'totalDraws', n: 4 },
    ],
  },
  {
    num: 102, quizId: 'stands-11-2-26', live: '2026-11-02', dateLabel: 'November 2, 2026', sunday: false,
    teams: ['Ashenden', 'Bledlow', 'Calderhurst', 'Draymoor', 'Enderby'],
    clues: [
      { type: 'points', x: 2, p: 7 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'points', x: 0, p: 9 },
      { type: 'wins', x: 4, n: 2 },
    ],
  },
  {
    num: 103, quizId: 'stands-11-3-26', live: '2026-11-03', dateLabel: 'November 3, 2026', sunday: false,
    teams: ['Averton', 'Bryning', 'Croftwood', 'Dunsmere', 'Everleigh'],
    clues: [
      { type: 'points', x: 2, p: 7 },
      { type: 'above', x: 3, y: 1 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'points', x: 4, p: 3 },
      { type: 'points', x: 0, p: 4 },
      { type: 'beat', x: 0, y: 3 },
    ],
  },
  {
    num: 104, quizId: 'stands-11-4-26', live: '2026-11-04', dateLabel: 'November 4, 2026', sunday: false,
    teams: ['Arrowfield', 'Bellhaven', 'Comberton', 'Dockwray', 'Enderby'],
    clues: [
      { type: 'points', x: 3, p: 10 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'points', x: 4, p: 1 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'totalDraws', n: 2 },
      { type: 'wins', x: 1, n: 2 },
      { type: 'beat', x: 3, y: 1 },
    ],
  },
  {
    num: 105, quizId: 'stands-11-5-26', live: '2026-11-05', dateLabel: 'November 5, 2026', sunday: false,
    teams: ['Alverston', 'Braycott', 'Camberholt', 'Dockwray', 'Endermere'],
    clues: [
      { type: 'drew', x: 2, y: 3 },
      { type: 'points', x: 4, p: 5 },
      { type: 'points', x: 2, p: 4 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 1, p: 3 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 3, p: 5 },
    ],
  },
  {
    num: 106, quizId: 'stands-11-6-26', live: '2026-11-06', dateLabel: 'November 6, 2026', sunday: false,
    teams: ['Alderbeck', 'Brackwell', 'Chalkwell', 'Doverleigh', 'Ewhurst'],
    clues: [
      { type: 'points', x: 0, p: 10 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'wins', x: 1, n: 1 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'points', x: 2, p: 1 },
      { type: 'points', x: 4, p: 9 },
      { type: 'totalDraws', n: 2 },
    ],
  },
  {
    num: 107, quizId: 'stands-11-7-26', live: '2026-11-07', dateLabel: 'November 7, 2026', sunday: false,
    teams: ['Ashmore', 'Bellhaven', 'Camberholt', 'Delverton', 'Esk Vale'],
    clues: [
      { type: 'points', x: 3, p: 5 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'drew', x: 2, y: 3 },
      { type: 'points', x: 0, p: 7 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'points', x: 1, p: 2 },
      { type: 'drew', x: 2, y: 4 },
    ],
  },
  {
    num: 108, quizId: 'stands-11-8-26', live: '2026-11-08', dateLabel: 'November 8, 2026', sunday: true,
    teams: ['Arnfield', 'Beckwater', 'Culverton', 'Dunmoor', 'Endsleigh', 'Farnleigh'],
    clues: [
      { type: 'totalDraws', n: 9 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'drew', x: 0, y: 5 },
      { type: 'points', x: 4, p: 6 },
      { type: 'draws', x: 5, n: 3 },
      { type: 'draws', x: 3, n: 4 },
      { type: 'beat', x: 3, y: 1 },
      { type: 'points', x: 0, p: 4 },
      { type: 'drew', x: 0, y: 2 },
    ],
  },
  {
    num: 109, quizId: 'stands-11-9-26', live: '2026-11-09', dateLabel: 'November 9, 2026', sunday: false,
    teams: ['Anscombe', 'Blakeney', 'Cranmere', 'Drayfield', 'Ellerby'],
    clues: [
      { type: 'draws', x: 4, n: 2 },
      { type: 'draws', x: 3, n: 3 },
      { type: 'draws', x: 2, n: 3 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'draws', x: 0, n: 2 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'unbeaten', x: 1 },
    ],
  },
  {
    num: 110, quizId: 'stands-11-10-26', live: '2026-11-10', dateLabel: 'November 10, 2026', sunday: false,
    teams: ['Arkholme', 'Braycott', 'Corsley', 'Duxbury', 'Endermere'],
    clues: [
      { type: 'points', x: 0, p: 5 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'wins', x: 1, n: 0 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'beat', x: 4, y: 1 },
      { type: 'points', x: 2, p: 6 },
      { type: 'beat', x: 2, y: 3 },
    ],
  },
  {
    num: 111, quizId: 'stands-11-11-26', live: '2026-11-11', dateLabel: 'November 11, 2026', sunday: false,
    teams: ['Arkholme', 'Bowness End', 'Charnwood', 'Drayfield', 'Eddisford'],
    clues: [
      { type: 'above', x: 3, y: 0 },
      { type: 'unbeaten', x: 4 },
      { type: 'totalDraws', n: 3 },
      { type: 'drew', x: 0, y: 1 },
      { type: 'points', x: 2, p: 4 },
      { type: 'draws', x: 1, n: 3 },
      { type: 'drew', x: 1, y: 3 },
    ],
  },
  {
    num: 112, quizId: 'stands-11-12-26', live: '2026-11-12', dateLabel: 'November 12, 2026', sunday: false,
    teams: ['Arnfield', 'Bowness End', 'Charnwood', 'Dunmoor', 'Eastholm'],
    clues: [
      { type: 'wins', x: 3, n: 1 },
      { type: 'points', x: 1, p: 7 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'draws', x: 4, n: 0 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'points', x: 0, p: 4 },
      { type: 'beat', x: 1, y: 3 },
    ],
  },
  {
    num: 113, quizId: 'stands-11-13-26', live: '2026-11-13', dateLabel: 'November 13, 2026', sunday: false,
    teams: ['Aldwick', 'Bryning', 'Corvale', 'Dunmoor', 'Endsleigh'],
    clues: [
      { type: 'beat', x: 3, y: 0 },
      { type: 'wins', x: 4, n: 3 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'points', x: 3, p: 4 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'points', x: 1, p: 2 },
    ],
  },
  {
    num: 114, quizId: 'stands-11-14-26', live: '2026-11-14', dateLabel: 'November 14, 2026', sunday: false,
    teams: ['Ashcombe', 'Barrowfield', 'Chalkwell', 'Dinsdale', 'Elmbridge'],
    clues: [
      { type: 'wins', x: 0, n: 2 },
      { type: 'beat', x: 1, y: 0 },
      { type: 'above', x: 3, y: 1 },
      { type: 'above', x: 2, y: 0 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'above', x: 4, y: 2 },
    ],
  },
  {
    num: 115, quizId: 'stands-11-15-26', live: '2026-11-15', dateLabel: 'November 15, 2026', sunday: true,
    teams: ['Arkholme', 'Bexmoor', 'Chalkwell', 'Dunmoor', 'Everleigh', 'Fernhurst'],
    clues: [
      { type: 'wins', x: 5, n: 2 },
      { type: 'beat', x: 2, y: 5 },
      { type: 'points', x: 4, p: 8 },
      { type: 'wins', x: 3, n: 4 },
      { type: 'points', x: 1, p: 4 },
      { type: 'beat', x: 0, y: 3 },
      { type: 'draws', x: 5, n: 1 },
      { type: 'wins', x: 0, n: 3 },
    ],
  },
  {
    num: 116, quizId: 'stands-11-16-26', live: '2026-11-16', dateLabel: 'November 16, 2026', sunday: false,
    teams: ['Astley Vale', 'Braycott', 'Clayton Vale', 'Dockwray', 'Edenhall'],
    clues: [
      { type: 'beat', x: 4, y: 2 },
      { type: 'points', x: 4, p: 6 },
      { type: 'wins', x: 1, n: 3 },
      { type: 'points', x: 3, p: 2 },
      { type: 'points', x: 2, p: 7 },
    ],
  },
  {
    num: 117, quizId: 'stands-11-17-26', live: '2026-11-17', dateLabel: 'November 17, 2026', sunday: false,
    teams: ['Ashmore', 'Bowness End', 'Comberton', 'Dalridge', 'Endsleigh'],
    clues: [
      { type: 'beat', x: 0, y: 4 },
      { type: 'points', x: 3, p: 5 },
      { type: 'draws', x: 4, n: 1 },
      { type: 'totalDraws', n: 3 },
      { type: 'wins', x: 1, n: 2 },
      { type: 'beat', x: 3, y: 0 },
      { type: 'above', x: 2, y: 4 },
      { type: 'beat', x: 0, y: 2 },
      { type: 'beat', x: 1, y: 2 },
    ],
  },
  {
    num: 118, quizId: 'stands-11-18-26', live: '2026-11-18', dateLabel: 'November 18, 2026', sunday: false,
    teams: ['Ashburn', 'Barmoor', 'Camberholt', 'Duxbury', 'Eastfield'],
    clues: [
      { type: 'wins', x: 4, n: 2 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'drew', x: 1, y: 4 },
      { type: 'points', x: 0, p: 9 },
      { type: 'points', x: 3, p: 3 },
      { type: 'points', x: 1, p: 1 },
    ],
  },
  {
    num: 119, quizId: 'stands-11-19-26', live: '2026-11-19', dateLabel: 'November 19, 2026', sunday: false,
    teams: ['Ambleside', 'Bexmoor', 'Chatsmoor', 'Downholme', 'Everton Bar'],
    clues: [
      { type: 'draws', x: 1, n: 2 },
      { type: 'points', x: 2, p: 7 },
      { type: 'points', x: 0, p: 6 },
      { type: 'points', x: 3, p: 2 },
      { type: 'wins', x: 1, n: 0 },
      { type: 'draws', x: 0, n: 0 },
      { type: 'beat', x: 4, y: 3 },
    ],
  },
  {
    num: 120, quizId: 'stands-11-20-26', live: '2026-11-20', dateLabel: 'November 20, 2026', sunday: false,
    teams: ['Ashenden', 'Blakeney', 'Calderby', 'Downholme', 'Endermere'],
    clues: [
      { type: 'wins', x: 3, n: 2 },
      { type: 'draws', x: 4, n: 1 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'points', x: 2, p: 7 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'drew', x: 1, y: 4 },
      { type: 'wins', x: 0, n: 1 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 3, y: 0 },
    ],
  },
  {
    num: 121, quizId: 'stands-11-21-26', live: '2026-11-21', dateLabel: 'November 21, 2026', sunday: false,
    teams: ['Ashcombe', 'Bledlow', 'Cropwell', 'Drayfield', 'Enderby'],
    clues: [
      { type: 'wins', x: 2, n: 3 },
      { type: 'points', x: 1, p: 3 },
      { type: 'points', x: 3, p: 9 },
      { type: 'points', x: 0, p: 9 },
      { type: 'beat', x: 2, y: 3 },
    ],
  },
  {
    num: 122, quizId: 'stands-11-22-26', live: '2026-11-22', dateLabel: 'November 22, 2026', sunday: true,
    teams: ['Ashburn', 'Bowness End', 'Corvale', 'Drayfield', 'Elmsworth', 'Farnleigh'],
    clues: [
      { type: 'points', x: 5, p: 10 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'beat', x: 2, y: 5 },
      { type: 'points', x: 4, p: 4 },
      { type: 'wins', x: 0, n: 2 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'draws', x: 0, n: 1 },
      { type: 'points', x: 3, p: 5 },
      { type: 'points', x: 1, p: 8 },
    ],
  },
  {
    num: 123, quizId: 'stands-11-23-26', live: '2026-11-23', dateLabel: 'November 23, 2026', sunday: false,
    teams: ['Ashmore', 'Bramhope', 'Calderhurst', 'Danesmoor', 'Elmbridge'],
    clues: [
      { type: 'draws', x: 2, n: 1 },
      { type: 'draws', x: 4, n: 1 },
      { type: 'points', x: 3, p: 12 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'points', x: 1, p: 1 },
    ],
  },
  {
    num: 124, quizId: 'stands-11-24-26', live: '2026-11-24', dateLabel: 'November 24, 2026', sunday: false,
    teams: ['Alverston', 'Bexley Vale', 'Chalkwell', 'Drover Green', 'Eastfield'],
    clues: [
      { type: 'beat', x: 4, y: 0 },
      { type: 'draws', x: 1, n: 1 },
      { type: 'drew', x: 0, y: 2 },
      { type: 'points', x: 3, p: 9 },
      { type: 'wins', x: 2, n: 1 },
      { type: 'draws', x: 2, n: 1 },
      { type: 'above', x: 3, y: 4 },
      { type: 'wins', x: 1, n: 0 },
    ],
  },
  {
    num: 125, quizId: 'stands-11-25-26', live: '2026-11-25', dateLabel: 'November 25, 2026', sunday: false,
    teams: ['Aveley', 'Bexley Vale', 'Cranmere', 'Drayfield', 'Ewhurst'],
    clues: [
      { type: 'beat', x: 3, y: 1 },
      { type: 'beat', x: 2, y: 4 },
      { type: 'points', x: 2, p: 4 },
      { type: 'above', x: 0, y: 1 },
      { type: 'draws', x: 1, n: 0 },
      { type: 'wins', x: 4, n: 1 },
      { type: 'points', x: 3, p: 4 },
      { type: 'draws', x: 0, n: 0 },
    ],
  },
  {
    num: 126, quizId: 'stands-11-26-26', live: '2026-11-26', dateLabel: 'November 26, 2026', sunday: false,
    teams: ['Aveley', 'Brackwell', 'Cheveley', 'Dockwray', 'Ellerby'],
    clues: [
      { type: 'beat', x: 2, y: 3 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'draws', x: 3, n: 1 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'totalDraws', n: 4 },
      { type: 'beat', x: 0, y: 4 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'wins', x: 0, n: 3 },
    ],
  },
  {
    num: 127, quizId: 'stands-11-27-26', live: '2026-11-27', dateLabel: 'November 27, 2026', sunday: false,
    teams: ['Aveley', 'Bramhope', 'Calderhurst', 'Drayfield', 'Eskholme'],
    clues: [
      { type: 'draws', x: 3, n: 0 },
      { type: 'wins', x: 0, n: 3 },
      { type: 'beat', x: 1, y: 2 },
      { type: 'points', x: 4, p: 6 },
      { type: 'beat', x: 3, y: 4 },
      { type: 'wins', x: 3, n: 1 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'above', x: 1, y: 4 },
    ],
  },
  {
    num: 128, quizId: 'stands-11-28-26', live: '2026-11-28', dateLabel: 'November 28, 2026', sunday: false,
    teams: ['Ashcombe', 'Bowness End', 'Camberholt', 'Darnley', 'Endsleigh'],
    clues: [
      { type: 'beat', x: 1, y: 4 },
      { type: 'totalDraws', n: 4 },
      { type: 'points', x: 3, p: 3 },
      { type: 'beat', x: 4, y: 2 },
      { type: 'beat', x: 4, y: 0 },
      { type: 'wins', x: 2, n: 2 },
      { type: 'beat', x: 0, y: 3 },
    ],
  },
  {
    num: 129, quizId: 'stands-11-29-26', live: '2026-11-29', dateLabel: 'November 29, 2026', sunday: true,
    teams: ['Aldwick', 'Braycott', 'Cotterill', 'Duxbury', 'Elverdale', 'Fernhurst'],
    clues: [
      { type: 'above', x: 1, y: 5 },
      { type: 'beat', x: 3, y: 2 },
      { type: 'beat', x: 0, y: 2 },
      { type: 'points', x: 4, p: 12 },
      { type: 'above', x: 2, y: 1 },
      { type: 'beat', x: 0, y: 1 },
      { type: 'beat', x: 5, y: 2 },
      { type: 'drew', x: 0, y: 3 },
    ],
  },
  {
    num: 130, quizId: 'stands-11-30-26', live: '2026-11-30', dateLabel: 'November 30, 2026', sunday: false,
    teams: ['Ashburn', 'Bramhope', 'Calderby', 'Dunsmere', 'Endsleigh'],
    clues: [
      { type: 'above', x: 4, y: 0 },
      { type: 'points', x: 2, p: 4 },
      { type: 'points', x: 4, p: 6 },
      { type: 'beat', x: 2, y: 1 },
      { type: 'totalDraws', n: 1 },
      { type: 'beat', x: 1, y: 3 },
      { type: 'beat', x: 0, y: 3 },
    ],
  },
];
