// Niche facts: TV SHOWS (the Thursday universe). A fixed pool of famous,
// mainstream-known series, dramas and comedies plus a handful of institution
// reality and variety shows. No time-varying facts on purpose (nothing about
// "still airing"), so the bank cannot rot.
//
// FIELD RULES:
//   y     debut year of the original run (drives the decade attributes).
//   ani   animated.
//   emmy  won the Emmy for Outstanding Comedy Series or Outstanding Drama
//         Series at least once (through the 2025 ceremony).
//   ten   ran ten or more seasons (Friends, at exactly ten, is in).
//   str   a streaming original (Netflix, Prime Video, Hulu, Apple TV+,
//         Disney+, Max). Generous where a show is famous AS a streaming
//         series (Black Mirror counts); HBO cable series do not count.
//   nyc   set mainly in New York City (the Sopranos' New Jersey does not
//         count).
//   net   first aired on one of the four big broadcast networks, ABC, CBS,
//         NBC or Fox. The label names those four, so The CW, The WB, UPN,
//         PBS, the BBC and first-run syndication are all out, and no show
//         carries both net and cable.
//   cable first aired on a cable channel (HBO, AMC, FX, Showtime, Comedy
//         Central, Nickelodeon, USA, ESPN, Adult Swim, Paramount Network).
//         An HBO series is cable, never str, matching the str rule above.
//   book  adapted from a book, a comic or a video game rather than written
//         for the screen. Generous: the source only has to be where the
//         story and characters came from.
//   a     typed aliases, lowercase.
export const TVSHOWS = [
  // ── institutions ──
  { t: 'Saturday Night Live', a: ['snl'], y: 1975, ten: 1, net: 1 },
  { t: 'Jeopardy!', a: ['jeopardy'], y: 1984, ten: 1 },
  { t: 'Survivor', y: 2000, ten: 1, net: 1 },
  { t: 'American Idol', y: 2002, ten: 1, net: 1 },
  { t: 'The Bachelor', y: 2002, ten: 1, net: 1 },
  { t: 'Sesame Street', y: 1969, ten: 1 },
  { t: 'Doctor Who', y: 1963, ten: 1 },
  // ── pre-1990 ──
  { t: 'I Love Lucy', y: 1951, emmy: 1, nyc: 1, net: 1 },
  { t: 'The Twilight Zone', y: 1959, net: 1 },
  { t: 'Star Trek', y: 1966, net: 1 },
  { t: 'All in the Family', y: 1971, emmy: 1, nyc: 1, net: 1 },
  { t: 'M*A*S*H', a: ['mash'], y: 1972, emmy: 1, ten: 1, net: 1, book: 1 },
  { t: 'Happy Days', y: 1974, ten: 1, net: 1 },
  { t: 'Taxi', y: 1978, emmy: 1, nyc: 1, net: 1 },
  { t: 'Dallas', y: 1978, ten: 1, net: 1 },
  { t: 'Cheers', y: 1982, emmy: 1, ten: 1, net: 1 },
  { t: 'The Golden Girls', y: 1985, emmy: 1, net: 1 },
  { t: 'Miami Vice', y: 1984, net: 1 },
  { t: 'Murphy Brown', y: 1988, emmy: 1, ten: 1, net: 1 },
  { t: 'Full House', y: 1987, net: 1 },
  { t: 'The Wonder Years', y: 1988, emmy: 1, net: 1 },
  { t: 'Roseanne', y: 1988, ten: 1, net: 1 },
  { t: 'Married... with Children', a: ['married with children'], y: 1987, ten: 1, net: 1 },
  { t: 'The Simpsons', y: 1989, ani: 1, ten: 1, net: 1 },
  // ── 1990s ──
  { t: 'Seinfeld', y: 1989, emmy: 1, nyc: 1, net: 1 },
  { t: 'Fresh Prince of Bel-Air', a: ['fresh prince', 'the fresh prince of bel air'], y: 1990, net: 1 },
  { t: 'Law & Order', a: ['law and order'], y: 1990, emmy: 1, ten: 1, nyc: 1, net: 1 },
  { t: 'Beverly Hills, 90210', a: ['90210', 'beverly hills 90210'], y: 1990, ten: 1, net: 1 },
  { t: 'Home Improvement', y: 1991, net: 1 },
  { t: 'The X-Files', a: ['x files', 'xfiles'], y: 1993, ten: 1, net: 1 },
  { t: 'Frasier', y: 1993, emmy: 1, ten: 1, net: 1 },
  { t: 'NYPD Blue', y: 1993, emmy: 1, ten: 1, nyc: 1, net: 1 },
  { t: 'Friends', y: 1994, emmy: 1, ten: 1, nyc: 1, net: 1 },
  { t: 'ER', a: ['er'], y: 1994, emmy: 1, ten: 1, net: 1 },
  { t: 'Everybody Loves Raymond', y: 1996, emmy: 1, net: 1 },
  { t: 'King of the Hill', y: 1997, ani: 1, ten: 1, net: 1 },
  { t: 'South Park', y: 1997, ani: 1, ten: 1, cable: 1 },
  { t: 'Buffy the Vampire Slayer', a: ['buffy'], y: 1997 },
  { t: 'Will & Grace', a: ['will and grace'], y: 1998, emmy: 1, ten: 1, nyc: 1, net: 1 },
  { t: 'Sex and the City', y: 1998, emmy: 1, nyc: 1, cable: 1, book: 1 },
  { t: 'That \'70s Show', a: ['that 70s show'], y: 1998, net: 1 },
  { t: 'The Sopranos', y: 1999, emmy: 1, cable: 1 },
  { t: 'The West Wing', y: 1999, emmy: 1, net: 1 },
  { t: 'Family Guy', y: 1999, ani: 1, ten: 1, net: 1 },
  { t: 'SpongeBob SquarePants', a: ['spongebob'], y: 1999, ani: 1, ten: 1, cable: 1 },
  { t: 'Freaks and Geeks', y: 1999, net: 1 },
  // ── 2000s ──
  { t: 'Gilmore Girls', y: 2000 },
  { t: 'Malcolm in the Middle', y: 2000, net: 1 },
  { t: 'CSI: Crime Scene Investigation', a: ['csi'], y: 2000, ten: 1, net: 1 },
  { t: 'Curb Your Enthusiasm', y: 2000, ten: 1, cable: 1 },
  { t: '24', y: 2001, emmy: 1, net: 1 },
  { t: 'Scrubs', y: 2001, net: 1 },
  { t: 'Smallville', y: 2001, ten: 1, book: 1 },
  { t: 'The Wire', y: 2002, cable: 1 },
  { t: 'Two and a Half Men', y: 2003, ten: 1, net: 1 },
  { t: 'Arrested Development', y: 2003, emmy: 1, net: 1 },
  { t: 'One Tree Hill', y: 2003 },
  { t: "It's Always Sunny in Philadelphia", a: ['always sunny', 'its always sunny in philadelphia'], y: 2005, ten: 1, cable: 1 },
  { t: 'Lost', y: 2004, emmy: 1, net: 1 },
  { t: 'Desperate Housewives', y: 2004, net: 1 },
  { t: 'House', a: ['house md'], y: 2004, net: 1 },
  { t: 'The O.C.', a: ['the oc', 'oc'], y: 2003, net: 1 },
  { t: 'Entourage', y: 2004, cable: 1 },
  { t: 'Veronica Mars', y: 2004 },
  { t: 'The Office', a: ['the office us'], y: 2005, emmy: 1, net: 1 },
  { t: 'Grey\'s Anatomy', a: ['greys anatomy', 'greys'], y: 2005, ten: 1, net: 1 },
  { t: 'How I Met Your Mother', a: ['himym'], y: 2005, nyc: 1, net: 1 },
  { t: 'Supernatural', y: 2005, ten: 1 },
  { t: 'Prison Break', y: 2005, net: 1 },
  { t: 'NCIS', a: ['ncis'], y: 2003, ten: 1, net: 1 },
  { t: 'Criminal Minds', y: 2005, ten: 1, net: 1 },
  { t: 'Dexter', y: 2006, cable: 1, book: 1 },
  { t: '30 Rock', y: 2006, emmy: 1, nyc: 1, net: 1 },
  { t: 'Friday Night Lights', y: 2006, net: 1, book: 1 },
  { t: 'Mad Men', y: 2007, emmy: 1, cable: 1 },
  { t: 'The Big Bang Theory', a: ['big bang theory'], y: 2007, ten: 1, net: 1 },
  { t: 'Gossip Girl', y: 2007, nyc: 1, book: 1 },
  { t: 'Breaking Bad', y: 2008, emmy: 1, cable: 1 },
  { t: 'Sons of Anarchy', y: 2008, cable: 1 },
  { t: 'Parks and Recreation', a: ['parks and rec'], y: 2009, net: 1 },
  { t: 'Modern Family', y: 2009, emmy: 1, ten: 1, net: 1 },
  { t: 'Glee', y: 2009, net: 1 },
  { t: 'The Vampire Diaries', y: 2009, book: 1 },
  { t: 'Community', y: 2009, net: 1 },
  { t: 'Archer', y: 2009, ani: 1, ten: 1, cable: 1 },
  // ── 2010s ──
  { t: 'The Walking Dead', y: 2010, ten: 1, cable: 1, book: 1 },
  { t: 'Game of Thrones', y: 2011, emmy: 1, cable: 1, book: 1 },
  { t: 'Homeland', y: 2011, emmy: 1, cable: 1 },
  { t: 'American Horror Story', y: 2011, ten: 1, cable: 1 },
  { t: 'Black Mirror', y: 2011, str: 1 },
  { t: 'Veep', y: 2012, emmy: 1, cable: 1 },
  { t: 'Scandal', y: 2012, net: 1 },
  { t: 'House of Cards', y: 2013, str: 1, book: 1 },
  { t: 'Orange Is the New Black', a: ['oitnb'], y: 2013, str: 1, book: 1 },
  { t: 'Brooklyn Nine-Nine', a: ['brooklyn 99', 'brooklyn nine nine'], y: 2013, net: 1 },
  { t: 'Rick and Morty', y: 2013, ani: 1, cable: 1 },
  { t: 'Peaky Blinders', y: 2013, str: 1 },
  { t: 'True Detective', y: 2014, cable: 1 },
  { t: 'Fargo', y: 2014, cable: 1 },
  { t: 'BoJack Horseman', a: ['bojack'], y: 2014, ani: 1, str: 1 },
  { t: 'Better Call Saul', y: 2015, cable: 1 },
  { t: 'Narcos', y: 2015, str: 1 },
  { t: 'Mr. Robot', a: ['mr robot'], y: 2015, nyc: 1, cable: 1 },
  { t: 'Stranger Things', y: 2016, str: 1 },
  { t: 'The Crown', y: 2016, emmy: 1, str: 1 },
  { t: 'This Is Us', y: 2016, net: 1 },
  { t: 'Atlanta', y: 2016, cable: 1 },
  { t: 'Westworld', y: 2016, cable: 1 },
  { t: 'The Handmaid\'s Tale', a: ['handmaids tale'], y: 2017, emmy: 1, str: 1, book: 1 },
  { t: 'The Marvelous Mrs. Maisel', a: ['mrs maisel', 'marvelous mrs maisel'], y: 2017, emmy: 1, str: 1, nyc: 1 },
  { t: 'Big Little Lies', y: 2017, cable: 1, book: 1 },
  { t: 'Ozark', y: 2017, str: 1 },
  { t: 'Riverdale', y: 2017, book: 1 },
  { t: 'Succession', y: 2018, emmy: 1, nyc: 1, cable: 1 },
  { t: 'Yellowstone', y: 2018, cable: 1 },
  { t: 'The Boys', y: 2019, str: 1, book: 1 },
  { t: 'Fleabag', y: 2016, emmy: 1, str: 1 },
  { t: 'Schitt\'s Creek', a: ['schitts creek'], y: 2015, emmy: 1 },
  { t: 'The Mandalorian', y: 2019, str: 1 },
  { t: 'Euphoria', y: 2019, cable: 1 },
  { t: 'The Witcher', y: 2019, str: 1, book: 1 },
  { t: 'Chernobyl', y: 2019, cable: 1 },
  { t: 'When They See Us', y: 2019, str: 1, nyc: 1 },
  // ── 2020s ──
  { t: 'Ted Lasso', y: 2020, emmy: 1, str: 1 },
  { t: 'The Queen\'s Gambit', a: ['queens gambit'], y: 2020, str: 1, book: 1 },
  { t: 'Bridgerton', y: 2020, str: 1, book: 1 },
  { t: 'The Last Dance', y: 2020, cable: 1 },
  { t: 'Squid Game', y: 2021, str: 1 },
  { t: 'The White Lotus', a: ['white lotus'], y: 2021, cable: 1 },
  { t: 'Only Murders in the Building', a: ['only murders'], y: 2021, str: 1, nyc: 1 },
  { t: 'Yellowjackets', y: 2021, cable: 1 },
  { t: 'Hacks', y: 2021, emmy: 1, str: 1 },
  { t: 'Abbott Elementary', y: 2021, net: 1 },
  { t: 'Severance', y: 2022, str: 1 },
  { t: 'The Bear', y: 2022, emmy: 1, str: 1 },
  { t: 'Wednesday', y: 2022, str: 1, book: 1 },
  { t: 'House of the Dragon', y: 2022, cable: 1, book: 1 },
  { t: 'The Last of Us', y: 2023, cable: 1, book: 1 },
  { t: 'Shogun', a: ['shōgun'], y: 2024, emmy: 1, cable: 1, book: 1 },
  { t: 'Fallout', y: 2024, str: 1, book: 1 },
  { t: 'The Pitt', y: 2025, emmy: 1, str: 1 },
];
