// Niche facts: PRO SPORTS TEAMS (the Friday universe). The current 124 big
// four franchises (32 NFL, 30 NBA, 30 MLB, 32 NHL), one row each.
//
// FIELD RULES:
//   lg     nfl | nba | mlb | nhl.
//   st     home state (two-letter), or the province for a Canadian team. The
//         Giants and Jets carry NY (they are New York teams that play in New
//         Jersey, the generous reading); the Commanders carry MD.
//   can    based in Canada.
//   champ  won its league championship in 2000 or later, through the most
//          recently completed championships as of authoring: Super Bowl LX,
//          the 2026 NBA title (Knicks) and 2026 Stanley Cup (Hurricanes),
//          and the 2025 NBA, NHL and World Series titles. The 2026 World
//          Series is not yet decided.
//   animal name is a creature (Bruins are bears and the Mammoth counts, the
//          generous reading; mythical Kraken and generic Predators do not).
//   old    franchise founded before 1950 (original-16 MLB, Original Six NHL,
//          the pre-war NFL and BAA-era NBA clubs).
//   bird   the nickname is a bird, a strict subset of animal (the Blue Jays
//          and the Orioles included, the mythical Seahawks by the same
//          generous reading that lets the Bruins be bears).
//   a      typed aliases, lowercase (the bare nickname always works).
export const TEAMS = [
  // ── NFL ──
  { t: 'Arizona Cardinals', lg: 'nfl', st: 'AZ', animal: 1, old: 1, bird: 1 },
  { t: 'Atlanta Falcons', lg: 'nfl', st: 'GA', animal: 1, bird: 1 },
  { t: 'Baltimore Ravens', lg: 'nfl', st: 'MD', animal: 1, champ: 1, bird: 1 },
  { t: 'Buffalo Bills', lg: 'nfl', st: 'NY' },
  { t: 'Carolina Panthers', lg: 'nfl', st: 'NC', animal: 1 },
  { t: 'Chicago Bears', lg: 'nfl', st: 'IL', animal: 1, old: 1 },
  { t: 'Cincinnati Bengals', lg: 'nfl', st: 'OH', animal: 1 },
  { t: 'Cleveland Browns', lg: 'nfl', st: 'OH', old: 1 },
  { t: 'Dallas Cowboys', lg: 'nfl', st: 'TX' },
  { t: 'Denver Broncos', lg: 'nfl', st: 'CO', animal: 1, champ: 1 },
  { t: 'Detroit Lions', lg: 'nfl', st: 'MI', animal: 1, old: 1 },
  { t: 'Green Bay Packers', lg: 'nfl', st: 'WI', champ: 1, old: 1 },
  { t: 'Houston Texans', lg: 'nfl', st: 'TX' },
  { t: 'Indianapolis Colts', lg: 'nfl', st: 'IN', animal: 1, champ: 1 },
  { t: 'Jacksonville Jaguars', lg: 'nfl', st: 'FL', animal: 1 },
  { t: 'Kansas City Chiefs', lg: 'nfl', st: 'MO', champ: 1 },
  { t: 'Las Vegas Raiders', lg: 'nfl', st: 'NV' },
  { t: 'Los Angeles Chargers', lg: 'nfl', st: 'CA' },
  { t: 'Los Angeles Rams', lg: 'nfl', st: 'CA', animal: 1, champ: 1, old: 1 },
  { t: 'Miami Dolphins', lg: 'nfl', st: 'FL', animal: 1 },
  { t: 'Minnesota Vikings', lg: 'nfl', st: 'MN' },
  { t: 'New England Patriots', lg: 'nfl', st: 'MA', champ: 1 },
  { t: 'New Orleans Saints', lg: 'nfl', st: 'LA', champ: 1 },
  { t: 'New York Giants', lg: 'nfl', st: 'NY', champ: 1, old: 1 },
  { t: 'New York Jets', lg: 'nfl', st: 'NY' },
  { t: 'Philadelphia Eagles', lg: 'nfl', st: 'PA', animal: 1, champ: 1, old: 1, bird: 1 },
  { t: 'Pittsburgh Steelers', lg: 'nfl', st: 'PA', champ: 1, old: 1 },
  { t: 'San Francisco 49ers', a: ['49ers', 'niners'], lg: 'nfl', st: 'CA', old: 1 },
  { t: 'Seattle Seahawks', lg: 'nfl', st: 'WA', animal: 1, champ: 1, bird: 1 },
  { t: 'Tampa Bay Buccaneers', a: ['bucs'], lg: 'nfl', st: 'FL', champ: 1 },
  { t: 'Tennessee Titans', lg: 'nfl', st: 'TN' },
  { t: 'Washington Commanders', lg: 'nfl', st: 'MD', old: 1 },
  // ── NBA ──
  { t: 'Atlanta Hawks', lg: 'nba', st: 'GA', animal: 1, old: 1, bird: 1 },
  { t: 'Boston Celtics', lg: 'nba', st: 'MA', champ: 1, old: 1 },
  { t: 'Brooklyn Nets', lg: 'nba', st: 'NY' },
  { t: 'Charlotte Hornets', lg: 'nba', st: 'NC', animal: 1 },
  { t: 'Chicago Bulls', lg: 'nba', st: 'IL', animal: 1 },
  { t: 'Cleveland Cavaliers', a: ['cavs'], lg: 'nba', st: 'OH', champ: 1 },
  { t: 'Dallas Mavericks', a: ['mavs'], lg: 'nba', st: 'TX', champ: 1 },
  { t: 'Denver Nuggets', lg: 'nba', st: 'CO', champ: 1 },
  { t: 'Detroit Pistons', lg: 'nba', st: 'MI', champ: 1, old: 1 },
  { t: 'Golden State Warriors', lg: 'nba', st: 'CA', champ: 1, old: 1 },
  { t: 'Houston Rockets', lg: 'nba', st: 'TX' },
  { t: 'Indiana Pacers', lg: 'nba', st: 'IN' },
  { t: 'Los Angeles Clippers', lg: 'nba', st: 'CA' },
  { t: 'Los Angeles Lakers', lg: 'nba', st: 'CA', champ: 1, old: 1 },
  { t: 'Memphis Grizzlies', lg: 'nba', st: 'TN', animal: 1 },
  { t: 'Miami Heat', lg: 'nba', st: 'FL', champ: 1 },
  { t: 'Milwaukee Bucks', lg: 'nba', st: 'WI', animal: 1, champ: 1 },
  { t: 'Minnesota Timberwolves', lg: 'nba', st: 'MN', animal: 1 },
  { t: 'New Orleans Pelicans', lg: 'nba', st: 'LA', animal: 1, bird: 1 },
  { t: 'New York Knicks', lg: 'nba', st: 'NY', champ: 1, old: 1 },
  { t: 'Oklahoma City Thunder', a: ['okc thunder', 'okc'], lg: 'nba', st: 'OK', champ: 1 },
  { t: 'Orlando Magic', lg: 'nba', st: 'FL' },
  { t: 'Philadelphia 76ers', a: ['76ers', 'sixers'], lg: 'nba', st: 'PA', old: 1 },
  { t: 'Phoenix Suns', lg: 'nba', st: 'AZ' },
  { t: 'Portland Trail Blazers', a: ['blazers', 'trailblazers'], lg: 'nba', st: 'OR' },
  { t: 'Sacramento Kings', lg: 'nba', st: 'CA', old: 1 },
  { t: 'San Antonio Spurs', lg: 'nba', st: 'TX', champ: 1 },
  { t: 'Toronto Raptors', lg: 'nba', st: 'ON', can: 1, animal: 1, champ: 1 },
  { t: 'Utah Jazz', lg: 'nba', st: 'UT' },
  { t: 'Washington Wizards', lg: 'nba', st: 'DC' },
  // ── MLB ──
  { t: 'Arizona Diamondbacks', a: ['dbacks', 'd-backs'], lg: 'mlb', st: 'AZ', animal: 1, champ: 1 },
  { t: 'Athletics', a: ['oakland athletics', 'as', "a's"], lg: 'mlb', st: 'CA', old: 1 },
  { t: 'Atlanta Braves', lg: 'mlb', st: 'GA', champ: 1, old: 1 },
  { t: 'Baltimore Orioles', a: ['os'], lg: 'mlb', st: 'MD', animal: 1, old: 1, bird: 1 },
  { t: 'Boston Red Sox', lg: 'mlb', st: 'MA', champ: 1, old: 1 },
  { t: 'Chicago Cubs', lg: 'mlb', st: 'IL', animal: 1, champ: 1, old: 1 },
  { t: 'Chicago White Sox', lg: 'mlb', st: 'IL', champ: 1, old: 1 },
  { t: 'Cincinnati Reds', lg: 'mlb', st: 'OH', old: 1 },
  { t: 'Cleveland Guardians', lg: 'mlb', st: 'OH', old: 1 },
  { t: 'Colorado Rockies', lg: 'mlb', st: 'CO' },
  { t: 'Detroit Tigers', lg: 'mlb', st: 'MI', animal: 1, old: 1 },
  { t: 'Houston Astros', lg: 'mlb', st: 'TX', champ: 1 },
  { t: 'Kansas City Royals', lg: 'mlb', st: 'MO', champ: 1 },
  { t: 'Los Angeles Angels', lg: 'mlb', st: 'CA', champ: 1 },
  { t: 'Los Angeles Dodgers', lg: 'mlb', st: 'CA', champ: 1, old: 1 },
  { t: 'Miami Marlins', lg: 'mlb', st: 'FL', animal: 1, champ: 1 },
  { t: 'Milwaukee Brewers', lg: 'mlb', st: 'WI' },
  { t: 'Minnesota Twins', lg: 'mlb', st: 'MN', old: 1 },
  { t: 'New York Mets', lg: 'mlb', st: 'NY' },
  { t: 'New York Yankees', lg: 'mlb', st: 'NY', champ: 1, old: 1 },
  { t: 'Philadelphia Phillies', lg: 'mlb', st: 'PA', champ: 1, old: 1 },
  { t: 'Pittsburgh Pirates', lg: 'mlb', st: 'PA', old: 1 },
  { t: 'San Diego Padres', lg: 'mlb', st: 'CA' },
  { t: 'San Francisco Giants', lg: 'mlb', st: 'CA', champ: 1, old: 1 },
  { t: 'Seattle Mariners', lg: 'mlb', st: 'WA' },
  { t: 'St. Louis Cardinals', a: ['st louis cardinals', 'cardinals'], lg: 'mlb', st: 'MO', animal: 1, champ: 1, old: 1, bird: 1 },
  { t: 'Tampa Bay Rays', lg: 'mlb', st: 'FL', animal: 1 },
  { t: 'Texas Rangers', lg: 'mlb', st: 'TX', champ: 1 },
  { t: 'Toronto Blue Jays', a: ['jays'], lg: 'mlb', st: 'ON', can: 1, animal: 1, bird: 1 },
  { t: 'Washington Nationals', a: ['nats'], lg: 'mlb', st: 'DC', champ: 1 },
  // ── NHL ──
  { t: 'Anaheim Ducks', lg: 'nhl', st: 'CA', animal: 1, champ: 1, bird: 1 },
  { t: 'Boston Bruins', lg: 'nhl', st: 'MA', animal: 1, champ: 1, old: 1 },
  { t: 'Buffalo Sabres', lg: 'nhl', st: 'NY' },
  { t: 'Calgary Flames', lg: 'nhl', st: 'AB', can: 1 },
  { t: 'Carolina Hurricanes', a: ['canes'], lg: 'nhl', st: 'NC', champ: 1 },
  { t: 'Chicago Blackhawks', lg: 'nhl', st: 'IL', champ: 1, old: 1 },
  { t: 'Colorado Avalanche', a: ['avs'], lg: 'nhl', st: 'CO', champ: 1 },
  { t: 'Columbus Blue Jackets', lg: 'nhl', st: 'OH' },
  { t: 'Dallas Stars', lg: 'nhl', st: 'TX' },
  { t: 'Detroit Red Wings', lg: 'nhl', st: 'MI', champ: 1, old: 1 },
  { t: 'Edmonton Oilers', lg: 'nhl', st: 'AB', can: 1 },
  { t: 'Florida Panthers', lg: 'nhl', st: 'FL', animal: 1, champ: 1 },
  { t: 'Los Angeles Kings', lg: 'nhl', st: 'CA', champ: 1 },
  { t: 'Minnesota Wild', lg: 'nhl', st: 'MN' },
  { t: 'Montreal Canadiens', a: ['habs'], lg: 'nhl', st: 'QC', can: 1, old: 1 },
  { t: 'Nashville Predators', a: ['preds'], lg: 'nhl', st: 'TN' },
  { t: 'New Jersey Devils', lg: 'nhl', st: 'NJ', champ: 1 },
  { t: 'New York Islanders', a: ['isles'], lg: 'nhl', st: 'NY' },
  { t: 'New York Rangers', lg: 'nhl', st: 'NY', old: 1 },
  { t: 'Ottawa Senators', a: ['sens'], lg: 'nhl', st: 'ON', can: 1 },
  { t: 'Philadelphia Flyers', lg: 'nhl', st: 'PA' },
  { t: 'Pittsburgh Penguins', a: ['pens'], lg: 'nhl', st: 'PA', animal: 1, champ: 1, bird: 1 },
  { t: 'San Jose Sharks', lg: 'nhl', st: 'CA', animal: 1 },
  { t: 'Seattle Kraken', lg: 'nhl', st: 'WA' },
  { t: 'St. Louis Blues', a: ['st louis blues'], lg: 'nhl', st: 'MO', champ: 1 },
  { t: 'Tampa Bay Lightning', a: ['bolts'], lg: 'nhl', st: 'FL', champ: 1 },
  { t: 'Toronto Maple Leafs', a: ['leafs'], lg: 'nhl', st: 'ON', can: 1, old: 1 },
  { t: 'Utah Mammoth', lg: 'nhl', st: 'UT', animal: 1 },
  { t: 'Vancouver Canucks', lg: 'nhl', st: 'BC', can: 1 },
  { t: 'Vegas Golden Knights', a: ['las vegas golden knights', 'knights'], lg: 'nhl', st: 'NV', champ: 1 },
  { t: 'Washington Capitals', a: ['caps'], lg: 'nhl', st: 'DC', champ: 1 },
  { t: 'Winnipeg Jets', lg: 'nhl', st: 'MB', can: 1 },
];
