// Redact bank extension, Person lane. 19 capsule articles for the assembler to
// place on days; identity fields (num/quizId/live/dateLabel/sunday) are set there.
// Authored against the rules in app/redact/puzzles.js and gated by
// scripts/verify-redact.mjs.
export const ARTICLES = [
  {
    cat: 'Person', diff: 2, answer: 'Nelson Mandela',
    aka: { mandella: 'mandela', mandelaa: 'mandela', nelsen: 'nelson' },
    text: `For eighteen of his twenty seven years in prison he was held on Robben Island, off Cape Town, where the inmates broke limestone in a quarry whose glare damaged his eyes for the rest of his life. Prisoners were graded by race for rations and clothing, and he spent years in a cell of about two metres square. With other political prisoners he also ran an informal teaching programme that the men called their university.\n\nNelson Rolihlahla Mandela was born in 1918 in the Transkei, in the Eastern Cape, into a family attached to the Thembu royal house. He studied law, opened with Oliver Tambo the first Black law practice in Johannesburg in 1952, and rose through the African National Congress and its Youth League as the National Party built the system of racial legislation known as apartheid. After the Sharpeville shootings of 1960 and the banning of the Congress, he helped found its armed wing and went underground.\n\nArrested in 1962, he was sentenced at the Rivonia Trial in 1964 to life imprisonment for sabotage and conspiracy. His statement from the dock, which closed by describing a democratic and free society as an ideal for which he was prepared to die, was widely reprinted and became the best known text of the movement. He refused a conditional release in 1985 and walked free in February 1990.\n\nThe negotiations he then led with President F. W. de Klerk produced an interim constitution and the first election open to all South Africans, held in April 1994, after which he served a single term as president and did not seek a second. His government created the Truth and Reconciliation Commission, chaired by Desmond Tutu, which took testimony from victims and offered amnesty in exchange for full disclosure. He shared the Nobel Peace Prize with de Klerk in 1993, left office in 1999, and died in 2013.`,
  },
  {
    cat: 'Person', diff: 2, answer: 'Florence Nightingale',
    aka: { nightengale: 'nightingale', nightinggale: 'nightingale', florance: 'florence' },
    text: `The diagram is still reproduced in textbooks on statistical graphics. A circle is divided into twelve wedges, one for each month of the war, and each wedge is shaded to separate the men who died of wounds from those who died of other causes and those who died of preventable disease. The areas for disease dwarf the rest. It was drawn to be understood by ministers and generals who would not read a table of figures, and it worked.\n\nFlorence Nightingale was born in 1820 in the Italian city she was named for, into a wealthy and well connected English family, and trained against the wishes of her parents as a nurse in Germany and in Paris. In 1854, after newspaper reports on the treatment of British casualties in the Crimean War, the war secretary Sidney Herbert asked her to take a party of thirty eight nurses to the military hospital at Scutari, across the water from Constantinople.\n\nConditions there were worse than in the field. The building stood over blocked sewers, water was short, and the death rate rose through the first winter before a sanitary commission arrived to flush the drains and improve the ventilation. She has often been credited with cutting the mortality by nursing alone, a claim she did not make herself; her later analysis of the figures concluded that most of the deaths had been preventable and that sanitation had made the difference.\n\nShe came home in 1856 a national figure, having been described in dispatches carrying a lamp through the wards at night, and she used that standing for the rest of a long life spent largely in her room in poor health. She published Notes on Nursing in 1859, founded a training school at St Thomas' Hospital in London in 1860, and pressed committees and viceroys on the sanitary state of the army in India. She was elected the first woman member of the Statistical Society of London in 1858, and she died in 1910.`,
  },
  {
    cat: 'Person', diff: 2, answer: 'Mahatma Gandhi',
    aka: { ghandi: 'gandhi', gandi: 'gandhi', gandhii: 'gandhi', mahatama: 'mahatma' },
    text: `In March 1930 a column of marchers left an ashram near Ahmedabad and walked for twenty four days to the Arabian Sea at Dandi, gathering people as it went. At the shore its leader picked up a lump of natural salt from the mud, an act that broke a colonial monopoly under which Indians were forbidden to make or sell their own. Tens of thousands were arrested in the campaign that followed, and the photographs travelled around the world.\n\nMohandas Karamchand Gandhi was born in 1869 at Porbandar, on the coast of Gujarat, and trained as a barrister in London. His formative political years were spent in South Africa, where he arrived in 1893 and stayed more than twenty, organising Indian merchants and labourers against discriminatory laws and working out the method he called satyagraha, usually translated as truth force or holding firmly to truth.\n\nHe returned to India in 1915 and helped turn the Indian National Congress from a body of lawyers and notables into a mass movement. He led non cooperation after the Amritsar massacre of 1919, called the campaign off when protesters killed policemen at Chauri Chaura, and used fasting repeatedly as a political instrument. He spun cotton daily and made homespun cloth a symbol of self reliance, and he campaigned against untouchability, giving the name Harijan to communities excluded by caste, a term many of them later rejected.\n\nMahatma Gandhi is an honorific rather than a name, meaning roughly great soul, and by most accounts he was uncomfortable with it. He was nominated for the Nobel Peace Prize several times and never received it. Independence came in August 1947 together with partition, which he had opposed and whose violence he spent his last months trying to quiet in Bengal and in Delhi. He was shot in Delhi on 30 January 1948 by a Hindu nationalist who objected to his conciliation of Muslims, and his methods went on to shape protest movements on several continents.`,
  },
  {
    cat: 'Person', diff: 2, answer: 'Confucius',
    aka: { confucious: 'confucius', confusius: 'confucius', konfucius: 'confucius', confuscius: 'confucius' },
    text: `The book that carries his teaching was not written by him. The Analects is a compilation of short sayings and exchanges, assembled by pupils and by pupils of pupils over perhaps a century and a half after his death, and its twenty books vary in style and in reliability. Much of it takes the form of replies: the master said, when asked about government, or about ritual, or about the conduct proper to a son.\n\nConfucius is the Latinised form of Kong Fuzi, meaning Master Kong. He was born about 551 BC in the small state of Lu, in what is now Shandong province, during the long decline of the Zhou dynasty. He held minor office there and then spent years travelling between courts in search of a ruler who would apply his ideas. He found none, and came back to teach.\n\nHis concern was less with gods than with conduct. He argued that order in a state grows out of order in a family and in the self, that a ruler governs best by moral example rather than by punishment, and that the old rites, properly understood, train people in benevolence. Two terms recur: ren, usually rendered as humaneness, and li, the forms of ritual and propriety. He also stated a version of the golden rule in the negative, telling a questioner not to impose on others what he did not want for himself.\n\nHis pupils carried the teaching on, and later thinkers such as Mencius and Xunzi developed it in different directions. From the Han dynasty onward his teaching was state orthodoxy, and the classics associated with him later supplied the matter of the civil service examinations, which shaped Chinese officialdom until 1905. The tradition spread through Korea, Japan and Vietnam. Temples were built in his honour, his descendants were ennobled for many centuries, and his reputation has been attacked and restored repeatedly, most sharply during the political campaigns of the twentieth century.`,
  },
  {
    cat: 'Person', diff: 2, answer: 'Amelia Earhart',
    aka: { earheart: 'earhart', airhart: 'earhart', earhardt: 'earhart', amelie: 'amelia' },
    text: `On 20 May 1932, five years to the day after Charles Lindbergh left New York, a single engine Lockheed Vega took off from Harbour Grace in Newfoundland bound for Paris. Ice, a cracked exhaust manifold and a leaking fuel tank turned the crossing into a fight, and after roughly fifteen hours the pilot put down in a pasture near Culmore in Northern Ireland and asked a farmhand where she was.\n\nAmelia Earhart, born at Atchison in Kansas in 1897, had come to flying late and by way of odd jobs, taking lessons from Neta Snook in California in 1921 and buying a second hand biplane she called the Canary. In 1928 she was invited to cross the Atlantic as a passenger aboard the Friendship, becoming the first woman to make the trip by air, and she said plainly afterwards that she had been little more than baggage. Publicity organised by the publisher George Putnam, whom she later married, gave her the means to fly seriously.\n\nRecords followed. She was the first woman to fly the Atlantic alone, and in 1935 the first person to fly solo from Hawaii to California, a route on which several fliers had died. She was a founder and the first president of the Ninety Nines, an organisation of women pilots, and she wrote and lectured constantly, arguing that women should be judged on the same terms as men in aviation and elsewhere.\n\nIn 1937 she set out with the navigator Fred Noonan to fly around the world near the equator in a twin engine Lockheed Electra. They had covered about two thirds of the distance when they left Lae in New Guinea on 2 July for Howland Island, a flat speck of coral in the central Pacific. Radio contact with a coastguard cutter grew fragmentary and then stopped. A large naval search found nothing, and the disappearance has never been explained, which has kept a steady traffic of theories in circulation ever since.`,
  },
  {
    cat: 'Person', diff: 2, answer: 'Pele',
    aka: { pelee: 'pele', pelle: 'pele' },
    text: `The goal that people describe most often was never filmed. In a league match at the Maracana in 1961 he is said to have beaten most of the opposing side from inside his own half before scoring, and Brazilian newspapers called it the goal of the plaque, since a plaque was later fixed at the stadium to record it. No footage survives, which has probably made it a better story.\n\nPele was born Edson Arantes do Nascimento in 1940 at Tres Coracoes in Minas Gerais, the son of a footballer whose own career had been cut short by injury. The nickname came from schoolmates, he disliked it at first, and he never gave a settled account of what it meant. He was playing for Santos at fifteen and for the national side at sixteen.\n\nHe arrived at the 1958 World Cup in Sweden as an unknown seventeen year old carrying a knee injury, scored three goals in the semi final against France and two in the final against the hosts, and finished the tournament in tears. Injury limited him in 1962, and in 1966 in England he was kicked out of the competition by defenders in an era before referees protected attacking players. He came back in 1970 with the Brazilian side often called the finest ever assembled, and he remains the only player to hold three World Cup winners medals.\n\nHe spent almost his whole club career at Santos, a provincial team that toured the world because he was in it, and he finished with the New York Cosmos from 1975, where he did more than anyone to establish the professional game in the United States. His career total is usually given as more than a thousand goals, a figure that includes friendly and exhibition matches and is disputed on that ground. He later served as his country's minister of sport, and he died in 2022.`,
  },
  {
    cat: 'Person', diff: 3, answer: 'Harriet Tubman',
    aka: { tubmann: 'tubman', tubmen: 'tubman', harriett: 'harriet', harryet: 'harriet' },
    text: `In June 1863, on the Combahee River in South Carolina, three Union gunboats worked upriver past batteries and mines, guided by a scout who had spent weeks gathering intelligence from enslaved people along the banks. The raid burned rice stores and plantation property and carried away more than seven hundred people, who waded and swam out to the boats. The scout was a woman who had been enslaved herself, and she is generally described as the first woman to lead an armed expedition in that war.\n\nShe was born Araminta Ross, about 1822, on the Eastern Shore of Maryland, and later took her mother's first name and her husband's surname. As a girl she was struck in the head by an iron weight thrown by an overseer at somebody else, an injury that left her with seizures and vivid dreams for the rest of her life. In 1849 she escaped alone to Philadelphia, guided by the North Star and by a network of sympathisers.\n\nHarriet Tubman then went back. Over about a decade she made some thirteen journeys into Maryland and brought out roughly seventy people, family members first among them, working mostly in winter and at night. The Fugitive Slave Act of 1850 obliged her to take her passengers as far as Canada. Later tallies crediting her with hundreds of rescues appear to derive from an admiring early biography rather than from her own careful accounts.\n\nAfter the war she settled at Auburn in New York, cared for elderly and destitute neighbours and eventually founded a home for them, and spoke for women's suffrage alongside Susan B. Anthony. She spent decades petitioning for a pension for her own war service and was granted one first as a soldier's widow, and only in 1899 at a rate that acknowledged what she had done herself. She died in 1913. A proposal to place her portrait on United States currency, announced in 2016, has been repeatedly delayed.`,
  },
  {
    cat: 'Person', diff: 3, answer: 'Simon Bolivar',
    aka: { boliver: 'bolivar', bolivaar: 'bolivar', symon: 'simon' },
    text: `In 1819, at the head of an army that mixed llanero horsemen from the Venezuelan plains with British and Irish veterans of the Napoleonic wars, a Creole general took a route his enemies thought impassable. He crossed the flooded lowlands of the Orinoco in the rainy season and then the Andes by the paramo of Pisba, losing horses and men to the cold at four thousand metres, and came down on the far side into New Granada. Days later he destroyed the royalist force at Boyaca and rode into Bogota.\n\nSimon Bolivar was born in Caracas in 1783 into a wealthy landowning family, was orphaned young, and was educated in part by Simon Rodriguez, a tutor of radical views who took him to Europe. He came home committed to independence from Spain. The first republics he helped proclaim collapsed twice, once after an earthquake that royalist clergy read as a judgement, and exile in Jamaica and then Haiti followed. Haitian support was given on the condition that he free the enslaved in any territory he took.\n\nHe is remembered as the Liberator, a title granted him by the city of Caracas in 1813. Campaigns he led or directed contributed to the independence of the territories that became Venezuela, Colombia, Panama, Ecuador, Peru and Bolivia, the last of which took his name. His ablest lieutenant, Antonio Jose de Sucre, won the decisive battle at Ayacucho in 1824.\n\nHis political project outlasted him less well than his military one. He founded the union usually called Gran Colombia and served as its president, argued in the Cartagena manifesto and the Angostura address for a strong central authority, and grew convinced that the region could not be governed by the constitutions it kept writing. The union was breaking apart in the year he died of tuberculosis, in 1830, at Santa Marta on the Colombian coast, aged forty seven.`,
  },
  {
    cat: 'Person', diff: 3, answer: 'Katsushika Hokusai',
    aka: { hokusi: 'hokusai', hokasai: 'hokusai', hokusay: 'hokusai', katsushica: 'katsushika' },
    text: `The print is often mistaken for a picture of a tsunami. It shows a deep trough and a curling crest tipped with claws of foam, three long boats of the kind used to rush fish to the markets of Edo, and behind them, small and still, the cone of Mount Fuji. It was published about 1831 in a series of thirty six views of that mountain, printed from carved cherry blocks in an edition that eventually ran to thousands of impressions, and it sold for roughly the price of a bowl of noodles.\n\nThe artist who designed it was born in Edo in 1760 and apprenticed to a woodblock carver before entering the studio of the print designer Katsukawa Shunsho. He changed his professional name some thirty times over a long career, a habit unusual even in that trade, and is said to have moved house nearly a hundred times. Katsushika Hokusai is the name under which most of his best known work appeared, adopted in middle age.\n\nHe worked in nearly every category of the Japanese print market: actors and courtesans early on, then landscapes, studies of birds and flowers, privately commissioned greeting prints, book illustration and erotica. From 1814 he issued the Manga, fifteen volumes of sketches of people, animals, tools, gods and grotesques, intended partly as a drawing manual and now the source of the modern use of that word. The famous wave owes some of its effect to imported Prussian blue, a cheap and stable pigment newly available in Japan.\n\nHe went on working into his late eighties, writing that nothing he had made before the age of seventy was of any account and that another decade might make him a real painter. His daughter Oi was an accomplished artist who worked alongside him. After Japan opened to trade his prints reached Europe in quantity and shaped the taste of Degas, Monet and Whistler, and the wave has since become one of the most reproduced images anywhere.`,
  },
  {
    cat: 'Person', diff: 3, answer: 'Adam Smith',
    aka: { smyth: 'smith', smithe: 'smith' },
    text: `The phrase everyone remembers appears exactly once in the book. In a passage explaining why merchants tend to invest at home, the author writes that each of them is led by an invisible hand to promote an end that formed no part of his intention. The image occurs twice more across his other writings and carries less weight there than later readers have given it; he used it in passing, and most of the theory built around it belongs to his successors.\n\nAn Inquiry into the Nature and Causes of the Wealth of Nations was published in March 1776 in two volumes. It opens not with markets but with a pin factory, where dividing the work into eighteen distinct operations lets ten people make far more pins than they could working singly, and it builds from there into arguments about specialisation, the extent of the market, wages, rent and the folly of restricting trade.\n\nAdam Smith was baptised at Kirkcaldy in Fife in 1723, studied at Glasgow and at Balliol College in Oxford, which he thought idle, and became professor of moral philosophy at Glasgow in 1752. His first book, The Theory of Moral Sentiments of 1759, grounds ethics in sympathy, the capacity to imagine oneself in another position and to judge conduct through an impartial spectator. He seems to have regarded it as the more important work, and scholars have long argued over how the two books fit together.\n\nHe spent three years as travelling tutor to a young duke, meeting Voltaire and the French economists, then lived on the resulting pension and wrote for a decade. He later took a post as a commissioner of customs in Edinburgh, an office his admirers find awkward. He had his unpublished manuscripts burned shortly before his death in 1790. His arguments were used to justify free trade through the following century, often more confidently than he had made them, since he also wrote about the dulling effect of repetitive labour and defended schooling at public expense.`,
  },
  {
    cat: 'Person', diff: 3, answer: 'Zaha Hadid',
    aka: { zahra: 'zaha', hadeed: 'hadid', haddid: 'hadid', hadidd: 'hadid' },
    text: `For more than a decade the practice was known for buildings that did not get built. A competition win in 1983 for a leisure club on the Peak above Hong Kong produced a set of paintings, owing something to Russian Suprematism, in which the plan is exploded and seen from several angles at once; the club was never constructed. A design that won the competition for an opera house at Cardiff Bay in 1994 was abandoned after a political quarrel over funding. Critics called the work unbuildable, which was partly a comment on the drawings and partly on the technology of the time.\n\nZaha Hadid was born in Baghdad in 1950, studied mathematics at the American University of Beirut, and came to London in 1972 to the Architectural Association, where she later taught. She worked briefly with her former tutors Rem Koolhaas and Elia Zenghelis before opening her own office in 1980.\n\nThe first completed building of note was a small fire station for the Vitra furniture factory at Weil am Rhein in Germany, finished in 1993 and made of sharp folded planes of concrete. Advances in computer modelling then allowed the curves her drawings had implied, and a run of major commissions followed: the Rosenthal Center in Cincinnati, the Phaeno science centre at Wolfsburg, the Guangzhou opera house, the London Aquatics Centre, and the Heydar Aliyev Center in Baku.\n\nShe was the first woman to receive the Pritzker Prize, in 2004, and won the Stirling Prize in two consecutive years. Her work drew steady criticism as well: for cost, for indifference to its surroundings, and, over a stadium project in Qatar, for the treatment of migrant construction workers, a charge she disputed. She died in Miami in 2016, at sixty five, with a large number of projects still on the boards, and the firm has continued under her longtime partner Patrik Schumacher.`,
  },
  {
    cat: 'Person', diff: 4, answer: 'Ibn Battuta',
    aka: { battutah: 'battuta', batuta: 'battuta', battouta: 'battuta', ibnbattuta: 'battuta' },
    text: `The book was not written by the traveller. Back in Morocco after nearly three decades on the road, he was assigned by the sultan a young Andalusian scholar, Ibn Juzayy, who took down the account, polished the prose, and lifted passages from an earlier writer to fill out descriptions the narrator had lost or perhaps never made. The result, whose title translates roughly as a gift to those who contemplate the wonders of cities and the marvels of travelling, is usually shortened to the Rihla, meaning simply the journey.\n\nHe set out from Tangier in 1325, aged twenty one, to make the pilgrimage to Mecca, and did not come home for twenty four years. The route ran through Egypt, Syria and the Hijaz, then east into Iraq and Persia, down the Red Sea and along the Swahili coast as far as Kilwa, back through Oman and the Gulf, and north across Anatolia and the steppe to the Golden Horde. Everywhere he sought out judges, scholars and rulers, since he was a qualified jurist of the Maliki school and hospitality to such men was expected of the pious rich.\n\nIbn Battuta reached India about 1333 and served the sultan of Delhi, Muhammad bin Tughluq, as a judge for several years, an unpredictable employer whose favour he was lucky to survive. Sent on an embassy to China, he was shipwrecked, spent time in the Maldives, where he served as a judge again, and eventually reached the Chinese coast, though this stretch of the narrative is the most doubted. A later journey took him across the Sahara to the empire of Mali.\n\nHistorians treat the Rihla as a mixture of eyewitness reporting, borrowed description and plain error, and several legs of the route are disputed. What is not disputed is its range. It remains one of the fullest portraits of the fourteenth century Muslim world, from Granada to Bengal, by a man who claimed a distance no medieval traveller is known to have matched. He died in Morocco some time in the 1360s or 1370s.`,
  },
  {
    cat: 'Person', diff: 4, answer: 'Hatshepsut',
    aka: { hatchepsut: 'hatshepsut', hatshepsit: 'hatshepsut', hatsheput: 'hatshepsut', hatshepsute: 'hatshepsut' },
    text: `Archaeologists clearing a terraced temple of colonnades at Deir el Bahari, cut back into the cliff on the west bank of the Nile opposite Thebes, found that a great many of its reliefs had been deliberately damaged. Faces and names had been chiselled out and in places replaced with those of other kings. Later digging nearby turned up the statues that had stood there, broken up and tipped into a quarry pit. The erasure was systematic but incomplete, and it is largely from what the workmen missed that the reign can be reconstructed.\n\nShe was the daughter of one king, the wife of the next, and on his death about 1479 BC became regent for her young stepson. Within a few years she had assumed the full titles of a king herself, and she ruled for roughly two decades. Egypt had known women who governed before, but none who reigned so long or left so much building behind.\n\nHatshepsut is usually shown in the conventional male royal costume, with kilt and false beard, which is best read as the standard iconography of kingship rather than as any attempt at disguise. Her temple reliefs advance two claims to legitimacy: that the god Amun fathered her, and that her father had named her his successor. The reign was largely peaceful and rich in trade, and its most celebrated relief records an expedition down the Red Sea to the land of Punt, whose ships come back loaded with myrrh trees, ebony, ivory and live baboons.\n\nHer chief official, Senenmut, oversaw much of the building and appears in unusual places within the temple, which has generated a great deal of speculation on very little evidence. The erasure of her name seems to have begun well into her successor's reign, decades after her death, which argues against a simple story of personal revenge; the likelier explanations concern the succession and the official record of kingship. Left out of later king lists, she was recovered only by excavation and by scholars reading the defaced walls.`,
  },
  {
    cat: 'Person', diff: 4, answer: 'Toussaint Louverture',
    aka: { ouverture: 'louverture', louvertur: 'louverture', toussant: 'toussaint', tousaint: 'toussaint' },
    text: `He was about fifty before he took any part in public events, and had been free for perhaps two decades before that. Born into slavery on the Breda plantation in the north of the French colony of Saint Domingue, probably in 1743, he worked as a coachman and a healer, learned to read, and was manumitted in the 1770s. He then rented land and for a time held enslaved people himself, a fact his admirers long passed over and which historians now discuss openly.\n\nThe colony was the richest in the Caribbean, producing a large share of the sugar and coffee sold in Europe on the labour of half a million enslaved people. When they rose in August 1791 he joined the insurgents, at first under Spanish colours, and emerged as their most capable commander. In 1794, after the French republic abolished slavery in its colonies, he changed sides and fought for France.\n\nToussaint Louverture added the second name himself, and contemporaries offered various explanations for it. By 1798 he had induced the British to withdraw, and by 1801 he governed the whole island, having marched into the Spanish east and freed the enslaved there as well. The constitution he promulgated that year abolished slavery permanently and named him governor for life, leaving France a nominal role; it also compelled former field workers to stay on the plantations under paid contract, since he judged that the export economy would otherwise collapse.\n\nNapoleon Bonaparte sent an expedition under his brother in law to restore French control and, it was widely suspected, slavery with it. After months of fighting and negotiation the governor was seized at a parley in 1802 and shipped to France, where he died in a cold fortress in the Jura in April 1803. The struggle went on without him and ended in the independence of Haiti in 1804, the first state in the Americas founded by people who had freed themselves from slavery.`,
  },
  {
    cat: 'Person', diff: 4, answer: 'Wangari Maathai',
    aka: { mathai: 'maathai', maatai: 'maathai', maathei: 'maathai', wangaari: 'wangari' },
    text: `The idea began with complaints, not with a theory. Rural women told her that the streams were drying up, that firewood had to be fetched from further away each year, and that the food they could grow was poorer than it had been. Her answer was to pay them a small sum for every seedling that survived, and to organise the planting in groups. The scheme, launched under the National Council of Women of Kenya in 1977, became the Green Belt Movement, and by most counts it has since put tens of millions of trees in the ground.\n\nWangari Muta Maathai was born in 1940 at Ihithe in the central highlands and went to the United States on a scholarship programme that brought hundreds of East African students to American universities. She studied biology in Kansas and Pittsburgh, came home, and in 1971 became the first woman in East or Central Africa to earn a doctorate, in veterinary anatomy at the University of Nairobi, where she later chaired her department.\n\nPlanting trees turned political because land was political. She campaigned against the allocation of public land to developers, most visibly in 1989 when she helped block a tower planned for Uhuru Park in Nairobi, and against the clearing of the Karura forest. She was arrested repeatedly, beaten on one occasion, and denounced in parliament during the long presidency of Daniel arap Moi.\n\nAfter multiparty elections she entered parliament in 2002 with a large majority and served as an assistant minister for the environment. In 2004 she became the first African woman to receive the Nobel Peace Prize, awarded for her contribution to sustainable development, democracy and peace, a linkage some observers questioned at the time and which has since become commonplace. She wrote several books, among them a memoir called Unbowed, sat on international commissions on forests and on Africa, and died in 2011.`,
  },
  {
    cat: 'Person', diff: 4, answer: 'Gabriela Mistral',
    aka: { mistrall: 'mistral', mistrale: 'mistral', gabriella: 'gabriela', gabrielle: 'gabriela' },
    text: `The name on the books was invented. She was born Lucila Godoy Alcayaga in 1889 in the Elqui valley, a narrow line of vineyards between bare hills in the north of Chile, and began publishing verse and articles in provincial newspapers while still a teenager. She had almost no formal schooling and was refused a place at a teacher training college, qualifying instead by examination, which did not stop her from spending most of her working life in classrooms and later in ministries of education.\n\nHer reputation was made in 1914, when three poems entered under a pen name won a national competition in Santiago. Gabriela Mistral is often said to join the names of the Italian poet Gabriele D'Annunzio and the Provencal poet Frederic Mistral, though she gave other explanations at different times and the question is not settled. A first collection, Desolacion, was published in New York in 1922 at the urging of an American scholarly society, and Ternura and Tala followed.\n\nBy then she was also an educational administrator of standing. The Mexican minister of education Jose Vasconcelos invited her in 1922 to help with a rural schooling and library programme, and she spent most of the rest of her life abroad, holding Chilean consular posts in Madrid, Lisbon, Nice, Petropolis and Los Angeles and teaching at American colleges. Her poems circulated in school readers across Latin America, many of them written for or about children.\n\nIn 1945 she became the first Latin American writer to receive the Nobel Prize in Literature, cited for lyric poetry that had made her name a symbol of the idealistic aspiration of her whole part of the world. She assigned the proceeds of Tala to children displaced by the Spanish civil war. She died in New York in 1957, and her body was taken back to Chile for a state funeral and buried at Montegrande, in the valley where she grew up.`,
  },
  {
    cat: 'Person', diff: 5, answer: 'Marie Tharp',
    aka: { tharpe: 'tharp', tharpp: 'tharp', marrie: 'marie' },
    text: `Women were not allowed on the ships. Through the 1950s the soundings that the Lamont Geological Observatory gathered in the Atlantic were taken by men aboard research vessels, and the work of turning columns of depth figures into pictures of the sea floor was done ashore, at a drafting table, by a geologist holding degrees in music, English, geology and mathematics. She plotted the profiles by hand, six of them across the North Atlantic, and drew the terrain between them in the oblique perspective that made the maps famous.\n\nMarie Tharp was born in Michigan in 1920, the daughter of a soil surveyor whose work moved the family constantly, and took a geology degree during the war, when petroleum programmes opened to women because the men had gone. She joined Lamont in 1948 and began working with Bruce Heezen, who supplied the data she drew.\n\nIn 1952 she noticed a notch shaped like a letter V running down the middle of the ridge that divides the Atlantic, present on all six of her profiles, and concluded that it was a rift valley, a place where the sea floor was pulling apart. Heezen is said to have called the idea girl talk, since it implied continental drift, which was then out of favour. He was persuaded when the rift was found to line up with a belt of earthquake epicentres, and the two of them published together.\n\nThe published form was itself a workaround. Detailed contour maps of the ocean floor were treated as sensitive by the United States Navy, on the ground that they would help a submarine navigate, so the results were issued instead as oblique panoramas drawn as though the water had been drained away. The compromise proved fortunate, since a painting of a mountain range reaches a reader who would take nothing from a sheet of contours.\n\nTheir physiographic diagrams of the ocean floor, painted with the Austrian landscape artist Heinrich Berann, culminated in a world map issued in 1977, and did as much as any single image to make sea floor spreading visible to people outside the field. Credit came slowly. Her name was left off some early presentations and papers, and her contribution was properly acknowledged only late in her life, after decades in which the maps were credited chiefly to the men she worked for. She died in 2006, and the rift she first drew is now understood as part of a ridge system that encircles the planet.`,
  },
  {
    cat: 'Person', diff: 5, answer: 'Murasaki Shikibu',
    aka: { murazaki: 'murasaki', murasake: 'murasaki', shikibou: 'shikibu', shikubu: 'shikibu' },
    text: `Nobody knows her name. The two words by which she is known are an office and a nickname: one refers to her father's post in the Bureau of Ceremonial, and the other is either the name of a character in her own book or a play on her family name, which was Fujiwara. Court women of eleventh century Japan were recorded by such labels rather than by personal names, and hers has not survived.\n\nShe was born about 973 into a minor branch of the great Fujiwara clan, a family of provincial governors and scholars rather than of ministers. Her father taught her brother the Chinese classics and remarked, she reports in her diary, that it was a pity she had not been born a boy, since she picked them up faster. She married a much older kinsman, had a daughter, was widowed within a few years, and entered the household of the empress Shoshi about 1005.\n\nMurasaki Shikibu wrote The Tale of Genji in the vernacular script used by women, at a court where men wrote in Chinese. It runs to fifty four chapters and follows the son of an emperor by a low ranking consort through a long life of love affairs, exile and political manoeuvre, then carries on for another generation after his death. It is frequently called the first novel, a claim worth hedging, though few dispute that it is a psychological narrative of great length and subtlety written centuries before anything comparable in Europe.\n\nHer diary survives as well, and is sharp about her colleagues; she thought Sei Shonagon far too pleased with herself. The tale circulated in manuscript, was copied, illustrated and annotated for centuries, and shaped Japanese poetry, painting and theatre. The English translation by Arthur Waley, issued in six volumes from 1925, made it known in the West, and several later translations have followed. Her death is usually placed around 1014, though the date is uncertain.\n\nNothing survives in her hand. The text scholars use descends chiefly from an edition prepared in the early thirteenth century by the poet Fujiwara no Teika, working two hundred years after her death from copies that already disagreed with one another, and a rival line of manuscripts complicates the picture further. The oldest illustrated version, a set of handscrolls painted about 1120 and now divided between two museums, is among the treasures of Japanese painting, and a detail from one of them was printed on a banknote issued in the year 2000.`,
  },
  {
    cat: 'Person', diff: 5, answer: 'Ibn Khaldun',
    aka: { khaldoun: 'khaldun', khaldon: 'khaldun', kaldun: 'khaldun', khaldum: 'khaldun' },
    text: `He wrote most of it in four or five months, in a castle in what is now Algeria, having withdrawn there from politics with his family in 1375. The Muqaddima, meaning the introduction, was intended as a preface to a universal history of the Arabs and the Berbers, and it grew into a book in its own right: an attempt to set out the principles by which a historian might tell true reports from false, and to explain why states rise and fall.\n\nIts central idea is asabiyya, usually translated as group feeling or social cohesion. A hard life on the desert margins, he argued, breeds solidarity; a group with strong cohesion overcomes a settled dynasty grown soft on luxury and taxation; the conquerors then settle in turn, their solidarity decays over three or four generations, and another group replaces them. He treated this as a natural cycle to be described rather than as a moral tale, and he built it from close observation of the North African dynasties he had served and watched.\n\nIbn Khaldun was born in Tunis in 1332 into a family of Andalusian officials, was orphaned by plague in his teens, and spent his career as a secretary, judge and envoy at courts in Fez, Granada, Tlemcen and Cairo, imprisoned or exiled several times as his patrons fell. Sent to negotiate with Timur outside Damascus in 1401, he was lowered over the city wall in a basket to reach him and left an account of their conversations.\n\nHe was appointed Maliki chief judge in Cairo, an office he held and lost several times, and he made himself unpopular by refusing the customary accommodations of the post. He gave chapters to demolishing the claims of alchemy and of judicial astrology, on the ground that their practitioners could show no results, and he wrote of the plague that had carried off his parents as an event which emptied the world and required a new history to be written.\n\nHe wrote too on the economics of taxation, arguing that light taxes on a growing economy yield more than heavy ones, and on the way crafts and learning flourish in cities. His work was little read outside Ottoman circles until European and Arab scholars took it up in the nineteenth century. He is now commonly described as a forerunner of sociology, economics and historiography, a description that flatters the modern disciplines as much as it does him. He died in Cairo in 1406.`,
  },
];
