// Per-quiz hero image registry: the single source of truth for which quizzes
// carry a hero photo. Drives all three featured slots on the quiz hub
// (app/quizzes/QuizHomeClient.jsx):
//   * Category card   = the most-PLAYED quiz in that category that has a hero here
//                       (so it follows plays but never hands off to a heroless quiz).
//   * Newest tile     = the newest quiz; its registry hero is preferred, and it
//                       falls back to a department photo so it is never blank.
//   * Quiz of the Day = auto-rotates each Eastern midnight over QOTD_POOL, with
//                       per-date pins in QOTD_OVERRIDES. Only heroed quizzes are
//                       eligible, so the QOTD banner always has a real photo.
// A featured slot only ever shows a quiz listed here, so no slot is ever heroless.
// Every `src` must be a JPEG or PNG (never WebP/AVIF) and should verify live
// through the site image optimizer (/_next/image -> image/jpeg). `pos` is an
// optional CSS background-position for portrait/off-center crops.

// THE DEPARTMENT HERO: the photo a quiz falls back to when it has no entry of
// its own below. It lived in app/quizzes/QuizHomeClient.jsx until 2026-09-04,
// when the quiz home at /quizzes needed the same map for its featured row: two
// surfaces reading one registry, which is what this file is for. A department
// with no entry here has no photo, and a caller that needs one always must say
// what it does instead.
export const DEPT_HERO = {
  movies: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/1280px-Hollywood_sign_%288485145044%29.jpg',
  music: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/D%C3%BClmen%2C_D%C3%BClmener_Sommer%2C_Open-Air-Konzert%2C_%22Bounce%22_--_2018_--_0051.jpg/960px-D%C3%BClmen%2C_D%C3%BClmener_Sommer%2C_Open-Air-Konzert%2C_%22Bounce%22_--_2018_--_0051.jpg',
  gaming: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Universum_TV_Multispiel_2006.jpg/960px-Universum_TV_Multispiel_2006.jpg',
  travel: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Beach_at_Fort_Lauderdale.jpg/960px-Beach_at_Fort_Lauderdale.jpg',
  sports: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Michigan_Stadium_Aerial.jpg/960px-Michigan_Stadium_Aerial.jpg',
  geography: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Meteosat-12-fci-march-equinox-2025-noon.jpg/960px-Meteosat-12-fci-march-equinox-2025-noon.jpg',
  food: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Barbieri_-_ViaSophia25668.jpg/960px-Barbieri_-_ViaSophia25668.jpg',
  business: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/NYC_Downtown_Manhattan_Skyline_seen_from_Paulus_Hook_2019-12-20_IMG_7347_FRD.jpg/960px-NYC_Downtown_Manhattan_Skyline_seen_from_Paulus_Hook_2019-12-20_IMG_7347_FRD.jpg',
  science: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Startrails_above_Gunung_Bromo_-_Indonesia.jpg/960px-Startrails_above_Gunung_Bromo_-_Indonesia.jpg',
  entertainment: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/%ED%8F%AC%EC%8B%9C%EC%A6%8C%EC%8A%A4_%EC%82%B0%EB%A6%AC%EC%98%A4%EB%8C%84%EC%8A%A4%ED%83%80%EC%9E%84_2025.jpg/960px-%ED%8F%AC%EC%8B%9C%EC%A6%8C%EC%8A%A4_%EC%82%B0%EB%A6%AC%EC%98%A4%EB%8C%84%EC%8A%A4%ED%83%80%EC%9E%84_2025.jpg',
  literature: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/SanDiegoCityCollegeLearningResource_-_bookshelf.jpg/960px-SanDiegoCityCollegeLearningResource_-_bookshelf.jpg',
  history: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/960px-Colosseo_2020.jpg',
  arts: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Museo_Chileno_de_Arte_Precolombino_-_2020_-_10.jpg/960px-Museo_Chileno_de_Arte_Precolombino_-_2020_-_10.jpg',
};

export const QUIZ_HEROES = {
  'paypal-2q26-earnings-quiz':             { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/PayPal_San_Jose_Headquarters.jpg/1280px-PayPal_San_Jose_Headquarters.jpg' },
  'alphabet-2q26-earnings-quiz':             { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Google_Campus%2C_Mountain_View%2C_CA.jpg/1280px-Google_Campus%2C_Mountain_View%2C_CA.jpg' },
  'netflix-2q26-earnings-quiz':             { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Netflix_headquarters.jpg/1280px-Netflix_headquarters.jpg', pos: 'center 70%' },
  'boston-landmarks-geo-guesser':           { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Boston_skyline_at_earlymorning.jpg/1280px-Boston_skyline_at_earlymorning.jpg' },
  'nolan-every-feature-film': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/ChrisNolanBFI150224_%2810_of_12%29_%2853532289710%29_%28cropped2%29.jpg/960px-ChrisNolanBFI150224_%2810_of_12%29_%2853532289710%29_%28cropped2%29.jpg', pos: 'center 20%' },
  'closer-mlb-ballparks': { src: '/quiz-heroes/closer.png' },
  'closer-nfl-stadiums': { src: '/quiz-heroes/closer.png' },
  'closer-nba-arenas': { src: '/quiz-heroes/closer.png' },
  'closer-college-football-stadiums': { src: '/quiz-heroes/closer.png' },
  'closer-european-soccer-grounds': { src: '/quiz-heroes/closer.png' },
  'closer-f1-circuits': { src: '/quiz-heroes/closer.png' },
  'closer-us-cities': { src: '/quiz-heroes/closer.png' },
  'closer-us-state-capitals': { src: '/quiz-heroes/closer.png' },
  'closer-us-national-parks': { src: '/quiz-heroes/closer.png' },
  'closer-american-landmarks': { src: '/quiz-heroes/closer.png' },
  'closer-world-capitals': { src: '/quiz-heroes/closer.png' },
  'closer-world-landmarks': { src: '/quiz-heroes/closer.png' },
  'closer-seven-wonders': { src: '/quiz-heroes/closer.png' },
  'closer-famous-islands': { src: '/quiz-heroes/closer.png' },
  'closer-airport-hubs': { src: '/quiz-heroes/closer.png' },
  'closer-famous-mountains': { src: '/quiz-heroes/closer.png' },
  'closer-active-volcanoes': { src: '/quiz-heroes/closer.png' },
  'closer-great-rivers': { src: '/quiz-heroes/closer.png' },
  'closer-world-deserts': { src: '/quiz-heroes/closer.png' },
  'closer-great-waterfalls': { src: '/quiz-heroes/closer.png' },
  'closer-ancient-ruins': { src: '/quiz-heroes/closer.png' },
  'closer-world-heritage-sites': { src: '/quiz-heroes/closer.png' },
  'closer-movie-filming-locations': { src: '/quiz-heroes/closer.png' },
  'closer-theme-parks': { src: '/quiz-heroes/closer.png' },
  'closer-tech-hqs': { src: '/quiz-heroes/closer.png' },
  'name-all-64-crayola-colors': { src: '/quiz-heroes/crayons-64.png', pos: 'center 30%' },
  'us-news-top-50-national-universities': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Nassau_Hall_-_Princeton_University_-_Princeton%2C_NJ_-_DSC00807.jpg', pos: 'center 42%' },
  'crux-7-6-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-7-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-8-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-9-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-10-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-11-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-12-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-13-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-14-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-15-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-16-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-17-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-18-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-19-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-20-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-21-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-22-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-23-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-24-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-25-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-26-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-27-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-28-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-29-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-30-26': { src: '/quiz-heroes/crux.png' },
  'crux-7-31-26': { src: '/quiz-heroes/crux.png' },
  'crux-8-1-26': { src: '/quiz-heroes/crux.png' },
  'crux-8-2-26': { src: '/quiz-heroes/crux.png' },
  'garble-7-9-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-10-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-11-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-12-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-13-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-14-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-15-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-16-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-17-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-18-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-19-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-20-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-21-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-22-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-23-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-24-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-25-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-26-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-27-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-28-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-29-26': { src: '/quiz-heroes/garble.png' },
  'garble-7-30-26': { src: '/quiz-heroes/garble.png' },
  'links-7-12-26': { src: '/quiz-heroes/links.png' },
  'links-7-13-26': { src: '/quiz-heroes/links.png' },
  'links-7-14-26': { src: '/quiz-heroes/links.png' },
  'links-7-15-26': { src: '/quiz-heroes/links.png' },
  'links-7-16-26': { src: '/quiz-heroes/links.png' },
  'links-7-17-26': { src: '/quiz-heroes/links.png' },
  'links-7-18-26': { src: '/quiz-heroes/links.png' },
  'links-7-19-26': { src: '/quiz-heroes/links.png' },
  'links-7-20-26': { src: '/quiz-heroes/links.png' },
  'links-7-21-26': { src: '/quiz-heroes/links.png' },
  'links-7-22-26': { src: '/quiz-heroes/links.png' },
  'links-7-23-26': { src: '/quiz-heroes/links.png' },
  'links-7-24-26': { src: '/quiz-heroes/links.png' },
  'links-7-25-26': { src: '/quiz-heroes/links.png' },
  'span-7-12-26': { src: '/quiz-heroes/span.png' },
  'span-7-13-26': { src: '/quiz-heroes/span.png' },
  'span-7-14-26': { src: '/quiz-heroes/span.png' },
  'span-7-15-26': { src: '/quiz-heroes/span.png' },
  'span-7-16-26': { src: '/quiz-heroes/span.png' },
  'span-7-17-26': { src: '/quiz-heroes/span.png' },
  'span-7-18-26': { src: '/quiz-heroes/span.png' },
  'span-7-19-26': { src: '/quiz-heroes/span.png' },
  'span-7-20-26': { src: '/quiz-heroes/span.png' },
  'span-7-21-26': { src: '/quiz-heroes/span.png' },
  'span-7-22-26': { src: '/quiz-heroes/span.png' },
  'span-7-23-26': { src: '/quiz-heroes/span.png' },
  'span-7-24-26': { src: '/quiz-heroes/span.png' },
  'span-7-25-26': { src: '/quiz-heroes/span.png' },
  'span-7-26-26': { src: '/quiz-heroes/span.png' },
  'dating-7-14-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-15-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-16-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-17-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-18-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-19-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-20-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-21-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-22-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-23-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-24-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-25-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-26-26': { src: '/quiz-heroes/dating.png' },
  'dating-7-27-26': { src: '/quiz-heroes/dating.png' },
  'tally-7-14-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-15-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-16-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-17-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-18-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-19-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-20-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-21-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-22-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-23-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-24-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-25-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-26-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-27-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-28-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-29-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-30-26': { src: '/quiz-heroes/tally.png' },
  'tally-7-31-26': { src: '/quiz-heroes/tally.png' },
  'tally-8-1-26': { src: '/quiz-heroes/tally.png' },
  'tally-8-2-26': { src: '/quiz-heroes/tally.png' },
  'tally-8-3-26': { src: '/quiz-heroes/tally.png' },
  'suds-7-14-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-15-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-16-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-17-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-18-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-19-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-20-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-21-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-22-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-23-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-24-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-25-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-26-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-27-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-28-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-29-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-30-26': { src: '/quiz-heroes/suds.png' },
  'suds-7-31-26': { src: '/quiz-heroes/suds.png' },
  'suds-8-1-26': { src: '/quiz-heroes/suds.png' },
  'suds-8-2-26': { src: '/quiz-heroes/suds.png' },
  'suds-8-3-26': { src: '/quiz-heroes/suds.png' },
  'carve-7-15-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-16-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-17-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-18-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-19-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-20-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-21-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-22-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-23-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-24-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-25-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-26-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-27-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-28-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-29-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-30-26': { src: '/quiz-heroes/carve.png' },
  'carve-7-31-26': { src: '/quiz-heroes/carve.png' },
  'carve-8-1-26': { src: '/quiz-heroes/carve.png' },
  'carve-8-2-26': { src: '/quiz-heroes/carve.png' },
  'carve-8-3-26': { src: '/quiz-heroes/carve.png' },
  'carve-8-4-26': { src: '/quiz-heroes/carve.png' },
  'emcee-7-16-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-17-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-18-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-19-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-20-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-21-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-22-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-23-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-24-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-25-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-26-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-27-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-28-26': { src: '/quiz-heroes/emcee.png' },
  'emcee-7-29-26': { src: '/quiz-heroes/emcee.png' },
  'stet-7-17-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-18-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-19-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-20-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-21-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-22-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-23-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-24-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-25-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-26-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-27-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-28-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-29-26': { src: '/quiz-heroes/stet.png' },
  'stet-7-30-26': { src: '/quiz-heroes/stet.png' },
  'outwit-7-17-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-18-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-19-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-20-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-21-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-22-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-23-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-24-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-25-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-26-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-27-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-28-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-29-26': { src: '/quiz-heroes/outwit.png' },
  'outwit-7-30-26': { src: '/quiz-heroes/outwit.png' },
  'outrank-7-21-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-22-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-23-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-24-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-25-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-26-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-27-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-28-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-29-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-30-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-7-31-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-1-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-2-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-3-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-4-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-5-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-6-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-7-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-8-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-9-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-10-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-11-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-12-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-13-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-14-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-15-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-16-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-17-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-18-26': { src: '/quiz-heroes/outrank.png' },
  'outrank-8-19-26': { src: '/quiz-heroes/outrank.png' },
  'tuck-7-18-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-19-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-20-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-21-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-22-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-23-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-24-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-25-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-26-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-27-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-28-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-29-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-30-26': { src: '/quiz-heroes/tuck.png' },
  'tuck-7-31-26': { src: '/quiz-heroes/tuck.png' },
  'alibi-7-18-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-19-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-20-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-21-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-22-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-23-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-24-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-25-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-26-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-27-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-28-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-29-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-30-26': { src: '/quiz-heroes/alibi.png' },
  'alibi-7-31-26': { src: '/quiz-heroes/alibi.png' },
  'cipher-7-18-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-19-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-20-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-21-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-22-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-23-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-24-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-25-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-26-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-27-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-28-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-29-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-30-26': { src: '/quiz-heroes/cipher.png' },
  'cipher-7-31-26': { src: '/quiz-heroes/cipher.png' },
  'warmer-7-18-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-19-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-20-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-21-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-22-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-23-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-24-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-25-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-26-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-27-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-28-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-29-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-30-26': { src: '/quiz-heroes/warmer.png' },
  'warmer-7-31-26': { src: '/quiz-heroes/warmer.png' },
  'jester-7-18-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-19-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-20-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-21-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-22-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-23-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-24-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-25-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-26-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-27-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-28-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-29-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-30-26': { src: '/quiz-heroes/jester.png' },
  'jester-7-31-26': { src: '/quiz-heroes/jester.png' },
  'sworn-7-18-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-19-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-20-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-21-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-22-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-23-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-24-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-25-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-26-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-27-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-28-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-29-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-30-26': { src: '/quiz-heroes/sworn.png' },
  'sworn-7-31-26': { src: '/quiz-heroes/sworn.png' },
  'ping-7-18-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-19-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-20-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-21-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-22-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-23-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-24-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-25-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-26-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-27-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-28-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-29-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-30-26': { src: '/quiz-heroes/ping.png' },
  'ping-7-31-26': { src: '/quiz-heroes/ping.png' },
  'circa-7-14-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-15-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-16-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-17-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-18-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-19-26': { src: '/quiz-heroes/circa.png' },
  'circa-7-20-26': { src: '/quiz-heroes/circa.png' },
  'extra-7-15-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-16-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-17-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-18-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-19-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-20-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-21-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-22-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-23-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-24-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-25-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-26-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-27-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-28-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-29-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-30-26': { src: '/quiz-heroes/extra.png' },
  'extra-7-31-26': { src: '/quiz-heroes/extra.png' },
  'extra-8-1-26': { src: '/quiz-heroes/extra.png' },
  'extra-8-2-26': { src: '/quiz-heroes/extra.png' },
  'extra-8-3-26': { src: '/quiz-heroes/extra.png' },
  'extra-8-4-26': { src: '/quiz-heroes/extra.png' },
  'name-the-continent-part-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Sydney_Australia._%2821339175489%29.jpg', pos: 'center 50%' },
  'name-the-continent-part-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Dubai_Marina_Skyline.jpg', pos: 'center 42%' },
  'name-the-continent-part-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Cidade_Maravilhosa.jpg', pos: 'center 42%' },
  'name-the-continent-part-4': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Kremlin_and_Red_Square.1.jpg', pos: 'center 55%' },
  'name-the-continent-part-5': { src: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Hagia_Sophia_%28228968325%29.jpeg', pos: 'center 48%' },
  'name-every-heisman-winner-since-1990': { src: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Desmond_Howard_in_uniform_with_Heisman_trophy%2C_1991.jpg', pos: 'center 28%' },
  'name-every-super-bowl-winning-qb': { src: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Tom_Brady_with_Vince_Lombardi_trophy.jpg', pos: 'center 35%' },
  'mortal-kombat-1992-roster': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/MortalKombat1992LegacyScreenshot.png', pos: 'center 25%' },
  'sb-starters-2016-broncos': { src: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Von_Miller_Super_Bowl_50.jpg', pos: 'center 22%' },
  'sb-starters-2015-patriots': { src: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Rob_Gronkowski_20131201.jpg', pos: 'center 20%' },
  'sb-starters-2014-seahawks': { src: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Russell_Wilson_vs._Rams_2014.jpg', pos: 'center 15%' },
  'sb-starters-2013-ravens': { src: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Ray_Lewis_MNF_2008.jpg', pos: 'center 18%' },
  'sb-starters-2012-giants': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Eli_Manning_is_back_to_pass_in_warm_ups..jpg', pos: 'center 15%' },
  'sb-starters-2011-packers': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Aaron_Rodgers_-_November_14%2C_2011.jpg', pos: 'center 12%' },
  'sb-starters-2010-saints': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Drew_Brees_Saints_2008.jpg', pos: 'center 18%' },
  'sb-starters-2009-steelers': { src: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Troy_Polamalu_2013.jpg', pos: 'center 18%' },
  'sb-starters-2008-giants': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Justin_tuck_2012.jpg', pos: 'center 18%' },
  'sb-starters-2007-colts': { src: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Peyton_Manning%2C_September_26%2C2010%2C_vs_Denver.jpg', pos: 'center 12%' },
  'nba-starters-2016-cavaliers': { src: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Kyrie_Irving_%2810355627426%29.jpg', pos: 'center 18%' },
  'nba-starters-2015-warriors': { src: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Andre_Iguodala_2016_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-starters-2014-spurs': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Tim_Duncan.jpg', pos: 'center 18%' },
  'nba-starters-2013-heat': { src: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Dwyane_Wade_2012.jpg', pos: 'center 20%' },
  'nba-starters-2012-heat': { src: 'https://upload.wikimedia.org/wikipedia/commons/8/89/LeBronJamesDunkingHeat.jpg', pos: 'center 20%' },
  'nba-starters-2011-mavericks': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Dirk_Nowitzki_2_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-starters-2010-lakers': { src: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Kobe_Bryant_Drives2_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-starters-2009-lakers': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Pau_Gasol_boxout.jpg', pos: 'center 20%' },
  'nba-starters-2008-celtics': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Paul_Pierce_2008-01-13_%28cropped%29.jpg', pos: 'center 15%' },
  'nba-starters-2007-spurs': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Parker_tongue1.JPG', pos: 'center 15%' },
  'sb-starters-2026-seahawks': { src: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Jaxon_Smith-Njigba_FanDuel_Interview.png', pos: 'center 25%' },
  'sb-starters-2025-eagles': { src: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Jalen_Hurts_2022_Eagles.jpg', pos: 'center 18%' },
  'sb-starters-2024-chiefs': { src: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Patrick_Mahomes_military_appreciation2018.jpg', pos: 'center 22%' },
  'sb-starters-2023-chiefs': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Travis_Kelce_%2853791318648%29.jpg', pos: 'center 30%' },
  'sb-starters-2022-rams': { src: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Cooper_Kupp.jpg', pos: 'center 18%' },
  'sb-starters-2021-buccaneers': { src: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Tom_Brady_WFT-Buccaneers_NOV2021.jpg', pos: 'center 20%' },
  'sb-starters-2020-chiefs': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Tyreek_Hill%2C_Khaleke_Hudson_%2851614638887%29.jpg', pos: 'center 25%' },
  'sb-starters-2019-patriots': { src: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Julian_Edelman_In_2019.jpg', pos: 'center 25%' },
  'sb-starters-2018-eagles': { src: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Fletcher_Cox_2019.jpg', pos: 'center 22%' },
  'sb-starters-2017-patriots': { src: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Tom_Brady_2017.JPG', pos: 'center 22%' },
  'nba-starters-2026-knicks': { src: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Jalen_Brunson_2023_%28cropped%29.jpg', pos: 'center 15%' },
  'nba-starters-2025-thunder': { src: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Shai_Gilgeous-Alexander_%2851815871018%29_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-starters-2024-celtics': { src: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Jayson_Tatum_%28cropped%29.jpg', pos: 'center 15%' },
  'nba-starters-2023-nuggets': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-starters-2022-warriors': { src: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Stephen_Curry_%2816454505719%29.jpg', pos: 'center 22%' },
  'nba-starters-2021-bucks': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Giannis_Antetokounmpo_%2824845003687%29_%28cropped%29.jpg', pos: 'center 15%' },
  'nba-starters-2020-lakers': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/LeBron_James_-_51959723161.jpg', pos: 'center 18%' },
  'nba-starters-2019-raptors': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/1_kawhi_leonard_2019_%28cropped%29.jpg', pos: 'center 20%' },
  'nba-starters-2018-warriors': { src: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Kevin_Durant_Warriors_2019_%28cropped%29.jpg', pos: 'center 15%' },
  'nba-starters-2017-warriors': { src: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Golden_State_Warriors_Point_Guard_Stephen_Curry_01.jpg', pos: 'center 25%' },
  'the-white-lotus-character-match':      { src: 'https://image.tmdb.org/t/p/original/w9Fj6q6YSXBZmGZCsxAo1ekO6If.jpg', pos: 'center 30%' },
  'cities-most-skyscrapers-world':          { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Hong_Kong_Night_Skyline.jpg/1280px-Hong_Kong_Night_Skyline.jpg', pos: 'center 45%' },
  'mlb-career-history':                     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Shohei_Ohtani_vs_Orioles_2022.jpg/1280px-Shohei_Ohtani_vs_Orioles_2022.jpg', pos: 'center 20%' },
  'nba-career-history':                     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/LeBron_James_dribbling_%28March_21%2C_2022%29.jpg/1280px-LeBron_James_dribbling_%28March_21%2C_2022%29.jpg', pos: 'center 20%' },
  'nfl-career-history':                     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Tom_Brady_WFT-Buccaneers_NOV2021.jpg/1280px-Tom_Brady_WFT-Buccaneers_NOV2021.jpg', pos: 'center 20%' },
  'name-the-movie-from-poster':             { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg', pos: 'center 32%' },
  'match-rapper-hometown':                  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/50_cent_en_concierto.jpg/1280px-50_cent_en_concierto.jpg' },
  'gaming-pokemon-to-type':                 { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'name-the-ski-resort-from-the-trail-map': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/View_of_Val_Thorens_in_the_morning_from_Boismint_1.jpg/1280px-View_of_Val_Thorens_in_the_morning_from_Boismint_1.jpg', pos: 'center 40%' },
  'world-cup-winners':                      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Stadium_of_Football_Club_FC_Barcelona_-_Camp_Nou.jpg/1280px-Stadium_of_Football_Club_FC_Barcelona_-_Camp_Nou.jpg' },
  'europe-no-outline':                      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Europe_%28MODIS_2017-04-22%29.jpg/1280px-Europe_%28MODIS_2017-04-22%29.jpg' },
  'countries-of-the-world-no-outline':       { src: '/quiz-heroes/world-no-outline.png' },
  'flag-to-map-europe':                    { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-asia':                      { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-africa':                    { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-north-america':             { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-south-america':             { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-oceania':                   { src: '/quiz-heroes/flag-to-map.png' },
  'flag-to-map-world':                     { src: '/quiz-heroes/flag-to-map.png' },
  'erase-the-world-no-outline':              { src: '/quiz-heroes/world-no-outline.png' },
  'countries-without-the-letter-a':          { src: '/quiz-heroes/no-letter-a.png' },
  'countries-without-the-letter-e':          { src: '/quiz-heroes/no-letter-e.png' },
  'countries-without-the-letter-i':          { src: '/quiz-heroes/no-letter-i.png' },
  'countries-without-the-letter-o':          { src: '/quiz-heroes/no-letter-o.png' },
  'canada-provinces-no-outline':            { src: '/outlines/north-american-countries__canada.svg', pos: 'center' },
  'nyc-restaurant-geo-guesser':             { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Katz%27s_Delicatessen_%2851623899326%29.jpg/1280px-Katz%27s_Delicatessen_%2851623899326%29.jpg' },
  'company-slogans':                        { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'match-element-to-symbol':                { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/%C3%80t%E1%BA%B9_%C3%88r%C3%B2j%C3%A0_Al%C3%A1%C3%ACl%C3%A1b%C3%B9l%C3%A0_%28Yoruba_Periodic_Table_of_the_Elements%29.jpg/1280px-%C3%80t%E1%BA%B9_%C3%88r%C3%B2j%C3%A0_Al%C3%A1%C3%ACl%C3%A1b%C3%B9l%C3%A0_%28Yoruba_Periodic_Table_of_the_Elements%29.jpg' },
  'match-the-succession-character':         { src: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Brian_Cox_Edinburgh_2025.jpg', pos: 'center 20%' },
  'opening-lines':                          { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'match-empire-to-capital':                { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/1280px-Colosseo_2020.jpg' },
  'name-the-painting':                      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg' },
  'name-the-state-from-its-quarter':        { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/2022_Washington_quarter_obverse.jpeg/1280px-2022_Washington_quarter_obverse.jpeg' },
  'los-angeles-landmarks-geo-guesser':      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Skyline_of_Los_Angeles%2C_Downtown_Los_Angeles%2C_California_13.jpg/1280px-Skyline_of_Los_Angeles%2C_Downtown_Los_Angeles%2C_California_13.jpg' },
  'london-landmarks-geo-guesser-pt-1':      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/London_Thames_Sunset_panorama_-_Feb_2008.jpg/1280px-London_Thames_Sunset_panorama_-_Feb_2008.jpg' },
  'chicago-landmarks-geo-guesser-pt-1':     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chicago_sunrise_1.jpg/1280px-Chicago_sunrise_1.jpg' },
  'chicago-restaurant-geo-guesser':         { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chicago_sunrise_1.jpg/1280px-Chicago_sunrise_1.jpg' },
  'los-angeles-restaurant-geo-guesser':     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Skyline_of_Los_Angeles%2C_Downtown_Los_Angeles%2C_California_13.jpg/1280px-Skyline_of_Los_Angeles%2C_Downtown_Los_Angeles%2C_California_13.jpg' },
  'san-francisco-landmarks-geo-guesser-pt-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GoldenGateBridge-001.jpg/1280px-GoldenGateBridge-001.jpg' },
  'rome-landmarks-geo-guesser-pt-1':        { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Colosseum_in_Rome,_Italy_-_April_2007.jpg/1280px-Colosseum_in_Rome,_Italy_-_April_2007.jpg' },
  'tokyo-landmarks-geo-guesser-pt-1':       { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg' },
  'paris-landmarks-geo-guesser-pt-1':       { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Paris_pano_%40_Cit%C3%A9_de_l%27Architecture_et_du_Patrimoine_roof.jpg/1280px-Paris_pano_%40_Cit%C3%A9_de_l%27Architecture_et_du_Patrimoine_roof.jpg' },
  // Hamptons geo-guessers: Montauk Point Lighthouse (the East End's signature
  // landmark) so these stop falling back to DEPT_HERO.travel, a Fort Lauderdale
  // beach that reads as Miami. Pt 1 sunset view; Pt 2 daytime sign-in-frame view.
  'hamptons-geo-guesser-pt-1':              { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Montauk_Point_Lighthouse.jpg/1280px-Montauk_Point_Lighthouse.jpg' },
  'hamptons-geo-guesser-pt-2':              { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Montauk_Lighthouse_National_Historic_Site.JPG/1280px-Montauk_Lighthouse_National_Historic_Site.JPG' },
  // Remaining geo-guessers that had no registered hero and were falling back to
  // DEPT_HERO.travel (a Fort Lauderdale BEACH — wrong for DC/NYC/Paris/SF/Orlando)
  // or the generic food plate. Each now gets its own city/landmark photo so no
  // geo-guesser is ever heroless. All Wikimedia 1280px JPEG thumbs, verified live.
  'dc-landmarks-geo-guesser':               { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Capitol_Building_Full_View.jpg/1280px-Capitol_Building_Full_View.jpg' }, // US Capitol west front (daytime)
  'nyc-landmarks-geo-guesser':              { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/1280px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg' }, // Empire State Building
  'nyc-restaurant-geo-guesser-pt-2':        { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/NYPizzaPie.jpg/1280px-NYPizzaPie.jpg' }, // NY slice
  'nyc-restaurant-geo-guesser-pt-3':        { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Katz%27s_Delicatessen_%2851623899326%29.jpg/1280px-Katz%27s_Delicatessen_%2851623899326%29.jpg' }, // Katz's Deli
  'boston-restaurant-geo-guesser':          { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Boston_skyline_at_earlymorning.jpg/1280px-Boston_skyline_at_earlymorning.jpg' }, // Boston skyline (matches boston-landmarks)
  'atlanta-restaurant-geo-guesser':         { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Atlanta_Skyline_from_Buckhead.jpg/1280px-Atlanta_Skyline_from_Buckhead.jpg' }, // Atlanta skyline at night
  'miami-restaurant-geo-guesser':           { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Downtown_Miami_skyline_20100305.jpg/1280px-Downtown_Miami_skyline_20100305.jpg' }, // Downtown Miami skyline
  'paris-landmarks-geo-guesser-pt-2':       { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg/1280px-Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg' }, // Eiffel Tower (distinct from pt-1 panorama)
  'san-francisco-landmarks-geo-guesser-pt-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Painted_Ladies%2C_Alamo_Square.jpg/1280px-Painted_Ladies%2C_Alamo_Square.jpg' }, // Painted Ladies + skyline (distinct from pt-1 Golden Gate)
  'orlando-amusement-park-ride-geo-guesser': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Roller_coaster_in_a_park_%28Unsplash%29.jpg/1280px-Roller_coaster_in_a_park_%28Unsplash%29.jpg' }, // roller coaster
  'f1-circuit-from-a-photo':                { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/2005_Monaco_GP2%2C_Monaco_Grand_Prix_Support_Race%2C_Monte_Carlo%2C_21st_May.jpg/1280px-2005_Monaco_GP2%2C_Monaco_Grand_Prix_Support_Race%2C_Monte_Carlo%2C_21st_May.jpg' },
  'top-grossing-julia-roberts-movies':      { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Julia_Roberts_2025.jpg/960px-Julia_Roberts_2025.jpg', pos: 'center 18%' },
  'top-grossing-meryl-streep-movies':       { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg/960px-Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg', pos: 'center 15%' },
  'top-grossing-sandra-bullock-movies':     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Sandra_Bullock_at_The_Egyptian_Theatre_2024.jpg/960px-Sandra_Bullock_at_The_Egyptian_Theatre_2024.jpg', pos: 'center 15%' },
  'top-grossing-scarlett-johansson-movies': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Scarlett_Johansson-8588.jpg/960px-Scarlett_Johansson-8588.jpg', pos: 'center 18%' },
  'top-grossing-jennifer-lawrence-movies':  { src: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Jennifer_Lawrence_in_2018.png', pos: 'center 18%' },
  'top-grossing-angelina-jolie-movies':     { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Angelina_Jolie-643531_%28cropped%29.jpg/960px-Angelina_Jolie-643531_%28cropped%29.jpg', pos: 'center 18%' },
  'nba-arena-state-1-strike':               { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Crypto.com_Arena_interior_2024.jpg/1280px-Crypto.com_Arena_interior_2024.jpg', pos: 'center 55%' },
  'mlb-ballpark-state-1-strike':            { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wrigley_Field_in_line_with_sign.jpg/1280px-Wrigley_Field_in_line_with_sign.jpg' },
  'artworks-to-museums-pt-1':               { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', pos: 'center 35%' },
  'artworks-to-museums-pt-2':               { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg', pos: 'center 30%' },
  'artworks-to-museums-pt-3':               { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg', pos: 'center 45%' },
  // --- Top-50 most-played evergreen quizzes without a hero (added 2026-07-09) ---
  // Continent maps use the NASA "satellite orthographic" globe set for a consistent
  // geography family; US map quizzes use NASA night-lights; others use canonical
  // Wikimedia subject photos. All verified to load + show the right subject.
  'africa-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Africa_satellite_orthographic.jpg/1280px-Africa_satellite_orthographic.jpg' },
  'find-the-lower-48-states': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/City_Lights_of_the_United_States_2012.jpg/1280px-City_Lights_of_the_United_States_2012.jpg' },
  'asia-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'south-america-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/South_America_satellite_orthographic.jpg' },
  'caribbean-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/North_America_satellite_orthographic.jpg/1280px-North_America_satellite_orthographic.jpg' },
  'central-america-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/North_America_satellite_orthographic.jpg/1280px-North_America_satellite_orthographic.jpg' },
  'southeast-asia-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'middle-east-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'largest-cities-europe': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Historical_peninsula_and_modern_skyline_of_Istanbul.jpg/1280px-Historical_peninsula_and_modern_skyline_of_Istanbul.jpg', pos: 'center 40%' },
  'largest-cities-world-population': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg', pos: 'center 35%' },
  'erase-the-usa-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/City_Lights_of_the_United_States_2012.jpg/1280px-City_Lights_of_the_United_States_2012.jpg' },
  'golf-course-aerials-easy': { src: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-9131470.55,3961061.25,-9129311.93,3963219.87&bboxSR=3857&imageSR=3857&size=1000,1000&format=jpg&f=image' },
  'golf-course-aerials-medium': { src: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-314046.72,7625077.95,-310077.14,7629047.53&bboxSR=3857&imageSR=3857&size=1000,1000&format=jpg&f=image' },
  'golf-course-aerials-hard': { src: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=16144176.37,-4577445.81,16146713.61,-4574908.57&bboxSR=3857&imageSR=3857&size=1000,1000&format=jpg&f=image' },
  'erase-the-usa-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/City_Lights_of_the_United_States_2012.jpg/1280px-City_Lights_of_the_United_States_2012.jpg' },
  'erase-europe-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Europe_satellite_orthographic.jpg' },
  'erase-asia-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'erase-africa-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Africa_satellite_orthographic.jpg/1280px-Africa_satellite_orthographic.jpg' },
  'erase-north-america-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/North_America_satellite_orthographic.jpg/1280px-North_America_satellite_orthographic.jpg' },
  'erase-south-america-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/South_America_satellite_orthographic.jpg' },
  'erase-oceania-by-capital': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Australia_satellite_orthographic.jpg/1280px-Australia_satellite_orthographic.jpg' },
  'erase-the-world-by-capital': { src: '/quiz-heroes/world-no-outline.png' },
  'north-america-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/North_America_satellite_orthographic.jpg/1280px-North_America_satellite_orthographic.jpg' },
  'five-most-populous-cities-in-every-state': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/City_Lights_of_the_United_States_2012.jpg/1280px-City_Lights_of_the_United_States_2012.jpg' },
  'us-states-by-outline-1-strike': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/City_Lights_of_the_United_States_2012.jpg/1280px-City_Lights_of_the_United_States_2012.jpg' },
  'countries-of-europe': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Europe_satellite_orthographic.jpg' },
  'erase-europe-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Europe_satellite_orthographic.jpg' },
  'european-countries-by-outline-1-strike': { src: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Europe_satellite_orthographic.jpg' },
  'capitals-of-europe': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Schoenbrunn_philharmoniker_2012.jpg/1280px-Schoenbrunn_philharmoniker_2012.jpg' },
  'closest-countries-to-antarctica': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Brunt_Ice_Shelf%2C_Antarctica_-_11_December_2022_%2852559137901%29.jpg/1280px-Brunt_Ice_Shelf%2C_Antarctica_-_11_December_2022_%2852559137901%29.jpg' },
  'name-the-company-from-its-ceo-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/New_York_Stock_Exchange_Facade_2015.jpg/1280px-New_York_Stock_Exchange_Facade_2015.jpg', pos: 'center 38%' },
  'name-the-manhattan-pizzeria-from-the-pie': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/NYPizzaPie.jpg/1280px-NYPizzaPie.jpg' },
  'name-the-f1-circuit-from-the-track': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2010_Malaysian_GP_opening_lap.jpg/1280px-2010_Malaysian_GP_opening_lap.jpg' },
  'name-the-brand-from-logo': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'closest-countries-to-the-north-pole': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/North_Pole%2C_Arctic_Ocean%2C_sea_ice_02.jpg/1280px-North_Pole%2C_Arctic_Ocean%2C_sea_ice_02.jpg' },
  'who-owns-it-food-and-beverage-brands': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Stop%26Shop.jpg/1280px-Stop%26Shop.jpg' },
  'name-the-fast-food-chain-from-the-food': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Hamburger_%2812164386105%29.jpg/1280px-Hamburger_%2812164386105%29.jpg' },
  'asian-countries-by-outline-1-strike': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'erase-africa-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Africa_satellite_orthographic.jpg/1280px-Africa_satellite_orthographic.jpg' },
  'countries-of-south-america': { src: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/South_America_satellite_orthographic.jpg' },
  'name-the-city-from-the-photo-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg/1280px-Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg' },
  'closest-countries-to-mount-everest': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg/1280px-Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg', pos: 'center 30%' },
  'flags-of-europe': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/International_Flags_at_Gyeongju_Hilton_%285281871663%29.jpg/1280px-International_Flags_at_Gyeongju_Hilton_%285281871663%29.jpg' },
  'name-every-nba-team': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Steph_Curry_%2851915116957%29.jpg/1280px-Steph_Curry_%2851915116957%29.jpg', pos: 'center 30%' },
  'name-the-us-city-from-satellite': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Landsat_satellite_image_of_the_Middle_Atlantic_States%2C_eastern_part_%281977%29.jpg/1280px-Landsat_satellite_image_of_the_Middle_Atlantic_States%2C_eastern_part_%281977%29.jpg' },
  'oceania-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Australia_satellite_orthographic.jpg/1280px-Australia_satellite_orthographic.jpg' },
  'beer-brands-500': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Hacker-Pschorr_Oktoberfest_Girl_Remix.jpg/1280px-Hacker-Pschorr_Oktoberfest_Girl_Remix.jpg', pos: 'center 25%' },
  'largest-ski-areas-north-america': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/La_Toussuire_Ski_Resort_Wide.jpg/1280px-La_Toussuire_Ski_Resort_Wide.jpg' },
  'name-the-movie-from-poster-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Grauman%27s_Chinese_Theatre%2C_by_Carol_Highsmith.jpg/1280px-Grauman%27s_Chinese_Theatre%2C_by_Carol_Highsmith.jpg', pos: 'center 38%' },
  'every-country-to-play-at-a-world-cup': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/ARG_Line-up_-_ARG_vs_MEX_for_2022_FIFA_WC.jpg/1280px-ARG_Line-up_-_ARG_vs_MEX_for_2022_FIFA_WC.jpg' },
  'name-every-nfl-team': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Larry_Fitzgerald_catches_TD_at_2009_Pro_Bowl.jpg/1280px-Larry_Fitzgerald_catches_TD_at_2009_Pro_Bowl.jpg', pos: 'center 35%' },
  'london-landmarks-geo-guesser-pt-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/1280px-London_Skyline_%28125508655%29.jpeg' },
  'name-the-movie-from-poster-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Grauman%27s_Chinese_Theatre%2C_by_Carol_Highsmith.jpg/1280px-Grauman%27s_Chinese_Theatre%2C_by_Carol_Highsmith.jpg', pos: 'center 38%' },
  'name-the-us-airport-from-satellite': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Palm_Springs_International_Airport_photo_Don_Ramey_Logan.jpg/1280px-Palm_Springs_International_Airport_photo_Don_Ramey_Logan.jpg' },
  'order-historical-events-5': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/1280px-Pyramids_of_the_Giza_Necropolis.jpg' },
  'world-cup-player-to-country': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/FC_Zenit_players_before_a_match_with_Juventus.jpg/1280px-FC_Zenit_players_before_a_match_with_Juventus.jpg' },
  'erase-asia-no-outline': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/1280px-Asia_satellite_orthographic.jpg' },
  'largest-cities-north-america': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/1280px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg' },
  'nyc-pizza-geo-finder': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/NYPizzaPie.jpg/1280px-NYPizzaPie.jpg' },
  'tricky-us-airport-codes': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/An_airport_apron_at_sunset.jpg/1280px-An_airport_apron_at_sunset.jpg' },
  'canadian-provinces-by-outline-1-strike': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Canada_from_space.png/1280px-Canada_from_space.png', pos: 'center 55%' },
  'closest-countries-to-eiffel-tower': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg/1280px-Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg', pos: 'center 35%' },
  'flags-of-north-america': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_map_of_North_America_and_Central_America.png/1280px-Flag_map_of_North_America_and_Central_America.png' },
  'african-countries-by-outline-1-strike': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Africa_satellite_orthographic.jpg/1280px-Africa_satellite_orthographic.jpg' },
  'higher-or-lower-country-population-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Earth%27s_City_Lights_by_DMSP%2C_1994-1995_%28large%29.jpg/1280px-Earth%27s_City_Lights_by_DMSP%2C_1994-1995_%28large%29.jpg' },
  'movie-characters': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'which-earned-more-movies-adjusted-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'which-earned-more-movies-adjusted-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'which-earned-more-movies-adjusted-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'which-earned-more-movies-adjusted-4': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'which-earned-more-movies-adjusted-5': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/View_from_behind_Hollywood_Sign_overlooking_LA.jpg/1280px-View_from_behind_Hollywood_Sign_overlooking_LA.jpg' },
  'name-the-members-of-nsync': { src: 'https://upload.wikimedia.org/wikipedia/commons/b/be/NSYNC.jpg', pos: 'center 20%' },
  'name-the-members-of-the-backstreet-boys': { src: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Backstreet_Boys_2019_by_Glenn_Francis.jpg', pos: 'center 20%' },
  'name-the-snack-from-the-label': { src: '/quiz-heroes/nutrition-labels.png' },
  'name-the-soda-from-the-label': { src: '/quiz-heroes/nutrition-labels.png' },
  'name-the-drink-from-the-label': { src: '/quiz-heroes/nutrition-labels.png' },
  'name-the-candy-from-the-label': { src: '/quiz-heroes/nutrition-labels.png' },
  'name-the-city-from-its-metro-map': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/London_Underground_full_map.svg/1280px-London_Underground_full_map.svg.png' },
  'ski-resort-to-state-or-country': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Rastkogel_ski_slope.jpg/1280px-Rastkogel_ski_slope.jpg', pos: 'center 35%' },
  'worst-all-time-win-percentage-big-four': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Nationals_Park_Opening_Day_empty_stadium_2020-07-23.jpg/1280px-Nationals_Park_Opening_Day_empty_stadium_2020-07-23.jpg' },

  // Added 2026-08-21: departmental heroes for the most-played previously unheroed
  // quizzes in the five thinnest departments, so each category card can follow play
  // counts instead of being pinned to the one quiz that happened to carry a photo.
  'fill-in-the-blank-book-titles-pt-1': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'fill-in-the-blank-book-titles-pt-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'fill-in-the-blank-book-titles-pt-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'opening-lines-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'opening-lines-3': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bibliotheca_Bodleiana.jpg/1280px-Bibliotheca_Bodleiana.jpg' },
  'name-the-movie-from-poster-4': { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg' },
  'name-the-movie-from-poster-5': { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg' },
  'movie-quotes-to-movies': { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg' },
  'movie-characters-2': { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg' },
  'match-villain-to-film': { src: 'https://image.tmdb.org/t/p/w780/AmyQTQsNxITitCM0Ya5l5bpYGpn.jpg' },
  'match-console-to-maker': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'street-fighter-2-original-roster': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'highest-grossing-video-games': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'best-selling-game-consoles': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'best-selling-game-boy-games': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/1280px-SNES-Controller-in-Hand.jpg' },
  'micron-lightning-50': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'weekly-business-quiz-2026-06-12': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'companies-to-headquarters': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'name-the-brand-from-logo-2': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'nike-2q26-earnings-quiz': { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/1280px-New_york_times_square-terabass.jpg' },
  'match-album-to-band': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Bundesarchiv_B_145_Bild-F079073-0006%2C_Bonn%2C_Sternstra%C3%9Fe%2C_Schallplattengesch%C3%A4ft.jpg' },
  'name-the-artist-from-the-cover': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Bundesarchiv_B_145_Bild-F079073-0006%2C_Bonn%2C_Sternstra%C3%9Fe%2C_Schallplattengesch%C3%A4ft.jpg' },
  'match-band-member-to-band': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Bundesarchiv_B_145_Bild-F079073-0006%2C_Bonn%2C_Sternstra%C3%9Fe%2C_Schallplattengesch%C3%A4ft.jpg' },
  'match-dj-genre': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Bundesarchiv_B_145_Bild-F079073-0006%2C_Bonn%2C_Sternstra%C3%9Fe%2C_Schallplattengesch%C3%A4ft.jpg' },
  'top-songs-1960s': { src: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Bundesarchiv_B_145_Bild-F079073-0006%2C_Bonn%2C_Sternstra%C3%9Fe%2C_Schallplattengesch%C3%A4ft.jpg' },
};

export function heroFor(id) { return (id && QUIZ_HEROES[id]) || null; }

// ---- Quiz of the Day rotation ----------------------------------------------
// Per-date pins win; every other Eastern day auto-rotates over QOTD_POOL. To
// feature a specific quiz on a specific day, add a pin here (the quiz MUST be in
// QUIZ_HEROES). Dates are Eastern YYYY-MM-DD; the flip happens at ET midnight.
export const QOTD_OVERRIDES = {
  '2026-07-10': 'nyc-pizza-geo-finder',
  '2026-07-01': 'f1-circuit-from-a-photo',                 // today, unchanged
  '2026-07-02': 'f1-circuit-from-a-photo',                 // tonight's ET midnight: hold (ski resort is NOT tonight)
  '2026-07-03': 'name-the-ski-resort-from-the-trail-map',  // tomorrow night's ET midnight: ski resort trail map
};

// Heroed quizzes eligible to auto-rotate as Quiz of the Day, cycled by day index.
export const QOTD_POOL = [
  'f1-circuit-from-a-photo',
  'name-the-ski-resort-from-the-trail-map',
  'nyc-restaurant-geo-guesser',
  'los-angeles-landmarks-geo-guesser',
  'london-landmarks-geo-guesser-pt-1',
  'paris-landmarks-geo-guesser-pt-1',
  'name-the-movie-from-poster',
  'match-the-succession-character',
  'match-rapper-hometown',
  'nyc-pizza-geo-finder',
  'world-cup-winners',
  'europe-no-outline',
  'company-slogans',
  'match-element-to-symbol',
  'opening-lines',
  'match-empire-to-capital',
  'name-the-painting',
  'name-the-state-from-its-quarter',
];

const QOTD_EPOCH = '2026-07-01';
function dayIndex(ymd) {
  return Math.round((Date.parse(ymd + 'T00:00:00.000Z') - Date.parse(QOTD_EPOCH + 'T00:00:00.000Z')) / 86400000);
}

// Resolve the Quiz-of-the-Day quiz id for an Eastern YYYY-MM-DD. `existing` is an
// optional Set of valid quiz ids; ids not in it (or not heroed) are skipped, so a
// retired or heroless quiz never surfaces. Returns null only if nothing qualifies.
export function qotdIdFor(ymd, existing) {
  const ok = (id) => !!(id && QUIZ_HEROES[id] && (!existing || existing.has(id)));
  const pin = QOTD_OVERRIDES[ymd];
  if (ok(pin)) return pin;
  const pool = QOTD_POOL.filter(ok);
  if (!pool.length) return null;
  const i = ((dayIndex(ymd) % pool.length) + pool.length) % pool.length;
  return pool[i];
}
