// Puzzle data for Rung, the daily word ladder. Imported ONLY by the server page
// (app/rung/page.js), which filters live<=today before handing the bank to the
// client, so tomorrow's pair never reaches a browser.
//
//   start / target  the two ends of the ladder, both familiar words
//   par             the EXACT shortest ladder between them, i.e. what the game
//                   now shows as PERFECT (the field keeps its old name so no
//                   banked board has to be rewritten; the softer target players
//                   see is derived in lib/par.js). By breadth-first
//                   search over VOCAB, confirmed by an independent bidirectional
//                   search. Weekdays 10 to 12 rungs, Sundays 15 or more.
//   routes          how many distinct shortest ladders exist, capped at 9999.
//                   Often 1, which is why matching perfect is hard.
//   example         one shortest ladder, shown only after the game ends.
//
// VOCAB is the whole word list, and it is the ONLY thing a rung may be: common
// five-letter words, built from the site's frequency list, filtered to words the
// dictionary knows in lower case (which drops proper nouns) and then screened
// for anything unsuitable. It is computed over exactly this list, so validating
// against exactly this list is what keeps it honest: a wider dictionary would
// let a player find a shorter ladder than the one it was measured on.
export const VOCAB = ["abide","abode","abort","about","above","abuse","acorn","adapt","adept","admin","admit","adobe","adopt","adore","adorn","alert","alien","align","alley","allow","alloy","aloha","alone","along","aloud","alpha","altar","alter","among","ample","amuse","angel","anger","angle","ankle","apple","apply","arbor","arise","armor","arose","aside","assay","audio","audit","avert","awake","award","aware","awoke","bacon","badge","baggy","baked","baker","barge","baron","barre","basal","basic","basil","basin","basis","batch","bathe","baths","baton","beach","beard","beast","beech","began","begin","begun","being","belle","belly","bench","benny","berry","berth","biker","billy","binge","bingo","birch","birth","black","blade","blame","bland","blank","blast","blaze","bleak","bleed","bleep","blend","bless","blind","blink","bliss","block","bloke","blond","blood","bloom","blown","bluff","blunt","blush","board","boast","bobby","bogus","bonus","boost","booth","booty","bound","bowed","bowel","bower","boxer","brace","braid","brain","brake","brand","brass","brave","bravo","brawl","bread","break","breed","brent","bribe","brick","bride","brief","brill","brine","bring","brink","brisk","broad","brock","broke","brood","brook","broom","broth","brown","brunt","brush","buddy","budge","buggy","build","built","bulge","bulky","bully","bunch","bunny","burnt","burst","butch","cabal","cable","cadre","caged","camel","cameo","canal","candy","canoe","canon","carry","carte","carve","caste","catch","cater","cause","cease","cello","chain","chair","champ","chant","charm","chart","chase","cheap","cheat","check","cheek","cheer","chess","chest","chick","chico","chief","child","chili","chill","chime","china","chino","choir","choke","chord","chore","chose","chuck","chunk","cider","cisco","civic","civil","clamp","clash","clasp","class","clean","clear","click","cling","cloak","clock","clone","close","cloth","cloud","clout","clown","coach","coast","cocky","colon","color","condo","conte","coral","couch","cough","could","count","court","coven","cover","craft","cramp","crane","crank","crash","crass","crate","crave","crawl","craze","crazy","cream","creed","creek","creep","creme","crept","crest","crime","crock","croft","crook","crore","cross","crowd","crown","crush","crust","crypt","cubic","curly","curry","curse","curve","curvy","daddy","daily","dairy","daisy","dance","dandy","dated","dazed","death","debit","debut","decal","decay","decor","decoy","delay","demon","dense","depth","derby","derry","deter","diner","disco","ditch","diver","dixie","dodge","dodgy","doggy","doing","dolly","donna","donor","dough","draft","drain","drake","drank","drawn","dread","dream","dress","drier","drift","drill","drink","drive","drone","drove","drown","drunk","dryer","dummy","dusty","dutch","dwell","eager","eaten","eater","eight","elect","emery","enact","enjoy","enter","envoy","erect","essay","ester","ether","every","exact","excel","expel","fable","faint","fairy","fancy","farce","fatal","fatty","fault","fauna","feast","felon","fence","feral","ferry","fetal","fetch","fever","fiber","field","fiend","fifth","fifty","fight","filly","filth","finch","fired","firth","fitch","fixed","fixer","flake","flame","flank","flare","flash","flask","flesh","flick","fling","flint","flirt","flock","flood","floor","floss","flour","flown","fluff","fluke","flung","flush","flute","focal","focus","foggy","folio","folly","footy","foray","force","forge","forte","forty","found","frail","frame","franc","frank","freak","fresh","front","frost","frown","fudge","fully","funky","funny","furry","gable","gamma","gemma","genes","genie","genre","genus","giant","given","giver","gland","glare","glass","glaze","glide","globe","gloom","gloss","glove","going","gonna","goods","goody","goofy","goose","gorge","grace","grade","graft","grail","grain","grand","grant","grape","graph","grasp","grass","grate","grave","gravy","graze","great","greed","green","greet","grief","grill","grime","grind","groan","groin","groom","gross","grove","growl","grown","grunt","guess","guest","guide","guild","guilt","guise","gully","hairy","handy","happy","hardy","harry","harsh","haste","hasty","hatch","hater","haven","heard","heart","heath","hedge","hefty","heist","hello","hence","highs","hilly","hinge","hippo","hippy","hitch","hoard","hobby","hogan","hoist","holly","homer","honey","honor","horde","horse","hotel","hound","house","hover","howdy","hubby","humor","hunch","hurry","hurst","hutch","hydra","hydro","inept","inert","infer","inner","intel","inter","ionic","jelly","jenny","jerky","jerry","jetty","joint","joker","jolly","judge","juice","juicy","kelly","kinda","kinds","kitty","knack","knock","kraft","label","lager","lance","large","laser","latch","latte","layer","leach","leafy","leaky","leapt","lease","leash","least","leave","ledge","leech","lefty","legal","lemon","level","lever","libel","light","lined","linen","liner","lingo","liter","liver","lobby","local","locus","lodge","lofty","logan","logic","login","loner","loose","lorry","loser","lotto","lotus","loved","lover","lower","loyal","lunch","lying","lynch","macho","macro","mafia","magic","magma","major","maker","mamma","manga","mango","mania","manic","manor","march","marge","maria","marry","marsh","match","matte","mayor","medal","media","medic","melon","mercy","merge","merle","merry","messy","metal","meter","metro","micro","might","milky","mince","miner","minor","minus","missy","misty","mixed","mixer","modal","model","modem","moist","molly","mommy","monde","money","monte","month","moody","moose","moral","moray","morse","motel","moths","motor","motto","mound","mount","mouse","mouth","moved","mover","mower","muddy","mummy","munch","mural","myths","nacho","naive","naked","named","nancy","nanny","nasal","nasty","natal","naval","needy","nelly","nerdy","nerve","never","niece","nifty","night","noise","noisy","north","nudge","nurse","oasis","onion","other","otter","overt","owned","owner","paddy","padre","paint","palsy","panic","paper","parry","party","pasha","pasta","paste","patch","paths","patio","patsy","patty","pause","paved","payer","peace","peach","pedal","penal","pence","penny","perch","perry","petal","peter","petty","phase","phone","phony","piece","pilot","pinch","piper","pitch","pivot","pixie","place","plaid","plain","plane","plank","plant","plate","playa","plaza","plead","pleas","plume","plump","plush","point","poise","poker","polar","polio","poppy","porch","posse","potty","pouch","pound","power","prank","press","price","pride","prime","print","prize","probe","prose","prove","pubic","pulse","punch","puppy","purge","purse","quack","quark","quart","queen","queer","quell","quest","quick","quiet","quill","quilt","quirk","quite","quota","quote","rabid","radio","rally","randy","rapid","rated","ratio","raven","reach","react","rebel","regal","relax","relay","remit","remix","renal","repel","retro","revel","rhino","rhyme","rider","right","rigor","river","roach","roast","rocky","rodeo","roger","rogue","roman","romeo","rondo","roost","roper","rotor","rouge","rough","round","rouse","route","rover","rowan","rowdy","rower","royal","ruddy","rumor","rural","rusty","saber","saint","sally","salty","sandy","sassy","sauna","saved","saver","savoy","savvy","scale","scalp","scant","scare","scarf","scary","scene","scent","scoop","scope","score","scorn","scout","scrap","scrub","scrum","seine","seize","sense","serge","serum","serve","seven","sever","sewer","shack","shade","shady","shaft","shake","shaky","shale","shall","shalt","shame","shank","shape","shard","share","shark","sharp","shave","shawl","shear","sheen","sheep","sheer","sheet","shelf","shell","shift","shine","shiny","shire","shirt","shock","shone","shook","shoot","shore","short","shout","shove","shrub","shrug","siege","sieve","sighs","sight","silky","silly","since","sinus","sissy","sixth","sixty","skate","skill","skirt","skull","slack","slang","slant","slash","slate","slave","sleek","sleep","slept","slice","slick","slide","slime","slimy","sling","slope","sloth","slump","slush","smack","small","smart","smash","smear","smell","smoke","smoky","snack","snake","snare","sneak","sniff","snipe","snoop","snort","snout","snuff","sober","soggy","solar","sonar","sonic","sonny","sorry","sound","south","space","spade","spank","spare","spark","speak","spear","speck","specs","speed","spell","spend","spent","spice","spicy","spike","spill","spine","spire","spite","spoke","spoof","spoon","spore","sport","spout","spray","squad","squat","squid","stack","staff","stage","stain","stair","stake","stale","stalk","stall","stamp","stare","stark","start","stash","state","stave","stead","steak","steal","steam","steel","steep","steer","stein","stern","stick","stiff","still","sting","stink","stint","stock","stoke","stole","stomp","stone","stony","stood","stool","stoop","store","storm","story","stout","stove","strap","straw","stray","strip","strut","stuck","stuff","stump","stung","stunt","style","suede","suite","sully","sunny","surge","swain","swami","swamp","swear","sweat","swede","sweep","sweet","swell","swept","swift","swine","swing","swipe","swoop","sword","swore","sworn","swung","table","tacky","taken","taker","takin","tally","tamed","tammy","tango","taper","taser","taste","tasty","taxed","teach","tease","telly","tempo","tempt","tense","terra","terry","thank","theme","there","these","thick","thief","thine","thing","think","thong","those","three","threw","throw","thyme","tiger","tight","timer","tired","toast","token","tonal","toner","tonic","tooth","topic","torch","total","touch","tough","towel","tower","toxic","toxin","trace","track","tract","trade","trail","train","trait","tramp","trash","tread","treat","trend","triad","trial","tribe","trick","tried","trope","trove","truce","truck","trump","trunk","truss","trust","tummy","tumor","tunic","tutor","twain","tweed","tweet","tying","unify","union","unite","unity","upped","upper","urine","utter","vague","valor","value","valve","vapor","vault","vegan","verge","verse","vigor","villa","viola","viper","viral","vital","vocal","vogue","vouch","vowel","wacky","wafer","waged","wager","waist","waive","wally","waste","watch","water","weave","wedge","whack","whale","wheat","where","while","whine","white","whole","whose","wield","wight","winch","wired","witch","witty","woman","women","woods","woody","world","worry","worse","worst","worth","would","wound","woven","wrist","write","wrote","yeast","yield","youth","yummy"];

export const PUZZLES = [
  {
    num: 1,
    quizId: 'rung-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'creep',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creep"],
  },
  {
    num: 2,
    quizId: 'rung-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'spend',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "spent", "spend"],
  },
  {
    num: 3,
    quizId: 'rung-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'bread',
    routes: 7,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "block", "brock", "brook", "brood", "broad", "bread"],
  },
  {
    num: 4,
    quizId: 'rung-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    par: 15,
    start: 'crane',
    target: 'theme',
    routes: 8,
    example: ["crane", "crank", "prank", "plank", "plane", "plate", "slate", "slave", "shave", "shale", "whale", "whole", "whose", "those", "these", "theme"],
  },
  {
    num: 5,
    quizId: 'rung-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    par: 10,
    start: 'shock',
    target: 'scene',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "scene"],
  },
  {
    num: 6,
    quizId: 'rung-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    par: 11,
    start: 'suite',
    target: 'broad',
    routes: 5,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "block", "brock", "brook", "brood", "broad"],
  },
  {
    num: 7,
    quizId: 'rung-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    par: 12,
    start: 'shock',
    target: 'speed',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "spent", "spend", "speed"],
  },
  {
    num: 8,
    quizId: 'rung-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'creed',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creed"],
  },
  {
    num: 9,
    quizId: 'rung-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'steel',
    routes: 3,
    example: ["shock", "shack", "slack", "black", "blank", "bland", "blend", "bleed", "bleep", "sleep", "steep", "steel"],
  },
  {
    num: 10,
    quizId: 'rung-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'green',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creed", "greed", "green"],
  },
  {
    num: 11,
    quizId: 'rung-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    par: 16,
    start: 'along',
    target: 'rouge',
    routes: 1,
    example: ["along", "alone", "clone", "close", "chose", "chase", "cease", "lease", "leash", "leach", "reach", "roach", "coach", "couch", "cough", "rough", "rouge"],
  },
  {
    num: 12,
    quizId: 'rung-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    par: 10,
    start: 'crane',
    target: 'crest',
    routes: 1,
    example: ["crane", "crank", "frank", "flank", "flask", "flash", "clash", "crash", "crush", "crust", "crest"],
  },
  {
    num: 13,
    quizId: 'rung-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    par: 11,
    start: 'beech',
    target: 'bloom',
    routes: 1,
    example: ["beech", "beach", "peach", "peace", "place", "plane", "plank", "blank", "bland", "blond", "blood", "bloom"],
  },
  {
    num: 14,
    quizId: 'rung-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    par: 12,
    start: 'brace',
    target: 'steal',
    routes: 1,
    example: ["brace", "trace", "track", "trick", "thick", "chick", "check", "cheek", "cheer", "sheer", "steer", "steel", "steal"],
  },
  {
    num: 15,
    quizId: 'rung-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    par: 10,
    start: 'being',
    target: 'sheer',
    routes: 2,
    example: ["being", "bring", "brink", "blink", "blind", "blend", "bleed", "bleep", "sleep", "sheep", "sheer"],
  },
  {
    num: 16,
    quizId: 'rung-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    par: 11,
    start: 'brunt',
    target: 'sweet',
    routes: 2,
    example: ["brunt", "grunt", "grant", "grand", "brand", "bland", "blend", "bleed", "bleep", "sleep", "sweep", "sweet"],
  },
  {
    num: 17,
    quizId: 'rung-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    par: 12,
    start: 'beach',
    target: 'greet',
    routes: 1,
    example: ["beach", "peach", "peace", "place", "plane", "plank", "blank", "bland", "blend", "bleed", "breed", "greed", "greet"],
  },
  {
    num: 18,
    quizId: 'rung-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    par: 15,
    start: 'crane',
    target: 'there',
    routes: 8,
    example: ["crane", "crank", "prank", "plank", "plane", "plate", "slate", "slave", "shave", "shale", "whale", "whole", "whose", "those", "these", "there"],
  },
  {
    num: 19,
    quizId: 'rung-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    par: 10,
    start: 'bribe',
    target: 'steer',
    routes: 1,
    example: ["bribe", "brine", "brink", "blink", "blind", "blend", "bleed", "bleep", "sleep", "steep", "steer"],
  },
  {
    num: 20,
    quizId: 'rung-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    par: 11,
    start: 'blaze',
    target: 'groom',
    routes: 1,
    example: ["blaze", "glaze", "graze", "grace", "trace", "track", "trick", "brick", "brock", "brook", "broom", "groom"],
  },
  {
    num: 21,
    quizId: 'rung-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    par: 12,
    start: 'clash',
    target: 'sweat',
    routes: 1,
    example: ["clash", "flash", "flask", "flank", "blank", "bland", "blend", "bleed", "bleep", "sleep", "sweep", "sweet", "sweat"],
  },
  {
    num: 22,
    quizId: 'rung-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    par: 10,
    start: 'bench',
    target: 'blood',
    routes: 1,
    example: ["bench", "beach", "peach", "peace", "place", "plane", "plank", "blank", "bland", "blond", "blood"],
  },
  {
    num: 23,
    quizId: 'rung-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    par: 11,
    start: 'brain',
    target: 'swear',
    routes: 2,
    example: ["brain", "braid", "brand", "bland", "blend", "bleed", "bleep", "sleep", "sheep", "sheer", "shear", "swear"],
  },
  {
    num: 24,
    quizId: 'rung-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    par: 12,
    start: 'blunt',
    target: 'steel',
    routes: 2,
    example: ["blunt", "brunt", "grunt", "grant", "grand", "brand", "bland", "blend", "bleed", "bleep", "sleep", "steep", "steel"],
  },
  {
    num: 25,
    quizId: 'rung-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    par: 18,
    start: 'bleep',
    target: 'house',
    routes: 4,
    example: ["bleep", "bleed", "blend", "bland", "blank", "plank", "plane", "place", "peace", "peach", "reach", "roach", "coach", "couch", "cough", "rough", "rouge", "rouse", "house"],
  },
  {
    num: 26,
    quizId: 'rung-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    par: 10,
    start: 'crane',
    target: 'trust',
    routes: 1,
    example: ["crane", "crank", "frank", "flank", "flask", "flash", "clash", "crash", "crush", "crust", "trust"],
  },
  {
    num: 27,
    quizId: 'rung-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    par: 11,
    start: 'blown',
    target: 'breed',
    routes: 2,
    example: ["blown", "brown", "drown", "drawn", "drain", "brain", "braid", "brand", "bland", "blend", "bleed", "breed"],
  },
  {
    num: 28,
    quizId: 'rung-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    par: 12,
    start: 'craft',
    target: 'swept',
    routes: 2,
    example: ["craft", "graft", "grant", "grand", "brand", "bland", "blend", "bleed", "bleep", "sleep", "sweep", "sweet", "swept"],
  },
  {
    num: 29,
    quizId: 'rung-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    par: 12,
    start: 'force',
    target: 'legal',
    routes: 1,
    example: ["force","forte","forty","foray","moray","moral","modal","medal","pedal","penal","renal","regal","legal"],
  },
  {
    num: 30,
    quizId: 'rung-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    par: 11,
    start: 'shore',
    target: 'punch',
    routes: 1,
    example: ["shore","chore","chose","chase","cease","lease","leash","leach","beach","bench","bunch","punch"],
  },
  {
    num: 31,
    quizId: 'rung-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    par: 11,
    start: 'inter',
    target: 'named',
    routes: 1,
    example: ["inter","enter","eater","eager","lager","laser","taser","taker","baker","baked","naked","named"],
  },
  {
    num: 32,
    quizId: 'rung-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    par: 17,
    start: 'story',
    target: 'house',
    routes: 4,
    example: ["story","store","stare","state","slate","plate","place","peace","peach","perch","porch","pouch","couch","cough","rough","rouge","rouse","house"],
  },
  {
    num: 33,
    quizId: 'rung-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    par: 12,
    start: 'these',
    target: 'bring',
    routes: 1,
    example: ["these","those","whose","whole","while","whine","thine","think","thick","trick","brick","brink","bring"],
  },
  {
    num: 34,
    quizId: 'rung-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    par: 12,
    start: 'lunch',
    target: 'score',
    routes: 3,
    example: ["lunch","bunch","bench","beach","leach","leash","lease","cease","chase","chose","chore","shore","score"],
  },
  {
    num: 35,
    quizId: 'rung-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    par: 11,
    start: 'terry',
    target: 'nasty',
    routes: 2,
    example: ["terry","ferry","furry","curry","curvy","curve","carve","carte","caste","haste","hasty","nasty"],
  },
  {
    num: 36,
    quizId: 'rung-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    par: 12,
    start: 'stole',
    target: 'sheep',
    routes: 4,
    example: ["stole","stone","shone","shine","thine","think","thick","chick","check","cheek","cheer","sheer","sheep"],
  },
  {
    num: 37,
    quizId: 'rung-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    par: 12,
    start: 'sheep',
    target: 'broke',
    routes: 1,
    example: ["sheep","sheer","cheer","cheek","check","chick","thick","trick","track","trace","brace","brake","broke"],
  },
  {
    num: 38,
    quizId: 'rung-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    par: 10,
    start: 'carry',
    target: 'verse',
    routes: 1,
    example: ["carry","curry","curvy","curve","curse","purse","purge","surge","serge","verge","verse"],
  },
  {
    num: 39,
    quizId: 'rung-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    par: 15,
    start: 'stole',
    target: 'chest',
    routes: 2,
    example: ["stole","stale","state","slate","plate","plane","plank","flank","flask","flash","clash","crash","crush","crust","crest","chest"],
  },
  {
    num: 40,
    quizId: 'rung-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    par: 10,
    start: 'short',
    target: 'trade',
    routes: 3,
    example: ["short","shirt","shire","shine","thine","think","thick","trick","track","trace","trade"],
  },
  {
    num: 41,
    quizId: 'rung-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    par: 10,
    start: 'space',
    target: 'brain',
    routes: 1,
    example: ["space","spice","slice","slick","slack","black","blank","bland","brand","braid","brain"],
  },
  {
    num: 42,
    quizId: 'rung-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    par: 11,
    start: 'spoke',
    target: 'sheet',
    routes: 1,
    example: ["spoke","spike","spice","slice","slick","click","chick","check","cheek","cheer","sheer","sheet"],
  },
  {
    num: 43,
    quizId: 'rung-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    par: 11,
    start: 'fatal',
    target: 'booth',
    routes: 1,
    example: ["fatal","fetal","metal","medal","modal","moral","moray","foray","forty","footy","booty","booth"],
  },
  {
    num: 44,
    quizId: 'rung-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    par: 11,
    start: 'taken',
    target: 'fired',
    routes: 2,
    example: ["taken","taker","taser","laser","loser","loner","liner","miner","mixer","fixer","fixed","fired"],
  },
  {
    num: 45,
    quizId: 'rung-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    par: 10,
    start: 'baker',
    target: 'fixed',
    routes: 2,
    example: ["baker","taker","taser","laser","loser","loner","liner","miner","mixer","fixer","fixed"],
  },
  {
    num: 46,
    quizId: 'rung-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    par: 18,
    start: 'bread',
    target: 'among',
    routes: 2,
    example: ["bread","breed","bleed","blend","bland","blank","black","slack","shack","shark","share","shore","chore","chose","close","clone","alone","along","among"],
  },
  {
    num: 47,
    quizId: 'rung-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    par: 12,
    start: 'pride',
    target: 'blame',
    routes: 2,
    example: ["pride","bride","brine","brink","brick","trick","track","trace","grace","graze","glaze","blaze","blame"],
  },
  {
    num: 48,
    quizId: 'rung-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    par: 12,
    start: 'witch',
    target: 'rough',
    routes: 6,
    example: ["witch","winch","pinch","punch","bunch","bench","beach","reach","roach","coach","couch","cough","rough"],
  },
  {
    num: 49,
    quizId: 'rung-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    par: 10,
    start: 'among',
    target: 'write',
    routes: 1,
    example: ["among","along","alone","clone","close","chose","whose","whole","while","white","write"],
  },
  {
    num: 50,
    quizId: 'rung-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    par: 10,
    start: 'joint',
    target: 'white',
    routes: 1,
    example: ["joint","point","paint","saint","stint","sting","swing","swine","shine","whine","white"],
  },
  {
    num: 51,
    quizId: 'rung-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    par: 10,
    start: 'sharp',
    target: 'floor',
    routes: 1,
    example: ["sharp","shark","shack","slack","black","blank","bland","blond","blood","flood","floor"],
  },
  {
    num: 52,
    quizId: 'rung-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    par: 10,
    start: 'alone',
    target: 'coast',
    routes: 1,
    example: ["alone","clone","close","chose","chase","cease","lease","least","beast","boast","coast"],
  },
  {
    num: 53,
    quizId: 'rung-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    par: 16,
    start: 'broad',
    target: 'sense',
    routes: 1,
    example: ["broad","brood","blood","blond","bland","blank","plank","plane","place","peace","peach","leach","leash","lease","tease","tense","sense"],
  },
  {
    num: 54,
    quizId: 'rung-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    par: 11,
    start: 'match',
    target: 'state',
    routes: 1,
    example: ["match","batch","butch","bunch","bench","beach","peach","peace","place","plate","slate","state"],
  },
  {
    num: 55,
    quizId: 'rung-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    par: 12,
    start: 'stick',
    target: 'blade',
    routes: 1,
    example: ["stick","slick","click","chick","thick","trick","track","trace","grace","graze","glaze","blaze","blade"],
  },
  {
    num: 56,
    quizId: 'rung-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    par: 11,
    start: 'trade',
    target: 'class',
    routes: 3,
    example: ["trade","grade","grave","crave","crane","crank","frank","flank","flask","flash","clash","class"],
  },
  {
    num: 57,
    quizId: 'rung-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    par: 10,
    start: 'quite',
    target: 'creek',
    routes: 1,
    example: ["quite","suite","spite","spice","slice","slick","click","chick","check","cheek","creek"],
  },
  {
    num: 58,
    quizId: 'rung-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    par: 11,
    start: 'green',
    target: 'sharp',
    routes: 1,
    example: ["green","greed","breed","bleed","blend","bland","blank","black","slack","shack","shark","sharp"],
  },
  {
    num: 59,
    quizId: 'rung-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    par: 11,
    start: 'sleep',
    target: 'brown',
    routes: 2,
    example: ["sleep","bleep","bleed","blend","bland","brand","braid","brain","grain","groin","grown","brown"],
  },
  {
    num: 60,
    quizId: 'rung-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    par: 16,
    start: 'thank',
    target: 'rough',
    routes: 16,
    example: ["thank","shank","shack","slack","black","blank","plank","plane","place","peace","peach","reach","roach","coach","couch","cough","rough"],
  },
  {
    num: 61,
    quizId: 'rung-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    par: 12,
    start: 'women',
    target: 'tired',
    routes: 4,
    example: ["women","woven","coven","cover","lover","liver","liner","miner","mixer","mixed","fixed","fired","tired"],
  },
  {
    num: 62,
    quizId: 'rung-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    par: 12,
    start: 'woman',
    target: 'fired',
    routes: 4,
    example: ["woman","women","woven","coven","cover","lover","liver","liner","miner","mixer","fixer","fixed","fired"],
  },
  {
    num: 63,
    quizId: 'rung-9-30-26',
    live: '2026-09-30',
    dateLabel: 'September 30, 2026',
    sunday: false,
    par: 10,
    start: 'spite',
    target: 'grade',
    routes: 2,
    example: ["spite","spine","shine","thine","think","thick","trick","track","trace","grace","grade"],
  },
  {
    num: 64,
    quizId: 'rung-10-1-26',
    live: '2026-10-01',
    dateLabel: 'October 1, 2026',
    sunday: false,
    par: 12,
    start: 'tough',
    target: 'slack',
    routes: 2,
    example: ["tough","touch","pouch","porch","perch","peach","peace","place","plane","plank","blank","black","slack"],
  },
  {
    num: 65,
    quizId: 'rung-10-2-26',
    live: '2026-10-02',
    dateLabel: 'October 2, 2026',
    sunday: false,
    par: 11,
    start: 'feral',
    target: 'booth',
    routes: 1,
    example: ["feral","fetal","metal","medal","modal","moral","moray","foray","forty","footy","booty","booth"],
  },
  {
    num: 66,
    quizId: 'rung-10-3-26',
    live: '2026-10-03',
    dateLabel: 'October 3, 2026',
    sunday: false,
    par: 12,
    start: 'dough',
    target: 'stare',
    routes: 4,
    example: ["dough","cough","couch","pouch","porch","perch","peach","peace","place","plate","slate","state","stare"],
  },
  {
    num: 67,
    quizId: 'rung-10-4-26',
    live: '2026-10-04',
    dateLabel: 'October 4, 2026',
    sunday: true,
    par: 19,
    start: 'trump',
    target: 'sense',
    routes: 1,
    example: ["trump","tramp","cramp","clamp","clasp","clash","flash","flask","flank","plank","plane","place","peace","peach","leach","leash","lease","tease","tense","sense"],
  },
  {
    num: 68,
    quizId: 'rung-10-5-26',
    live: '2026-10-05',
    dateLabel: 'October 5, 2026',
    sunday: false,
    par: 10,
    start: 'drunk',
    target: 'swore',
    routes: 3,
    example: ["drunk","trunk","truck","trick","thick","think","thine","shine","shire","shore","swore"],
  },
  {
    num: 69,
    quizId: 'rung-10-6-26',
    live: '2026-10-06',
    dateLabel: 'October 6, 2026',
    sunday: false,
    par: 12,
    start: 'crust',
    target: 'grade',
    routes: 3,
    example: ["crust","crush","crash","clash","flash","flask","flank","frank","crank","crane","crate","grate","grade"],
  },
  {
    num: 70,
    quizId: 'rung-10-7-26',
    live: '2026-10-07',
    dateLabel: 'October 7, 2026',
    sunday: false,
    par: 12,
    start: 'vouch',
    target: 'slash',
    routes: 1,
    example: ["vouch","pouch","porch","perch","peach","peace","place","plane","plank","flank","flask","flash","slash"],
  },
  {
    num: 71,
    quizId: 'rung-10-8-26',
    live: '2026-10-08',
    dateLabel: 'October 8, 2026',
    sunday: false,
    par: 12,
    start: 'shake',
    target: 'roost',
    routes: 2,
    example: ["shake","share","shore","chore","chose","chase","cease","lease","least","beast","boast","boost","roost"],
  },
  {
    num: 72,
    quizId: 'rung-10-9-26',
    live: '2026-10-09',
    dateLabel: 'October 9, 2026',
    sunday: false,
    par: 12,
    start: 'drone',
    target: 'china',
    routes: 1,
    example: ["drone","drove","grove","grave","grace","trace","track","trick","thick","chick","chico","chino","china"],
  },
  {
    num: 73,
    quizId: 'rung-10-10-26',
    live: '2026-10-10',
    dateLabel: 'October 10, 2026',
    sunday: false,
    par: 12,
    start: 'slush',
    target: 'story',
    routes: 4,
    example: ["slush","flush","flash","flask","flank","blank","black","slack","stack","stark","stare","store","story"],
  },
  {
    num: 74,
    quizId: 'rung-10-11-26',
    live: '2026-10-11',
    dateLabel: 'October 11, 2026',
    sunday: true,
    par: 16,
    start: 'blame',
    target: 'couch',
    routes: 2,
    example: ["blame","blaze","glaze","graze","craze","crane","crank","prank","plank","plane","place","peace","peach","reach","roach","coach","couch"],
  },
  {
    num: 75,
    quizId: 'rung-10-12-26',
    live: '2026-10-12',
    dateLabel: 'October 12, 2026',
    sunday: false,
    par: 12,
    start: 'shout',
    target: 'smash',
    routes: 1,
    example: ["shout","shoot","shook","shock","shack","slack","black","blank","flank","flask","flash","slash","smash"],
  },
  {
    num: 76,
    quizId: 'rung-10-13-26',
    live: '2026-10-13',
    dateLabel: 'October 13, 2026',
    sunday: false,
    par: 11,
    start: 'chose',
    target: 'print',
    routes: 2,
    example: ["chose","chore","shore","shire","shine","swine","swing","sting","stint","saint","paint","print"],
  },
  {
    num: 77,
    quizId: 'rung-10-14-26',
    live: '2026-10-14',
    dateLabel: 'October 14, 2026',
    sunday: false,
    par: 10,
    start: 'forty',
    target: 'nasal',
    routes: 1,
    example: ["forty","foray","moray","moral","modal","medal","metal","fetal","fatal","natal","nasal"],
  },
  {
    num: 78,
    quizId: 'rung-10-15-26',
    live: '2026-10-15',
    dateLabel: 'October 15, 2026',
    sunday: false,
    par: 11,
    start: 'draft',
    target: 'clown',
    routes: 2,
    example: ["draft","graft","grant","grand","brand","braid","brain","drain","drawn","drown","crown","clown"],
  },
  {
    num: 79,
    quizId: 'rung-10-16-26',
    live: '2026-10-16',
    dateLabel: 'October 16, 2026',
    sunday: false,
    par: 10,
    start: 'motel',
    target: 'broth',
    routes: 1,
    example: ["motel","model","modal","moral","moray","foray","forty","footy","booty","booth","broth"],
  },
  {
    num: 80,
    quizId: 'rung-10-17-26',
    live: '2026-10-17',
    dateLabel: 'October 17, 2026',
    sunday: false,
    par: 10,
    start: 'stark',
    target: 'torch',
    routes: 1,
    example: ["stark","stare","state","slate","plate","place","peace","peach","perch","porch","torch"],
  },
  {
    num: 81,
    quizId: 'rung-10-18-26',
    live: '2026-10-18',
    dateLabel: 'October 18, 2026',
    sunday: true,
    par: 21,
    start: 'trump',
    target: 'along',
    routes: 1,
    example: ["trump","tramp","cramp","clamp","clasp","clash","flash","flask","flank","blank","black","slack","shack","shark","share","shore","chore","chose","close","clone","alone","along"],
  },
  {
    num: 82,
    quizId: 'rung-10-19-26',
    live: '2026-10-19',
    dateLabel: 'October 19, 2026',
    sunday: false,
    par: 11,
    start: 'toast',
    target: 'tough',
    routes: 4,
    example: ["toast","boast","beast","least","leash","leach","reach","roach","coach","couch","cough","tough"],
  },
  {
    num: 83,
    quizId: 'rung-10-20-26',
    live: '2026-10-20',
    dateLabel: 'October 20, 2026',
    sunday: false,
    par: 11,
    start: 'prank',
    target: 'slept',
    routes: 1,
    example: ["prank","plank","blank","bland","blend","bleed","bleep","sleep","sweep","sweet","swept","slept"],
  },
  {
    num: 84,
    quizId: 'rung-10-21-26',
    live: '2026-10-21',
    dateLabel: 'October 21, 2026',
    sunday: false,
    par: 12,
    start: 'crypt',
    target: 'drink',
    routes: 1,
    example: ["crypt","crept","crest","crust","crush","crash","clash","flash","flask","flank","frank","drank","drink"],
  },
  {
    num: 85,
    quizId: 'rung-10-22-26',
    live: '2026-10-22',
    dateLabel: 'October 22, 2026',
    sunday: false,
    par: 12,
    start: 'feast',
    target: 'trunk',
    routes: 1,
    example: ["feast","least","leash","leach","peach","peace","place","plane","plank","prank","drank","drunk","trunk"],
  },
  {
    num: 86,
    quizId: 'rung-10-23-26',
    live: '2026-10-23',
    dateLabel: 'October 23, 2026',
    sunday: false,
    par: 12,
    start: 'pinch',
    target: 'rouse',
    routes: 1,
    example: ["pinch","punch","bunch","bench","beach","reach","roach","coach","couch","cough","rough","rouge","rouse"],
  },
  {
    num: 87,
    quizId: 'rung-10-24-26',
    live: '2026-10-24',
    dateLabel: 'October 24, 2026',
    sunday: false,
    par: 10,
    start: 'hence',
    target: 'close',
    routes: 1,
    example: ["hence","pence","peace","peach","leach","leash","lease","cease","chase","chose","close"],
  },
  {
    num: 88,
    quizId: 'rung-10-25-26',
    live: '2026-10-25',
    dateLabel: 'October 25, 2026',
    sunday: true,
    par: 16,
    start: 'creep',
    target: 'dutch',
    routes: 1,
    example: ["creep","creed","breed","bleed","blend","bland","blank","plank","plane","place","peace","peach","beach","bench","bunch","butch","dutch"],
  },
  {
    num: 89,
    quizId: 'rung-10-26-26',
    live: '2026-10-26',
    dateLabel: 'October 26, 2026',
    sunday: false,
    par: 11,
    start: 'potty',
    target: 'paste',
    routes: 1,
    example: ["potty","patty","party","parry","carry","curry","curvy","curve","carve","carte","caste","paste"],
  },
  {
    num: 90,
    quizId: 'rung-10-27-26',
    live: '2026-10-27',
    dateLabel: 'October 27, 2026',
    sunday: false,
    par: 12,
    start: 'brave',
    target: 'dream',
    routes: 1,
    example: ["brave","brace","trace","track","trick","brick","brock","brook","brood","broad","bread","dread","dream"],
  },
  {
    num: 91,
    quizId: 'rung-10-28-26',
    live: '2026-10-28',
    dateLabel: 'October 28, 2026',
    sunday: false,
    par: 11,
    start: 'these',
    target: 'plank',
    routes: 7,
    example: ["these","those","chose","chore","shore","share","shark","shack","slack","black","blank","plank"],
  },
  {
    num: 92,
    quizId: 'rung-10-29-26',
    live: '2026-10-29',
    dateLabel: 'October 29, 2026',
    sunday: false,
    par: 12,
    start: 'stole',
    target: 'drawn',
    routes: 1,
    example: ["stole","stale","stalk","stack","slack","black","blank","bland","brand","braid","brain","drain","drawn"],
  },
  {
    num: 93,
    quizId: 'rung-10-30-26',
    live: '2026-10-30',
    dateLabel: 'October 30, 2026',
    sunday: false,
    par: 10,
    start: 'daily',
    target: 'purge',
    routes: 2,
    example: ["daily","dairy","hairy","harry","carry","curry","curvy","curve","curse","purse","purge"],
  },
  {
    num: 94,
    quizId: 'rung-10-31-26',
    live: '2026-10-31',
    dateLabel: 'October 31, 2026',
    sunday: false,
    par: 12,
    start: 'catch',
    target: 'stake',
    routes: 1,
    example: ["catch","batch","butch","bunch","bench","beach","peach","peace","place","plate","slate","state","stake"],
  },
  {
    num: 95,
    quizId: 'rung-11-1-26',
    live: '2026-11-01',
    dateLabel: 'November 1, 2026',
    sunday: true,
    par: 15,
    start: 'shame',
    target: 'crowd',
    routes: 2,
    example: ["shame","share","shark","shack","slack","black","blank","bland","brand","braid","brain","grain","groin","grown","crown","crowd"],
  },
  {
    num: 96,
    quizId: 'rung-11-2-26',
    live: '2026-11-02',
    dateLabel: 'November 2, 2026',
    sunday: false,
    par: 11,
    start: 'stone',
    target: 'coach',
    routes: 5,
    example: ["stone","stoke","stake","state","slate","plate","place","peace","peach","reach","roach","coach"],
  },
  {
    num: 97,
    quizId: 'rung-11-3-26',
    live: '2026-11-03',
    dateLabel: 'November 3, 2026',
    sunday: false,
    par: 10,
    start: 'tweet',
    target: 'thing',
    routes: 1,
    example: ["tweet","sweet","sheet","sheer","cheer","cheek","check","chick","thick","think","thing"],
  },
  {
    num: 98,
    quizId: 'rung-11-4-26',
    live: '2026-11-04',
    dateLabel: 'November 4, 2026',
    sunday: false,
    par: 12,
    start: 'break',
    target: 'fence',
    routes: 1,
    example: ["break","bread","breed","bleed","blend","bland","blank","plank","plane","place","peace","pence","fence"],
  },
  {
    num: 99,
    quizId: 'rung-11-5-26',
    live: '2026-11-05',
    dateLabel: 'November 5, 2026',
    sunday: false,
    par: 11,
    start: 'smart',
    target: 'fresh',
    routes: 1,
    example: ["smart","start","stark","stack","slack","black","blank","flank","flask","flash","flesh","fresh"],
  },
  {
    num: 100,
    quizId: 'rung-11-6-26',
    live: '2026-11-06',
    dateLabel: 'November 6, 2026',
    sunday: false,
    par: 10,
    start: 'shave',
    target: 'touch',
    routes: 2,
    example: ["shave","slave","slate","plate","place","peace","peach","perch","porch","torch","touch"],
  },
  {
    num: 101,
    quizId: 'rung-11-7-26',
    live: '2026-11-07',
    dateLabel: 'November 7, 2026',
    sunday: false,
    par: 12,
    start: 'slice',
    target: 'bunch',
    routes: 1,
    example: ["slice","slick","slack","black","blank","plank","plane","place","peace","peach","beach","bench","bunch"],
  },
  {
    num: 102,
    quizId: 'rung-11-8-26',
    live: '2026-11-08',
    dateLabel: 'November 8, 2026',
    sunday: true,
    par: 18,
    start: 'tense',
    target: 'cream',
    routes: 1,
    example: ["tense","tease","lease","leash","leach","peach","peace","place","plane","plank","blank","bland","blend","bleed","breed","bread","dread","dream","cream"],
  },
  {
    num: 103,
    quizId: 'rung-11-9-26',
    live: '2026-11-09',
    dateLabel: 'November 9, 2026',
    sunday: false,
    par: 11,
    start: 'cheek',
    target: 'peace',
    routes: 3,
    example: ["cheek","check","chick","click","clock","block","black","blank","plank","plane","place","peace"],
  },
  {
    num: 104,
    quizId: 'rung-11-10-26',
    live: '2026-11-10',
    dateLabel: 'November 10, 2026',
    sunday: false,
    par: 10,
    start: 'grove',
    target: 'cheer',
    routes: 1,
    example: ["grove","grave","grace","trace","track","trick","thick","chick","check","cheek","cheer"],
  },
  {
    num: 105,
    quizId: 'rung-11-11-26',
    live: '2026-11-11',
    dateLabel: 'November 11, 2026',
    sunday: false,
    par: 12,
    start: 'shine',
    target: 'steam',
    routes: 1,
    example: ["shine","thine","think","thick","chick","check","cheek","cheer","sheer","steer","steel","steal","steam"],
  },
  {
    num: 106,
    quizId: 'rung-11-12-26',
    live: '2026-11-12',
    dateLabel: 'November 12, 2026',
    sunday: false,
    par: 11,
    start: 'spark',
    target: 'blast',
    routes: 3,
    example: ["spark","spare","share","shore","chore","chose","chase","cease","lease","least","beast","blast"],
  },
  {
    num: 107,
    quizId: 'rung-11-13-26',
    live: '2026-11-13',
    dateLabel: 'November 13, 2026',
    sunday: false,
    par: 10,
    start: 'react',
    target: 'flesh',
    routes: 1,
    example: ["react","reach","peach","peace","place","plane","plank","flank","flask","flash","flesh"],
  },
  {
    num: 108,
    quizId: 'rung-11-14-26',
    live: '2026-11-14',
    dateLabel: 'November 14, 2026',
    sunday: false,
    par: 12,
    start: 'brush',
    target: 'prize',
    routes: 1,
    example: ["brush","blush","flush","flash","flask","flank","blank","blink","brink","brine","bride","pride","prize"],
  },
  {
    num: 109,
    quizId: 'rung-11-15-26',
    live: '2026-11-15',
    dateLabel: 'November 15, 2026',
    sunday: true,
    par: 18,
    start: 'chess',
    target: 'beast',
    routes: 1,
    example: ["chess","chest","crest","crust","crush","crash","clash","flash","flask","flank","plank","plane","place","peace","peach","leach","leash","least","beast"],
  },
  {
    num: 110,
    quizId: 'rung-11-16-26',
    live: '2026-11-16',
    dateLabel: 'November 16, 2026',
    sunday: false,
    par: 11,
    start: 'point',
    target: 'spell',
    routes: 3,
    example: ["point","paint","saint","stint","stink","stick","stack","stalk","stall","small","smell","spell"],
  },
  {
    num: 111,
    quizId: 'rung-11-17-26',
    live: '2026-11-17',
    dateLabel: 'November 17, 2026',
    sunday: false,
    par: 10,
    start: 'sober',
    target: 'mayor',
    routes: 1,
    example: ["sober","saber","saver","sever","lever","liver","liner","miner","minor","manor","mayor"],
  },
  {
    num: 112,
    quizId: 'rung-11-18-26',
    live: '2026-11-18',
    dateLabel: 'November 18, 2026',
    sunday: false,
    par: 12,
    start: 'naked',
    target: 'major',
    routes: 1,
    example: ["naked","baked","baker","taker","taser","laser","loser","loner","liner","miner","minor","manor","major"],
  },
  {
    num: 113,
    quizId: 'rung-11-19-26',
    live: '2026-11-19',
    dateLabel: 'November 19, 2026',
    sunday: false,
    par: 11,
    start: 'grace',
    target: 'smoke',
    routes: 2,
    example: ["grace","trace","track","trick","thick","think","thine","shine","spine","spike","spoke","smoke"],
  },
  {
    num: 114,
    quizId: 'rung-11-20-26',
    live: '2026-11-20',
    dateLabel: 'November 20, 2026',
    sunday: false,
    par: 10,
    start: 'fiber',
    target: 'paper',
    routes: 2,
    example: ["fiber","fixer","mixer","miner","liner","loner","loser","laser","taser","taper","paper"],
  },
  {
    num: 115,
    quizId: 'rung-11-21-26',
    live: '2026-11-21',
    dateLabel: 'November 21, 2026',
    sunday: false,
    par: 12,
    start: 'scare',
    target: 'crush',
    routes: 3,
    example: ["scare","stare","stark","stack","slack","black","blank","flank","flask","flash","clash","crash","crush"],
  },
  {
    num: 116,
    quizId: 'rung-11-22-26',
    live: '2026-11-22',
    dateLabel: 'November 22, 2026',
    sunday: true,
    par: 17,
    start: 'sneak',
    target: 'flown',
    routes: 2,
    example: ["sneak","steak","steal","steel","steep","sleep","bleep","bleed","blend","bland","brand","braid","brain","grain","groin","grown","frown","flown"],
  },
  {
    num: 117,
    quizId: 'rung-11-23-26',
    live: '2026-11-23',
    dateLabel: 'November 23, 2026',
    sunday: false,
    par: 11,
    start: 'crime',
    target: 'trail',
    routes: 1,
    example: ["crime","prime","pride","bride","brine","brink","brick","trick","track","tract","trait","trail"],
  },
  {
    num: 118,
    quizId: 'rung-11-24-26',
    live: '2026-11-24',
    dateLabel: 'November 24, 2026',
    sunday: false,
    par: 10,
    start: 'shade',
    target: 'bride',
    routes: 1,
    example: ["shade","share","shark","shack","slack","black","blank","blink","brink","brine","bride"],
  },
  {
    num: 119,
    quizId: 'rung-11-25-26',
    live: '2026-11-25',
    dateLabel: 'November 25, 2026',
    sunday: false,
    par: 12,
    start: 'crash',
    target: 'saint',
    routes: 3,
    example: ["crash","clash","flash","flask","flank","plank","plant","slant","slang","sling","sting","stint","saint"],
  },
  {
    num: 120,
    quizId: 'rung-11-26-26',
    live: '2026-11-26',
    dateLabel: 'November 26, 2026',
    sunday: false,
    par: 11,
    start: 'stock',
    target: 'leave',
    routes: 6,
    example: ["stock","shock","shook","shoot","short","shore","chore","chose","chase","cease","lease","leave"],
  },
  {
    num: 121,
    quizId: 'rung-11-27-26',
    live: '2026-11-27',
    dateLabel: 'November 27, 2026',
    sunday: false,
    par: 10,
    start: 'plane',
    target: 'trial',
    routes: 1,
    example: ["plane","plank","blank","bland","blend","bleed","breed","bread","tread","triad","trial"],
  },
  {
    num: 122,
    quizId: 'rung-11-28-26',
    live: '2026-11-28',
    dateLabel: 'November 28, 2026',
    sunday: false,
    par: 12,
    start: 'glass',
    target: 'shall',
    routes: 1,
    example: ["glass","class","clash","flash","flask","flank","blank","black","slack","stack","stalk","stall","shall"],
  },
  {
    num: 123,
    quizId: 'rung-11-29-26',
    live: '2026-11-29',
    dateLabel: 'November 29, 2026',
    sunday: true,
    par: 17,
    start: 'probe',
    target: 'phase',
    routes: 3,
    example: ["probe","prove","grove","grave","grace","trace","track","trick","thick","think","thine","whine","while","whole","whose","chose","chase","phase"],
  },
  {
    num: 124,
    quizId: 'rung-11-30-26',
    live: '2026-11-30',
    dateLabel: 'November 30, 2026',
    sunday: false,
    par: 11,
    start: 'basis',
    target: 'coral',
    routes: 1,
    example: ["basis","basil","basal","nasal","natal","fatal","fetal","metal","medal","modal","moral","coral"],
  },
];
