// scripts/gen-dario.mjs — writes app/dario/puzzles.js.
//
// Dario ships no authored board: the day's course remix is generated from the
// quizId by lib/dario-engine.js buildLevels, in the client and the verifier
// alike. A row is the calendar and nothing more.
//
//   node scripts/gen-dario.mjs > app/dario/puzzles.js
//
// Deterministic, and it never renumbers: day 1 is FIRST.
const FIRST = '2026-10-07';
const LAST = '2027-01-31';
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const rows = [];
let d = new Date(FIRST + 'T12:00:00Z');
const end = new Date(LAST + 'T12:00:00Z');
let num = 1;
while (d <= end) {
  const y = d.getUTCFullYear(), m = d.getUTCMonth() + 1, day = d.getUTCDate();
  const live = `${y}-${String(m).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  rows.push(`  { num: ${num}, quizId: 'dario-${m}-${day}-${String(y).slice(2)}', live: '${live}', dateLabel: '${MONTHS[m - 1]} ${day}, ${y}', sunday: false },`);
  num++;
  d = new Date(d.getTime() + 86400000);
}
process.stdout.write(`// Puzzle data for Dario, the daily side-scroller. Imported ONLY by the server
// page (app/dario/page.js), which filters live<=today. Generated by
// scripts/gen-dario.mjs; edit that, not this.
//
// A row is only the calendar: the course remix (enemies, chips, crates, the
// shield, rocket and platform timing) comes from \`quizId\` through
// lib/dario-engine.js buildLevels, so nothing about tomorrow ships today.
// Dario has no Sunday Edition.
export const PUZZLES = [
${rows.join('\n')}
];
`);
