// scripts/gen-flank.mjs — generates app/flank/puzzles.js from the curated
// day schedule below plus the app/flank/borders.js dataset. Run from the
// repo root:
//
//   node scripts/gen-flank.mjs
//
// The schedule is hand-picked, not derived: each day names its country, and
// this script resolves the answer set from the dataset, enforces the weekday
// difficulty bands, the Sunday-giant rule, the no-repeat rule and the
// noSubject exclusions, and refuses to write a bank that breaks any of them.
// Extending the bank means appending days here and re-running; days already
// live are regenerated byte-identical because everything is derived from the
// same frozen schedule (never edit a past day's country).
//
// Weekday bands (neighbor count): Mon 1-2, Tue 2-3, Wed 3-4, Thu 4-5,
// Fri 5-6, Sat 6-7, Sun 8+ (the Sunday Edition giant).
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { BORDERS } from '../app/flank/borders.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, '..', 'app', 'flank', 'puzzles.js');

// date (ET calendar date the day goes live) -> country display name.
// Peru is deliberately never used: it is the share-card demo board.
const SCHEDULE = [
  ['2026-08-28', 'Afghanistan'],
  ['2026-08-29', 'Poland'],
  ['2026-08-30', 'China'],
  ['2026-08-31', 'Portugal'],
  ['2026-09-01', 'Mexico'],
  ['2026-09-02', 'Vietnam'],
  ['2026-09-03', 'Argentina'],
  ['2026-09-04', 'Israel'],
  ['2026-09-05', 'India'],
  ['2026-09-06', 'Germany'],
  ['2026-09-07', 'Canada'],
  ['2026-09-08', 'Nepal'],
  ['2026-09-09', 'Chile'],
  ['2026-09-10', 'Thailand'],
  ['2026-09-11', 'Iraq'],
  ['2026-09-12', 'Ukraine'],
  ['2026-09-13', 'Russia'],
  ['2026-09-14', 'United Kingdom'],
  ['2026-09-15', 'United States'],
  ['2026-09-16', 'Norway'],
  ['2026-09-17', 'Egypt'],
  ['2026-09-18', 'Colombia'],
  ['2026-09-19', 'Ethiopia'],
  ['2026-09-20', 'Turkey'],
  ['2026-09-21', 'Denmark'],
  ['2026-09-22', 'Ecuador'],
  ['2026-09-23', 'Finland'],
  ['2026-09-24', 'Nigeria'],
  ['2026-09-25', 'Kazakhstan'],
  ['2026-09-26', 'Iran'],
  ['2026-09-27', 'Austria'],
  ['2026-09-28', 'South Korea'],
  ['2026-09-29', 'Uruguay'],
  ['2026-09-30', 'Greece'],
  ['2026-10-01', 'Croatia'],
  ['2026-10-02', 'Bolivia'],
  ['2026-10-03', 'Hungary'],
  ['2026-10-04', 'Tanzania'],
  ['2026-10-05', 'Ireland'],
  ['2026-10-06', 'Sweden'],
  ['2026-10-07', 'Cambodia'],
  ['2026-10-08', 'Pakistan'],
  ['2026-10-09', 'Myanmar'],
  ['2026-10-10', 'Sudan'],
  ['2026-10-11', 'DR Congo'],
  ['2026-10-12', 'Papua New Guinea'],
  ['2026-10-13', 'Mongolia'],
  ['2026-10-14', 'Indonesia'],
  ['2026-10-15', 'Georgia'],
  ['2026-10-16', 'Belarus'],
  ['2026-10-17', 'Niger'],
  ['2026-10-18', 'Zambia'],
  ['2026-10-19', 'Lesotho'],
  ['2026-10-20', 'Moldova'],
  ['2026-10-21', 'Belgium'],
  ['2026-10-22', 'Romania'],
  ['2026-10-23', 'Switzerland'],
  ['2026-10-24', 'Mali'],
  ['2026-10-25', 'Serbia'],
  ['2026-10-26', 'Monaco'],
  ['2026-10-27', 'Panama'],
  ['2026-10-28', 'Somalia'],
  ['2026-10-29', 'Bulgaria'],
  ['2026-10-30', 'South Africa'],
  ['2026-10-31', 'Saudi Arabia'],
  ['2026-11-01', 'China'],
  ['2026-11-02', 'Haiti'],
  ['2026-11-03', 'Costa Rica'],
  ['2026-11-04', 'Ghana'],
  ['2026-11-05', 'Czechia'],
  ['2026-11-06', 'Kenya'],
  ['2026-11-07', 'Italy'],
  ['2026-11-08', 'Germany'],
  ['2026-11-09', 'Qatar'],
  ['2026-11-10', 'Netherlands'],
  ['2026-11-11', 'Venezuela'],
  ['2026-11-12', 'Latvia'],
  ['2026-11-13', 'Jordan'],
  ['2026-11-14', 'Libya'],
  ['2026-11-15', 'Russia'],
  ['2026-11-16', 'Dominican Republic'],
  ['2026-11-17', 'Bangladesh'],
  ['2026-11-18', 'Malaysia'],
  ['2026-11-19', 'Armenia'],
  ['2026-11-20', 'Slovakia'],
  ['2026-11-21', 'Cameroon'],
  ['2026-11-22', 'Turkey'],
  ['2026-11-23', 'Brunei'],
  ['2026-11-24', 'Estonia'],
  ['2026-11-25', 'Paraguay'],
  ['2026-11-26', 'Guatemala'],
  ['2026-11-27', 'Uganda'],
  ['2026-11-28', 'Chad'],
  ['2026-11-29', 'Austria'],
  ['2026-11-30', 'Eswatini'],
];

const BAND = { 1: [1, 2], 2: [2, 3], 3: [3, 4], 4: [4, 5], 5: [5, 6], 6: [6, 7], 0: [8, 99] };
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const byName = new Map(Object.entries(BORDERS).map(([code, e]) => [e.name, code]));
const errs = [];
const lastSeen = new Map();
const GIANT_REPEAT_FROM = '2026-11-01', GIANT_GAP = 63;
const puzzles = [];

// Consecutive-date check plus everything else, one pass.
let prevDate = null;
SCHEDULE.forEach(([iso, country], i) => {
  const [y, mo, dy] = iso.split('-').map(Number);
  const d = new Date(Date.UTC(y, mo - 1, dy));
  if (prevDate != null && d - prevDate !== 86400000) errs.push(`${iso}: schedule dates are not consecutive`);
  prevDate = d;
  const dow = d.getUTCDay();
  const code = byName.get(country);
  if (!code) { errs.push(`${iso}: unknown country "${country}"`); return; }
  const e = BORDERS[code];
  if (e.noSubject) errs.push(`${iso}: ${country} is noSubject (contested set) and may not be a day's country`);
  // PROPOSED (2026-09-23, needs owner sign-off): the pool of Sunday giants
  // (8+ neighbors, not noSubject) is nine countries and all nine ran by
  // 2026-10-25, so from GIANT_REPEAT_FROM a Sunday giant may return once at
  // least GIANT_GAP days have passed since its last Sunday. Weekday countries
  // still never repeat.
  const prev = lastSeen.get(code);
  if (prev) {
    const ok = dow === 0 && iso >= GIANT_REPEAT_FROM && prev.sunday && (d - prev.d) / 86400000 >= GIANT_GAP;
    if (!ok) errs.push(`${iso}: ${country} repeats within the bank`);
  }
  lastSeen.set(code, { d, sunday: dow === 0 });
  const n = e.n.length;
  const [lo, hi] = BAND[dow];
  if (n < lo || n > hi) errs.push(`${iso}: ${country} has ${n} neighbors, outside the ${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][dow]} band ${lo}-${hi}`);
  const answers = [...e.n].sort((a, b) => BORDERS[a].name.localeCompare(BORDERS[b].name));
  puzzles.push({
    num: i + 1,
    quizId: `flank-${mo}-${dy}-${String(y).slice(2)}`,
    live: iso,
    dateLabel: `${MONTHS[mo - 1]} ${dy}, ${y}`,
    sunday: dow === 0,
    c: code,
    a: answers,
  });
});

if (errs.length) { console.error(errs.join('\n')); process.exit(1); }

const lines = [];
lines.push('// Puzzle data for Flank, the daily borders game. Each day names one country');
lines.push('// (`c`, an entity code from borders.js) and its full land-neighbor answer');
lines.push('// set (`a`, codes sorted by display name). GENERATED by scripts/gen-flank.mjs');
lines.push('// from the curated schedule there; edit the schedule and re-run, never this');
lines.push('// file. The server page resolves and strips a day before it ships, so the');
lines.push('// bank\'s answers never reach a browser ahead of their day. The shared daily');
lines.push('// consumers read only num/quizId/live/dateLabel/sunday and ignore the rest.');
lines.push('export const PUZZLES = [');
for (const p of puzzles) {
  lines.push(`  { num: ${p.num}, quizId: '${p.quizId}', live: '${p.live}', dateLabel: '${p.dateLabel}', sunday: ${p.sunday}, c: '${p.c}', a: ${JSON.stringify(p.a)} },`);
}
lines.push('];');
lines.push('');
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`gen-flank: wrote ${puzzles.length} days (${puzzles[0].live} .. ${puzzles[puzzles.length - 1].live}), ${puzzles.filter((p) => p.sunday).length} Sundays`);
