// scripts/gen-snake.mjs — writes app/snake/puzzles.js.
//
// Snake ships no board: the day's APPLE ORDER is generated from the quizId by
// lib/snake-engine.js, in the client and in the verifier alike. A row carries
// only the frame (size, grow, par), so this is a calendar walk and nothing more.
//
//   node scripts/gen-snake.mjs > app/snake/puzzles.js
//
// Deterministic. Re-running it on an unchanged calendar is byte-identical, and
// it never renumbers: day 1 is FIRST and every later row follows by date.

const FIRST = '2026-10-07';
const LAST = '2027-01-31';
const SIZE = 15;
const WEEKDAY = { grow: 1, par: 20 };
const SUNDAY = { grow: 2, par: 15 };

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const rows = [];
let d = new Date(FIRST + 'T12:00:00Z');
const end = new Date(LAST + 'T12:00:00Z');
let num = 1;
while (d <= end) {
  const y = d.getUTCFullYear(), m = d.getUTCMonth() + 1, day = d.getUTCDate();
  const live = `${y}-${String(m).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  const sunday = d.getUTCDay() === 0;
  const f = sunday ? SUNDAY : WEEKDAY;
  rows.push(`  { num: ${num}, quizId: 'snake-${m}-${day}-${String(y).slice(2)}', live: '${live}', dateLabel: '${MONTHS[m - 1]} ${day}, ${y}', sunday: ${sunday}, size: ${SIZE}, grow: ${f.grow}, par: ${f.par} },`);
  num++;
  d = new Date(d.getTime() + 86400000);
}

process.stdout.write(`// Puzzle data for Snake, the daily snake game. Imported ONLY by the server page
// (app/snake/page.js), which filters live<=today before handing the bank to the
// client. Generated by scripts/gen-snake.mjs; edit that, not this.
//
// Snake has no authored board: the day's APPLE ORDER is generated in the client
// from \`quizId\` (lib/snake-engine.js dayPlan), so every player on a given day
// gets the same apples in the same order and nothing about tomorrow leaks by
// shipping today's row. A row therefore carries only the frame:
//
//   size  the board is size x size and its edges wrap. Always 15.
//   grow  squares the snake grows per apple. 1 on a weekday, 2 on the Sunday
//         Edition, which fills the board twice as fast.
//   par   the day's BENCHMARK apple count, not a ceiling. Apples are the score,
//         posted raw and uncapped, and par is only the denominator the combined
//         board uses for its completion ratio (it clamps at 1). Reaching par
//         wins the end card. Set below what a greedy solver reaches (median 27
//         apples a weekday) because Blocks taught us a solver is no guide to a
//         human: revisit once a fortnight of real scores exists.
export const PUZZLES = [
${rows.join('\n')}
];
`);
