// scripts/gen-potluck.mjs: builds app/potluck/puzzles.js, the Potluck bank.
//
// Potluck (owner, 2026-10-09) is three catalog quizzes a day, picked from the
// quizzes that already play on /quiz/<id>. The bank is DATED and generated
// here rather than derived at read time, so every player gets the same three,
// a reviewer can read a day before it goes live, and scripts/verify-potluck.mjs
// can prove the rules below.
//
// THE RULES (enforced again by the verifier):
//   1. Only formats the shared quiz shell plays (QuizClient). Potluck hands the
//      player to /quiz/<id>?potluck=<num>&i=<slot>, and only QuizClient knows
//      to report back. The full-page boards (timed-mcq, place-map, globe,
//      geo-aerial and the rest) post on their own and would leave the slot
//      empty, so they are never picked.
//   2. VARIETY: the three come from three different format families (typed,
//      matching, visual) AND three different departments.
//   3. FACTUAL ONLY, the Daily Challenge rule: no quiz paired to a non-facts
//      list, and no quiz whose source cites a publications consensus.
//   4. No quiz is used twice in the bank, and 8 to 50 answers each.
//   5. Only published, listed quizzes.
//
//   node scripts/gen-potluck.mjs [--from 2026-10-10] [--days 120] [--seed 7]
import fs from 'fs';
import path from 'path';
import { register } from 'node:module';
register('./alias-loader.mjs', import.meta.url);

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const arg = (k, d) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : d; };
const FROM = arg('--from', '2026-10-10');
const DAYS = Number(arg('--days', '120'));
const SEED = Number(arg('--seed', '7'));

const { QUIZZES } = await import(path.join(root, 'lib/quizzes.js'));
const { LISTS } = await import(path.join(root, 'lib/data.js'));
const { quizDept } = await import(path.join(root, 'lib/quiz-departments.js'));
const { POTLUCK_FAMILY, potluckEligible } = await import(path.join(root, 'lib/potluck.js'));

const listMode = new Map(LISTS.map((l) => [l.id, l.mode || 'consensus']));
const pool = QUIZZES.filter((q) => potluckEligible(q, listMode, Date.parse(FROM + 'T04:00:00Z')));
const byFam = { typed: [], match: [], visual: [] };
for (const q of pool) byFam[POTLUCK_FAMILY[q.format || 'default']].push(q);

// Deterministic shuffle.
let s = SEED >>> 0;
const rnd = () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; };
for (const f of Object.keys(byFam)) {
  const a = byFam[f];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
}

function ymd(d) { return d.toISOString().slice(0, 10); }
function addDays(iso, n) { const d = new Date(iso + 'T12:00:00Z'); d.setUTCDate(d.getUTCDate() + n); return ymd(d); }
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
function label(iso) { const [y, m, d] = iso.split('-').map(Number); return `${MONTHS[m - 1]} ${d}, ${y}`; }
function qid(iso) { const [y, m, d] = iso.split('-').map(Number); return `potluck-${m}-${d}-${String(y).slice(2)}`; }

const used = new Set();
const out = [];
let prevDepts = new Set();
// The visual family is the scarcest, so it is drawn first; order on the day is
// shuffled afterwards so the visual quiz is not always slot one.
const ORDER = ['visual', 'match', 'typed'];
for (let n = 0; n < DAYS; n++) {
  const live = addDays(FROM, n);
  const picks = [];
  const depts = new Set();
  for (const fam of ORDER) {
    const cand = byFam[fam].find((q) => !used.has(q.id) && !depts.has(quizDept(q)) && !prevDepts.has(quizDept(q)))
      || byFam[fam].find((q) => !used.has(q.id) && !depts.has(quizDept(q)));
    if (!cand) { console.error(`ran out of ${fam} quizzes on ${live}`); process.exit(1); }
    used.add(cand.id); depts.add(quizDept(cand)); picks.push(cand.id);
  }
  // Rotate the slot order by day so each family takes every slot in turn.
  const rot = n % 3;
  const quizzes = [...picks.slice(rot), ...picks.slice(0, rot)];
  prevDepts = depts;
  out.push({ num: n + 1, quizId: qid(live), live, dateLabel: label(live), quizzes });
}

const header = `// Potluck bank: three catalog quizzes a day. GENERATED by scripts/gen-potluck.mjs
// (${FROM}, ${DAYS} days, seed ${SEED}); checked by scripts/verify-potluck.mjs.
// Never hand-edit a day that has gone live: its leaderboard is keyed to it.
// Pool at build: ${byFam.typed.length} typed, ${byFam.match.length} matching, ${byFam.visual.length} visual.
`;
const body = 'export const PUZZLES = [\n' + out.map((p) => '  ' + JSON.stringify(p)).join(',\n') + '\n];\n';
fs.writeFileSync(path.join(root, 'app/potluck/puzzles.js'), header + body);
console.log(`gen-potluck: ${out.length} days ${out[0].live} to ${out[out.length - 1].live}; pool typed ${byFam.typed.length}, match ${byFam.match.length}, visual ${byFam.visual.length}`);
