// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to
// the client — so future puzzles (and their perfect routes) never ship to the
// browser bundle.
//
// perfect = BFS-minimum border hops on app/span/borders.js, the shortest road
// that exists. It is the target players are shown, and it is a proven minimum
// rather than an average, which is why it is called perfect and not par.
// Recompute with the validator after ANY borders change; a stale perfect
// breaks scoring. `note` is
// revealed at game end (a fun fact about the route, never a spoiler before).
//
// SUNDAY EDITIONS (every Sunday, starting 2026-07-19): one twist per Sunday,
// either `via: '<Country>'` (the chain must pass through it before reaching
// the destination) or `avoid: '<Country>'` (that country is closed and can't
// be entered). Set `sunday: true` alongside. RULES FOR AUTHORING:
// - perfect MUST be the CONSTRAINED shortest: for avoid, BFS with the country
//   blocked (the destination must stay reachable!); for via, hops(start,via)
//   + hops(via,end), which the validator also proves is achievable as a
//   simple path (the two legs must compose without reusing a country).
// - Never both via and avoid on one puzzle. Weekday puzzles get neither.
// - Pick twists that genuinely reroute the road (base perfect should change).
export const PUZZLES = [
  {
    num: 1,
    quizId: 'span-7-12-26',
    live: '2026-07-12',
    dateLabel: 'July 12, 2026',
    start: 'Canada',
    end: 'Panama',
    perfect: 7,
    note: 'The full mainland run: there is exactly one shortest road, and no country on it can be skipped.',
  },
  {
    num: 2,
    quizId: 'span-7-13-26',
    live: '2026-07-13',
    dateLabel: 'July 13, 2026',
    start: 'Finland',
    end: 'Greece',
    perfect: 4,
    note: 'Both shortest roads leave Europe: Russia opens the door, and Turkey or the Caucasus closes it.',
  },
  {
    num: 3,
    quizId: 'span-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    start: 'Argentina',
    end: 'Ecuador',
    perfect: 3,
    note: 'Brazil borders every South American country except Ecuador and Chile — which is exactly why it is the perfect middle step.',
  },
  {
    num: 4,
    quizId: 'span-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    start: 'Senegal',
    end: 'Egypt',
    perfect: 4,
    note: 'The Sahara is a highway here: Algeria and Libya between them touch almost everything across North Africa.',
  },
  {
    num: 5,
    quizId: 'span-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    start: 'Norway',
    end: 'South Korea',
    perfect: 3,
    note: 'Russia borders both Norway and North Korea — one country spans the whole of Eurasia.',
  },
  {
    num: 6,
    quizId: 'span-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    start: 'Oman',
    end: 'Tunisia',
    perfect: 6,
    note: 'The one shortest road runs Jordan → Israel → Egypt: the Sinai crossing is the only land door between Asia and Africa.',
  },
  {
    num: 7,
    quizId: 'span-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    start: 'Mexico',
    end: 'Chile',
    perfect: 8,
    note: 'Eight hops, one road: Central America is a single-file line, and the shortest way into Chile comes through Peru at the far end.',
  },
  {
    num: 8,
    quizId: 'span-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    start: 'Sweden',
    end: 'Switzerland',
    sunday: true,
    via: 'Italy',
    perfect: 7, // hops(Sweden,Italy)=6 + hops(Italy,Switzerland)=1, legs disjoint
    note: 'Without the detour this is a 5-hop road. Italy drags you the long way around: out through Russia, across Poland and Germany, down through France, and into Switzerland from the south.',
  },
  {
    num: 9,
    quizId: 'span-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    start: 'Thailand',
    end: 'Georgia',
    perfect: 4,
    note: 'China and Russia stitched together bridge Southeast Asia to the Caucasus in just two giant steps.',
  },
  {
    num: 10,
    quizId: 'span-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    start: 'South Africa',
    end: 'Nigeria',
    perfect: 5,
    note: 'The Atlantic coast is the fast lane — Angola reaches the Republic of the Congo through Cabinda, its exclave north of the DRC.',
  },
  {
    num: 11,
    quizId: 'span-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    start: 'Timor-Leste',
    end: 'Bangladesh',
    perfect: 5,
    note: 'Indonesia and Malaysia share a land border on Borneo — the island route quietly connects to mainland Asia.',
  },
  {
    num: 12,
    quizId: 'span-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    start: 'Estonia',
    end: 'Portugal',
    perfect: 6,
    note: 'The Baltic chain through Latvia and Lithuania is one hop longer — the single shortest road slips out through Russia and crosses into Poland at Kaliningrad.',
  },
  {
    num: 13,
    quizId: 'span-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    start: 'Ghana',
    end: 'Ethiopia',
    perfect: 5,
    note: 'Both shortest roads cross the Sahara — the coast route through Nigeria and Cameroon is the scenic detour.',
  },
  {
    num: 14,
    quizId: 'span-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    start: 'Spain',
    end: 'India',
    perfect: 6,
    note: 'The one shortest road runs through Russia and China — the southern route through Iran and Pakistan costs two extra hops.',
  },
  {
    num: 15,
    quizId: 'span-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    start: 'Germany',
    end: 'China',
    sunday: true,
    avoid: 'Russia',
    perfect: 8, // base perfect is 3 (Poland–Russia–China); with Russia closed the road is the old Silk Road
    note: 'With Russia open this is three hops. Closed, the only way east is the old Silk Road: down the Balkans, through Turkey and Iran, and over the mountains into China.',
  },
  {
    num: 16,
    quizId: 'span-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    start: 'Norway',
    end: 'Portugal',
    perfect: 6,
    note: 'One road, no shortcuts: Sweden and Finland only loop back to Russia, so the fast way to the Atlantic\'s far corner leaves Norway heading east and comes all the way down the spine of Europe.',
  },
  {
    num: 17,
    quizId: 'span-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    start: 'Kenya',
    end: 'Nigeria',
    perfect: 4,
    note: 'Four different four-hop roads tie for the shortest, and every one slices due west across the Sahel — the belt of countries that stitches East Africa to West.',
  },
  {
    num: 18,
    quizId: 'span-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    start: 'Iran',
    end: 'Vietnam',
    perfect: 3,
    note: 'Two roads, one giant between them: cut through Afghanistan or through Pakistan, either way China is unavoidable — no other country touches both this corner of Asia and the South China Sea.',
  },
  {
    num: 19,
    quizId: 'span-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    start: 'Peru',
    end: 'Panama',
    perfect: 2,
    note: 'All of South America funnels through one doorway: Colombia is its only link to Panama and the road north, so every crossing between the two continents — Peru\'s included — runs through it.',
  },
  {
    num: 20,
    quizId: 'span-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    start: 'Morocco',
    end: 'Nigeria',
    perfect: 3,
    note: 'The Mediterranean coast is a dead end, so the short road runs south into the Sahara: Algeria stretches down to touch Niger, and Niger opens straight into Nigeria.',
  },
  {
    num: 21,
    quizId: 'span-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    start: 'Greece',
    end: 'Egypt',
    perfect: 4,
    note: 'No land road links Europe to Africa around the Mediterranean, so the way to Egypt bends east through Turkey and Syria, then crosses from Israel over the Sinai, the only land bridge between the two continents.',
  },
  {
    num: 22,
    quizId: 'span-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    start: 'Argentina',
    end: 'Colombia',
    sunday: true,
    avoid: 'Brazil',
    perfect: 3, // base perfect is 2 (Argentina-Brazil-Colombia); with Brazil closed the road climbs the Andes
    note: 'With Brazil open this is two hops. Closed, the only way north hugs the Andes: up through Bolivia and Peru before crossing into Colombia.',
  },
  {
    num: 23,
    quizId: 'span-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    start: 'Portugal',
    end: 'Poland',
    perfect: 4,
    note: 'Portugal has only one neighbor, so every road out starts in Spain, then runs the width of the continent through France and Germany to reach Poland.',
  },
  {
    num: 24,
    quizId: 'span-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    start: 'Italy',
    end: 'Netherlands',
    perfect: 3,
    note: 'The Alps are no barrier here: step west into France, north into Germany, and the Low Countries open up, three hops to the North Sea.',
  },
  {
    num: 25,
    quizId: 'span-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    start: 'Egypt',
    end: 'Ghana',
    perfect: 4,
    note: 'There is no coastal road along the Gulf of Guinea, so the short way dives into the Sahara: through Libya and Niger, then down through Burkina Faso to the Gold Coast.',
  },
  {
    num: 26,
    quizId: 'span-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    start: 'India',
    end: 'Turkey',
    perfect: 3,
    note: 'A straight westward march across the old Silk Road: Pakistan, then Iran, which reaches all the way to Turkey in a tidy three hops.',
  },
  {
    num: 27,
    quizId: 'span-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    start: 'Norway',
    end: 'Italy',
    perfect: 5,
    note: 'Scandinavia has only one land door to the continent: Norway touches Russia, and from there the road runs back west through Poland, Germany and France before finally reaching Italy.',
  },
  {
    num: 28,
    quizId: 'span-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    start: 'Venezuela',
    end: 'Chile',
    perfect: 3,
    note: 'Down the Pacific spine of the continent: Colombia, then Peru, which shares the long desert frontier with Chile.',
  },
  {
    num: 29,
    quizId: 'span-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    start: 'France',
    end: 'Poland',
    sunday: true,
    avoid: 'Germany',
    perfect: 4,
    note: 'With Germany open this is a quick two hops. Closed, the road detours through the Alps and central Europe: Italy, Austria and Czechia before slipping into Poland.',
  },
  {
    num: 30,
    quizId: 'span-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    start: 'France',
    end: 'Serbia',
    perfect: 4,
    note: 'East across the middle of Europe: Italy, then Austria and Hungary, which open the door to the Balkans and Serbia.',
  },
  {
    num: 31,
    quizId: 'span-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    start: 'Kyrgyzstan',
    end: 'Jordan',
    perfect: 5,
    note: "One shortest road runs through Kazakhstan, Turkmenistan, Iran and Iraq before reaching Jordan.",
  },
  {
    num: 32,
    quizId: 'span-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    start: 'Slovenia',
    end: 'Cambodia',
    perfect: 6,
    note: "One shortest road runs through Hungary, Ukraine, Russia, China and Laos before reaching Cambodia.",
  },
  {
    num: 33,
    quizId: 'span-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    start: 'San Marino',
    end: 'Andorra',
    perfect: 3,
    note: "One shortest road runs through Italy and France before reaching Andorra.",
  },
  {
    num: 34,
    quizId: 'span-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    start: 'Pakistan',
    end: 'Bosnia and Herzegovina',
    perfect: 5,
    note: "One shortest road runs through Iran, Turkey, Bulgaria and Serbia before reaching Bosnia and Herzegovina.",
  },
  {
    num: 35,
    quizId: 'span-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    start: 'San Marino',
    end: 'Serbia',
    perfect: 4,
    note: "One shortest road runs through Italy, Austria and Hungary before reaching Serbia.",
  },
  {
    num: 36,
    quizId: 'span-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    start: 'Armenia',
    end: 'Vietnam',
    sunday: true,
    avoid: 'China',
    perfect: 6,
    note: "One shortest road runs through Iran, Pakistan, India, Myanmar and Laos before reaching Vietnam. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 37,
    quizId: 'span-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    start: 'Mongolia',
    end: 'Albania',
    perfect: 5,
    note: "One shortest road runs through Russia, Georgia, Turkey and Greece before reaching Albania.",
  },
  {
    num: 38,
    quizId: 'span-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    start: 'Kazakhstan',
    end: 'Liechtenstein',
    perfect: 5,
    note: "One shortest road runs through Russia, Poland, Germany and Switzerland before reaching Liechtenstein.",
  },
  {
    num: 39,
    quizId: 'span-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    start: 'Lithuania',
    end: 'Laos',
    perfect: 3,
    note: "One shortest road runs through Russia and China before reaching Laos.",
  },
  {
    num: 40,
    quizId: 'span-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    start: 'Croatia',
    end: 'South Korea',
    perfect: 5,
    note: "One shortest road runs through Hungary, Ukraine, Russia and North Korea before reaching South Korea.",
  },
  {
    num: 41,
    quizId: 'span-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    start: 'Serbia',
    end: 'Mongolia',
    perfect: 4,
    note: "One shortest road runs through Hungary, Ukraine and Russia before reaching Mongolia.",
  },
  {
    num: 42,
    quizId: 'span-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    start: 'Azerbaijan',
    end: 'Croatia',
    perfect: 4,
    note: "One shortest road runs through Russia, Ukraine and Hungary before reaching Croatia.",
  },
  {
    num: 43,
    quizId: 'span-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    start: 'Luxembourg',
    end: 'Sweden',
    sunday: true,
    avoid: 'Poland',
    perfect: 7,
    note: "One shortest road runs through Germany, Austria, Slovakia, Ukraine, Russia and Finland before reaching Sweden. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 44,
    quizId: 'span-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    start: 'Qatar',
    end: 'Sudan',
    perfect: 5,
    note: "One shortest road runs through Saudi Arabia, Jordan, Israel and Egypt before reaching Sudan.",
  },
  {
    num: 45,
    quizId: 'span-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    start: 'Bhutan',
    end: 'Serbia',
    perfect: 5,
    note: "One shortest road runs through China, Russia, Ukraine and Hungary before reaching Serbia.",
  },
  {
    num: 46,
    quizId: 'span-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    start: 'Austria',
    end: 'Jordan',
    perfect: 6,
    note: "One shortest road runs through Hungary, Romania, Bulgaria, Turkey and Iraq before reaching Jordan.",
  },
  {
    num: 47,
    quizId: 'span-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    start: 'Oman',
    end: 'Estonia',
    perfect: 6,
    note: "One shortest road runs through Saudi Arabia, Iraq, Turkey, Georgia and Russia before reaching Estonia.",
  },
  {
    num: 48,
    quizId: 'span-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    start: 'Cambodia',
    end: 'Hungary',
    perfect: 5,
    note: "One shortest road runs through Laos, China, Russia and Ukraine before reaching Hungary.",
  },
  {
    num: 49,
    quizId: 'span-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    start: 'Myanmar',
    end: 'Belgium',
    perfect: 5,
    note: "One shortest road runs through China, Russia, Poland and Germany before reaching Belgium.",
  },
  {
    num: 50,
    quizId: 'span-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    start: 'Denmark',
    end: 'Turkmenistan',
    sunday: true,
    avoid: 'Poland',
    perfect: 7,
    note: "One shortest road runs through Germany, Austria, Slovakia, Ukraine, Russia and Kazakhstan before reaching Turkmenistan. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 51,
    quizId: 'span-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    start: 'Qatar',
    end: 'Ukraine',
    perfect: 6,
    note: "One shortest road runs through Saudi Arabia, Iraq, Turkey, Bulgaria and Romania before reaching Ukraine.",
  },
  {
    num: 52,
    quizId: 'span-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    start: 'Ethiopia',
    end: 'Greece',
    perfect: 6,
    note: "One shortest road runs through Sudan, Egypt, Israel, Syria and Turkey before reaching Greece.",
  },
  {
    num: 53,
    quizId: 'span-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    start: 'Uzbekistan',
    end: 'Ukraine',
    perfect: 3,
    note: "One shortest road runs through Kazakhstan and Russia before reaching Ukraine.",
  },
  {
    num: 54,
    quizId: 'span-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    start: 'Finland',
    end: 'Belgium',
    perfect: 4,
    note: "One shortest road runs through Russia, Poland and Germany before reaching Belgium.",
  },
  {
    num: 55,
    quizId: 'span-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    start: 'Democratic Republic of the Congo',
    end: 'Somalia',
    perfect: 3,
    note: "One shortest road runs through South Sudan and Kenya before reaching Somalia.",
  },
  {
    num: 56,
    quizId: 'span-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    start: 'China',
    end: 'United Arab Emirates',
    perfect: 5,
    note: "One shortest road runs through Afghanistan, Iran, Iraq and Saudi Arabia before reaching United Arab Emirates.",
  },
  {
    num: 57,
    quizId: 'span-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    start: 'Ukraine',
    end: 'Georgia',
    sunday: true,
    avoid: 'Russia',
    perfect: 4,
    note: "One shortest road runs through Romania, Bulgaria and Turkey before reaching Georgia. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 58,
    quizId: 'span-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    start: 'Belgium',
    end: 'Iraq',
    perfect: 6,
    note: "One shortest road runs through Germany, Poland, Russia, Georgia and Turkey before reaching Iraq.",
  },
  {
    num: 59,
    quizId: 'span-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    start: 'Lebanon',
    end: 'Belarus',
    perfect: 5,
    note: "One shortest road runs through Syria, Turkey, Georgia and Russia before reaching Belarus.",
  },
  {
    num: 60,
    quizId: 'span-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    start: 'Turkey',
    end: 'Slovenia',
    perfect: 4,
    note: "One shortest road runs through Bulgaria, Serbia and Hungary before reaching Slovenia.",
  },
  {
    num: 61,
    quizId: 'span-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    start: 'Cameroon',
    end: 'Tanzania',
    perfect: 3,
    note: "One shortest road runs through Central African Republic and Democratic Republic of the Congo before reaching Tanzania.",
  },
  {
    num: 62,
    quizId: 'span-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    start: 'Albania',
    end: 'Austria',
    perfect: 4,
    note: "One shortest road runs through Montenegro, Croatia and Hungary before reaching Austria.",
  },
  {
    num: 63,
    quizId: 'span-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    start: 'Estonia',
    end: 'Slovakia',
    perfect: 3,
    note: "One shortest road runs through Russia and Poland before reaching Slovakia.",
  },
  {
    num: 64,
    quizId: 'span-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    start: 'Myanmar',
    end: 'Hungary',
    sunday: true,
    avoid: 'Russia',
    perfect: 7,
    note: "One shortest road runs through India, Pakistan, Iran, Turkey, Bulgaria and Serbia before reaching Hungary. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 65,
    quizId: 'span-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    start: 'Myanmar',
    end: 'Papua New Guinea',
    perfect: 4,
    note: "One shortest road runs through Thailand, Malaysia and Indonesia before reaching Papua New Guinea.",
  },
  {
    num: 66,
    quizId: 'span-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    start: 'Uzbekistan',
    end: 'Oman',
    perfect: 5,
    note: "One shortest road runs through Afghanistan, Iran, Iraq and Saudi Arabia before reaching Oman.",
  },
  {
    num: 67,
    quizId: 'span-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    start: 'Andorra',
    end: 'Laos',
    perfect: 6,
    note: "One shortest road runs through France, Germany, Poland, Russia and China before reaching Laos.",
  },
  {
    num: 68,
    quizId: 'span-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    start: 'Armenia',
    end: 'Romania',
    perfect: 3,
    note: "One shortest road runs through Turkey and Bulgaria before reaching Romania.",
  },
  {
    num: 69,
    quizId: 'span-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    start: 'South Sudan',
    end: 'Botswana',
    perfect: 4,
    note: "One shortest road runs through Democratic Republic of the Congo, Zambia and Namibia before reaching Botswana.",
  },
  {
    num: 70,
    quizId: 'span-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    start: 'Belgium',
    end: 'India',
    perfect: 5,
    note: "One shortest road runs through Germany, Poland, Russia and China before reaching India.",
  },
  {
    num: 71,
    quizId: 'span-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    start: 'Georgia',
    end: 'Greece',
    sunday: true,
    avoid: 'Turkey',
    perfect: 5,
    note: "One shortest road runs through Russia, Ukraine, Romania and Bulgaria before reaching Greece. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 72,
    quizId: 'span-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    start: 'Norway',
    end: 'Egypt',
    perfect: 6,
    note: "One shortest road runs through Russia, Georgia, Turkey, Syria and Israel before reaching Egypt.",
  },
  {
    num: 73,
    quizId: 'span-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    start: 'Qatar',
    end: 'Bosnia and Herzegovina',
    perfect: 6,
    note: "One shortest road runs through Saudi Arabia, Iraq, Turkey, Bulgaria and Serbia before reaching Bosnia and Herzegovina.",
  },
  {
    num: 74,
    quizId: 'span-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    start: 'Georgia',
    end: 'Montenegro',
    perfect: 4,
    note: "One shortest road runs through Turkey, Greece and Albania before reaching Montenegro.",
  },
  {
    num: 75,
    quizId: 'span-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    start: 'Romania',
    end: 'Norway',
    perfect: 3,
    note: "One shortest road runs through Ukraine and Russia before reaching Norway.",
  },
  {
    num: 76,
    quizId: 'span-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    start: 'Spain',
    end: 'North Macedonia',
    perfect: 6,
    note: "One shortest road runs through France, Italy, Austria, Hungary and Serbia before reaching North Macedonia.",
  },
  {
    num: 77,
    quizId: 'span-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    start: 'Saudi Arabia',
    end: 'Germany',
    perfect: 6,
    note: "One shortest road runs through Iraq, Turkey, Georgia, Russia and Poland before reaching Germany.",
  },
  {
    num: 78,
    quizId: 'span-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    start: 'Syria',
    end: 'Uganda',
    sunday: true,
    avoid: 'South Sudan',
    perfect: 6,
    note: "One shortest road runs through Israel, Egypt, Sudan, Central African Republic and Democratic Republic of the Congo before reaching Uganda. With the closed country open the crossing is shorter, so the detour is the whole puzzle.",
  },
  {
    num: 79,
    quizId: 'span-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    start: 'Thailand',
    end: 'Pakistan',
    perfect: 3,
    note: "One shortest road runs through Myanmar and India before reaching Pakistan.",
  },
  {
    num: 80,
    quizId: 'span-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    start: 'Iraq',
    end: 'Uganda',
    perfect: 6,
    note: "One shortest road runs through Syria, Israel, Egypt, Sudan and South Sudan before reaching Uganda.",
  },
  {
    num: 81,
    quizId: 'span-9-30-26',
    live: '2026-09-30',
    dateLabel: 'September 30, 2026',
    start: 'Eritrea',
    end: 'Bangladesh',
    perfect: 9,
    note: 'There are 3 shortest roads, and all of them pass through Sudan and Egypt.',
  },
  {
    num: 82,
    quizId: 'span-10-1-26',
    live: '2026-10-01',
    dateLabel: 'October 1, 2026',
    start: 'Rwanda',
    end: 'Sierra Leone',
    perfect: 7,
    note: 'Exactly one shortest road exists, and every country on it is unavoidable.',
  },
  {
    num: 83,
    quizId: 'span-10-2-26',
    live: '2026-10-02',
    dateLabel: 'October 2, 2026',
    start: 'Democratic Republic of the Congo',
    end: 'Latvia',
    perfect: 9,
    note: 'There are 4 shortest roads, and all of them pass through Sudan and Egypt.',
  },
  {
    num: 84,
    quizId: 'span-10-3-26',
    live: '2026-10-03',
    dateLabel: 'October 3, 2026',
    start: 'Kazakhstan',
    end: 'Oman',
    perfect: 5,
    note: 'Exactly one shortest road exists, and every country on it is unavoidable.',
  },
  {
    num: 85,
    quizId: 'span-10-4-26',
    live: '2026-10-04',
    dateLabel: 'October 4, 2026',
    sunday: true,
    start: 'Germany',
    end: 'United Arab Emirates',
    via: 'Tajikistan',
    perfect: 9,
    note: 'Routing through Tajikistan makes it 9 hops instead of 7.',
  },
  {
    num: 86,
    quizId: 'span-10-5-26',
    live: '2026-10-05',
    dateLabel: 'October 5, 2026',
    start: 'Uzbekistan',
    end: 'Central African Republic',
    perfect: 8,
    note: 'There are 6 shortest roads, and all of them pass through Iran and Israel.',
  },
  {
    num: 87,
    quizId: 'span-10-6-26',
    live: '2026-10-06',
    dateLabel: 'October 6, 2026',
    start: 'Chad',
    end: 'Croatia',
    perfect: 8,
    note: 'There are 2 shortest roads, and all of them pass through Egypt and Israel.',
  },
  {
    num: 88,
    quizId: 'span-10-7-26',
    live: '2026-10-07',
    dateLabel: 'October 7, 2026',
    start: 'Kosovo',
    end: 'Andorra',
    perfect: 6,
    note: 'There are 6 shortest roads, and every one of them passes through France.',
  },
  {
    num: 89,
    quizId: 'span-10-8-26',
    live: '2026-10-08',
    dateLabel: 'October 8, 2026',
    start: 'Liechtenstein',
    end: 'Brunei',
    perfect: 9,
    note: 'There are 12 shortest roads, and all of them pass through Russia and China.',
  },
  {
    num: 90,
    quizId: 'span-10-9-26',
    live: '2026-10-09',
    dateLabel: 'October 9, 2026',
    start: 'Bulgaria',
    end: 'South Korea',
    perfect: 5,
    note: 'There are 3 shortest roads, and all of them pass through Russia and North Korea.',
  },
  {
    num: 91,
    quizId: 'span-10-10-26',
    live: '2026-10-10',
    dateLabel: 'October 10, 2026',
    start: 'North Macedonia',
    end: 'Malaysia',
    perfect: 8,
    note: 'There are 24 shortest roads, and every one of them passes through Thailand.',
  },
  {
    num: 92,
    quizId: 'span-10-11-26',
    live: '2026-10-11',
    dateLabel: 'October 11, 2026',
    sunday: true,
    start: 'Bangladesh',
    end: 'Romania',
    avoid: 'Ukraine',
    perfect: 6,
    note: 'With Ukraine closed the road is 6 hops instead of 5. Exactly one shortest road exists, and every country on it is unavoidable.',
  },
  {
    num: 93,
    quizId: 'span-10-12-26',
    live: '2026-10-12',
    dateLabel: 'October 12, 2026',
    start: 'Lebanon',
    end: 'Portugal',
    perfect: 9,
    note: 'There are 2 shortest roads, and all of them pass through Syria and Turkey.',
  },
  {
    num: 94,
    quizId: 'span-10-13-26',
    live: '2026-10-13',
    dateLabel: 'October 13, 2026',
    start: 'Myanmar',
    end: 'Yemen',
    perfect: 6,
    note: 'There are 3 shortest roads, and all of them pass through Iran and Iraq.',
  },
  {
    num: 95,
    quizId: 'span-10-14-26',
    live: '2026-10-14',
    dateLabel: 'October 14, 2026',
    start: 'Kosovo',
    end: 'Yemen',
    perfect: 6,
    note: 'There are 4 shortest roads, and all of them pass through Turkey and Iraq.',
  },
  {
    num: 96,
    quizId: 'span-10-15-26',
    live: '2026-10-15',
    dateLabel: 'October 15, 2026',
    start: 'Namibia',
    end: 'Turkey',
    perfect: 8,
    note: 'There are 5 shortest roads, and all of them pass through Sudan and Egypt.',
  },
  {
    num: 97,
    quizId: 'span-10-16-26',
    live: '2026-10-16',
    dateLabel: 'October 16, 2026',
    start: 'Czechia',
    end: 'Kuwait',
    perfect: 6,
    note: 'There are 3 shortest roads, and all of them pass through Poland and Russia.',
  },
  {
    num: 98,
    quizId: 'span-10-17-26',
    live: '2026-10-17',
    dateLabel: 'October 17, 2026',
    start: 'Thailand',
    end: 'Slovenia',
    perfect: 6,
    note: 'There are 2 shortest roads, and all of them pass through China and Russia.',
  },
  {
    num: 99,
    quizId: 'span-10-18-26',
    live: '2026-10-18',
    dateLabel: 'October 18, 2026',
    sunday: true,
    start: 'Mali',
    end: 'Botswana',
    avoid: 'Niger',
    perfect: 8,
    note: 'With Niger closed the road is 8 hops instead of 7. There are 13 shortest roads of 8 hops, with no single country common to them all.',
  },
  {
    num: 100,
    quizId: 'span-10-19-26',
    live: '2026-10-19',
    dateLabel: 'October 19, 2026',
    start: 'Cameroon',
    end: 'Belarus',
    perfect: 9,
    note: 'There are 6 shortest roads, and all of them pass through Egypt and Israel.',
  },
  {
    num: 101,
    quizId: 'span-10-20-26',
    live: '2026-10-20',
    dateLabel: 'October 20, 2026',
    start: 'North Korea',
    end: 'Tunisia',
    perfect: 8,
    note: 'There are 2 shortest roads, and all of them pass through Russia and Turkey.',
  },
  {
    num: 102,
    quizId: 'span-10-21-26',
    live: '2026-10-21',
    dateLabel: 'October 21, 2026',
    start: 'Timor-Leste',
    end: 'Iraq',
    perfect: 8,
    note: 'There are 5 shortest roads, and all of them pass through Indonesia and Malaysia.',
  },
  {
    num: 103,
    quizId: 'span-10-22-26',
    live: '2026-10-22',
    dateLabel: 'October 22, 2026',
    start: 'Syria',
    end: 'Czechia',
    perfect: 5,
    note: 'There are 2 shortest roads, and all of them pass through Turkey and Russia.',
  },
  {
    num: 104,
    quizId: 'span-10-23-26',
    live: '2026-10-23',
    dateLabel: 'October 23, 2026',
    start: 'Kosovo',
    end: 'Tunisia',
    perfect: 8,
    note: 'There are 4 shortest roads, and all of them pass through Turkey and Syria.',
  },
  {
    num: 105,
    quizId: 'span-10-24-26',
    live: '2026-10-24',
    dateLabel: 'October 24, 2026',
    start: 'Serbia',
    end: 'Morocco',
    perfect: 8,
    note: 'Exactly one shortest road exists, and every country on it is unavoidable.',
  },
  {
    num: 106,
    quizId: 'span-10-25-26',
    live: '2026-10-25',
    dateLabel: 'October 25, 2026',
    sunday: true,
    start: 'South Africa',
    end: 'Senegal',
    avoid: 'Mali',
    perfect: 9,
    note: 'With Mali closed the road is 9 hops instead of 8. There are 29 shortest roads, and all of them pass through Algeria and Mauritania.',
  },
  {
    num: 107,
    quizId: 'span-10-26-26',
    live: '2026-10-26',
    dateLabel: 'October 26, 2026',
    start: 'Brunei',
    end: 'Turkey',
    perfect: 7,
    note: 'There are 9 shortest roads, and all of them pass through Malaysia and Thailand.',
  },
  {
    num: 108,
    quizId: 'span-10-27-26',
    live: '2026-10-27',
    dateLabel: 'October 27, 2026',
    start: 'Montenegro',
    end: 'Uzbekistan',
    perfect: 6,
    note: 'There are 7 shortest roads of 6 hops, with no single country common to them all.',
  },
  {
    num: 109,
    quizId: 'span-10-28-26',
    live: '2026-10-28',
    dateLabel: 'October 28, 2026',
    start: 'Monaco',
    end: 'Turkmenistan',
    perfect: 6,
    note: 'Exactly one shortest road exists, and every country on it is unavoidable.',
  },
  {
    num: 110,
    quizId: 'span-10-29-26',
    live: '2026-10-29',
    dateLabel: 'October 29, 2026',
    start: 'Timor-Leste',
    end: 'Moldova',
    perfect: 8,
    note: 'There are 2 shortest roads, and all of them pass through Indonesia and Malaysia.',
  },
  {
    num: 111,
    quizId: 'span-10-30-26',
    live: '2026-10-30',
    dateLabel: 'October 30, 2026',
    start: 'Nigeria',
    end: 'Ukraine',
    perfect: 9,
    note: 'There are 9 shortest roads, and all of them pass through Egypt and Israel.',
  },
  {
    num: 112,
    quizId: 'span-10-31-26',
    live: '2026-10-31',
    dateLabel: 'October 31, 2026',
    start: 'Tunisia',
    end: 'Mongolia',
    perfect: 8,
    note: 'There are 2 shortest roads, and all of them pass through Libya and Egypt.',
  },
  {
    num: 113,
    quizId: 'span-11-1-26',
    live: '2026-11-01',
    dateLabel: 'November 1, 2026',
    sunday: true,
    start: 'Luxembourg',
    end: 'United Arab Emirates',
    via: 'Mongolia',
    perfect: 10,
    note: 'Routing through Mongolia makes it 10 hops instead of 8.',
  },
  {
    num: 114,
    quizId: 'span-11-2-26',
    live: '2026-11-02',
    dateLabel: 'November 2, 2026',
    start: 'Botswana',
    end: 'Djibouti',
    perfect: 6,
    note: 'There are 11 shortest roads of 6 hops, with no single country common to them all.',
  },
  {
    num: 115,
    quizId: 'span-11-3-26',
    live: '2026-11-03',
    dateLabel: 'November 3, 2026',
    start: 'Germany',
    end: 'Bhutan',
    perfect: 4,
    note: 'One shortest road runs through Poland, Russia and China before reaching Bhutan.',
  },
  {
    num: 116,
    quizId: 'span-11-4-26',
    live: '2026-11-04',
    dateLabel: 'November 4, 2026',
    start: 'Syria',
    end: 'Sweden',
    perfect: 5,
    note: 'There are 4 shortest roads, and all of them pass through Turkey and Russia.',
  },
  {
    num: 117,
    quizId: 'span-11-5-26',
    live: '2026-11-05',
    dateLabel: 'November 5, 2026',
    start: 'Austria',
    end: 'Papua New Guinea',
    perfect: 9,
    note: 'There are 10 shortest roads, and all of them pass through Russia and China.',
  },
  {
    num: 118,
    quizId: 'span-11-6-26',
    live: '2026-11-06',
    dateLabel: 'November 6, 2026',
    start: 'Lebanon',
    end: 'Togo',
    perfect: 6,
    note: 'There are 2 shortest roads, and all of them pass through Israel and Egypt.',
  },
  {
    num: 119,
    quizId: 'span-11-7-26',
    live: '2026-11-07',
    dateLabel: 'November 7, 2026',
    start: 'Jordan',
    end: 'Myanmar',
    perfect: 5,
    note: 'There are 3 shortest roads, and all of them pass through Iraq and Iran.',
  },
  {
    num: 120,
    quizId: 'span-11-8-26',
    live: '2026-11-08',
    dateLabel: 'November 8, 2026',
    sunday: true,
    start: 'Ivory Coast',
    end: 'Bulgaria',
    avoid: 'Libya',
    perfect: 9,
    note: 'With Libya closed the road is 9 hops instead of 8. There are 2 shortest roads, and all of them pass through Niger and Chad.',
  },
  {
    num: 121,
    quizId: 'span-11-9-26',
    live: '2026-11-09',
    dateLabel: 'November 9, 2026',
    start: 'Pakistan',
    end: 'Algeria',
    perfect: 7,
    note: 'There are 3 shortest roads, and all of them pass through Iran and Israel.',
  },
  {
    num: 122,
    quizId: 'span-11-10-26',
    live: '2026-11-10',
    dateLabel: 'November 10, 2026',
    start: 'Croatia',
    end: 'Central African Republic',
    perfect: 8,
    note: 'One shortest road runs through Serbia, Bulgaria, Turkey, Syria, Israel, Egypt and Sudan before reaching Central African Republic.',
  },
  {
    num: 123,
    quizId: 'span-11-11-26',
    live: '2026-11-11',
    dateLabel: 'November 11, 2026',
    start: 'Cambodia',
    end: 'Turkey',
    perfect: 5,
    note: 'There are 8 shortest roads, and every one of them passes through China.',
  },
  {
    num: 124,
    quizId: 'span-11-12-26',
    live: '2026-11-12',
    dateLabel: 'November 12, 2026',
    start: 'Kyrgyzstan',
    end: 'Greece',
    perfect: 5,
    note: 'There are 10 shortest roads, and every one of them passes through Turkey.',
  },
  {
    num: 125,
    quizId: 'span-11-13-26',
    live: '2026-11-13',
    dateLabel: 'November 13, 2026',
    start: 'Armenia',
    end: 'Ghana',
    perfect: 8,
    note: 'One shortest road runs through Turkey, Syria, Israel, Egypt, Libya, Niger and Burkina Faso before reaching Ghana.',
  },
  {
    num: 126,
    quizId: 'span-11-14-26',
    live: '2026-11-14',
    dateLabel: 'November 14, 2026',
    start: 'Niger',
    end: 'Bosnia and Herzegovina',
    perfect: 8,
    note: 'One shortest road runs through Libya, Egypt, Israel, Syria, Turkey, Bulgaria and Serbia before reaching Bosnia and Herzegovina.',
  },
  {
    num: 127,
    quizId: 'span-11-15-26',
    live: '2026-11-15',
    dateLabel: 'November 15, 2026',
    sunday: true,
    start: 'Cameroon',
    end: 'Qatar',
    via: 'Iraq',
    perfect: 8,
    note: 'Routing through Iraq makes it 8 hops instead of 7.',
  },
  {
    num: 128,
    quizId: 'span-11-16-26',
    live: '2026-11-16',
    dateLabel: 'November 16, 2026',
    start: 'Thailand',
    end: 'United Arab Emirates',
    perfect: 7,
    note: 'There are 5 shortest roads, and all of them pass through Iran and Iraq.',
  },
  {
    num: 129,
    quizId: 'span-11-17-26',
    live: '2026-11-17',
    dateLabel: 'November 17, 2026',
    start: 'Latvia',
    end: 'Republic of the Congo',
    perfect: 9,
    note: 'There are 2 shortest roads, and all of them pass through Russia and Turkey.',
  },
  {
    num: 130,
    quizId: 'span-11-18-26',
    live: '2026-11-18',
    dateLabel: 'November 18, 2026',
    start: 'Morocco',
    end: 'Albania',
    perfect: 8,
    note: 'One shortest road runs through Algeria, Libya, Egypt, Israel, Syria, Turkey and Greece before reaching Albania.',
  },
  {
    num: 131,
    quizId: 'span-11-19-26',
    live: '2026-11-19',
    dateLabel: 'November 19, 2026',
    start: 'Eritrea',
    end: 'Serbia',
    perfect: 7,
    note: 'One shortest road runs through Sudan, Egypt, Israel, Syria, Turkey and Bulgaria before reaching Serbia.',
  },
  {
    num: 132,
    quizId: 'span-11-20-26',
    live: '2026-11-20',
    dateLabel: 'November 20, 2026',
    start: 'Tanzania',
    end: 'Oman',
    perfect: 8,
    note: 'There are 5 shortest roads, and all of them pass through Sudan and Egypt.',
  },
  {
    num: 133,
    quizId: 'span-11-21-26',
    live: '2026-11-21',
    dateLabel: 'November 21, 2026',
    start: 'Namibia',
    end: 'Libya',
    perfect: 5,
    note: 'There are 9 shortest roads of 5 hops, with no single country common to them all.',
  },
  {
    num: 134,
    quizId: 'span-11-22-26',
    live: '2026-11-22',
    dateLabel: 'November 22, 2026',
    sunday: true,
    start: 'Angola',
    end: 'Djibouti',
    avoid: 'Democratic Republic of the Congo',
    perfect: 5,
    note: 'With Democratic Republic of the Congo closed the road is 5 hops instead of 4. There are 5 shortest roads of 5 hops, with no single country common to them all.',
  },
  {
    num: 135,
    quizId: 'span-11-23-26',
    live: '2026-11-23',
    dateLabel: 'November 23, 2026',
    start: 'Gabon',
    end: 'Bulgaria',
    perfect: 8,
    note: 'There are 4 shortest roads, and all of them pass through Egypt and Israel.',
  },
  {
    num: 136,
    quizId: 'span-11-24-26',
    live: '2026-11-24',
    dateLabel: 'November 24, 2026',
    start: 'Netherlands',
    end: 'Brunei',
    perfect: 8,
    note: 'There are 2 shortest roads, and all of them pass through Germany and Poland.',
  },
  {
    num: 137,
    quizId: 'span-11-25-26',
    live: '2026-11-25',
    dateLabel: 'November 25, 2026',
    start: 'Papua New Guinea',
    end: 'Finland',
    perfect: 7,
    note: 'There are 2 shortest roads, and all of them pass through Indonesia and Malaysia.',
  },
  {
    num: 138,
    quizId: 'span-11-26-26',
    live: '2026-11-26',
    dateLabel: 'November 26, 2026',
    start: 'Zimbabwe',
    end: 'Liberia',
    perfect: 8,
    note: 'There are 3 shortest roads, and all of them pass through Zambia and Democratic Republic of the Congo.',
  },
  {
    num: 139,
    quizId: 'span-11-27-26',
    live: '2026-11-27',
    dateLabel: 'November 27, 2026',
    start: 'Thailand',
    end: 'Turkey',
    perfect: 5,
    note: 'There are 9 shortest roads of 5 hops, with no single country common to them all.',
  },
  {
    num: 140,
    quizId: 'span-11-28-26',
    live: '2026-11-28',
    dateLabel: 'November 28, 2026',
    start: 'Qatar',
    end: 'Uzbekistan',
    perfect: 5,
    note: 'There are 2 shortest roads, and all of them pass through Saudi Arabia and Iraq.',
  },
  {
    num: 141,
    quizId: 'span-11-29-26',
    live: '2026-11-29',
    dateLabel: 'November 29, 2026',
    sunday: true,
    start: 'Chad',
    end: 'Sierra Leone',
    via: 'Mauritania',
    perfect: 6,
    note: 'Routing through Mauritania makes it 6 hops instead of 4.',
  },
  {
    num: 142,
    quizId: 'span-11-30-26',
    live: '2026-11-30',
    dateLabel: 'November 30, 2026',
    start: 'North Korea',
    end: 'United Arab Emirates',
    perfect: 6,
    note: 'There are 5 shortest roads, and all of them pass through Iraq and Saudi Arabia.',
  },
];
