// Shoe — the playout proofs behind every banked par and ace.
//
// Par and ace are not formulas. Par is basic strategy played blind on the
// day's shoe, and ace is the best of 120 blind runs — and these are the actual
// decision lines, one string of H / S / D per hand in the order the decisions
// were made (a hand settled by a natural has the empty string).
//
// This file exists so scripts/verify-shoe.mjs can replay both claims through
// the real rules engine (app/shoe/rules.js) rather than trusting a number in
// the bank. It is deliberately SEPARATE from puzzles.js and imported by
// nothing the browser loads, because the ace line is an excellent round on a
// live shoe and shipping it would hand today's players a solution.
export const PROOFS = {
  'shoe-8-21-26': { par: ["S","S","","H","H"], ace: ["S","D","","D","HS"] },
  'shoe-8-22-26': { par: ["H","S","HS","HH","S"], ace: ["H","S","S","D","S"] },
  'shoe-8-23-26': { par: ["S","HHS","HS","HS","D","HH","S"], ace: ["S","D","D","S","HHHS","D","S"] },
  'shoe-8-24-26': { par: ["S","HS","HS","S","S"], ace: ["S","HS","HS","S","D"] },
  'shoe-8-25-26': { par: ["HHS","S","S","S","S"], ace: ["HHS","S","D","D","D"] },
  'shoe-8-26-26': { par: ["S","HHS","HH","H","HH"], ace: ["S","HHH","D","S","D"] },
  'shoe-8-27-26': { par: ["S","HHH","D","S","D"], ace: ["S","HS","D","","S"] },
  'shoe-8-28-26': { par: ["S","HS","S","","S"], ace: ["S","HHS","S","","S"] },
  'shoe-8-29-26': { par: ["S","S","","","HS"], ace: ["D","S","","","D"] },
  'shoe-8-30-26': { par: ["HH","HH","S","D","S","S","S"], ace: ["D","S","H","S","S","D","S"] },
  'shoe-8-31-26': { par: ["H","S","HS","HH","S"], ace: ["S","HH","HS","D","S"] },
  'shoe-9-1-26': { par: ["S","HHS","S","S",""], ace: ["D","HHS","S","D","HS"] },
  'shoe-9-2-26': { par: ["S","S","S","S","S"], ace: ["D","S","S","HS","S"] },
  'shoe-9-3-26': { par: ["HH","HS","S","S","S"], ace: ["S","S","D","D","HS"] },
  'shoe-9-4-26': { par: ["S","S","HHS","H","S"], ace: ["S","S","S","D","D"] },
  'shoe-9-5-26': { par: ["HS","D","H","HS","HS"], ace: ["D","S","H","HS","HS"] },
  'shoe-9-6-26': { par: ["HS","S","S","D","D","S","H"], ace: ["HS","S","S","D","S","HS","H"] },
  'shoe-9-7-26': { par: ["D","HHHHS","HHS","HS","HH"], ace: ["D","HHHHS","HHH","S","S"] },
  'shoe-9-8-26': { par: ["S","S","HH","S","HS"], ace: ["S","S","D","HS","S"] },
  'shoe-9-9-26': { par: ["H","HH","D","HHH","D"], ace: ["D","S","D","HHH","D"] },
  'shoe-9-10-26': { par: ["S","S","HS","HH",""], ace: ["D","","HH","S",""] },
  'shoe-9-11-26': { par: ["S","","H","H","S"], ace: ["S","","S","S","D"] },
  'shoe-9-12-26': { par: ["HH","S","HHS","HH","S"], ace: ["S","","S","H","S"] },
  'shoe-9-13-26': { par: ["S","","S","HH","S","S","S"], ace: ["S","","S","D","S","S","S"] },
  'shoe-9-14-26': { par: ["HHS","H","S","S","HH"], ace: ["S","","D","","S"] },
  'shoe-9-15-26': { par: ["HHS","HS","S","S","HHS"], ace: ["HHS","D","S","S","D"] },
  'shoe-9-16-26': { par: ["HS","HHH","S","HS","S"], ace: ["S","S","D","S","S"] },
  'shoe-9-17-26': { par: ["S","S","HH","S","S"], ace: ["D","HHS","S","HH","D"] },
  'shoe-9-18-26': { par: ["HS","S","HHS","S","S"], ace: ["HS","HS","D","H","D"] },
  'shoe-9-19-26': { par: ["S","S","S","S","HHS"], ace: ["S","S","S","HH","D"] },
  'shoe-9-20-26': { par: ["HS","D","HS","HS","S","S","S"], ace: ["D","D","HS","HS","S","H","S"] },
  'shoe-9-21-26': { par: ["","HS","","S","S"], ace: ["","HH","S","D","S"] },
  'shoe-9-22-26': { par: ["S","D","","H","HS"], ace: ["S","D","","S","S"] },
  'shoe-9-23-26': { par: ["S","S","S","S","HH"], ace: ["S","S","D","HHS","D"] },
  'shoe-9-24-26': { par: ["S","HHH","D","S","HS"], ace: ["S","D","HS","S","HS"] },
  'shoe-9-25-26': { par: ["S","S","S","HS","D"], ace: ["HS","S","D","D","H"] },
  'shoe-9-26-26': { par: ["HH","D","HS","HHS","H"], ace: ["HH","D","HS","D","S"] },
  'shoe-9-27-26': { par: ["HHH","S","HS","H","S","HH","S"], ace: ["S","","D","H","HS","HHS","D"] },
  'shoe-9-28-26': { par: ["HHS","S","S","S","HS"], ace: ["D","HS","HS","S",""] },
  'shoe-9-29-26': { par: ["HH","HH","S","HS","S"], ace: ["HH","HH","D","H","HS"] },
  'shoe-9-30-26': { par: ["S","D","S","HH","S","S","S","HS","S","S"], ace: ["S","D","S","HH","S","S","S","S","D","S"] },
  'shoe-10-1-26': { par: ["S","S","D","S","HS","H","S","HH","HS","S"], ace: ["S","S","D","S","S","D","S","HS","HS","S"] },
  'shoe-10-2-26': { par: ["HS","D","S","","S","S","HS","S","HS","S"], ace: ["HS","HHS","HS","","HH","S","HHS","HS","S","S"] },
  'shoe-10-3-26': { par: ["HHH","H","S","HS","HS","HS","H","S","S","S"], ace: ["HHH","H","S","HS","HS","S","HS","S","S","HS"] },
  'shoe-10-4-26': { par: ["HS","HHS","H","S","HH","S","","","D","S","HS","D","S","HHS"], ace: ["D","HHHS","H","D","S","HHS","","D","","S","HHS","D","S","HHS"] },
  'shoe-10-5-26': { par: ["D","S","HS","HHS","S","D","S","S","HS","HHHS"], ace: ["HS","S","HS","D","S","D","S","S","HS","HHHS"] },
  'shoe-10-6-26': { par: ["D","HHS","D","S","","S","","S","H","H"], ace: ["D","HHH","D","D","","D","","S","S","S"] },
  'shoe-10-7-26': { par: ["HS","HH","HHHS","HHS","S","H","H","HHS","S",""], ace: ["HS","D","HHHS","HHS","D","HS","S","HHS","S",""] },
  'shoe-10-8-26': { par: ["HHS","S","S","HHS","S","D","D","S","H","S"], ace: ["S","D","D","S","S","D","D","S","H","S"] },
  'shoe-10-9-26': { par: ["S","HHS","D","S","HS","S","S","S","S","S"], ace: ["S","D","D","S","S","S","HHS","D","D","S"] },
  'shoe-10-10-26': { par: ["H","HHS","S","S","H","D","H","HHHS","HHS",""], ace: ["H","HHS","S","S","H","D","H","HHHH","S","S"] },
  'shoe-10-11-26': { par: ["H","HS","S","D","D","D","HHS","S","HHH","","D","H","S","S"], ace: ["S","HS","S","D","D","HH","HHH","S","HHH","","D","H","S","S"] },
  'shoe-10-12-26': { par: ["S","HS","S","S","HHH","S","S","HS","D","S"], ace: ["H","HS","S","D","S","S","S","D","D","S"] },
  'shoe-10-13-26': { par: ["S","S","D","S","H","H","HH","HH","S","S"], ace: ["S","S","D","HS","S","HS","D","S","D","S"] },
  'shoe-10-14-26': { par: ["H","D","S","S","S","D","S","S","HS","S"], ace: ["S","D","S","S","S","D","S","D","S","HS"] },
  'shoe-10-15-26': { par: ["","S","S","D","HH","HHS","HS","D","HHS","HS"], ace: ["","S","S","D","D","HHS","HS","D","HHS","HS"] },
  'shoe-10-16-26': { par: ["S","S","S","HH","S","S","HS","D","S","H"], ace: ["S","S","S","HH","HS","S","S","D","HS","D"] },
  'shoe-10-17-26': { par: ["S","S","S","S","H","S","HS","HS","HS","H"], ace: ["S","S","S","S","H","S","HS","HHH","D","S"] },
  'shoe-10-18-26': { par: ["HS","H","S","D","H","HHHHS","S","S","D","S","S","S","HHH","S"], ace: ["HS","H","S","D","H","HHHHS","S","S","D","S","D","S","D","S"] },
  'shoe-10-19-26': { par: ["HS","D","S","HH","S","H","","H","D","HS"], ace: ["S","D","S","HH","S","H","","H","D","D"] },
  'shoe-10-20-26': { par: ["S","S","D","D","S","S","HH","D","HS",""], ace: ["S","S","D","D","S","S","HS","HS","HS",""] },
  'shoe-10-21-26': { par: ["S","HS","S","S","D","HS","S","D","H","S"], ace: ["S","HH","HHS","D","HS","HS","","D","H","S"] },
  'shoe-10-22-26': { par: ["S","D","","D","H","S","H","HH","S","HH"], ace: ["S","D","","D","S","S","H","HH","S","D"] },
  'shoe-10-23-26': { par: ["S","S","HS","S","HS","","HS","","S","S"], ace: ["S","S","HHS","D","S","S","S","S","S","HH"] },
  'shoe-10-24-26': { par: ["S","","S","D","","","H","S","HH","S"], ace: ["S","","S","S","","D","D","D","S","HHS"] },
  'shoe-10-25-26': { par: ["S","S","H","HS","HHS","S","HS","HHHS","HS","HS","HHS","HS","HS","S"], ace: ["S","S","H","HS","HHS","S","HS","HHHS","D","HHS","S","S","S","S"] },
  'shoe-10-26-26': { par: ["H","","HS","S","S","HS","S","HH","S","D"], ace: ["H","","D","S","D","S","S","D","S",""] },
  'shoe-10-27-26': { par: ["HHHS","H","S","S","S","HHS","D","H","H","HHHHS"], ace: ["HHHS","H","S","S","HS","D","D","S","S","S"] },
  'shoe-10-28-26': { par: ["S","S","","S","HS","S","HS","S","","S"], ace: ["HS","S","","D","H","S","HS","S","","S"] },
  'shoe-10-29-26': { par: ["S","HHS","H","","S","HS","S","S","S","S"], ace: ["S","D","H","","HH","HH","D","D","HS","S"] },
  'shoe-10-30-26': { par: ["HS","H","HS","S","HS","H","HHS","HS","D","D"], ace: ["D","H","HS","S","HH","S","S","S","D","D"] },
  'shoe-10-31-26': { par: ["H","D","S","S","S","HS","HS","S","HH","D"], ace: ["H","D","D","S","S","HS","HS","S","HS","HS"] },
  'shoe-11-1-26': { par: ["HHS","S","","HH","HHS","","HS","H","S","S","HHHS","","D","HS"], ace: ["HHS","D","H","HS","S","D","HS","S","HS","S","HS","","D","HS"] },
  'shoe-11-2-26': { par: ["H","HS","S","","HS","S","HH","H","HHS","S"], ace: ["S","H","","D","S","HS","D","S","S","D"] },
  'shoe-11-3-26': { par: ["S","H","","HS","H","H","D","S","S","S"], ace: ["S","H","","HH","HS","S","HS","H","D","D"] },
  'shoe-11-4-26': { par: ["S","H","S","HS","HH","HH","S","D","S","D"], ace: ["S","H","H","S","S","S","HH","HHS","HS","D"] },
  'shoe-11-5-26': { par: ["HS","S","D","H","HS","H","S","","S",""], ace: ["D","D","S","S","S","S","HS","S","D",""] },
  'shoe-11-6-26': { par: ["D","HS","HH","H","HHS","","HS","HHS","S",""], ace: ["D","HH","","H","HHS","","HS","HHS","S",""] },
  'shoe-11-7-26': { par: ["HHS","HS","HS","HS","H","HS","H","","HS","HS"], ace: ["S","D","S","HS","H","HHS","S","","S","S"] },
  'shoe-11-8-26': { par: ["S","","S","S","S","S","S","H","S","HS","H","HS","S","S"], ace: ["S","","D","","D","S","HS","H","HH","S","S","D","S","HS"] },
  'shoe-11-9-26': { par: ["S","S","S","S","HHS","S","","S","HS","D"], ace: ["S","S","S","D","S","S","","HS","","D"] },
  'shoe-11-10-26': { par: ["HS","HHHS","S","S","S","HS","S","S","D","S"], ace: ["HS","HS","S","S","S","HHS","S","S","D","S"] },
  'shoe-11-11-26': { par: ["S","S","S","S","D","S","S","HHH","S","HS"], ace: ["S","S","S","S","D","D","S","HS","D","S"] },
  'shoe-11-12-26': { par: ["S","D","S","HHS","HS","S","S","","D","S"], ace: ["S","HH","HS","","HHS","S","S","","D","HS"] },
  'shoe-11-13-26': { par: ["S","D","S","HHS","S","H","S","D","",""], ace: ["S","D","S","HHS","H","D","H","D","H","S"] },
  'shoe-11-14-26': { par: ["HHH","S","S","S","H","D","HS","D","S","HHHH"], ace: ["D","S","S","S","S","D","HS","D","S","HHHS"] },
  'shoe-11-15-26': { par: ["S","H","D","HS","HS","HH","S","H","S","S","H","S","S",""], ace: ["S","H","D","S","","","HH","HS","S","HH","HH","HS","D","D"] },
  'shoe-11-16-26': { par: ["S","S","HS","S","S","HS","","HS","H","HH"], ace: ["S","S","HS","S","S","S","D","HS","S","HHH"] },
  'shoe-11-17-26': { par: ["","S","HHHS","H","S","D","S","S","D","HH"], ace: ["","S","HHS","HS","S","D","S","D","D","HS"] },
  'shoe-11-18-26': { par: ["S","HH","S","S","H","D","HS","D","","HS"], ace: ["S","D","S","S","H","D","D","D","","HS"] },
  'shoe-11-19-26': { par: ["S","S","D","HHS","S","S","H","S","HS","S"], ace: ["S","S","D","HHS","S","S","S","D","S","D"] },
};
