// Puzzle data for Sworn, the daily liars puzzle. Imported ONLY by the
// server page (app/sworn/page.js), which filters live<=today AND strips the
// solution before passing cases to the client — the client re-derives the
// unique (thief, liar-set) world from the testimony with its own brute-force
// solver, so the answer never ships over the wire.
//
// Every case was generated (seeded world -> one true-to-world statement per
// suspect -> uniqueness + §7a deducibility filters: parity propagation per
// candidate thief with a human-small case fan-out, NO search) and then
// independently re-verified. Weekdays seat 5 suspects; Sundays seat 6 for
// the Grand Inquest. Validate with scripts/verify-sworn.mjs after ANY edit.
//
// Statement schema (x = suspect index; speaker is the array position):
//   accuse {x}      "X is the thief."
//   innocent {x}    "X is innocent."
//   selfInnocent    "I am not the thief."
//   liar {x}        "X is lying."
//   honest {x}      "X is telling the truth."
//   thiefLiar       "The thief is lying."
//   thiefHonest     "The thief is telling the truth."
export const PUZZLES = [
  {
    num: 1, quizId: "sworn-7-18-26", live: "2026-07-18", dateLabel: "July 18, 2026", sunday: false,
    k: 2,
    suspects: ["Simon","Monty","Flora","Gideon","Rufus"],
    venue: "the Gilded Rooster tavern",
    stolen: "a purse of guineas",
    statements: [
      {"type":"innocent","x":4},
      {"type":"honest","x":3},
      {"type":"innocent","x":3},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[1,3]},
  },
  {
    num: 2, quizId: "sworn-7-19-26", live: "2026-07-19", dateLabel: "July 19, 2026", sunday: true,
    k: 3,
    suspects: ["Winnie","Lottie","Vera","Hazel","Felix","Monty"],
    venue: "the Saltmarsh docks",
    stolen: "a crate of silk",
    statements: [
      {"type":"accuse","x":3},
      {"type":"liar","x":5},
      {"type":"innocent","x":0},
      {"type":"liar","x":5},
      {"type":"honest","x":2},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[0,1,3]},
  },
  {
    num: 3, quizId: "sworn-7-20-26", live: "2026-07-20", dateLabel: "July 20, 2026", sunday: false,
    k: 2,
    suspects: ["Monty","Pearl","Bruno","Barnaby","Ezra"],
    venue: "Fenwick's bakery",
    stolen: "the prize sourdough starter",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":2},
      {"type":"honest","x":1},
      {"type":"honest","x":2},
      {"type":"liar","x":1},
    ],
    solution: {"thief":3,"liars":[0,4]},
  },
  {
    num: 4, quizId: "sworn-7-21-26", live: "2026-07-21", dateLabel: "July 21, 2026", sunday: false,
    k: 3,
    suspects: ["Flora","Nell","Edmund","Percy","Jasper"],
    venue: "the Old Mill counting-house",
    stolen: "the week's wages",
    statements: [
      {"type":"innocent","x":2},
      {"type":"thiefHonest"},
      {"type":"honest","x":3},
      {"type":"accuse","x":0},
      {"type":"liar","x":0},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 5, quizId: "sworn-7-22-26", live: "2026-07-22", dateLabel: "July 22, 2026", sunday: false,
    k: 2,
    suspects: ["Flora","Gideon","Winnie","Nell","Simon"],
    venue: "the Harbor Light inn",
    stolen: "a captain's sextant",
    statements: [
      {"type":"liar","x":4},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
      {"type":"liar","x":1},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":0,"liars":[0,3]},
  },
  {
    num: 6, quizId: "sworn-7-23-26", live: "2026-07-23", dateLabel: "July 23, 2026", sunday: false,
    k: 3,
    suspects: ["Gideon","Winnie","Ezra","Victor","Felix"],
    venue: "the Penny Farthing playhouse",
    stolen: "the leading lady's tiara",
    statements: [
      {"type":"honest","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":1},
      {"type":"accuse","x":1},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[2,3,4]},
  },
  {
    num: 7, quizId: "sworn-7-24-26", live: "2026-07-24", dateLabel: "July 24, 2026", sunday: false,
    k: 2,
    suspects: ["Opal","Mabel","Rufus","Hazel","Delia"],
    venue: "the Copperfield apothecary",
    stolen: "a jar of rare saffron",
    statements: [
      {"type":"accuse","x":2},
      {"type":"honest","x":3},
      {"type":"innocent","x":4},
      {"type":"innocent","x":0},
      {"type":"honest","x":1},
    ],
    solution: {"thief":4,"liars":[0,2]},
  },
  {
    num: 8, quizId: "sworn-7-25-26", live: "2026-07-25", dateLabel: "July 25, 2026", sunday: false,
    k: 3,
    suspects: ["Simon","Delia","Mabel","Hazel","Cyrus"],
    venue: "the Drover's Arms",
    stolen: "a champion racing pigeon",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":2},
      {"type":"liar","x":4},
      {"type":"innocent","x":2},
      {"type":"liar","x":2},
    ],
    solution: {"thief":3,"liars":[0,1,4]},
  },
  {
    num: 9, quizId: "sworn-7-26-26", live: "2026-07-26", dateLabel: "July 26, 2026", sunday: true,
    k: 3,
    suspects: ["Ezra","Gideon","Opal","Jasper","Cyrus","Nell"],
    venue: "the Lantern Street pawnshop",
    stolen: "a silver pocket watch",
    statements: [
      {"type":"accuse","x":2},
      {"type":"innocent","x":0},
      {"type":"accuse","x":3},
      {"type":"honest","x":5},
      {"type":"thiefHonest"},
      {"type":"liar","x":2},
    ],
    solution: {"thief":4,"liars":[0,2,4]},
  },
  {
    num: 10, quizId: "sworn-7-27-26", live: "2026-07-27", dateLabel: "July 27, 2026", sunday: false,
    k: 3,
    suspects: ["Iris","Mabel","Rosa","Amos","Percy"],
    venue: "the Wheatsheaf granary",
    stolen: "the harvest ledger",
    statements: [
      {"type":"honest","x":4},
      {"type":"innocent","x":4},
      {"type":"innocent","x":4},
      {"type":"liar","x":0},
      {"type":"liar","x":1},
    ],
    solution: {"thief":4,"liars":[1,2,3]},
  },
  {
    num: 11, quizId: "sworn-7-28-26", live: "2026-07-28", dateLabel: "July 28, 2026", sunday: false,
    k: 2,
    suspects: ["Clara","Hazel","Otis","Rosa","Lottie"],
    venue: "the Bellfound foundry",
    stolen: "the chapel's hand bell",
    statements: [
      {"type":"honest","x":2},
      {"type":"innocent","x":0},
      {"type":"accuse","x":3},
      {"type":"innocent","x":1},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":2,"liars":[0,2]},
  },
  {
    num: 12, quizId: "sworn-7-29-26", live: "2026-07-29", dateLabel: "July 29, 2026", sunday: false,
    k: 3,
    suspects: ["Sadie","Simon","Rufus","Bruno","Felix"],
    venue: "the Quayside fish market",
    stolen: "the day's takings",
    statements: [
      {"type":"honest","x":2},
      {"type":"liar","x":2},
      {"type":"innocent","x":1},
      {"type":"innocent","x":0},
      {"type":"liar","x":2},
    ],
    solution: {"thief":0,"liars":[1,3,4]},
  },
  {
    num: 13, quizId: "sworn-7-30-26", live: "2026-07-30", dateLabel: "July 30, 2026", sunday: false,
    k: 2,
    suspects: ["Nell","Vera","Winnie","Gideon","Mabel"],
    venue: "the Tinker's Row workshop",
    stolen: "a walnut music box",
    statements: [
      {"type":"accuse","x":2},
      {"type":"accuse","x":0},
      {"type":"innocent","x":4},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":3,"liars":[0,1]},
  },
  {
    num: 14, quizId: "sworn-7-31-26", live: "2026-07-31", dateLabel: "July 31, 2026", sunday: false,
    k: 3,
    suspects: ["Tessa","Rosa","Lottie","Gideon","Nell"],
    venue: "the Hollybush coaching inn",
    stolen: "the mail satchel",
    statements: [
      {"type":"honest","x":3},
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"accuse","x":0},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":3,"liars":[0,1,3]},
  },
  {
    num: 15, quizId: "sworn-8-1-26", live: "2026-08-01", dateLabel: "August 1, 2026", sunday: false,
    k: 3,
    suspects: ["Mordecai","Prudence","Alastair","Cordelia","Thaddeus"],
    venue: "the Marigold coffee-house",
    stolen: "an ivory chess set",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":3},
      {"type":"honest","x":3},
      {"type":"liar","x":1},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[2,3,4]},
  },
  {
    num: 16, quizId: "sworn-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true,
    k: 4,
    suspects: ["Agatha","Barnaby","Cornelius","Delphine","Ephraim","Marguerite"],
    venue: "the Ashgrove printworks",
    stolen: "a jeweled snuffbox",
    statements: [
      {"type":"liar","x":1},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[0,3,4,5]},
  },
  {
    num: 17, quizId: "sworn-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false,
    k: 3,
    suspects: ["Ignatius","Bellamy","Constance","Percival","Ottoline"],
    venue: "the Candlewick chandlery",
    stolen: "the guild's brass seal",
    statements: [
      {"type":"liar","x":4},
      {"type":"accuse","x":3},
      {"type":"innocent","x":4},
      {"type":"innocent","x":2},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":2,"liars":[1,3,4]},
  },
  {
    num: 18, quizId: "sworn-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false,
    k: 2,
    suspects: ["Alaric","Cressida","Dorian","Isolde","Roland"],
    venue: "the Peppercorn spice-house",
    stolen: "a brass astrolabe",
    statements: [
      {"type":"honest","x":2},
      {"type":"honest","x":4},
      {"type":"liar","x":4},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":2,"liars":[0,2]},
  },
  {
    num: 19, quizId: "sworn-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false,
    k: 3,
    suspects: ["Matilda","Osric","Perpetua","Quentin","Sybil"],
    venue: "the Blackthorn brewery",
    stolen: "the vintner's tasting cup",
    statements: [
      {"type":"innocent","x":4},
      {"type":"liar","x":0},
      {"type":"liar","x":4},
      {"type":"liar","x":1},
      {"type":"honest","x":0},
    ],
    solution: {"thief":4,"liars":[0,3,4]},
  },
  {
    num: 20, quizId: "sworn-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false,
    k: 2,
    suspects: ["Casimir","Edwina","Fitzgerald","Griselda","Humphrey"],
    venue: "the Willowmere boathouse",
    stolen: "a bundle of beaver pelts",
    statements: [
      {"type":"liar","x":3},
      {"type":"innocent","x":0},
      {"type":"honest","x":1},
      {"type":"selfInnocent"},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":2,"liars":[0,4]},
  },
  {
    num: 21, quizId: "sworn-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false,
    k: 3,
    suspects: ["Jerome","Katharine","Lucius","Millicent","Nathaniel"],
    venue: "the Sable and Crane haberdashery",
    stolen: "the mayor's signet ring",
    statements: [
      {"type":"liar","x":1},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
      {"type":"honest","x":1},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[1,3,4]},
  },
  {
    num: 22, quizId: "sworn-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false,
    k: 2,
    suspects: ["Octavia","Peregrine","Rosalind","Sebastian","Theodora"],
    venue: "the Greenhollow orchard",
    stolen: "a basket of heirloom apples",
    statements: [
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":1,"liars":[2,3]},
  },
  {
    num: 23, quizId: "sworn-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true,
    k: 4,
    suspects: ["Ambrose","Beatrix","Cuthbert","Drusilla","Eldon","Fenwick"],
    venue: "the Ironmonger's yard",
    stolen: "a set of surgeon's blades",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":4},
      {"type":"accuse","x":4},
      {"type":"innocent","x":2},
      {"type":"thiefHonest"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":2,"liars":[1,2,3,4]},
  },
  {
    num: 24, quizId: "sworn-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false,
    k: 3,
    suspects: ["Godfrey","Henrietta","Isambard","Jocasta","Kingsley"],
    venue: "the Cloverdale creamery",
    stolen: "the dairy's copper churn",
    statements: [
      {"type":"innocent","x":2},
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
      {"type":"selfInnocent"},
      {"type":"liar","x":3},
    ],
    solution: {"thief":3,"liars":[1,2,3]},
  },
  {
    num: 25, quizId: "sworn-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false,
    k: 3,
    suspects: ["Percival","Sylvester","Quenby","Gulliver","Ignatius"],
    venue: "the Mercer Lane glassworks",
    stolen: "a bolt of Flanders lace",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":3},
      {"type":"thiefLiar"},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":4,"liars":[1,2,3]},
  },
  {
    num: 26, quizId: "sworn-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false,
    k: 2,
    suspects: ["Winifred","Albertine","Clementine","Valentine","Peregrine"],
    venue: "the Rookery bathhouse",
    stolen: "the master key to the strongroom",
    statements: [
      {"type":"thiefHonest"},
      {"type":"accuse","x":0},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":0,"liars":[3,4]},
  },
  {
    num: 27, quizId: "sworn-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false,
    k: 3,
    suspects: ["Beatrix","Theodora","Tabitha","Percival","Ophelia"],
    venue: "the Thistledown tea rooms",
    stolen: "a case of surgical mirrors",
    statements: [
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"innocent","x":0},
      {"type":"liar","x":1},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":2,"liars":[0,3,4]},
  },
  {
    num: 28, quizId: "sworn-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false,
    k: 3,
    suspects: ["Quintus","Xanthe","Zillah","Ulric","Griselda"],
    venue: "the Kettlewick smithy",
    stolen: "the founder's inkstand",
    statements: [
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":1,"liars":[0,1,3]},
  },
  {
    num: 29, quizId: "sworn-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false,
    k: 2,
    suspects: ["Idris","Ophelia","Ezra","Tabitha","Octavia"],
    venue: "the Pargeter almshouse",
    stolen: "a tray of uncut garnets",
    statements: [
      {"type":"liar","x":2},
      {"type":"honest","x":4},
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[2,3]},
  },
  {
    num: 30, quizId: "sworn-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true,
    k: 2,
    suspects: ["Kester","Horatio","Griselda","Norbert","Yvette","Idris"],
    venue: "the Verity Street bindery",
    stolen: "the lifeboat's brass bell",
    statements: [
      {"type":"accuse","x":3},
      {"type":"liar","x":3},
      {"type":"honest","x":4},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
    ],
    solution: {"thief":3,"liars":[3,5]},
  },
  {
    num: 31, quizId: "sworn-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false,
    k: 2,
    suspects: ["Ursula","Quenby","Xanthe","Kester","Zillah"],
    venue: "the Saffron Hill dyehouse",
    stolen: "a crate of seed potatoes",
    statements: [
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"honest","x":0},
      {"type":"honest","x":0},
    ],
    solution: {"thief":1,"liars":[1,2]},
  },
  {
    num: 32, quizId: "sworn-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false,
    k: 3,
    suspects: ["Josiah","Rosamund","Quintus","Millicent","Xanthe"],
    venue: "the Longspur riding school",
    stolen: "the tollkeeper's cashbox",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
      {"type":"liar","x":2},
    ],
    solution: {"thief":0,"liars":[0,3,4]},
  },
  {
    num: 33, quizId: "sworn-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false,
    k: 3,
    suspects: ["Kester","Rowena","Drusilla","Horatio","Mortimer"],
    venue: "the Crowder Alley clockmakers",
    stolen: "a folio of engraved maps",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":0},
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[0,3,4]},
  },
  {
    num: 34, quizId: "sworn-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false,
    k: 2,
    suspects: ["Ezra","Lavinia","Beatrix","Peregrine","Ambrose"],
    venue: "the Barleycorn malthouse",
    stolen: "the parish christening cup",
    statements: [
      {"type":"selfInnocent"},
      {"type":"honest","x":3},
      {"type":"accuse","x":3},
      {"type":"accuse","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[2,4]},
  },
  {
    num: 35, quizId: "sworn-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false,
    k: 3,
    suspects: ["Xanthe","Albertine","Zebedee","Ferdinand","Yvette"],
    venue: "the Fossgate ropewalk",
    stolen: "a set of tuning forks",
    statements: [
      {"type":"liar","x":1},
      {"type":"thiefHonest"},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":3,"liars":[1,3,4]},
  },
  {
    num: 36, quizId: "sworn-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false,
    k: 2,
    suspects: ["Ignatius","Millicent","Eulalia","Tabitha","Drusilla"],
    venue: "the Nettlebed toll house",
    stolen: "the auctioneer's gavel",
    statements: [
      {"type":"honest","x":3},
      {"type":"thiefHonest"},
      {"type":"liar","x":4},
      {"type":"honest","x":2},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[1,4]},
  },
  {
    num: 37, quizId: "sworn-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true,
    k: 3,
    suspects: ["Horatio","Zillah","Ambrose","Albertine","Cornelius","Desmond"],
    venue: "the Chandler Quay warehouse",
    stolen: "a tin of Ceylon tea",
    statements: [
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"accuse","x":0},
    ],
    solution: {"thief":0,"liars":[0,2,3]},
  },
  {
    num: 38, quizId: "sworn-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false,
    k: 3,
    suspects: ["Peregrine","Mortimer","Rosamund","Theodora","Octavia"],
    venue: "the Havelock reading room",
    stolen: "the weighbridge ledger",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":0},
      {"type":"innocent","x":1},
      {"type":"honest","x":2},
    ],
    solution: {"thief":0,"liars":[0,2,4]},
  },
  {
    num: 39, quizId: "sworn-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false,
    k: 2,
    suspects: ["Kester","Octavia","Idris","Valentine","Percival"],
    venue: "the Sparrowgate mews",
    stolen: "a pair of duelling pistols",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 40, quizId: "sworn-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false,
    k: 2,
    suspects: ["Katrina","Clementine","Idris","Millicent","Lavinia"],
    venue: "the Pipers Croft cider press",
    stolen: "the choirmaster's baton",
    statements: [
      {"type":"innocent","x":2},
      {"type":"accuse","x":0},
      {"type":"accuse","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":3},
    ],
    solution: {"thief":1,"liars":[1,4]},
  },
  {
    num: 41, quizId: "sworn-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false,
    k: 3,
    suspects: ["Ignatius","Mortimer","Eulalia","Quenby","Winifred"],
    venue: "the Dunwold assembly rooms",
    stolen: "a bundle of raw silk skeins",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 42, quizId: "sworn-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false,
    k: 3,
    suspects: ["Fenella","Beatrix","Percival","Rowena","Wilfred"],
    venue: "the Marlpit lime kiln",
    stolen: "the lighthouse logbook",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
      {"type":"accuse","x":0},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 43, quizId: "sworn-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false,
    k: 3,
    suspects: ["Ulric","Zillah","Kester","Drusilla","Horatio"],
    venue: "the Ravensworth seed merchant",
    stolen: "a canister of indigo dye",
    statements: [
      {"type":"accuse","x":2},
      {"type":"liar","x":0},
      {"type":"innocent","x":1},
      {"type":"innocent","x":2},
      {"type":"liar","x":1},
    ],
    solution: {"thief":1,"liars":[0,2,4]},
  },
  {
    num: 44, quizId: "sworn-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true,
    k: 4,
    suspects: ["Nerissa","Cornelius","Verena","Wilfred","Quintus","Peregrine"],
    venue: "the Turnstile lending library",
    stolen: "the physician's pocket scales",
    statements: [
      {"type":"liar","x":3},
      {"type":"liar","x":0},
      {"type":"thiefLiar"},
      {"type":"liar","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[1,2,3,5]},
  },
  {
    num: 45, quizId: "sworn-8-31-26", live: "2026-08-31", dateLabel: "August 31, 2026", sunday: false,
    k: 3,
    suspects: ["Rowena","Cornelius","Ursula","Quenby","Millicent"],
    venue: "the Whitcombe salt works",
    stolen: "a sack of cardamom",
    statements: [
      {"type":"thiefLiar"},
      {"type":"innocent","x":3},
      {"type":"liar","x":1},
      {"type":"liar","x":2},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[0,2,4]},
  },
  {
    num: 46, quizId: "sworn-9-1-26", live: "2026-09-01", dateLabel: "September 1, 2026", sunday: false,
    k: 3,
    suspects: ["Mortimer","Idris","Ezra","Nerissa","Rowena"],
    venue: "the Pelham Row surgery",
    stolen: "the regimental colours",
    statements: [
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
      {"type":"liar","x":1},
      {"type":"thiefHonest"},
      {"type":"accuse","x":3},
    ],
    solution: {"thief":3,"liars":[0,1,3]},
  },
  {
    num: 47, quizId: "sworn-9-2-26", live: "2026-09-02", dateLabel: "September 2, 2026", sunday: false,
    k: 3,
    suspects: ["Ambrose","Verena","Yvette","Wilfred","Idris"],
    venue: "the Ferrybridge weighhouse",
    stolen: "a tray of printer's type",
    statements: [
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"accuse","x":3},
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[0,2,4]},
  },
  {
    num: 48, quizId: "sworn-9-3-26", live: "2026-09-03", dateLabel: "September 3, 2026", sunday: false,
    k: 2,
    suspects: ["Harriet","Tabitha","Ezra","Lysander","Gulliver"],
    venue: "the Corncrake auction hall",
    stolen: "the harbourmaster's telescope",
    statements: [
      {"type":"thiefLiar"},
      {"type":"innocent","x":3},
      {"type":"innocent","x":1},
      {"type":"innocent","x":1},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":3,"liars":[0,1]},
  },
  {
    num: 49, quizId: "sworn-9-4-26", live: "2026-09-04", dateLabel: "September 4, 2026", sunday: false,
    k: 3,
    suspects: ["Rosamund","Tabitha","Horatio","Gulliver","Winifred"],
    venue: "the Ashgrove tannery",
    stolen: "a copper diving helmet",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[1,2,4]},
  },
  {
    num: 50, quizId: "sworn-9-5-26", live: "2026-09-05", dateLabel: "September 5, 2026", sunday: false,
    k: 2,
    suspects: ["Zillah","Kester","Beatrix","Cornelius","Ulric"],
    venue: "the Bellwether coaching yard",
    stolen: "the guild's ceremonial mace",
    statements: [
      {"type":"thiefLiar"},
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[1,4]},
  },
  {
    num: 51, quizId: "sworn-9-6-26", live: "2026-09-06", dateLabel: "September 6, 2026", sunday: true,
    k: 3,
    suspects: ["Theodora","Nerissa","Peregrine","Beatrix","Lavinia","Tabitha"],
    venue: "the Corvid Lane theatre",
    stolen: "a tray of glass eyes",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"honest","x":5},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[1,2,3]},
  },
  {
    num: 52, quizId: "sworn-9-7-26", live: "2026-09-07", dateLabel: "September 7, 2026", sunday: false,
    k: 2,
    suspects: ["Desmond","Cornelius","Ignatius","Millicent","Jemima"],
    venue: "the Dunmow toll bridge",
    stolen: "the harbourmaster's flag",
    statements: [
      {"type":"accuse","x":4},
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":2,"liars":[0,2]},
  },
  {
    num: 53, quizId: "sworn-9-8-26", live: "2026-09-08", dateLabel: "September 8, 2026", sunday: false,
    k: 2,
    suspects: ["Albertine","Rosamund","Eulalia","Clementine","Yvette"],
    venue: "the Eastcheap counting room",
    stolen: "a crate of bone china",
    statements: [
      {"type":"accuse","x":1},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
      {"type":"honest","x":0},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":0,"liars":[0,3]},
  },
  {
    num: 54, quizId: "sworn-9-9-26", live: "2026-09-09", dateLabel: "September 9, 2026", sunday: false,
    k: 3,
    suspects: ["Idris","Lysander","Rosamund","Katrina","Lavinia"],
    venue: "the Fettleworth mill",
    stolen: "the mill's brass whistle",
    statements: [
      {"type":"honest","x":2},
      {"type":"innocent","x":2},
      {"type":"innocent","x":3},
      {"type":"liar","x":0},
      {"type":"liar","x":3},
    ],
    solution: {"thief":3,"liars":[0,2,4]},
  },
  {
    num: 55, quizId: "sworn-9-10-26", live: "2026-09-10", dateLabel: "September 10, 2026", sunday: false,
    k: 2,
    suspects: ["Sebastian","Verena","Albertine","Theodora","Ophelia"],
    venue: "the Garrick Street atelier",
    stolen: "a bolt of cloth of gold",
    statements: [
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"accuse","x":0},
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[0,2]},
  },
  {
    num: 56, quizId: "sworn-9-11-26", live: "2026-09-11", dateLabel: "September 11, 2026", sunday: false,
    k: 3,
    suspects: ["Griselda","Verena","Peregrine","Bartholomew","Josiah"],
    venue: "the Hollowbrook forge",
    stolen: "the founder's death mask",
    statements: [
      {"type":"liar","x":2},
      {"type":"thiefHonest"},
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"liar","x":1},
    ],
    solution: {"thief":3,"liars":[0,1,3]},
  },
  {
    num: 57, quizId: "sworn-9-12-26", live: "2026-09-12", dateLabel: "September 12, 2026", sunday: false,
    k: 2,
    suspects: ["Horatio","Clementine","Ursula","Sylvester","Rowena"],
    venue: "the Ivy Court conservatory",
    stolen: "a case of duelling foils",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":2},
      {"type":"innocent","x":3},
      {"type":"selfInnocent"},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":0,"liars":[0,1]},
  },
  {
    num: 58, quizId: "sworn-9-13-26", live: "2026-09-13", dateLabel: "September 13, 2026", sunday: true,
    k: 2,
    suspects: ["Theodora","Ignatius","Millicent","Gulliver","Quintus","Verena"],
    venue: "the Jessop Row surgery",
    stolen: "the sexton's lantern",
    statements: [
      {"type":"accuse","x":5},
      {"type":"thiefLiar"},
      {"type":"innocent","x":1},
      {"type":"accuse","x":5},
      {"type":"accuse","x":0},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":5,"liars":[4,5]},
  },
  {
    num: 59, quizId: "sworn-9-14-26", live: "2026-09-14", dateLabel: "September 14, 2026", sunday: false,
    k: 3,
    suspects: ["Desmond","Tabitha","Zebedee","Katrina","Kester"],
    venue: "the Kettleby granary",
    stolen: "a box of ivory dominoes",
    statements: [
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[0,2,4]},
  },
  {
    num: 60, quizId: "sworn-9-15-26", live: "2026-09-15", dateLabel: "September 15, 2026", sunday: false,
    k: 2,
    suspects: ["Ambrose","Lysander","Percival","Fenella","Sylvester"],
    venue: "the Larkspur perfumery",
    stolen: "the chemist's mortar",
    statements: [
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[0,3]},
  },
  {
    num: 61, quizId: "sworn-9-16-26", live: "2026-09-16", dateLabel: "September 16, 2026", sunday: false,
    k: 2,
    suspects: ["Zillah","Theodora","Lavinia","Idris","Fenella"],
    venue: "the Mallow Street dairy",
    stolen: "a rolled Persian rug",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":3},
      {"type":"thiefLiar"},
      {"type":"accuse","x":2},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[3,4]},
  },
  {
    num: 62, quizId: "sworn-9-17-26", live: "2026-09-17", dateLabel: "September 17, 2026", sunday: false,
    k: 2,
    suspects: ["Zillah","Tabitha","Sylvester","Ophelia","Quenby"],
    venue: "the Netherfield stables",
    stolen: "the town's fire bell",
    statements: [
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"honest","x":0},
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":1,"liars":[1,3]},
  },
  {
    num: 63, quizId: "sworn-9-18-26", live: "2026-09-18", dateLabel: "September 18, 2026", sunday: false,
    k: 2,
    suspects: ["Beatrix","Quintus","Ferdinand","Idris","Ambrose"],
    venue: "the Orchard Gate cannery",
    stolen: "a set of silver spurs",
    statements: [
      {"type":"honest","x":3},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
      {"type":"honest","x":0},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[1,4]},
  },
  {
    num: 64, quizId: "sworn-9-19-26", live: "2026-09-19", dateLabel: "September 19, 2026", sunday: false,
    k: 3,
    suspects: ["Beatrix","Wilfred","Sebastian","Kester","Norbert"],
    venue: "the Pinfold weighbridge",
    stolen: "the pilot's brass compass",
    statements: [
      {"type":"liar","x":1},
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"liar","x":0},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[0,2,4]},
  },
  {
    num: 65, quizId: "sworn-9-20-26", live: "2026-09-20", dateLabel: "September 20, 2026", sunday: true,
    k: 2,
    suspects: ["Josiah","Valentine","Lysander","Ursula","Idris","Griselda"],
    venue: "the Quarry Lane sawmill",
    stolen: "a crate of blown glass",
    statements: [
      {"type":"thiefHonest"},
      {"type":"accuse","x":0},
      {"type":"selfInnocent"},
      {"type":"accuse","x":1},
      {"type":"honest","x":0},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[1,3]},
  },
  {
    num: 66, quizId: "sworn-9-21-26", live: "2026-09-21", dateLabel: "September 21, 2026", sunday: false,
    k: 3,
    suspects: ["Verena","Katrina","Lysander","Horatio","Ambrose"],
    venue: "the Rushmere boat yard",
    stolen: "the abbot's psalter",
    statements: [
      {"type":"selfInnocent"},
      {"type":"honest","x":2},
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"accuse","x":0},
    ],
    solution: {"thief":4,"liars":[1,2,4]},
  },
  {
    num: 67, quizId: "sworn-9-22-26", live: "2026-09-22", dateLabel: "September 22, 2026", sunday: false,
    k: 3,
    suspects: ["Tabitha","Peregrine","Valentine","Ferdinand","Norbert"],
    venue: "the Stanhope glasshouse",
    stolen: "a chest of tea caddies",
    statements: [
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[0,2,4]},
  },
  {
    num: 68, quizId: "sworn-9-23-26", live: "2026-09-23", dateLabel: "September 23, 2026", sunday: false,
    k: 2,
    suspects: ["Ursula","Kester","Griselda","Ophelia","Mortimer"],
    venue: "the Thurlow bindery",
    stolen: "the tanner's silver knife",
    statements: [
      {"type":"accuse","x":4},
      {"type":"innocent","x":3},
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 69, quizId: "sworn-9-24-26", live: "2026-09-24", dateLabel: "September 24, 2026", sunday: false,
    k: 3,
    suspects: ["Beatrix","Gulliver","Cornelius","Ambrose","Horatio"],
    venue: "the Underwood cooperage",
    stolen: "a bale of raw indigo",
    statements: [
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"honest","x":2},
      {"type":"liar","x":1},
    ],
    solution: {"thief":0,"liars":[2,3,4]},
  },
  {
    num: 70, quizId: "sworn-9-25-26", live: "2026-09-25", dateLabel: "September 25, 2026", sunday: false,
    k: 3,
    suspects: ["Valentine","Sylvester","Horatio","Ambrose","Winifred"],
    venue: "the Vellum Court press",
    stolen: "the printer's first folio",
    statements: [
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"accuse","x":4},
      {"type":"selfInnocent"},
      {"type":"liar","x":0},
    ],
    solution: {"thief":3,"liars":[2,3,4]},
  },
  {
    num: 71, quizId: "sworn-9-26-26", live: "2026-09-26", dateLabel: "September 26, 2026", sunday: false,
    k: 3,
    suspects: ["Millicent","Valentine","Horatio","Ophelia","Griselda"],
    venue: "the Wexham brickworks",
    stolen: "a cage of canaries",
    statements: [
      {"type":"thiefHonest"},
      {"type":"liar","x":2},
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":2,"liars":[0,2,3]},
  },
  {
    num: 72, quizId: "sworn-9-27-26", live: "2026-09-27", dateLabel: "September 27, 2026", sunday: true,
    k: 3,
    suspects: ["Fenella","Albertine","Nerissa","Winifred","Zebedee","Horatio"],
    venue: "the Yardley candle works",
    stolen: "the smith's anvil horn",
    statements: [
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"accuse","x":0},
      {"type":"accuse","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":0},
    ],
    solution: {"thief":0,"liars":[1,3,4]},
  },
  {
    num: 73, quizId: "sworn-9-28-26", live: "2026-09-28", dateLabel: "September 28, 2026", sunday: false,
    k: 3,
    suspects: ["Yvette","Harriet","Wilfred","Ursula","Norbert"],
    venue: "the Zephyr Street arcade",
    stolen: "a purse of trade beads",
    statements: [
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":1,"liars":[0,1,4]},
  },
  {
    num: 74, quizId: "sworn-9-29-26", live: "2026-09-29", dateLabel: "September 29, 2026", sunday: false,
    k: 2,
    suspects: ["Horatio","Lysander","Rosamund","Valentine","Verena"],
    venue: "the Alderman's bathhouse",
    stolen: "the sailmaker's palm",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"innocent","x":2},
      {"type":"honest","x":2},
    ],
    solution: {"thief":0,"liars":[0,1]},
  },
  {
    num: 75, quizId: "sworn-9-30-26", live: "2026-09-30", dateLabel: "September 30, 2026", sunday: false,
    k: 2,
    suspects: ["Gideon","Prudence","Cordelia","Delia","Felix"],
    venue: "the Marlpit brick kiln",
    stolen: "the kilnmaster's tally board",
    statements: [
      {"type":"honest","x":3},
      {"type":"innocent","x":3},
      {"type":"honest","x":0},
      {"type":"innocent","x":0},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[1,4]},
  },
  {
    num: 76, quizId: "sworn-10-1-26", live: "2026-10-01", dateLabel: "October 1, 2026", sunday: false,
    k: 3,
    suspects: ["Winnie","Constance","Tessa","Opal","Cornelius"],
    venue: "the Norbury cutlery shop",
    stolen: "a tray of bone-handled knives",
    statements: [
      {"type":"innocent","x":1},
      {"type":"liar","x":2},
      {"type":"accuse","x":3},
      {"type":"liar","x":1},
      {"type":"liar","x":2},
    ],
    solution: {"thief":1,"liars":[0,2,3]},
  },
  {
    num: 77, quizId: "sworn-10-2-26", live: "2026-10-02", dateLabel: "October 2, 2026", sunday: false,
    k: 2,
    suspects: ["Thaddeus","Horatio","Verena","Katharine","Nell"],
    venue: "the Oakhanger charcoal burn",
    stolen: "the burner's iron rake",
    statements: [
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[1,2]},
  },
  {
    num: 78, quizId: "sworn-10-3-26", live: "2026-10-03", dateLabel: "October 3, 2026", sunday: false,
    k: 2,
    suspects: ["Ferdinand","Cressida","Sybil","Valentine","Zillah"],
    venue: "the Pilgrim Wharf fish market",
    stolen: "a barrel of pickled herring",
    statements: [
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"honest","x":4},
      {"type":"honest","x":4},
      {"type":"liar","x":0},
    ],
    solution: {"thief":4,"liars":[0,1]},
  },
  {
    num: 79, quizId: "sworn-10-4-26", live: "2026-10-04", dateLabel: "October 4, 2026", sunday: true,
    k: 2,
    suspects: ["Lysander","Ophelia","Godfrey","Bartholomew","Quentin","Henrietta"],
    venue: "the Quenby carriage works",
    stolen: "the coachbuilder's gilding brush",
    statements: [
      {"type":"accuse","x":1},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"honest","x":1},
    ],
    solution: {"thief":1,"liars":[1,5]},
  },
  {
    num: 80, quizId: "sworn-10-5-26", live: "2026-10-05", dateLabel: "October 5, 2026", sunday: false,
    k: 3,
    suspects: ["Lysander","Constance","Winnie","Rosa","Eldon"],
    venue: "the Ravelston button mill",
    stolen: "a card of mother-of-pearl buttons",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":0,"liars":[0,1,4]},
  },
  {
    num: 81, quizId: "sworn-10-6-26", live: "2026-10-06", dateLabel: "October 6, 2026", sunday: false,
    k: 2,
    suspects: ["Monty","Jerome","Rosamund","Ursula","Peregrine"],
    venue: "the Sedgemoor withy beds",
    stolen: "the cutter's hooked billhook",
    statements: [
      {"type":"honest","x":1},
      {"type":"honest","x":4},
      {"type":"accuse","x":3},
      {"type":"innocent","x":2},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":2,"liars":[2,3]},
  },
  {
    num: 82, quizId: "sworn-10-7-26", live: "2026-10-07", dateLabel: "October 7, 2026", sunday: false,
    k: 2,
    suspects: ["Humphrey","Beatrix","Rufus","Norbert","Sybil"],
    venue: "the Tarnbrook fulling mill",
    stolen: "a bale of teasels",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
      {"type":"honest","x":1},
      {"type":"honest","x":1},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[0,4]},
  },
  {
    num: 83, quizId: "sworn-10-8-26", live: "2026-10-08", dateLabel: "October 8, 2026", sunday: false,
    k: 2,
    suspects: ["Sylvester","Opal","Simon","Quenby","Wilfred"],
    venue: "the Upcott lace school",
    stolen: "the lacemaker's parchment prickings",
    statements: [
      {"type":"honest","x":4},
      {"type":"liar","x":4},
      {"type":"accuse","x":1},
      {"type":"liar","x":2},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":1,"liars":[1,3]},
  },
  {
    num: 84, quizId: "sworn-10-9-26", live: "2026-10-09", dateLabel: "October 9, 2026", sunday: false,
    k: 3,
    suspects: ["Osric","Simon","Ursula","Mabel","Lysander"],
    venue: "the Vintry Lane spice loft",
    stolen: "a chest of green cardamom",
    statements: [
      {"type":"innocent","x":2},
      {"type":"innocent","x":3},
      {"type":"liar","x":0},
      {"type":"honest","x":1},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":3,"liars":[1,2,3]},
  },
  {
    num: 85, quizId: "sworn-10-10-26", live: "2026-10-10", dateLabel: "October 10, 2026", sunday: false,
    k: 2,
    suspects: ["Edwina","Beatrix","Otis","Jemima","Quentin"],
    venue: "the Whitlow horn works",
    stolen: "the hornworker's steaming pot",
    statements: [
      {"type":"innocent","x":4},
      {"type":"liar","x":0},
      {"type":"liar","x":0},
      {"type":"honest","x":1},
      {"type":"liar","x":2},
    ],
    solution: {"thief":4,"liars":[0,4]},
  },
  {
    num: 86, quizId: "sworn-10-11-26", live: "2026-10-11", dateLabel: "October 11, 2026", sunday: true,
    k: 3,
    suspects: ["Marguerite","Osric","Ignatius","Zillah","Gulliver","Griselda"],
    venue: "the Yalding oast house",
    stolen: "a pocket of Fuggle hops",
    statements: [
      {"type":"honest","x":2},
      {"type":"accuse","x":2},
      {"type":"thiefLiar"},
      {"type":"innocent","x":1},
      {"type":"honest","x":0},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[1,3,5]},
  },
  {
    num: 87, quizId: "sworn-10-12-26", live: "2026-10-12", dateLabel: "October 12, 2026", sunday: false,
    k: 3,
    suspects: ["Clara","Horatio","Idris","Ophelia","Quintus"],
    venue: "the Zeal Monachorum forge",
    stolen: "the smith's tempering trough",
    statements: [
      {"type":"innocent","x":1},
      {"type":"honest","x":2},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[0,3,4]},
  },
  {
    num: 88, quizId: "sworn-10-13-26", live: "2026-10-13", dateLabel: "October 13, 2026", sunday: false,
    k: 2,
    suspects: ["Rosa","Casimir","Norbert","Ulric","Bartholomew"],
    venue: "the Applegarth cooper yard",
    stolen: "a set of croze irons",
    statements: [
      {"type":"honest","x":1},
      {"type":"honest","x":3},
      {"type":"innocent","x":0},
      {"type":"liar","x":4},
      {"type":"liar","x":3},
    ],
    solution: {"thief":0,"liars":[2,4]},
  },
  {
    num: 89, quizId: "sworn-10-14-26", live: "2026-10-14", dateLabel: "October 14, 2026", sunday: false,
    k: 3,
    suspects: ["Alaric","Ferdinand","Winnie","Flora","Felix"],
    venue: "the Brindlemere gunsmiths",
    stolen: "the engraver's scrolling tool",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":0},
      {"type":"honest","x":0},
      {"type":"accuse","x":0},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[0,1,2]},
  },
  {
    num: 90, quizId: "sworn-10-15-26", live: "2026-10-15", dateLabel: "October 15, 2026", sunday: false,
    k: 3,
    suspects: ["Thaddeus","Alastair","Tessa","Matilda","Ferdinand"],
    venue: "the Coldbrook watch case shop",
    stolen: "a tray of engine-turned cases",
    statements: [
      {"type":"innocent","x":3},
      {"type":"selfInnocent"},
      {"type":"accuse","x":3},
      {"type":"honest","x":0},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[0,3,4]},
  },
  {
    num: 91, quizId: "sworn-10-16-26", live: "2026-10-16", dateLabel: "October 16, 2026", sunday: false,
    k: 3,
    suspects: ["Zebedee","Millicent","Mortimer","Theodora","Percival"],
    venue: "the Dunwich net store",
    stolen: "the harbour clerk's day book",
    statements: [
      {"type":"innocent","x":4},
      {"type":"innocent","x":2},
      {"type":"honest","x":1},
      {"type":"innocent","x":0},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[1,2,4]},
  },
  {
    num: 92, quizId: "sworn-10-17-26", live: "2026-10-17", dateLabel: "October 17, 2026", sunday: false,
    k: 3,
    suspects: ["Yvette","Sebastian","Mabel","Henrietta","Rufus"],
    venue: "the Ecclesfield pin works",
    stolen: "a paper of solid-headed pins",
    statements: [
      {"type":"honest","x":1},
      {"type":"innocent","x":0},
      {"type":"innocent","x":1},
      {"type":"innocent","x":1},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":0,"liars":[0,1,4]},
  },
  {
    num: 93, quizId: "sworn-10-18-26", live: "2026-10-18", dateLabel: "October 18, 2026", sunday: true,
    k: 3,
    suspects: ["Beatrix","Rowena","Simon","Sylvester","Mordecai","Fitzgerald"],
    venue: "the Farthingale corsetry",
    stolen: "the staymaker's whalebone busk",
    statements: [
      {"type":"honest","x":4},
      {"type":"innocent","x":3},
      {"type":"accuse","x":4},
      {"type":"selfInnocent"},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[0,4,5]},
  },
  {
    num: 94, quizId: "sworn-10-19-26", live: "2026-10-19", dateLabel: "October 19, 2026", sunday: false,
    k: 2,
    suspects: ["Victor","Theodora","Norbert","Josiah","Cressida"],
    venue: "the Grimshaw pewter shop",
    stolen: "a garnish of touchmarked plates",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":3},
      {"type":"accuse","x":0},
      {"type":"liar","x":1},
      {"type":"liar","x":3},
    ],
    solution: {"thief":3,"liars":[2,3]},
  },
  {
    num: 95, quizId: "sworn-10-20-26", live: "2026-10-20", dateLabel: "October 20, 2026", sunday: false,
    k: 2,
    suspects: ["Kester","Alastair","Ezra","Yvette","Fenella"],
    venue: "the Hetherwick glove loft",
    stolen: "the glover's dressing knife",
    statements: [
      {"type":"innocent","x":2},
      {"type":"honest","x":0},
      {"type":"innocent","x":1},
      {"type":"innocent","x":1},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":1,"liars":[2,3]},
  },
  {
    num: 96, quizId: "sworn-10-21-26", live: "2026-10-21", dateLabel: "October 21, 2026", sunday: false,
    k: 3,
    suspects: ["Jasper","Idris","Octavia","Jemima","Peregrine"],
    venue: "the Inkpen millstone quarry",
    stolen: "a pair of French burr stones",
    statements: [
      {"type":"innocent","x":4},
      {"type":"honest","x":3},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":4,"liars":[0,1,3]},
  },
  {
    num: 97, quizId: "sworn-10-22-26", live: "2026-10-22", dateLabel: "October 22, 2026", sunday: false,
    k: 2,
    suspects: ["Mortimer","Percy","Alastair","Osric","Roland"],
    venue: "the Jesmond ink works",
    stolen: "the colourman's lampblack pot",
    statements: [
      {"type":"liar","x":3},
      {"type":"accuse","x":2},
      {"type":"honest","x":3},
      {"type":"accuse","x":2},
      {"type":"honest","x":0},
    ],
    solution: {"thief":2,"liars":[0,4]},
  },
  {
    num: 98, quizId: "sworn-10-23-26", live: "2026-10-23", dateLabel: "October 23, 2026", sunday: false,
    k: 3,
    suspects: ["Isolde","Cornelius","Dorian","Nell","Millicent"],
    venue: "the Kelmscott willow yard",
    stolen: "a bundle of buff osiers",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":4},
      {"type":"accuse","x":4},
      {"type":"innocent","x":4},
      {"type":"honest","x":1},
    ],
    solution: {"thief":4,"liars":[1,3,4]},
  },
  {
    num: 99, quizId: "sworn-10-24-26", live: "2026-10-24", dateLabel: "October 24, 2026", sunday: false,
    k: 2,
    suspects: ["Cordelia","Idris","Desmond","Perpetua","Isolde"],
    venue: "the Ludbrook comb works",
    stolen: "the combmaker's tortoiseshell press",
    statements: [
      {"type":"thiefHonest"},
      {"type":"liar","x":4},
      {"type":"accuse","x":0},
      {"type":"honest","x":2},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":0,"liars":[0,1]},
  },
  {
    num: 100, quizId: "sworn-10-25-26", live: "2026-10-25", dateLabel: "October 25, 2026", sunday: true,
    k: 2,
    suspects: ["Edwina","Tessa","Gideon","Agatha","Rosalind","Fitzgerald"],
    venue: "the Mereworth wax chandlery",
    stolen: "a box of altar tapers",
    statements: [
      {"type":"liar","x":1},
      {"type":"accuse","x":5},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"honest","x":0},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":2,"liars":[1,2]},
  },
  {
    num: 101, quizId: "sworn-10-26-26", live: "2026-10-26", dateLabel: "October 26, 2026", sunday: false,
    k: 2,
    suspects: ["Wilfred","Ferdinand","Albertine","Eldon","Katrina"],
    venue: "the Nettlestone sponge loft",
    stolen: "the diver's brass helmet lamp",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"liar","x":1},
      {"type":"honest","x":1},
      {"type":"honest","x":0},
    ],
    solution: {"thief":4,"liars":[1,3]},
  },
  {
    num: 102, quizId: "sworn-10-27-26", live: "2026-10-27", dateLabel: "October 27, 2026", sunday: false,
    k: 2,
    suspects: ["Eldon","Mordecai","Rufus","Ottoline","Simon"],
    venue: "the Oxenhope worsted mill",
    stolen: "a warp of combed long wool",
    statements: [
      {"type":"liar","x":1},
      {"type":"innocent","x":3},
      {"type":"accuse","x":0},
      {"type":"liar","x":4},
      {"type":"honest","x":0},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 103, quizId: "sworn-10-28-26", live: "2026-10-28", dateLabel: "October 28, 2026", sunday: false,
    k: 3,
    suspects: ["Cressida","Nell","Clementine","Jemima","Zillah"],
    venue: "the Penhaligon rosewater still",
    stolen: "the perfumer's copper alembic",
    statements: [
      {"type":"liar","x":4},
      {"type":"liar","x":2},
      {"type":"selfInnocent"},
      {"type":"innocent","x":2},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":2,"liars":[0,2,3]},
  },
  {
    num: 104, quizId: "sworn-10-29-26", live: "2026-10-29", dateLabel: "October 29, 2026", sunday: false,
    k: 3,
    suspects: ["Millicent","Quintus","Isolde","Ottoline","Edwina"],
    venue: "the Quarrington slate splits",
    stolen: "a stack of countess slates",
    statements: [
      {"type":"liar","x":1},
      {"type":"liar","x":4},
      {"type":"innocent","x":0},
      {"type":"innocent","x":2},
      {"type":"liar","x":2},
    ],
    solution: {"thief":2,"liars":[0,3,4]},
  },
  {
    num: 105, quizId: "sworn-10-30-26", live: "2026-10-30", dateLabel: "October 30, 2026", sunday: false,
    k: 2,
    suspects: ["Jemima","Cyrus","Pearl","Yvette","Kester"],
    venue: "the Ramsholt eel house",
    stolen: "the eelman's wicker grig",
    statements: [
      {"type":"accuse","x":2},
      {"type":"accuse","x":0},
      {"type":"thiefLiar"},
      {"type":"honest","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 106, quizId: "sworn-10-31-26", live: "2026-10-31", dateLabel: "October 31, 2026", sunday: false,
    k: 2,
    suspects: ["Zebedee","Vera","Lysander","Winnie","Jemima"],
    venue: "the Stourpaine watercress beds",
    stolen: "a hamper of the spring cut",
    statements: [
      {"type":"accuse","x":2},
      {"type":"innocent","x":2},
      {"type":"liar","x":4},
      {"type":"accuse","x":0},
      {"type":"accuse","x":0},
    ],
    solution: {"thief":0,"liars":[0,2]},
  },
  {
    num: 107, quizId: "sworn-11-1-26", live: "2026-11-01", dateLabel: "November 1, 2026", sunday: true,
    k: 3,
    suspects: ["Casimir","Delia","Fenella","Percival","Rufus","Isambard"],
    venue: "the Tidworth rope loft",
    stolen: "the ropewalker's brass gauge",
    statements: [
      {"type":"accuse","x":1},
      {"type":"innocent","x":4},
      {"type":"accuse","x":0},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"honest","x":2},
    ],
    solution: {"thief":1,"liars":[2,4,5]},
  },
  {
    num: 108, quizId: "sworn-11-2-26", live: "2026-11-02", dateLabel: "November 2, 2026", sunday: false,
    k: 2,
    suspects: ["Ezra","Victor","Henrietta","Flora","Isambard"],
    venue: "the Ullswater boat sheds",
    stolen: "a set of varnished oars",
    statements: [
      {"type":"innocent","x":4},
      {"type":"honest","x":2},
      {"type":"honest","x":0},
      {"type":"accuse","x":4},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":0,"liars":[3,4]},
  },
  {
    num: 109, quizId: "sworn-11-3-26", live: "2026-11-03", dateLabel: "November 3, 2026", sunday: false,
    k: 3,
    suspects: ["Delia","Rosa","Bellamy","Norbert","Bruno"],
    venue: "the Vauxhall fireworks shed",
    stolen: "a crate of Catherine wheels",
    statements: [
      {"type":"honest","x":3},
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":4,"liars":[0,1,3]},
  },
  {
    num: 110, quizId: "sworn-11-4-26", live: "2026-11-04", dateLabel: "November 4, 2026", sunday: false,
    k: 3,
    suspects: ["Ambrose","Agatha","Casimir","Felix","Delphine"],
    venue: "the Wendover clock shop",
    stolen: "the clockmaker's gilt pendulum",
    statements: [
      {"type":"innocent","x":3},
      {"type":"honest","x":2},
      {"type":"innocent","x":0},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":0,"liars":[1,2,3]},
  },
  {
    num: 111, quizId: "sworn-11-5-26", live: "2026-11-05", dateLabel: "November 5, 2026", sunday: false,
    k: 2,
    suspects: ["Mordecai","Idris","Valentine","Katharine","Ophelia"],
    venue: "the Yelverton toy loft",
    stolen: "a sack of painted spinning tops",
    statements: [
      {"type":"accuse","x":2},
      {"type":"innocent","x":4},
      {"type":"thiefLiar"},
      {"type":"innocent","x":1},
      {"type":"liar","x":0},
    ],
    solution: {"thief":3,"liars":[0,2]},
  },
  {
    num: 112, quizId: "sworn-11-6-26", live: "2026-11-06", dateLabel: "November 6, 2026", sunday: false,
    k: 3,
    suspects: ["Agatha","Ottoline","Yvette","Barnaby","Alaric"],
    venue: "the Zelah pilchard cellars",
    stolen: "the salter's copper scale",
    statements: [
      {"type":"liar","x":4},
      {"type":"liar","x":4},
      {"type":"innocent","x":3},
      {"type":"selfInnocent"},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":3,"liars":[2,3,4]},
  },
  {
    num: 113, quizId: "sworn-11-7-26", live: "2026-11-07", dateLabel: "November 7, 2026", sunday: false,
    k: 2,
    suspects: ["Osric","Ezra","Ursula","Desmond","Matilda"],
    venue: "the Ashwell pottery",
    stolen: "a crate of glazed milk jugs",
    statements: [
      {"type":"accuse","x":4},
      {"type":"liar","x":3},
      {"type":"thiefLiar"},
      {"type":"innocent","x":1},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":4,"liars":[1,4]},
  },
  {
    num: 114, quizId: "sworn-11-8-26", live: "2026-11-08", dateLabel: "November 8, 2026", sunday: true,
    k: 3,
    suspects: ["Cuthbert","Eulalia","Prudence","Agatha","Isolde","Lysander"],
    venue: "the Blackmore harness shop",
    stolen: "the saddler's silver bit",
    statements: [
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"accuse","x":2},
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":5,"liars":[2,3,4]},
  },
  {
    num: 115, quizId: "sworn-11-9-26", live: "2026-11-09", dateLabel: "November 9, 2026", sunday: false,
    k: 2,
    suspects: ["Katharine","Wilfred","Kester","Ephraim","Percy"],
    venue: "the Cranmore cider barn",
    stolen: "a keg of pressed perry",
    statements: [
      {"type":"liar","x":1},
      {"type":"selfInnocent"},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":4,"liars":[0,3]},
  },
  {
    num: 116, quizId: "sworn-11-10-26", live: "2026-11-10", dateLabel: "November 10, 2026", sunday: false,
    k: 2,
    suspects: ["Ambrose","Otis","Godfrey","Sebastian","Katharine"],
    venue: "the Deverill hat shop",
    stolen: "the milliner's feather box",
    statements: [
      {"type":"innocent","x":3},
      {"type":"liar","x":3},
      {"type":"innocent","x":3},
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":0,"liars":[3,4]},
  },
  {
    num: 117, quizId: "sworn-11-11-26", live: "2026-11-11", dateLabel: "November 11, 2026", sunday: false,
    k: 2,
    suspects: ["Nathaniel","Cuthbert","Albertine","Jemima","Ephraim"],
    venue: "the Elmstead seed barn",
    stolen: "a sack of prize runner beans",
    statements: [
      {"type":"innocent","x":2},
      {"type":"innocent","x":0},
      {"type":"innocent","x":1},
      {"type":"innocent","x":1},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":1,"liars":[2,3]},
  },
  {
    num: 118, quizId: "sworn-11-12-26", live: "2026-11-12", dateLabel: "November 12, 2026", sunday: false,
    k: 3,
    suspects: ["Sybil","Eulalia","Idris","Fitzgerald","Barnaby"],
    venue: "the Fairford organ loft",
    stolen: "the organist's music satchel",
    statements: [
      {"type":"accuse","x":4},
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"selfInnocent"},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":3,"liars":[0,1,3]},
  },
  {
    num: 119, quizId: "sworn-11-13-26", live: "2026-11-13", dateLabel: "November 13, 2026", sunday: false,
    k: 2,
    suspects: ["Rowena","Henrietta","Tessa","Percival","Thaddeus"],
    venue: "the Glenridding slate yard",
    stolen: "a pallet of roofing slates",
    statements: [
      {"type":"accuse","x":3},
      {"type":"selfInnocent"},
      {"type":"honest","x":0},
      {"type":"innocent","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[0,2]},
  },
  {
    num: 120, quizId: "sworn-11-14-26", live: "2026-11-14", dateLabel: "November 14, 2026", sunday: false,
    k: 2,
    suspects: ["Kester","Isolde","Rosamund","Quintus","Lottie"],
    venue: "the Hartley map room",
    stolen: "the surveyor's brass chain",
    statements: [
      {"type":"honest","x":1},
      {"type":"accuse","x":0},
      {"type":"liar","x":4},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[3,4]},
  },
  {
    num: 121, quizId: "sworn-11-15-26", live: "2026-11-15", dateLabel: "November 15, 2026", sunday: true,
    k: 3,
    suspects: ["Gideon","Beatrix","Fitzgerald","Constance","Fenwick","Nathaniel"],
    venue: "the Ivinghoe windmill",
    stolen: "a sack of stone-ground flour",
    statements: [
      {"type":"accuse","x":1},
      {"type":"selfInnocent"},
      {"type":"innocent","x":3},
      {"type":"innocent","x":4},
      {"type":"innocent","x":0},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[0,2,5]},
  },
  {
    num: 122, quizId: "sworn-11-16-26", live: "2026-11-16", dateLabel: "November 16, 2026", sunday: false,
    k: 2,
    suspects: ["Lysander","Lucius","Jocasta","Nerissa","Marguerite"],
    venue: "the Jaywick bathing huts",
    stolen: "the attendant's ticket punch",
    statements: [
      {"type":"innocent","x":3},
      {"type":"accuse","x":0},
      {"type":"liar","x":4},
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[1,2]},
  },
  {
    num: 123, quizId: "sworn-11-17-26", live: "2026-11-17", dateLabel: "November 17, 2026", sunday: false,
    k: 2,
    suspects: ["Jasper","Sybil","Humphrey","Roland","Kingsley"],
    venue: "the Kettlewell dairy",
    stolen: "a wheel of blue cheese",
    statements: [
      {"type":"thiefLiar"},
      {"type":"innocent","x":0},
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":4,"liars":[0,2]},
  },
  {
    num: 124, quizId: "sworn-11-18-26", live: "2026-11-18", dateLabel: "November 18, 2026", sunday: false,
    k: 2,
    suspects: ["Isolde","Griselda","Simon","Fitzgerald","Alaric"],
    venue: "the Lynmouth lifeboat house",
    stolen: "the coxswain's brass lantern",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":1},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 125, quizId: "sworn-11-19-26", live: "2026-11-19", dateLabel: "November 19, 2026", sunday: false,
    k: 2,
    suspects: ["Humphrey","Osric","Cuthbert","Agatha","Felix"],
    venue: "the Middleham stables",
    stolen: "a set of racing silks",
    statements: [
      {"type":"accuse","x":3},
      {"type":"thiefLiar"},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":4,"liars":[0,4]},
  },
  {
    num: 126, quizId: "sworn-11-20-26", live: "2026-11-20", dateLabel: "November 20, 2026", sunday: false,
    k: 3,
    suspects: ["Gulliver","Prudence","Kingsley","Amos","Delia"],
    venue: "the Northleach wool hall",
    stolen: "the merchant's seal ring",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"honest","x":3},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":0,"liars":[0,2,3]},
  },
  {
    num: 127, quizId: "sworn-11-21-26", live: "2026-11-21", dateLabel: "November 21, 2026", sunday: false,
    k: 3,
    suspects: ["Fitzgerald","Casimir","Fenella","Millicent","Bartholomew"],
    venue: "the Orford smokehouse",
    stolen: "a side of oak-smoked salmon",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":2},
      {"type":"liar","x":3},
      {"type":"accuse","x":1},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":0,"liars":[0,1,3]},
  },
  {
    num: 128, quizId: "sworn-11-22-26", live: "2026-11-22", dateLabel: "November 22, 2026", sunday: true,
    k: 4,
    suspects: ["Nerissa","Clara","Zebedee","Ambrose","Rosalind","Hazel"],
    venue: "the Painswick bell tower",
    stolen: "the ringer's handbell set",
    statements: [
      {"type":"thiefLiar"},
      {"type":"accuse","x":3},
      {"type":"liar","x":1},
      {"type":"accuse","x":0},
      {"type":"innocent","x":5},
      {"type":"liar","x":1},
    ],
    solution: {"thief":5,"liars":[0,1,3,4]},
  },
  {
    num: 129, quizId: "sworn-11-23-26", live: "2026-11-23", dateLabel: "November 23, 2026", sunday: false,
    k: 2,
    suspects: ["Dorian","Edwina","Rowena","Idris","Millicent"],
    venue: "the Quorn candle shop",
    stolen: "a box of beeswax tapers",
    statements: [
      {"type":"innocent","x":4},
      {"type":"innocent","x":4},
      {"type":"selfInnocent"},
      {"type":"accuse","x":2},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[3,4]},
  },
  {
    num: 130, quizId: "sworn-11-24-26", live: "2026-11-24", dateLabel: "November 24, 2026", sunday: false,
    k: 3,
    suspects: ["Sybil","Lucius","Norbert","Griselda","Amos"],
    venue: "the Ringmer brickfield",
    stolen: "the brickmaker's wooden mold",
    statements: [
      {"type":"innocent","x":3},
      {"type":"liar","x":3},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[1,2,4]},
  },
  {
    num: 131, quizId: "sworn-11-25-26", live: "2026-11-25", dateLabel: "November 25, 2026", sunday: false,
    k: 2,
    suspects: ["Victor","Matilda","Barnaby","Ambrose","Alastair"],
    venue: "the Stanton glass studio",
    stolen: "a pane of cobalt glass",
    statements: [
      {"type":"innocent","x":1},
      {"type":"accuse","x":0},
      {"type":"thiefHonest"},
      {"type":"accuse","x":4},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[1,3]},
  },
  {
    num: 132, quizId: "sworn-11-26-26", live: "2026-11-26", dateLabel: "November 26, 2026", sunday: false,
    k: 3,
    suspects: ["Millicent","Verena","Griselda","Rowena","Ambrose"],
    venue: "the Tintern paper mill",
    stolen: "the papermaker's deckle",
    statements: [
      {"type":"innocent","x":2},
      {"type":"liar","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":2,"liars":[0,2,4]},
  },
  {
    num: 133, quizId: "sworn-11-27-26", live: "2026-11-27", dateLabel: "November 27, 2026", sunday: false,
    k: 2,
    suspects: ["Zillah","Nathaniel","Delia","Sylvester","Marguerite"],
    venue: "the Uffington chalk works",
    stolen: "a cart of carving chalk",
    statements: [
      {"type":"accuse","x":4},
      {"type":"liar","x":4},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[0,1]},
  },
  {
    num: 134, quizId: "sworn-11-28-26", live: "2026-11-28", dateLabel: "November 28, 2026", sunday: false,
    k: 3,
    suspects: ["Sadie","Desmond","Cornelius","Kester","Norbert"],
    venue: "the Ventnor tea gardens",
    stolen: "the proprietor's silver teapot",
    statements: [
      {"type":"thiefHonest"},
      {"type":"honest","x":0},
      {"type":"innocent","x":0},
      {"type":"innocent","x":0},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[2,3,4]},
  },
  {
    num: 135, quizId: "sworn-11-29-26", live: "2026-11-29", dateLabel: "November 29, 2026", sunday: true,
    k: 3,
    suspects: ["Godfrey","Quintus","Isolde","Perpetua","Wilfred","Josiah"],
    venue: "the Wroxham boatyard",
    stolen: "a coil of tarred rope",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":5},
      {"type":"innocent","x":0},
      {"type":"innocent","x":1},
      {"type":"liar","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":5,"liars":[1,4,5]},
  },
  {
    num: 136, quizId: "sworn-11-30-26", live: "2026-11-30", dateLabel: "November 30, 2026", sunday: false,
    k: 3,
    suspects: ["Xanthe","Fenwick","Ulric","Rosa","Agatha"],
    venue: "the Yarcombe honey farm",
    stolen: "the beekeeper's veil and gloves",
    statements: [
      {"type":"honest","x":4},
      {"type":"honest","x":4},
      {"type":"thiefHonest"},
      {"type":"innocent","x":1},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":2,"liars":[0,1,4]},
  },
];
